from enum import IntEnum, IntFlag
from .. import PlayerIndex, Vector2

class ButtonState(IntEnum): Released: int; Pressed: int
class KeyState(IntEnum): Up: int; Down: int
class Keys(IntEnum): None_: int; Escape: int
class Buttons(IntFlag): A: int; B: int; X: int; Y: int; DPadUp: int; DPadDown: int; DPadLeft: int; DPadRight: int
class GamePadDeadZone(IntEnum): None_: int; IndependentAxes: int; Circular: int
class KeyboardState:
    def __init__(self, keys: object = ...) -> None: ...
    def IsKeyDown(self, key: Keys) -> bool: ...
    def IsKeyUp(self, key: Keys) -> bool: ...
    def GetPressedKeys(self) -> list[Keys]: ...
class Keyboard:
    @staticmethod
    def GetState(*args: object) -> KeyboardState: ...
class MouseState:
    X: int; Y: int; ScrollWheelValue: int
    LeftButton: ButtonState; MiddleButton: ButtonState; RightButton: ButtonState; XButton1: ButtonState; XButton2: ButtonState
class Mouse:
    @staticmethod
    def GetState() -> MouseState: ...
    @staticmethod
    def SetPosition(x: int, y: int) -> None: ...
class GamePadButtons: ...
class GamePadDPad: ...
class GamePadThumbSticks: Left: Vector2; Right: Vector2
class GamePadTriggers: Left: float; Right: float
class GamePadState:
    IsConnected: bool; PacketNumber: int
    def IsButtonDown(self, button: Buttons) -> bool: ...
    def IsButtonUp(self, button: Buttons) -> bool: ...
class GamePad:
    @staticmethod
    def GetState(playerIndex: PlayerIndex, deadZoneMode: GamePadDeadZone = ...) -> GamePadState: ...
