from datetime import timedelta
from enum import IntEnum, IntFlag
from typing import overload

class MathHelper:
    E: float; Log2E: float; Log10E: float; Pi: float; TwoPi: float; PiOver2: float; PiOver4: float
    @staticmethod
    def Clamp(value: float, min: float, max: float) -> float: ...
    @staticmethod
    def Lerp(value1: float, value2: float, amount: float) -> float: ...
    @staticmethod
    def ToRadians(degrees: float) -> float: ...
    @staticmethod
    def ToDegrees(radians: float) -> float: ...

class Vector2:
    X: float; Y: float
    @overload
    def __init__(self, value: float = ...) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    Zero: Vector2; One: Vector2; UnitX: Vector2; UnitY: Vector2
    def Length(self) -> float: ...
    def LengthSquared(self) -> float: ...
    def Normalize(self) -> None: ...
    @staticmethod
    def Add(value1: Vector2, value2: Vector2) -> Vector2: ...

class Vector3:
    X: float; Y: float; Z: float
    @overload
    def __init__(self, value: float = ...) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @overload
    def __init__(self, xy: Vector2, z: float) -> None: ...
    Zero: Vector3; One: Vector3; UnitX: Vector3; UnitY: Vector3; UnitZ: Vector3
    Up: Vector3; Down: Vector3; Left: Vector3; Right: Vector3; Forward: Vector3; Backward: Vector3

class Vector4:
    X: float; Y: float; Z: float; W: float
    def __init__(self, x: float = ..., y: float | None = ..., z: float | None = ..., w: float | None = ...) -> None: ...
    Zero: Vector4; One: Vector4

class Quaternion:
    X: float; Y: float; Z: float; W: float
    Identity: Quaternion
    def __init__(self, x: float = ..., y: float = ..., z: float = ..., w: float = ...) -> None: ...

class Matrix:
    Identity: Matrix
    Translation: Vector3
    def __init__(self, *values: float) -> None: ...
    @staticmethod
    def CreateScale(scale: float | Vector3, y: float | None = ..., z: float | None = ...) -> Matrix: ...
    @staticmethod
    def CreateTranslation(x: float | Vector3, y: float | None = ..., z: float | None = ...) -> Matrix: ...
    @staticmethod
    def CreateRotationX(radians: float) -> Matrix: ...
    @staticmethod
    def CreateRotationY(radians: float) -> Matrix: ...

class Color:
    R: int; G: int; B: int; A: int; PackedValue: int
    White: Color; Black: Color; Transparent: Color; CornflowerBlue: Color
    def __init__(self, r: int | float | Vector3 | Vector4, g: int | float | None = ..., b: int | float | None = ..., a: int | float = ...) -> None: ...

class Point:
    X: int; Y: int; Zero: Point
    def __init__(self, x: int = ..., y: int = ...) -> None: ...

class Rectangle:
    X: int; Y: int; Width: int; Height: int
    Left: int; Right: int; Top: int; Bottom: int; Location: Point; Center: Point; Empty: Rectangle; IsEmpty: bool
    def __init__(self, x: int = ..., y: int = ..., width: int = ..., height: int = ...) -> None: ...

class GameTime:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, totalGameTime: timedelta, elapsedGameTime: timedelta) -> None: ...
    @overload
    def __init__(self, totalGameTime: timedelta, elapsedGameTime: timedelta, isRunningSlowly: bool) -> None: ...
    TotalGameTime: timedelta; ElapsedGameTime: timedelta; IsRunningSlowly: bool

class PlayerIndex(IntEnum): One: int; Two: int; Three: int; Four: int
class DisplayOrientation(IntFlag): Default: int; LandscapeLeft: int; LandscapeRight: int; Portrait: int

class Game:
    Content: object; GraphicsDevice: object; IsActive: bool
    IsFixedTimeStep: bool; IsMouseVisible: bool
    TargetElapsedTime: timedelta; InactiveSleepTime: timedelta
    def Run(self) -> None: ...
    def RunOneFrame(self) -> None: ...
    def Tick(self) -> None: ...
    def Exit(self) -> None: ...
    def Dispose(self) -> None: ...
    def Initialize(self) -> None: ...
    def LoadContent(self) -> None: ...
    def UnloadContent(self) -> None: ...
    def Update(self, gameTime: GameTime) -> None: ...
    def Draw(self, gameTime: GameTime) -> None: ...

class GraphicsDeviceManager:
    GraphicsDevice: object
    PreferredBackBufferWidth: int; PreferredBackBufferHeight: int
    def __init__(self, game: Game) -> None: ...
    def ApplyChanges(self) -> None: ...
    def ToggleFullScreen(self) -> None: ...
    def Dispose(self) -> None: ...
