from datetime import timedelta
from enum import IntEnum, IntFlag
from typing import Any, BinaryIO, Callable, ClassVar, Final, Iterable, Iterator, MutableSequence, Sequence, TypeVar, overload
from ._language import Event
from .Content import ContentManager
from .Graphics import GraphicsDevice, GraphicsProfile, DepthFormat, SurfaceFormat

T = TypeVar("T")

class BoundingBox:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, min: Vector3, max: Vector3) -> None: ...
    @overload
    def GetCorners(self) -> list[Vector3]: ...
    @overload
    def GetCorners(self, corners: MutableSequence[Vector3]) -> None: ...
    @overload
    def Equals(self, other: BoundingBox) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...
    @staticmethod
    def CreateMerged(original: BoundingBox, additional: BoundingBox) -> BoundingBox: ...
    @staticmethod
    def CreateFromSphere(sphere: BoundingSphere) -> BoundingBox: ...
    @staticmethod
    def CreateFromPoints(points: Iterable[Vector3]) -> BoundingBox: ...
    @overload
    def Intersects(self, box: BoundingBox) -> bool: ...
    @overload
    def Intersects(self, frustum: BoundingFrustum) -> bool: ...
    @overload
    def Intersects(self, plane: Plane) -> PlaneIntersectionType: ...
    @overload
    def Intersects(self, ray: Ray) -> float | None: ...
    @overload
    def Intersects(self, sphere: BoundingSphere) -> bool: ...
    @overload
    def Contains(self, box: BoundingBox) -> ContainmentType: ...
    @overload
    def Contains(self, frustum: BoundingFrustum) -> ContainmentType: ...
    @overload
    def Contains(self, point: Vector3) -> ContainmentType: ...
    @overload
    def Contains(self, sphere: BoundingSphere) -> ContainmentType: ...
    def __eq__(self, b: BoundingBox) -> bool: ...
    def __ne__(self, b: BoundingBox) -> bool: ...
    CornerCount: Final[int]
    Min: Vector3
    Max: Vector3
    def __copy__(self) -> BoundingBox: ...
    def __deepcopy__(self, memo: object) -> BoundingBox: ...

class BoundingFrustum:
    def __init__(self, value: Matrix) -> None: ...
    @overload
    def GetCorners(self) -> list[Vector3]: ...
    @overload
    def GetCorners(self, corners: MutableSequence[Vector3]) -> None: ...
    @overload
    def Equals(self, other: BoundingFrustum) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...
    @overload
    def Intersects(self, box: BoundingBox) -> bool: ...
    @overload
    def Intersects(self, frustum: BoundingFrustum) -> bool: ...
    @overload
    def Intersects(self, plane: Plane) -> PlaneIntersectionType: ...
    @overload
    def Intersects(self, ray: Ray) -> float | None: ...
    @overload
    def Intersects(self, sphere: BoundingSphere) -> bool: ...
    @overload
    def Contains(self, box: BoundingBox) -> ContainmentType: ...
    @overload
    def Contains(self, frustum: BoundingFrustum) -> ContainmentType: ...
    @overload
    def Contains(self, point: Vector3) -> ContainmentType: ...
    @overload
    def Contains(self, sphere: BoundingSphere) -> ContainmentType: ...
    def __eq__(self, b: BoundingFrustum) -> bool: ...
    def __ne__(self, b: BoundingFrustum) -> bool: ...
    @property
    def Near(self) -> Plane: ...
    @property
    def Far(self) -> Plane: ...
    @property
    def Left(self) -> Plane: ...
    @property
    def Right(self) -> Plane: ...
    @property
    def Top(self) -> Plane: ...
    @property
    def Bottom(self) -> Plane: ...
    @property
    def Matrix(self) -> Matrix: ...
    @Matrix.setter
    def Matrix(self, value: Matrix) -> None: ...
    CornerCount: Final[int]

class BoundingSphere:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, center: Vector3, radius: float) -> None: ...
    @overload
    def Equals(self, other: BoundingSphere) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...
    @staticmethod
    def CreateMerged(original: BoundingSphere, additional: BoundingSphere) -> BoundingSphere: ...
    @staticmethod
    def CreateFromBoundingBox(box: BoundingBox) -> BoundingSphere: ...
    @staticmethod
    def CreateFromPoints(points: Iterable[Vector3]) -> BoundingSphere: ...
    @staticmethod
    def CreateFromFrustum(frustum: BoundingFrustum) -> BoundingSphere: ...
    @overload
    def Intersects(self, box: BoundingBox) -> bool: ...
    @overload
    def Intersects(self, frustum: BoundingFrustum) -> bool: ...
    @overload
    def Intersects(self, plane: Plane) -> PlaneIntersectionType: ...
    @overload
    def Intersects(self, ray: Ray) -> float | None: ...
    @overload
    def Intersects(self, sphere: BoundingSphere) -> bool: ...
    @overload
    def Contains(self, box: BoundingBox) -> ContainmentType: ...
    @overload
    def Contains(self, frustum: BoundingFrustum) -> ContainmentType: ...
    @overload
    def Contains(self, point: Vector3) -> ContainmentType: ...
    @overload
    def Contains(self, sphere: BoundingSphere) -> ContainmentType: ...
    def Transform(self, matrix: Matrix) -> BoundingSphere: ...
    def __eq__(self, b: BoundingSphere) -> bool: ...
    def __ne__(self, b: BoundingSphere) -> bool: ...
    Center: Vector3
    Radius: float
    def __copy__(self) -> BoundingSphere: ...
    def __deepcopy__(self, memo: object) -> BoundingSphere: ...

class Color:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, r: int, g: int, b: int) -> None: ...
    @overload
    def __init__(self, r: int, g: int, b: int, a: int) -> None: ...
    @overload
    def __init__(self, r: float, g: float, b: float) -> None: ...
    @overload
    def __init__(self, r: float, g: float, b: float, a: float) -> None: ...
    @overload
    def __init__(self, vector: Vector3) -> None: ...
    @overload
    def __init__(self, vector: Vector4) -> None: ...
    @overload
    @staticmethod
    def FromNonPremultiplied(vector: Vector4) -> Color: ...
    @overload
    @staticmethod
    def FromNonPremultiplied(r: int, g: int, b: int, a: int) -> Color: ...
    def ToVector3(self) -> Vector3: ...
    def ToVector4(self) -> Vector4: ...
    @staticmethod
    def Lerp(value1: Color, value2: Color, amount: float) -> Color: ...
    @staticmethod
    def Multiply(value: Color, scale: float) -> Color: ...
    def __mul__(self, scale: float) -> Color: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Color) -> bool: ...
    def __eq__(self, b: Color) -> bool: ...
    def __ne__(self, b: Color) -> bool: ...
    @property
    def R(self) -> int: ...
    @R.setter
    def R(self, value: int) -> None: ...
    @property
    def G(self) -> int: ...
    @G.setter
    def G(self, value: int) -> None: ...
    @property
    def B(self) -> int: ...
    @B.setter
    def B(self, value: int) -> None: ...
    @property
    def A(self) -> int: ...
    @A.setter
    def A(self, value: int) -> None: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    Transparent: Final[Color]
    AliceBlue: Final[Color]
    AntiqueWhite: Final[Color]
    Aqua: Final[Color]
    Aquamarine: Final[Color]
    Azure: Final[Color]
    Beige: Final[Color]
    Bisque: Final[Color]
    Black: Final[Color]
    BlanchedAlmond: Final[Color]
    Blue: Final[Color]
    BlueViolet: Final[Color]
    Brown: Final[Color]
    BurlyWood: Final[Color]
    CadetBlue: Final[Color]
    Chartreuse: Final[Color]
    Chocolate: Final[Color]
    Coral: Final[Color]
    CornflowerBlue: Final[Color]
    Cornsilk: Final[Color]
    Crimson: Final[Color]
    Cyan: Final[Color]
    DarkBlue: Final[Color]
    DarkCyan: Final[Color]
    DarkGoldenrod: Final[Color]
    DarkGray: Final[Color]
    DarkGreen: Final[Color]
    DarkKhaki: Final[Color]
    DarkMagenta: Final[Color]
    DarkOliveGreen: Final[Color]
    DarkOrange: Final[Color]
    DarkOrchid: Final[Color]
    DarkRed: Final[Color]
    DarkSalmon: Final[Color]
    DarkSeaGreen: Final[Color]
    DarkSlateBlue: Final[Color]
    DarkSlateGray: Final[Color]
    DarkTurquoise: Final[Color]
    DarkViolet: Final[Color]
    DeepPink: Final[Color]
    DeepSkyBlue: Final[Color]
    DimGray: Final[Color]
    DodgerBlue: Final[Color]
    Firebrick: Final[Color]
    FloralWhite: Final[Color]
    ForestGreen: Final[Color]
    Fuchsia: Final[Color]
    Gainsboro: Final[Color]
    GhostWhite: Final[Color]
    Gold: Final[Color]
    Goldenrod: Final[Color]
    Gray: Final[Color]
    Green: Final[Color]
    GreenYellow: Final[Color]
    Honeydew: Final[Color]
    HotPink: Final[Color]
    IndianRed: Final[Color]
    Indigo: Final[Color]
    Ivory: Final[Color]
    Khaki: Final[Color]
    Lavender: Final[Color]
    LavenderBlush: Final[Color]
    LawnGreen: Final[Color]
    LemonChiffon: Final[Color]
    LightBlue: Final[Color]
    LightCoral: Final[Color]
    LightCyan: Final[Color]
    LightGoldenrodYellow: Final[Color]
    LightGreen: Final[Color]
    LightGray: Final[Color]
    LightPink: Final[Color]
    LightSalmon: Final[Color]
    LightSeaGreen: Final[Color]
    LightSkyBlue: Final[Color]
    LightSlateGray: Final[Color]
    LightSteelBlue: Final[Color]
    LightYellow: Final[Color]
    Lime: Final[Color]
    LimeGreen: Final[Color]
    Linen: Final[Color]
    Magenta: Final[Color]
    Maroon: Final[Color]
    MediumAquamarine: Final[Color]
    MediumBlue: Final[Color]
    MediumOrchid: Final[Color]
    MediumPurple: Final[Color]
    MediumSeaGreen: Final[Color]
    MediumSlateBlue: Final[Color]
    MediumSpringGreen: Final[Color]
    MediumTurquoise: Final[Color]
    MediumVioletRed: Final[Color]
    MidnightBlue: Final[Color]
    MintCream: Final[Color]
    MistyRose: Final[Color]
    Moccasin: Final[Color]
    NavajoWhite: Final[Color]
    Navy: Final[Color]
    OldLace: Final[Color]
    Olive: Final[Color]
    OliveDrab: Final[Color]
    Orange: Final[Color]
    OrangeRed: Final[Color]
    Orchid: Final[Color]
    PaleGoldenrod: Final[Color]
    PaleGreen: Final[Color]
    PaleTurquoise: Final[Color]
    PaleVioletRed: Final[Color]
    PapayaWhip: Final[Color]
    PeachPuff: Final[Color]
    Peru: Final[Color]
    Pink: Final[Color]
    Plum: Final[Color]
    PowderBlue: Final[Color]
    Purple: Final[Color]
    Red: Final[Color]
    RosyBrown: Final[Color]
    RoyalBlue: Final[Color]
    SaddleBrown: Final[Color]
    Salmon: Final[Color]
    SandyBrown: Final[Color]
    SeaGreen: Final[Color]
    SeaShell: Final[Color]
    Sienna: Final[Color]
    Silver: Final[Color]
    SkyBlue: Final[Color]
    SlateBlue: Final[Color]
    SlateGray: Final[Color]
    Snow: Final[Color]
    SpringGreen: Final[Color]
    SteelBlue: Final[Color]
    Tan: Final[Color]
    Teal: Final[Color]
    Thistle: Final[Color]
    Tomato: Final[Color]
    Turquoise: Final[Color]
    Violet: Final[Color]
    Wheat: Final[Color]
    White: Final[Color]
    WhiteSmoke: Final[Color]
    Yellow: Final[Color]
    YellowGreen: Final[Color]
    def __copy__(self) -> Color: ...
    def __deepcopy__(self, memo: object) -> Color: ...

class ContainmentType(IntEnum):
    Disjoint: int
    Contains: int
    Intersects: int

class DisplayOrientation(IntFlag):
    Default: int
    LandscapeLeft: int
    LandscapeRight: int
    Portrait: int

class DrawableGameComponent(GameComponent):
    def __init__(self, game: Game) -> None: ...
    def Initialize(self) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    def Draw(self, gameTime: GameTime) -> None: ...
    def LoadContent(self) -> None: ...
    def UnloadContent(self) -> None: ...
    def OnDrawOrderChanged(self, sender: object, args: object) -> None: ...
    def OnVisibleChanged(self, sender: object, args: object) -> None: ...
    @property
    def Visible(self) -> bool: ...
    @Visible.setter
    def Visible(self, value: bool) -> None: ...
    @property
    def DrawOrder(self) -> int: ...
    @DrawOrder.setter
    def DrawOrder(self, value: int) -> None: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    VisibleChanged: Final[Event]
    DrawOrderChanged: Final[Event]

class Game:
    def __init__(self) -> None: ...
    def Run(self) -> None: ...
    def RunOneFrame(self) -> None: ...
    def Tick(self) -> None: ...
    def SuppressDraw(self) -> None: ...
    def Exit(self) -> None: ...
    def BeginRun(self) -> None: ...
    def EndRun(self) -> None: ...
    def Update(self, gameTime: GameTime) -> None: ...
    def BeginDraw(self) -> bool: ...
    def Draw(self, gameTime: GameTime) -> None: ...
    def EndDraw(self) -> None: ...
    def Initialize(self) -> None: ...
    def ResetElapsedTime(self) -> None: ...
    def OnActivated(self, sender: object, args: object) -> None: ...
    def OnDeactivated(self, sender: object, args: object) -> None: ...
    def OnExiting(self, sender: object, args: object) -> None: ...
    def LoadContent(self) -> None: ...
    def UnloadContent(self) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    def ShowMissingRequirementMessage(self, exception: Exception) -> bool: ...
    @property
    def LaunchParameters(self) -> LaunchParameters: ...
    @property
    def Components(self) -> GameComponentCollection: ...
    @property
    def Services(self) -> GameServiceContainer: ...
    @property
    def InactiveSleepTime(self) -> timedelta: ...
    @InactiveSleepTime.setter
    def InactiveSleepTime(self, value: timedelta) -> None: ...
    @property
    def IsMouseVisible(self) -> bool: ...
    @IsMouseVisible.setter
    def IsMouseVisible(self, value: bool) -> None: ...
    @property
    def TargetElapsedTime(self) -> timedelta: ...
    @TargetElapsedTime.setter
    def TargetElapsedTime(self, value: timedelta) -> None: ...
    @property
    def IsFixedTimeStep(self) -> bool: ...
    @IsFixedTimeStep.setter
    def IsFixedTimeStep(self, value: bool) -> None: ...
    @property
    def Window(self) -> GameWindow: ...
    @property
    def IsActive(self) -> bool: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    @property
    def Content(self) -> ContentManager: ...
    @Content.setter
    def Content(self, value: ContentManager) -> None: ...
    Activated: Final[Event]
    Deactivated: Final[Event]
    Exiting: Final[Event]
    Disposed: Final[Event]
    def __enter__(self) -> Game: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class GameComponent:
    def __init__(self, game: Game) -> None: ...
    def Initialize(self) -> None: ...
    def Update(self, gameTime: GameTime) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    def OnUpdateOrderChanged(self, sender: object, args: object) -> None: ...
    def OnEnabledChanged(self, sender: object, args: object) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> None: ...
    @property
    def UpdateOrder(self) -> int: ...
    @UpdateOrder.setter
    def UpdateOrder(self, value: int) -> None: ...
    @property
    def Game(self) -> Game: ...
    EnabledChanged: Final[Event]
    UpdateOrderChanged: Final[Event]
    Disposed: Final[Event]
    def __enter__(self) -> GameComponent: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class GameComponentCollection:
    def __init__(self) -> None: ...
    def InsertItem(self, index: int, item: IGameComponent) -> None: ...
    def RemoveItem(self, index: int) -> None: ...
    def SetItem(self, index: int, item: IGameComponent) -> None: ...
    def ClearItems(self) -> None: ...
    ComponentAdded: Final[Event]
    ComponentRemoved: Final[Event]

class GameComponentCollectionEventArgs:
    def __init__(self, gameComponent: IGameComponent) -> None: ...
    @property
    def GameComponent(self) -> IGameComponent: ...

class GameServiceContainer:
    def __init__(self) -> None: ...
    def AddService(self, type: type, provider: object) -> None: ...
    def RemoveService(self, type: type) -> None: ...
    def GetService(self, type: type) -> object: ...

class GameTime:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, totalGameTime: timedelta, elapsedGameTime: timedelta, isRunningSlowly: bool) -> None: ...
    @overload
    def __init__(self, totalGameTime: timedelta, elapsedGameTime: timedelta) -> None: ...
    @property
    def TotalGameTime(self) -> timedelta: ...
    @property
    def ElapsedGameTime(self) -> timedelta: ...
    @property
    def IsRunningSlowly(self) -> bool: ...

class GameWindow:
    def BeginScreenDeviceChange(self, willBeFullScreen: bool) -> None: ...
    @overload
    def EndScreenDeviceChange(self, screenDeviceName: str, clientWidth: int, clientHeight: int) -> None: ...
    @overload
    def EndScreenDeviceChange(self, screenDeviceName: str) -> None: ...
    def SetTitle(self, title: str) -> None: ...
    def SetSupportedOrientations(self, orientations: DisplayOrientation) -> None: ...
    def OnActivated(self) -> None: ...
    def OnDeactivated(self) -> None: ...
    def OnPaint(self) -> None: ...
    def OnScreenDeviceNameChanged(self) -> None: ...
    def OnClientSizeChanged(self) -> None: ...
    def OnOrientationChanged(self) -> None: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> None: ...
    @property
    def Handle(self) -> IntPtr: ...
    @property
    def AllowUserResizing(self) -> bool: ...
    @AllowUserResizing.setter
    def AllowUserResizing(self, value: bool) -> None: ...
    @property
    def ClientBounds(self) -> Rectangle: ...
    @property
    def ScreenDeviceName(self) -> str: ...
    @property
    def CurrentOrientation(self) -> DisplayOrientation: ...
    ScreenDeviceNameChanged: Final[Event]
    ClientSizeChanged: Final[Event]
    OrientationChanged: Final[Event]

class GraphicsDeviceInformation:
    def __init__(self) -> None: ...
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def Clone(self) -> GraphicsDeviceInformation: ...
    @property
    def Adapter(self) -> GraphicsAdapter: ...
    @Adapter.setter
    def Adapter(self, value: GraphicsAdapter) -> None: ...
    @property
    def GraphicsProfile(self) -> GraphicsProfile: ...
    @GraphicsProfile.setter
    def GraphicsProfile(self, value: GraphicsProfile) -> None: ...
    @property
    def PresentationParameters(self) -> PresentationParameters: ...
    @PresentationParameters.setter
    def PresentationParameters(self, value: PresentationParameters) -> None: ...

class GraphicsDeviceManager:
    def __init__(self, game: Game) -> None: ...
    def ApplyChanges(self) -> None: ...
    def ToggleFullScreen(self) -> None: ...
    def FindBestDevice(self, anySuitableDevice: bool) -> GraphicsDeviceInformation: ...
    def CanResetDevice(self, newDeviceInfo: GraphicsDeviceInformation) -> bool: ...
    def RankDevices(self, foundDevices: list[GraphicsDeviceInformation]) -> None: ...
    def OnDeviceCreated(self, sender: object, args: object) -> None: ...
    def OnDeviceDisposing(self, sender: object, args: object) -> None: ...
    def OnDeviceReset(self, sender: object, args: object) -> None: ...
    def OnDeviceResetting(self, sender: object, args: object) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    def OnPreparingDeviceSettings(self, sender: object, args: PreparingDeviceSettingsEventArgs) -> None: ...
    @property
    def GraphicsProfile(self) -> GraphicsProfile: ...
    @GraphicsProfile.setter
    def GraphicsProfile(self, value: GraphicsProfile) -> None: ...
    @property
    def PreferredDepthStencilFormat(self) -> DepthFormat: ...
    @PreferredDepthStencilFormat.setter
    def PreferredDepthStencilFormat(self, value: DepthFormat) -> None: ...
    @property
    def PreferredBackBufferFormat(self) -> SurfaceFormat: ...
    @PreferredBackBufferFormat.setter
    def PreferredBackBufferFormat(self, value: SurfaceFormat) -> None: ...
    @property
    def PreferredBackBufferWidth(self) -> int: ...
    @PreferredBackBufferWidth.setter
    def PreferredBackBufferWidth(self, value: int) -> None: ...
    @property
    def PreferredBackBufferHeight(self) -> int: ...
    @PreferredBackBufferHeight.setter
    def PreferredBackBufferHeight(self, value: int) -> None: ...
    @property
    def IsFullScreen(self) -> bool: ...
    @IsFullScreen.setter
    def IsFullScreen(self, value: bool) -> None: ...
    @property
    def SynchronizeWithVerticalRetrace(self) -> bool: ...
    @SynchronizeWithVerticalRetrace.setter
    def SynchronizeWithVerticalRetrace(self, value: bool) -> None: ...
    @property
    def PreferMultiSampling(self) -> bool: ...
    @PreferMultiSampling.setter
    def PreferMultiSampling(self, value: bool) -> None: ...
    @property
    def SupportedOrientations(self) -> DisplayOrientation: ...
    @SupportedOrientations.setter
    def SupportedOrientations(self, value: DisplayOrientation) -> None: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    DeviceCreated: Final[Event]
    DeviceResetting: Final[Event]
    DeviceReset: Final[Event]
    DeviceDisposing: Final[Event]
    PreparingDeviceSettings: Final[Event]
    Disposed: Final[Event]
    DefaultBackBufferWidth: ClassVar[int]
    DefaultBackBufferHeight: ClassVar[int]
    def CreateDevice(self) -> None: ...
    def BeginDraw(self) -> bool: ...
    def EndDraw(self) -> None: ...
    def __enter__(self) -> GraphicsDeviceManager: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class IDrawable:
    def Draw(self, gameTime: GameTime) -> None: ...
    @property
    def Visible(self) -> bool: ...
    @property
    def DrawOrder(self) -> int: ...
    VisibleChanged: Final[Event]
    DrawOrderChanged: Final[Event]

class IGameComponent:
    def Initialize(self) -> None: ...

class IGraphicsDeviceManager:
    def CreateDevice(self) -> None: ...
    def BeginDraw(self) -> bool: ...
    def EndDraw(self) -> None: ...

class IUpdateable:
    def Update(self, gameTime: GameTime) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @property
    def UpdateOrder(self) -> int: ...
    EnabledChanged: Final[Event]
    UpdateOrderChanged: Final[Event]

class LaunchParameters:
    def __init__(self) -> None: ...

class MathHelper:
    @staticmethod
    def ToRadians(degrees: float) -> float: ...
    @staticmethod
    def ToDegrees(radians: float) -> float: ...
    @staticmethod
    def Distance(value1: float, value2: float) -> float: ...
    @staticmethod
    def Min(value1: float, value2: float) -> float: ...
    @staticmethod
    def Max(value1: float, value2: float) -> float: ...
    @staticmethod
    def Clamp(value: float, min: float, max: float) -> float: ...
    @staticmethod
    def Lerp(value1: float, value2: float, amount: float) -> float: ...
    @staticmethod
    def Barycentric(value1: float, value2: float, value3: float, amount1: float, amount2: float) -> float: ...
    @staticmethod
    def SmoothStep(value1: float, value2: float, amount: float) -> float: ...
    @staticmethod
    def CatmullRom(value1: float, value2: float, value3: float, value4: float, amount: float) -> float: ...
    @staticmethod
    def Hermite(value1: float, tangent1: float, value2: float, tangent2: float, amount: float) -> float: ...
    @staticmethod
    def WrapAngle(angle: float) -> float: ...
    E: Final[float]
    Log2E: Final[float]
    Log10E: Final[float]
    Pi: Final[float]
    TwoPi: Final[float]
    PiOver2: Final[float]
    PiOver4: Final[float]

class Matrix:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, m11: float, m12: float, m13: float, m14: float, m21: float, m22: float, m23: float, m24: float, m31: float, m32: float, m33: float, m34: float, m41: float, m42: float, m43: float, m44: float) -> None: ...
    @staticmethod
    def CreateBillboard(objectPosition: Vector3, cameraPosition: Vector3, cameraUpVector: Vector3, cameraForwardVector: Vector3 | None) -> Matrix: ...
    @staticmethod
    def CreateConstrainedBillboard(objectPosition: Vector3, cameraPosition: Vector3, rotateAxis: Vector3, cameraForwardVector: Vector3 | None, objectForwardVector: Vector3 | None) -> Matrix: ...
    @overload
    @staticmethod
    def CreateTranslation(position: Vector3) -> Matrix: ...
    @overload
    @staticmethod
    def CreateTranslation(xPosition: float, yPosition: float, zPosition: float) -> Matrix: ...
    @overload
    @staticmethod
    def CreateScale(xScale: float, yScale: float, zScale: float) -> Matrix: ...
    @overload
    @staticmethod
    def CreateScale(scales: Vector3) -> Matrix: ...
    @overload
    @staticmethod
    def CreateScale(scale: float) -> Matrix: ...
    @staticmethod
    def CreateRotationX(radians: float) -> Matrix: ...
    @staticmethod
    def CreateRotationY(radians: float) -> Matrix: ...
    @staticmethod
    def CreateRotationZ(radians: float) -> Matrix: ...
    @staticmethod
    def CreateFromAxisAngle(axis: Vector3, angle: float) -> Matrix: ...
    @staticmethod
    def CreatePerspectiveFieldOfView(fieldOfView: float, aspectRatio: float, nearPlaneDistance: float, farPlaneDistance: float) -> Matrix: ...
    @staticmethod
    def CreatePerspective(width: float, height: float, nearPlaneDistance: float, farPlaneDistance: float) -> Matrix: ...
    @staticmethod
    def CreatePerspectiveOffCenter(left: float, right: float, bottom: float, top: float, nearPlaneDistance: float, farPlaneDistance: float) -> Matrix: ...
    @staticmethod
    def CreateOrthographic(width: float, height: float, zNearPlane: float, zFarPlane: float) -> Matrix: ...
    @staticmethod
    def CreateOrthographicOffCenter(left: float, right: float, bottom: float, top: float, zNearPlane: float, zFarPlane: float) -> Matrix: ...
    @staticmethod
    def CreateLookAt(cameraPosition: Vector3, cameraTarget: Vector3, cameraUpVector: Vector3) -> Matrix: ...
    @staticmethod
    def CreateWorld(position: Vector3, forward: Vector3, up: Vector3) -> Matrix: ...
    @staticmethod
    def CreateFromQuaternion(quaternion: Quaternion) -> Matrix: ...
    @staticmethod
    def CreateFromYawPitchRoll(yaw: float, pitch: float, roll: float) -> Matrix: ...
    @staticmethod
    def CreateShadow(lightDirection: Vector3, plane: Plane) -> Matrix: ...
    @staticmethod
    def CreateReflection(value: Plane) -> Matrix: ...
    def Decompose(self) -> tuple[bool, Vector3, Quaternion, Vector3]: ...
    @staticmethod
    def Transform(value: Matrix, rotation: Quaternion) -> Matrix: ...
    def ToString(self) -> str: ...
    @overload
    def Equals(self, other: Matrix) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def Transpose(matrix: Matrix) -> Matrix: ...
    def Determinant(self) -> float: ...
    @staticmethod
    def Invert(matrix: Matrix) -> Matrix: ...
    @staticmethod
    def Lerp(matrix1: Matrix, matrix2: Matrix, amount: float) -> Matrix: ...
    @staticmethod
    def Negate(matrix: Matrix) -> Matrix: ...
    @staticmethod
    def Add(matrix1: Matrix, matrix2: Matrix) -> Matrix: ...
    @staticmethod
    def Subtract(matrix1: Matrix, matrix2: Matrix) -> Matrix: ...
    @overload
    @staticmethod
    def Multiply(matrix1: Matrix, matrix2: Matrix) -> Matrix: ...
    @overload
    @staticmethod
    def Multiply(matrix1: Matrix, scaleFactor: float) -> Matrix: ...
    @overload
    @staticmethod
    def Divide(matrix1: Matrix, matrix2: Matrix) -> Matrix: ...
    @overload
    @staticmethod
    def Divide(matrix1: Matrix, divider: float) -> Matrix: ...
    def __neg__(self) -> Matrix: ...
    def __eq__(self, matrix2: Matrix) -> bool: ...
    def __ne__(self, matrix2: Matrix) -> bool: ...
    def __add__(self, matrix2: Matrix) -> Matrix: ...
    def __sub__(self, matrix2: Matrix) -> Matrix: ...
    @overload
    def __mul__(self, matrix2: Matrix) -> Matrix: ...
    @overload
    def __mul__(self, scaleFactor: float) -> Matrix: ...
    @overload
    def __mul__(self, matrix: Matrix) -> Matrix: ...
    @overload
    def __truediv__(self, matrix2: Matrix) -> Matrix: ...
    @overload
    def __truediv__(self, divider: float) -> Matrix: ...
    Identity: Final[Matrix]
    @property
    def Up(self) -> Vector3: ...
    @Up.setter
    def Up(self, value: Vector3) -> None: ...
    @property
    def Down(self) -> Vector3: ...
    @Down.setter
    def Down(self, value: Vector3) -> None: ...
    @property
    def Right(self) -> Vector3: ...
    @Right.setter
    def Right(self, value: Vector3) -> None: ...
    @property
    def Left(self) -> Vector3: ...
    @Left.setter
    def Left(self, value: Vector3) -> None: ...
    @property
    def Forward(self) -> Vector3: ...
    @Forward.setter
    def Forward(self, value: Vector3) -> None: ...
    @property
    def Backward(self) -> Vector3: ...
    @Backward.setter
    def Backward(self, value: Vector3) -> None: ...
    @property
    def Translation(self) -> Vector3: ...
    @Translation.setter
    def Translation(self, value: Vector3) -> None: ...
    M11: float
    M12: float
    M13: float
    M14: float
    M21: float
    M22: float
    M23: float
    M24: float
    M31: float
    M32: float
    M33: float
    M34: float
    M41: float
    M42: float
    M43: float
    M44: float
    def __copy__(self) -> Matrix: ...
    def __deepcopy__(self, memo: object) -> Matrix: ...

class Plane:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, a: float, b: float, c: float, d: float) -> None: ...
    @overload
    def __init__(self, normal: Vector3, d: float) -> None: ...
    @overload
    def __init__(self, value: Vector4) -> None: ...
    @overload
    def __init__(self, point1: Vector3, point2: Vector3, point3: Vector3) -> None: ...
    @overload
    def Equals(self, other: Plane) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...
    @overload
    def Normalize(self) -> None: ...
    @overload
    @staticmethod
    def Normalize(value: Plane) -> Plane: ...
    @overload
    @staticmethod
    def Transform(plane: Plane, matrix: Matrix) -> Plane: ...
    @overload
    @staticmethod
    def Transform(plane: Plane, rotation: Quaternion) -> Plane: ...
    def Dot(self, value: Vector4) -> float: ...
    def DotCoordinate(self, value: Vector3) -> float: ...
    def DotNormal(self, value: Vector3) -> float: ...
    @overload
    def Intersects(self, box: BoundingBox) -> PlaneIntersectionType: ...
    @overload
    def Intersects(self, frustum: BoundingFrustum) -> PlaneIntersectionType: ...
    @overload
    def Intersects(self, sphere: BoundingSphere) -> PlaneIntersectionType: ...
    def __eq__(self, rhs: Plane) -> bool: ...
    def __ne__(self, rhs: Plane) -> bool: ...
    Normal: Vector3
    D: float
    def __copy__(self) -> Plane: ...
    def __deepcopy__(self, memo: object) -> Plane: ...

class PlaneIntersectionType(IntEnum):
    Front: int
    Back: int
    Intersecting: int

class PlayerIndex(IntEnum):
    One: int
    Two: int
    Three: int
    Four: int

class Point:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: int, y: int) -> None: ...
    @overload
    def Equals(self, other: Point) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...
    def __eq__(self, b: Point) -> bool: ...
    def __ne__(self, b: Point) -> bool: ...
    Zero: Final[Point]
    X: int
    Y: int
    def __copy__(self) -> Point: ...
    def __deepcopy__(self, memo: object) -> Point: ...

class PreparingDeviceSettingsEventArgs:
    def __init__(self, graphicsDeviceInformation: GraphicsDeviceInformation) -> None: ...
    @property
    def GraphicsDeviceInformation(self) -> GraphicsDeviceInformation: ...

class Quaternion:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @overload
    def __init__(self, vectorPart: Vector3, scalarPart: float) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def Equals(self, other: Quaternion) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def LengthSquared(self) -> float: ...
    def Length(self) -> float: ...
    @overload
    def Normalize(self) -> None: ...
    @overload
    @staticmethod
    def Normalize(quaternion: Quaternion) -> Quaternion: ...
    @overload
    def Conjugate(self) -> None: ...
    @overload
    @staticmethod
    def Conjugate(value: Quaternion) -> Quaternion: ...
    @staticmethod
    def Inverse(quaternion: Quaternion) -> Quaternion: ...
    @staticmethod
    def CreateFromAxisAngle(axis: Vector3, angle: float) -> Quaternion: ...
    @staticmethod
    def CreateFromYawPitchRoll(yaw: float, pitch: float, roll: float) -> Quaternion: ...
    @staticmethod
    def CreateFromRotationMatrix(matrix: Matrix) -> Quaternion: ...
    @staticmethod
    def Dot(quaternion1: Quaternion, quaternion2: Quaternion) -> float: ...
    @staticmethod
    def Slerp(quaternion1: Quaternion, quaternion2: Quaternion, amount: float) -> Quaternion: ...
    @staticmethod
    def Lerp(quaternion1: Quaternion, quaternion2: Quaternion, amount: float) -> Quaternion: ...
    @staticmethod
    def Concatenate(value1: Quaternion, value2: Quaternion) -> Quaternion: ...
    @staticmethod
    def Negate(quaternion: Quaternion) -> Quaternion: ...
    @staticmethod
    def Add(quaternion1: Quaternion, quaternion2: Quaternion) -> Quaternion: ...
    @staticmethod
    def Subtract(quaternion1: Quaternion, quaternion2: Quaternion) -> Quaternion: ...
    @overload
    @staticmethod
    def Multiply(quaternion1: Quaternion, quaternion2: Quaternion) -> Quaternion: ...
    @overload
    @staticmethod
    def Multiply(quaternion1: Quaternion, scaleFactor: float) -> Quaternion: ...
    @staticmethod
    def Divide(quaternion1: Quaternion, quaternion2: Quaternion) -> Quaternion: ...
    def __neg__(self) -> Quaternion: ...
    def __eq__(self, quaternion2: Quaternion) -> bool: ...
    def __ne__(self, quaternion2: Quaternion) -> bool: ...
    def __add__(self, quaternion2: Quaternion) -> Quaternion: ...
    def __sub__(self, quaternion2: Quaternion) -> Quaternion: ...
    @overload
    def __mul__(self, quaternion2: Quaternion) -> Quaternion: ...
    @overload
    def __mul__(self, scaleFactor: float) -> Quaternion: ...
    def __truediv__(self, quaternion2: Quaternion) -> Quaternion: ...
    Identity: Final[Quaternion]
    X: float
    Y: float
    Z: float
    W: float
    def __copy__(self) -> Quaternion: ...
    def __deepcopy__(self, memo: object) -> Quaternion: ...

class Ray:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, position: Vector3, direction: Vector3) -> None: ...
    @overload
    def Equals(self, other: Ray) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...
    @overload
    def Intersects(self, box: BoundingBox) -> float | None: ...
    @overload
    def Intersects(self, frustum: BoundingFrustum) -> float | None: ...
    @overload
    def Intersects(self, plane: Plane) -> float | None: ...
    @overload
    def Intersects(self, sphere: BoundingSphere) -> float | None: ...
    def __eq__(self, b: Ray) -> bool: ...
    def __ne__(self, b: Ray) -> bool: ...
    Position: Vector3
    Direction: Vector3
    def __copy__(self) -> Ray: ...
    def __deepcopy__(self, memo: object) -> Ray: ...

class Rectangle:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...
    @overload
    def Offset(self, amount: Point) -> None: ...
    @overload
    def Offset(self, offsetX: int, offsetY: int) -> None: ...
    def Inflate(self, horizontalAmount: int, verticalAmount: int) -> None: ...
    @overload
    def Contains(self, x: int, y: int) -> bool: ...
    @overload
    def Contains(self, value: Point) -> bool: ...
    @overload
    def Contains(self, value: Rectangle) -> bool: ...
    def Intersects(self, value: Rectangle) -> bool: ...
    @staticmethod
    def Intersect(value1: Rectangle, value2: Rectangle) -> Rectangle: ...
    @staticmethod
    def Union(value1: Rectangle, value2: Rectangle) -> Rectangle: ...
    @overload
    def Equals(self, other: Rectangle) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, b: Rectangle) -> bool: ...
    def __ne__(self, b: Rectangle) -> bool: ...
    @property
    def Left(self) -> int: ...
    @property
    def Right(self) -> int: ...
    @property
    def Top(self) -> int: ...
    @property
    def Bottom(self) -> int: ...
    @property
    def Location(self) -> Point: ...
    @Location.setter
    def Location(self, value: Point) -> None: ...
    @property
    def Center(self) -> Point: ...
    Empty: Final[Rectangle]
    @property
    def IsEmpty(self) -> bool: ...
    X: int
    Y: int
    Width: int
    Height: int
    def __copy__(self) -> Rectangle: ...
    def __deepcopy__(self, memo: object) -> Rectangle: ...

class Vector2:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    @overload
    def __init__(self, value: float) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def Equals(self, other: Vector2) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def Length(self) -> float: ...
    def LengthSquared(self) -> float: ...
    @staticmethod
    def Distance(value1: Vector2, value2: Vector2) -> float: ...
    @staticmethod
    def DistanceSquared(value1: Vector2, value2: Vector2) -> float: ...
    @staticmethod
    def Dot(value1: Vector2, value2: Vector2) -> float: ...
    @overload
    def Normalize(self) -> None: ...
    @overload
    @staticmethod
    def Normalize(value: Vector2) -> Vector2: ...
    @staticmethod
    def Reflect(vector: Vector2, normal: Vector2) -> Vector2: ...
    @staticmethod
    def Min(value1: Vector2, value2: Vector2) -> Vector2: ...
    @staticmethod
    def Max(value1: Vector2, value2: Vector2) -> Vector2: ...
    @staticmethod
    def Clamp(value1: Vector2, min: Vector2, max: Vector2) -> Vector2: ...
    @staticmethod
    def Lerp(value1: Vector2, value2: Vector2, amount: float) -> Vector2: ...
    @staticmethod
    def Barycentric(value1: Vector2, value2: Vector2, value3: Vector2, amount1: float, amount2: float) -> Vector2: ...
    @staticmethod
    def SmoothStep(value1: Vector2, value2: Vector2, amount: float) -> Vector2: ...
    @staticmethod
    def CatmullRom(value1: Vector2, value2: Vector2, value3: Vector2, value4: Vector2, amount: float) -> Vector2: ...
    @staticmethod
    def Hermite(value1: Vector2, tangent1: Vector2, value2: Vector2, tangent2: Vector2, amount: float) -> Vector2: ...
    @overload
    @staticmethod
    def Transform(position: Vector2, matrix: Matrix) -> Vector2: ...
    @overload
    @staticmethod
    def Transform(value: Vector2, rotation: Quaternion) -> Vector2: ...
    @overload
    @staticmethod
    def Transform(sourceArray: Sequence[Vector2], matrix: Matrix, destinationArray: MutableSequence[Vector2]) -> None: ...
    @overload
    @staticmethod
    def Transform(sourceArray: Sequence[Vector2], sourceIndex: int, matrix: Matrix, destinationArray: MutableSequence[Vector2], destinationIndex: int, length: int) -> None: ...
    @overload
    @staticmethod
    def Transform(sourceArray: Sequence[Vector2], rotation: Quaternion, destinationArray: MutableSequence[Vector2]) -> None: ...
    @overload
    @staticmethod
    def Transform(sourceArray: Sequence[Vector2], sourceIndex: int, rotation: Quaternion, destinationArray: MutableSequence[Vector2], destinationIndex: int, length: int) -> None: ...
    @overload
    @staticmethod
    def TransformNormal(normal: Vector2, matrix: Matrix) -> Vector2: ...
    @overload
    @staticmethod
    def TransformNormal(sourceArray: Sequence[Vector2], matrix: Matrix, destinationArray: MutableSequence[Vector2]) -> None: ...
    @overload
    @staticmethod
    def TransformNormal(sourceArray: Sequence[Vector2], sourceIndex: int, matrix: Matrix, destinationArray: MutableSequence[Vector2], destinationIndex: int, length: int) -> None: ...
    @staticmethod
    def Negate(value: Vector2) -> Vector2: ...
    @staticmethod
    def Add(value1: Vector2, value2: Vector2) -> Vector2: ...
    @staticmethod
    def Subtract(value1: Vector2, value2: Vector2) -> Vector2: ...
    @overload
    @staticmethod
    def Multiply(value1: Vector2, value2: Vector2) -> Vector2: ...
    @overload
    @staticmethod
    def Multiply(value1: Vector2, scaleFactor: float) -> Vector2: ...
    @overload
    @staticmethod
    def Divide(value1: Vector2, value2: Vector2) -> Vector2: ...
    @overload
    @staticmethod
    def Divide(value1: Vector2, divider: float) -> Vector2: ...
    def __neg__(self) -> Vector2: ...
    def __eq__(self, value2: Vector2) -> bool: ...
    def __ne__(self, value2: Vector2) -> bool: ...
    def __add__(self, value2: Vector2) -> Vector2: ...
    def __sub__(self, value2: Vector2) -> Vector2: ...
    @overload
    def __mul__(self, value2: Vector2) -> Vector2: ...
    @overload
    def __mul__(self, scaleFactor: float) -> Vector2: ...
    @overload
    def __mul__(self, value: Vector2) -> Vector2: ...
    @overload
    def __truediv__(self, value2: Vector2) -> Vector2: ...
    @overload
    def __truediv__(self, divider: float) -> Vector2: ...
    Zero: Final[Vector2]
    One: Final[Vector2]
    UnitX: Final[Vector2]
    UnitY: Final[Vector2]
    X: float
    Y: float
    def __copy__(self) -> Vector2: ...
    def __deepcopy__(self, memo: object) -> Vector2: ...

class Vector3:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @overload
    def __init__(self, value: float) -> None: ...
    @overload
    def __init__(self, value: Vector2, z: float) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def Equals(self, other: Vector3) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def Length(self) -> float: ...
    def LengthSquared(self) -> float: ...
    @staticmethod
    def Distance(value1: Vector3, value2: Vector3) -> float: ...
    @staticmethod
    def DistanceSquared(value1: Vector3, value2: Vector3) -> float: ...
    @staticmethod
    def Dot(vector1: Vector3, vector2: Vector3) -> float: ...
    @overload
    def Normalize(self) -> None: ...
    @overload
    @staticmethod
    def Normalize(value: Vector3) -> Vector3: ...
    @staticmethod
    def Cross(vector1: Vector3, vector2: Vector3) -> Vector3: ...
    @staticmethod
    def Reflect(vector: Vector3, normal: Vector3) -> Vector3: ...
    @staticmethod
    def Min(value1: Vector3, value2: Vector3) -> Vector3: ...
    @staticmethod
    def Max(value1: Vector3, value2: Vector3) -> Vector3: ...
    @staticmethod
    def Clamp(value1: Vector3, min: Vector3, max: Vector3) -> Vector3: ...
    @staticmethod
    def Lerp(value1: Vector3, value2: Vector3, amount: float) -> Vector3: ...
    @staticmethod
    def Barycentric(value1: Vector3, value2: Vector3, value3: Vector3, amount1: float, amount2: float) -> Vector3: ...
    @staticmethod
    def SmoothStep(value1: Vector3, value2: Vector3, amount: float) -> Vector3: ...
    @staticmethod
    def CatmullRom(value1: Vector3, value2: Vector3, value3: Vector3, value4: Vector3, amount: float) -> Vector3: ...
    @staticmethod
    def Hermite(value1: Vector3, tangent1: Vector3, value2: Vector3, tangent2: Vector3, amount: float) -> Vector3: ...
    @overload
    @staticmethod
    def Transform(position: Vector3, matrix: Matrix) -> Vector3: ...
    @overload
    @staticmethod
    def Transform(value: Vector3, rotation: Quaternion) -> Vector3: ...
    @overload
    @staticmethod
    def Transform(sourceArray: Sequence[Vector3], matrix: Matrix, destinationArray: MutableSequence[Vector3]) -> None: ...
    @overload
    @staticmethod
    def Transform(sourceArray: Sequence[Vector3], sourceIndex: int, matrix: Matrix, destinationArray: MutableSequence[Vector3], destinationIndex: int, length: int) -> None: ...
    @overload
    @staticmethod
    def Transform(sourceArray: Sequence[Vector3], rotation: Quaternion, destinationArray: MutableSequence[Vector3]) -> None: ...
    @overload
    @staticmethod
    def Transform(sourceArray: Sequence[Vector3], sourceIndex: int, rotation: Quaternion, destinationArray: MutableSequence[Vector3], destinationIndex: int, length: int) -> None: ...
    @overload
    @staticmethod
    def TransformNormal(normal: Vector3, matrix: Matrix) -> Vector3: ...
    @overload
    @staticmethod
    def TransformNormal(sourceArray: Sequence[Vector3], matrix: Matrix, destinationArray: MutableSequence[Vector3]) -> None: ...
    @overload
    @staticmethod
    def TransformNormal(sourceArray: Sequence[Vector3], sourceIndex: int, matrix: Matrix, destinationArray: MutableSequence[Vector3], destinationIndex: int, length: int) -> None: ...
    @staticmethod
    def Negate(value: Vector3) -> Vector3: ...
    @staticmethod
    def Add(value1: Vector3, value2: Vector3) -> Vector3: ...
    @staticmethod
    def Subtract(value1: Vector3, value2: Vector3) -> Vector3: ...
    @overload
    @staticmethod
    def Multiply(value1: Vector3, value2: Vector3) -> Vector3: ...
    @overload
    @staticmethod
    def Multiply(value1: Vector3, scaleFactor: float) -> Vector3: ...
    @overload
    @staticmethod
    def Divide(value1: Vector3, value2: Vector3) -> Vector3: ...
    @overload
    @staticmethod
    def Divide(value1: Vector3, value2: float) -> Vector3: ...
    def __neg__(self) -> Vector3: ...
    def __eq__(self, value2: Vector3) -> bool: ...
    def __ne__(self, value2: Vector3) -> bool: ...
    def __add__(self, value2: Vector3) -> Vector3: ...
    def __sub__(self, value2: Vector3) -> Vector3: ...
    @overload
    def __mul__(self, value2: Vector3) -> Vector3: ...
    @overload
    def __mul__(self, scaleFactor: float) -> Vector3: ...
    @overload
    def __mul__(self, value: Vector3) -> Vector3: ...
    @overload
    def __truediv__(self, value2: Vector3) -> Vector3: ...
    @overload
    def __truediv__(self, divider: float) -> Vector3: ...
    Zero: Final[Vector3]
    One: Final[Vector3]
    UnitX: Final[Vector3]
    UnitY: Final[Vector3]
    UnitZ: Final[Vector3]
    Up: Final[Vector3]
    Down: Final[Vector3]
    Right: Final[Vector3]
    Left: Final[Vector3]
    Forward: Final[Vector3]
    Backward: Final[Vector3]
    X: float
    Y: float
    Z: float
    def __copy__(self) -> Vector3: ...
    def __deepcopy__(self, memo: object) -> Vector3: ...

class Vector4:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @overload
    def __init__(self, value: Vector2, z: float, w: float) -> None: ...
    @overload
    def __init__(self, value: Vector3, w: float) -> None: ...
    @overload
    def __init__(self, value: float) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def Equals(self, other: Vector4) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def Length(self) -> float: ...
    def LengthSquared(self) -> float: ...
    @staticmethod
    def Distance(value1: Vector4, value2: Vector4) -> float: ...
    @staticmethod
    def DistanceSquared(value1: Vector4, value2: Vector4) -> float: ...
    @staticmethod
    def Dot(vector1: Vector4, vector2: Vector4) -> float: ...
    @overload
    def Normalize(self) -> None: ...
    @overload
    @staticmethod
    def Normalize(vector: Vector4) -> Vector4: ...
    @staticmethod
    def Min(value1: Vector4, value2: Vector4) -> Vector4: ...
    @staticmethod
    def Max(value1: Vector4, value2: Vector4) -> Vector4: ...
    @staticmethod
    def Clamp(value1: Vector4, min: Vector4, max: Vector4) -> Vector4: ...
    @staticmethod
    def Lerp(value1: Vector4, value2: Vector4, amount: float) -> Vector4: ...
    @staticmethod
    def Barycentric(value1: Vector4, value2: Vector4, value3: Vector4, amount1: float, amount2: float) -> Vector4: ...
    @staticmethod
    def SmoothStep(value1: Vector4, value2: Vector4, amount: float) -> Vector4: ...
    @staticmethod
    def CatmullRom(value1: Vector4, value2: Vector4, value3: Vector4, value4: Vector4, amount: float) -> Vector4: ...
    @staticmethod
    def Hermite(value1: Vector4, tangent1: Vector4, value2: Vector4, tangent2: Vector4, amount: float) -> Vector4: ...
    @overload
    @staticmethod
    def Transform(position: Vector2, matrix: Matrix) -> Vector4: ...
    @overload
    @staticmethod
    def Transform(position: Vector3, matrix: Matrix) -> Vector4: ...
    @overload
    @staticmethod
    def Transform(vector: Vector4, matrix: Matrix) -> Vector4: ...
    @overload
    @staticmethod
    def Transform(value: Vector2, rotation: Quaternion) -> Vector4: ...
    @overload
    @staticmethod
    def Transform(value: Vector3, rotation: Quaternion) -> Vector4: ...
    @overload
    @staticmethod
    def Transform(value: Vector4, rotation: Quaternion) -> Vector4: ...
    @overload
    @staticmethod
    def Transform(sourceArray: Sequence[Vector4], matrix: Matrix, destinationArray: MutableSequence[Vector4]) -> None: ...
    @overload
    @staticmethod
    def Transform(sourceArray: Sequence[Vector4], sourceIndex: int, matrix: Matrix, destinationArray: MutableSequence[Vector4], destinationIndex: int, length: int) -> None: ...
    @overload
    @staticmethod
    def Transform(sourceArray: Sequence[Vector4], rotation: Quaternion, destinationArray: MutableSequence[Vector4]) -> None: ...
    @overload
    @staticmethod
    def Transform(sourceArray: Sequence[Vector4], sourceIndex: int, rotation: Quaternion, destinationArray: MutableSequence[Vector4], destinationIndex: int, length: int) -> None: ...
    @staticmethod
    def Negate(value: Vector4) -> Vector4: ...
    @staticmethod
    def Add(value1: Vector4, value2: Vector4) -> Vector4: ...
    @staticmethod
    def Subtract(value1: Vector4, value2: Vector4) -> Vector4: ...
    @overload
    @staticmethod
    def Multiply(value1: Vector4, value2: Vector4) -> Vector4: ...
    @overload
    @staticmethod
    def Multiply(value1: Vector4, scaleFactor: float) -> Vector4: ...
    @overload
    @staticmethod
    def Divide(value1: Vector4, value2: Vector4) -> Vector4: ...
    @overload
    @staticmethod
    def Divide(value1: Vector4, divider: float) -> Vector4: ...
    def __neg__(self) -> Vector4: ...
    def __eq__(self, value2: Vector4) -> bool: ...
    def __ne__(self, value2: Vector4) -> bool: ...
    def __add__(self, value2: Vector4) -> Vector4: ...
    def __sub__(self, value2: Vector4) -> Vector4: ...
    @overload
    def __mul__(self, value2: Vector4) -> Vector4: ...
    @overload
    def __mul__(self, scaleFactor: float) -> Vector4: ...
    @overload
    def __mul__(self, value1: Vector4) -> Vector4: ...
    @overload
    def __truediv__(self, value2: Vector4) -> Vector4: ...
    @overload
    def __truediv__(self, divider: float) -> Vector4: ...
    Zero: Final[Vector4]
    One: Final[Vector4]
    UnitX: Final[Vector4]
    UnitY: Final[Vector4]
    UnitZ: Final[Vector4]
    UnitW: Final[Vector4]
    X: float
    Y: float
    Z: float
    W: float
    def __copy__(self) -> Vector4: ...
    def __deepcopy__(self, memo: object) -> Vector4: ...
