from datetime import timedelta
from enum import IntEnum, IntFlag
from typing import Callable, ClassVar, Final, Iterator, MutableSequence, Sequence, overload
from ... import DisplayOrientation, Vector2

class GestureSample:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, gestureType: GestureType, timestamp: timedelta, position: Vector2, position2: Vector2, delta: Vector2, delta2: Vector2) -> None: ...
    @property
    def Delta(self) -> Vector2: ...
    @property
    def Delta2(self) -> Vector2: ...
    @property
    def GestureType(self) -> GestureType: ...
    @property
    def Position(self) -> Vector2: ...
    @property
    def Position2(self) -> Vector2: ...
    @property
    def Timestamp(self) -> timedelta: ...
    def __copy__(self) -> GestureSample: ...
    def __deepcopy__(self, memo: object) -> GestureSample: ...

class GestureType(IntFlag):
    DoubleTap: int
    DragComplete: int
    Flick: int
    FreeDrag: int
    Hold: int
    HorizontalDrag: int
    None_: int
    Pinch: int
    PinchComplete: int
    Tap: int
    VerticalDrag: int

class TouchCollection:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, touches: Sequence[TouchLocation]) -> None: ...
    def FindById(self, id: int) -> tuple[bool, TouchLocation]: ...
    def IndexOf(self, item: TouchLocation) -> int: ...
    def Insert(self, index: int, item: TouchLocation) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def Add(self, item: TouchLocation) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, item: TouchLocation) -> bool: ...
    def CopyTo(self, array: MutableSequence[TouchLocation], arrayIndex: int) -> None: ...
    def Remove(self, item: TouchLocation) -> bool: ...
    def GetEnumerator(self) -> TouchCollection.Enumerator: ...
    @property
    def Count(self) -> int: ...
    @property
    def IsConnected(self) -> bool: ...
    @property
    def IsReadOnly(self) -> bool: ...
    def __getitem__(self, index: int) -> TouchLocation: ...
    def __setitem__(self, index: int, value: TouchLocation) -> None: ...
    def __iter__(self) -> Iterator[TouchLocation]: ...
    def __len__(self) -> int: ...
    def __copy__(self) -> TouchCollection: ...
    def __deepcopy__(self, memo: object) -> TouchCollection: ...
    class Enumerator:
        def MoveNext(self) -> bool: ...
        def Dispose(self) -> None: ...
        @property
        def Current(self) -> TouchLocation: ...
        def __iter__(self) -> Iterator[TouchLocation]: ...
        def __next__(self) -> TouchLocation: ...
        def __copy__(self) -> Enumerator: ...
        def __deepcopy__(self, memo: object) -> Enumerator: ...

class TouchLocation:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, id: int, state: TouchLocationState, position: Vector2) -> None: ...
    @overload
    def __init__(self, id: int, state: TouchLocationState, position: Vector2, previousState: TouchLocationState, previousPosition: Vector2) -> None: ...
    def TryGetPreviousLocation(self) -> tuple[bool, TouchLocation]: ...
    def ToString(self) -> str: ...
    @overload
    def Equals(self, other: TouchLocation) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, value2: TouchLocation) -> bool: ...
    def __ne__(self, value2: TouchLocation) -> bool: ...
    @property
    def Id(self) -> int: ...
    @property
    def Position(self) -> Vector2: ...
    @property
    def State(self) -> TouchLocationState: ...
    def __copy__(self) -> TouchLocation: ...
    def __deepcopy__(self, memo: object) -> TouchLocation: ...

class TouchLocationState(IntEnum):
    Invalid: int
    Moved: int
    Pressed: int
    Released: int

class TouchPanel:
    @staticmethod
    def GetCapabilities() -> TouchPanelCapabilities: ...
    @staticmethod
    def ReadGesture() -> GestureSample: ...
    @staticmethod
    def GetState() -> TouchCollection: ...
    DisplayHeight: ClassVar[int]
    DisplayOrientation: ClassVar[DisplayOrientation]
    DisplayWidth: ClassVar[int]
    EnabledGestures: ClassVar[GestureType]
    IsGestureAvailable: Final[bool]
    WindowHandle: ClassVar[int]

class TouchPanelCapabilities:
    @property
    def IsConnected(self) -> bool: ...
    @property
    def MaximumTouchCount(self) -> int: ...
    def __copy__(self) -> TouchPanelCapabilities: ...
    def __deepcopy__(self, memo: object) -> TouchPanelCapabilities: ...
