"""Microsoft.Xna.Framework.Input.Touch, as the Xbox 360 profile has it.

Generated by ``tools/generate_xbox_profile.py`` from the Xbox 360 reference
contract. Do not edit: run the generator, and the test suite checks that running
it changes nothing.
"""

from Microsoft.Xna.Framework.Input.Touch import (
    GestureSample,
    GestureType,
    TouchCollection,
    TouchLocation,
    TouchLocationState,
    TouchPanel,
    TouchPanelCapabilities,
)


__all__ = [
    "GestureSample",
    "GestureType",
    "TouchCollection",
    "TouchLocation",
    "TouchLocationState",
    "TouchPanel",
    "TouchPanelCapabilities",
]
