"""Microsoft.Xna.Framework.Input.Touch, as the XNA 4.0 Xbox 360 runtime profile has it.

Generated by ``tools/generate_platform_profile.py`` from the XNA 4.0 Xbox 360 runtime
reference contract. Do not edit: run the generator, and the test suite checks
that running it changes nothing.
"""

from Microsoft.Xna.Framework.Input.Touch import (
    GestureSample,
    GestureType,
    TouchCollection,
    TouchLocation,
    TouchLocationState,
    TouchPanel,
    TouchPanelCapabilities,
)


__all__ = [
    "GestureSample",
    "GestureType",
    "TouchCollection",
    "TouchLocation",
    "TouchLocationState",
    "TouchPanel",
    "TouchPanelCapabilities",
]
