from typing import Mapping
from .. import BoundingBox, BoundingSphere, Color, Matrix, Plane, Point, Quaternion, Ray, Rectangle, Vector2, Vector3, Vector4

class BoundingBoxConverter(MathTypeConverter):
    def __init__(self) -> None: ...
    def ConvertFrom(self, culture: str | None, value: object) -> object: ...
    def ConvertTo(self, culture: str | None, value: object, destinationType: type) -> object: ...
    def CreateInstance(self, propertyValues: Mapping[str, object]) -> object: ...

class BoundingSphereConverter(MathTypeConverter):
    def __init__(self) -> None: ...
    def ConvertFrom(self, culture: str | None, value: object) -> object: ...
    def ConvertTo(self, culture: str | None, value: object, destinationType: type) -> object: ...
    def CreateInstance(self, propertyValues: Mapping[str, object]) -> object: ...

class ColorConverter(MathTypeConverter):
    def __init__(self) -> None: ...
    def ConvertFrom(self, culture: str | None, value: object) -> object: ...
    def ConvertTo(self, culture: str | None, value: object, destinationType: type) -> object: ...
    def CreateInstance(self, propertyValues: Mapping[str, object]) -> object: ...

class MathTypeConverter:
    def __init__(self) -> None: ...
    def CanConvertFrom(self, sourceType: type) -> bool: ...
    def CanConvertTo(self, destinationType: type) -> bool: ...
    def GetCreateInstanceSupported(self) -> bool: ...
    def GetPropertiesSupported(self) -> bool: ...
    def GetProperties(self, value: object) -> Mapping[str, object]: ...
    propertyDescriptions: Mapping[str, object]
    supportStringConvert: bool

class MatrixConverter(MathTypeConverter):
    def __init__(self) -> None: ...
    def ConvertTo(self, culture: str | None, value: object, destinationType: type) -> object: ...
    def CreateInstance(self, propertyValues: Mapping[str, object]) -> object: ...

class PlaneConverter(MathTypeConverter):
    def __init__(self) -> None: ...
    def ConvertTo(self, culture: str | None, value: object, destinationType: type) -> object: ...
    def CreateInstance(self, propertyValues: Mapping[str, object]) -> object: ...

class PointConverter(MathTypeConverter):
    def __init__(self) -> None: ...
    def ConvertFrom(self, culture: str | None, value: object) -> object: ...
    def ConvertTo(self, culture: str | None, value: object, destinationType: type) -> object: ...
    def CreateInstance(self, propertyValues: Mapping[str, object]) -> object: ...

class QuaternionConverter(MathTypeConverter):
    def __init__(self) -> None: ...
    def ConvertFrom(self, culture: str | None, value: object) -> object: ...
    def ConvertTo(self, culture: str | None, value: object, destinationType: type) -> object: ...
    def CreateInstance(self, propertyValues: Mapping[str, object]) -> object: ...

class RayConverter(MathTypeConverter):
    def __init__(self) -> None: ...
    def ConvertFrom(self, culture: str | None, value: object) -> object: ...
    def ConvertTo(self, culture: str | None, value: object, destinationType: type) -> object: ...
    def CreateInstance(self, propertyValues: Mapping[str, object]) -> object: ...

class RectangleConverter(MathTypeConverter):
    def __init__(self) -> None: ...
    def ConvertTo(self, culture: str | None, value: object, destinationType: type) -> object: ...
    def CreateInstance(self, propertyValues: Mapping[str, object]) -> object: ...

class Vector2Converter(MathTypeConverter):
    def __init__(self) -> None: ...
    def ConvertFrom(self, culture: str | None, value: object) -> object: ...
    def ConvertTo(self, culture: str | None, value: object, destinationType: type) -> object: ...
    def CreateInstance(self, propertyValues: Mapping[str, object]) -> object: ...

class Vector3Converter(MathTypeConverter):
    def __init__(self) -> None: ...
    def ConvertFrom(self, culture: str | None, value: object) -> object: ...
    def ConvertTo(self, culture: str | None, value: object, destinationType: type) -> object: ...
    def CreateInstance(self, propertyValues: Mapping[str, object]) -> object: ...

class Vector4Converter(MathTypeConverter):
    def __init__(self) -> None: ...
    def ConvertFrom(self, culture: str | None, value: object) -> object: ...
    def ConvertTo(self, culture: str | None, value: object, destinationType: type) -> object: ...
    def CreateInstance(self, propertyValues: Mapping[str, object]) -> object: ...
