from typing import Any, BinaryIO, Callable, Final, Generic, TypeVar, overload
from .._language import Event

T = TypeVar("T")

class ContentLoadException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @overload
    def __init__(self, info: object, context: object) -> None: ...

class ContentManager:
    @overload
    def __init__(self, serviceProvider: object) -> None: ...
    @overload
    def __init__(self, serviceProvider: object, rootDirectory: str) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    def Unload(self) -> None: ...
    def Load(self, assetName: str) -> T: ...
    def ReadAsset(self, assetName: str, recordDisposableObject: Callable[[IDisposable], None]) -> T: ...
    def OpenStream(self, assetName: str) -> BinaryIO: ...
    @property
    def ServiceProvider(self) -> object: ...
    @property
    def RootDirectory(self) -> str: ...
    @RootDirectory.setter
    def RootDirectory(self, value: str) -> None: ...
    def __enter__(self) -> ContentManager: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class ContentReader:
    @overload
    def ReadObject(self) -> T: ...
    @overload
    def ReadObject(self, existingInstance: T) -> T: ...
    @overload
    def ReadObject(self, typeReader: ContentTypeReader) -> T: ...
    @overload
    def ReadObject(self, typeReader: ContentTypeReader, existingInstance: T) -> T: ...
    @overload
    def ReadRawObject(self) -> T: ...
    @overload
    def ReadRawObject(self, existingInstance: T) -> T: ...
    @overload
    def ReadRawObject(self, typeReader: ContentTypeReader) -> T: ...
    @overload
    def ReadRawObject(self, typeReader: ContentTypeReader, existingInstance: T) -> T: ...
    def ReadSharedResource(self, fixup: Callable[[T], None]) -> None: ...
    def ReadExternalReference(self) -> T: ...
    def ReadVector2(self) -> Vector2: ...
    def ReadVector3(self) -> Vector3: ...
    def ReadVector4(self) -> Vector4: ...
    def ReadMatrix(self) -> Matrix: ...
    def ReadQuaternion(self) -> Quaternion: ...
    def ReadColor(self) -> Color: ...
    def ReadSingle(self) -> float: ...
    def ReadDouble(self) -> float: ...
    @property
    def ContentManager(self) -> ContentManager: ...
    @property
    def AssetName(self) -> str: ...

class ContentSerializerAttribute:
    def __init__(self) -> None: ...
    def Clone(self) -> ContentSerializerAttribute: ...
    @property
    def ElementName(self) -> str: ...
    @ElementName.setter
    def ElementName(self, value: str) -> None: ...
    @property
    def FlattenContent(self) -> bool: ...
    @FlattenContent.setter
    def FlattenContent(self, value: bool) -> None: ...
    @property
    def Optional(self) -> bool: ...
    @Optional.setter
    def Optional(self, value: bool) -> None: ...
    @property
    def AllowNull(self) -> bool: ...
    @AllowNull.setter
    def AllowNull(self, value: bool) -> None: ...
    @property
    def SharedResource(self) -> bool: ...
    @SharedResource.setter
    def SharedResource(self, value: bool) -> None: ...
    @property
    def CollectionItemName(self) -> str: ...
    @CollectionItemName.setter
    def CollectionItemName(self, value: str) -> None: ...
    @property
    def HasCollectionItemName(self) -> bool: ...

class ContentSerializerCollectionItemNameAttribute:
    def __init__(self, collectionItemName: str) -> None: ...
    @property
    def CollectionItemName(self) -> str: ...

class ContentSerializerIgnoreAttribute:
    def __init__(self) -> None: ...

class ContentSerializerRuntimeTypeAttribute:
    def __init__(self, runtimeType: str) -> None: ...
    @property
    def RuntimeType(self) -> str: ...

class ContentSerializerTypeVersionAttribute:
    def __init__(self, typeVersion: int) -> None: ...
    @property
    def TypeVersion(self) -> int: ...

class ContentTypeReader:
    def __init__(self, targetType: type) -> None: ...
    def Initialize(self, manager: ContentTypeReaderManager) -> None: ...
    def Read(self, input: ContentReader, existingInstance: object) -> object: ...
    @property
    def TargetType(self) -> type: ...
    @property
    def TypeVersion(self) -> int: ...
    @property
    def CanDeserializeIntoExistingObject(self) -> bool: ...

class ContentTypeReaderManager:
    def GetTypeReader(self, targetType: type) -> ContentTypeReader: ...

class ContentTypeReaderOfT(ContentTypeReader, Generic[T]):
    def __init__(self) -> None: ...
    @overload
    def Read(self, input: ContentReader, existingInstance: object) -> object: ...
    @overload
    def Read(self, input: ContentReader, existingInstance: T) -> T: ...

class ResourceContentManager(ContentManager):
    def __init__(self, serviceProvider: object, resourceManager: object) -> None: ...
    def OpenStream(self, assetName: str) -> BinaryIO: ...
