class ContentLoadException(Exception): ...
class ContentManager:
    RootDirectory: str
    def __init__(self, serviceProvider: object, rootDirectory: str = ...) -> None: ...
    def Load(self, assetName: str) -> object: ...
    def Unload(self) -> None: ...
    def Dispose(self) -> None: ...
