from typing import Any, Final, TypeVar, overload
from .._language import Event

T = TypeVar("T")

class ContentLoadException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @overload
    def __init__(self, info: SerializationInfo, context: StreamingContext) -> None: ...

class ContentManager:
    @overload
    def __init__(self, serviceProvider: object) -> None: ...
    @overload
    def __init__(self, serviceProvider: object, rootDirectory: str) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    def Unload(self) -> None: ...
    def Load(self, assetName: str) -> T: ...
    @property
    def ServiceProvider(self) -> object: ...
    @property
    def RootDirectory(self) -> str: ...
    @RootDirectory.setter
    def RootDirectory(self, value: str) -> None: ...
    def __enter__(self) -> ContentManager: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...
