"""Microsoft.Xna.Framework.Media, as the XNA 4.0 Xbox 360 runtime profile has it.

Generated by ``tools/generate_platform_profile.py`` from the XNA 4.0 Xbox 360 runtime
reference contract. Do not edit: run the generator, and the test suite checks
that running it changes nothing.
"""

from Microsoft.Xna.Framework.Media import (
    Album,
    AlbumCollection,
    Artist,
    ArtistCollection,
    Genre,
    GenreCollection,
    MediaLibrary,
    MediaPlayer,
    MediaQueue,
    MediaSource,
    MediaSourceType,
    MediaState,
    Picture,
    PictureAlbum,
    PictureAlbumCollection,
    PictureCollection,
    Playlist,
    PlaylistCollection,
    Song,
    SongCollection,
    Video,
    VideoPlayer,
    VideoSoundtrackType,
    VisualizationData,
)


__all__ = [
    "Album",
    "AlbumCollection",
    "Artist",
    "ArtistCollection",
    "Genre",
    "GenreCollection",
    "MediaLibrary",
    "MediaPlayer",
    "MediaQueue",
    "MediaSource",
    "MediaSourceType",
    "MediaState",
    "Picture",
    "PictureAlbum",
    "PictureAlbumCollection",
    "PictureCollection",
    "Playlist",
    "PlaylistCollection",
    "Song",
    "SongCollection",
    "Video",
    "VideoPlayer",
    "VideoSoundtrackType",
    "VisualizationData",
]
