from typing import Any, Sequence

class BuildContent:
    def __init__(self) -> None: ...
    def Execute(self) -> bool: ...
    @property
    def PipelineAssemblies(self) -> list[object]: ...
    @PipelineAssemblies.setter
    def PipelineAssemblies(self, value: list[object]) -> None: ...
    @property
    def PipelineAssemblyDependencies(self) -> list[object]: ...
    @PipelineAssemblyDependencies.setter
    def PipelineAssemblyDependencies(self, value: list[object]) -> None: ...
    @property
    def SourceAssets(self) -> list[object]: ...
    @SourceAssets.setter
    def SourceAssets(self, value: list[object]) -> None: ...
    @property
    def ContentProjectGUID(self) -> str: ...
    @ContentProjectGUID.setter
    def ContentProjectGUID(self, value: str) -> None: ...
    @property
    def TargetPlatform(self) -> str: ...
    @TargetPlatform.setter
    def TargetPlatform(self, value: str) -> None: ...
    @property
    def TargetProfile(self) -> str: ...
    @TargetProfile.setter
    def TargetProfile(self, value: str) -> None: ...
    @property
    def BuildConfiguration(self) -> str: ...
    @BuildConfiguration.setter
    def BuildConfiguration(self, value: str) -> None: ...
    @property
    def CompressContent(self) -> bool: ...
    @CompressContent.setter
    def CompressContent(self, value: bool) -> None: ...
    @property
    def RootDirectory(self) -> str: ...
    @RootDirectory.setter
    def RootDirectory(self, value: str) -> None: ...
    @property
    def LoggerRootDirectory(self) -> str: ...
    @LoggerRootDirectory.setter
    def LoggerRootDirectory(self, value: str) -> None: ...
    @property
    def IntermediateDirectory(self) -> str: ...
    @IntermediateDirectory.setter
    def IntermediateDirectory(self, value: str) -> None: ...
    @property
    def OutputDirectory(self) -> str: ...
    @OutputDirectory.setter
    def OutputDirectory(self, value: str) -> None: ...
    @property
    def RebuildAll(self) -> bool: ...
    @RebuildAll.setter
    def RebuildAll(self, value: bool) -> None: ...
    @property
    def OutputContentFiles(self) -> list[object]: ...
    @property
    def RebuiltContentFiles(self) -> list[object]: ...
    @property
    def IntermediateFiles(self) -> list[object]: ...
    CancelEventNameFormat: Final[str]

class BuildXact:
    def __init__(self) -> None: ...
    def Execute(self) -> bool: ...
    @property
    def XactProjects(self) -> list[object]: ...
    @XactProjects.setter
    def XactProjects(self, value: list[object]) -> None: ...
    @property
    def XnaFrameworkVersion(self) -> str: ...
    @XnaFrameworkVersion.setter
    def XnaFrameworkVersion(self, value: str) -> None: ...
    @property
    def ContentProjectGUID(self) -> str: ...
    @ContentProjectGUID.setter
    def ContentProjectGUID(self, value: str) -> None: ...
    @property
    def TargetPlatform(self) -> str: ...
    @TargetPlatform.setter
    def TargetPlatform(self, value: str) -> None: ...
    @property
    def TargetProfile(self) -> str: ...
    @TargetProfile.setter
    def TargetProfile(self, value: str) -> None: ...
    @property
    def BuildConfiguration(self) -> str: ...
    @BuildConfiguration.setter
    def BuildConfiguration(self, value: str) -> None: ...
    @property
    def RootDirectory(self) -> str: ...
    @RootDirectory.setter
    def RootDirectory(self, value: str) -> None: ...
    @property
    def LoggerRootDirectory(self) -> str: ...
    @LoggerRootDirectory.setter
    def LoggerRootDirectory(self, value: str) -> None: ...
    @property
    def OutputDirectory(self) -> str: ...
    @OutputDirectory.setter
    def OutputDirectory(self, value: str) -> None: ...
    @property
    def IntermediateDirectory(self) -> str: ...
    @IntermediateDirectory.setter
    def IntermediateDirectory(self, value: str) -> None: ...
    @property
    def RebuildAll(self) -> bool: ...
    @RebuildAll.setter
    def RebuildAll(self, value: bool) -> None: ...
    @property
    def OutputXactFiles(self) -> list[object]: ...
    @property
    def RebuiltXactFiles(self) -> list[object]: ...
    @property
    def IntermediateFiles(self) -> list[object]: ...

class CleanContent:
    def __init__(self) -> None: ...
    def Execute(self) -> bool: ...
    @property
    def ContentProjectGUID(self) -> str: ...
    @ContentProjectGUID.setter
    def ContentProjectGUID(self, value: str) -> None: ...
    @property
    def TargetPlatform(self) -> str: ...
    @TargetPlatform.setter
    def TargetPlatform(self, value: str) -> None: ...
    @property
    def TargetProfile(self) -> str: ...
    @TargetProfile.setter
    def TargetProfile(self, value: str) -> None: ...
    @property
    def BuildConfiguration(self) -> str: ...
    @BuildConfiguration.setter
    def BuildConfiguration(self, value: str) -> None: ...
    @property
    def RootDirectory(self) -> str: ...
    @RootDirectory.setter
    def RootDirectory(self, value: str) -> None: ...
    @property
    def IntermediateDirectory(self) -> str: ...
    @IntermediateDirectory.setter
    def IntermediateDirectory(self, value: str) -> None: ...
    @property
    def OutputDirectory(self) -> str: ...
    @OutputDirectory.setter
    def OutputDirectory(self, value: str) -> None: ...

class GetLastOutputs:
    def __init__(self) -> None: ...
    def Execute(self) -> bool: ...
    @property
    def ContentProjectGUID(self) -> str: ...
    @ContentProjectGUID.setter
    def ContentProjectGUID(self, value: str) -> None: ...
    @property
    def IntermediateDirectory(self) -> str: ...
    @IntermediateDirectory.setter
    def IntermediateDirectory(self, value: str) -> None: ...
    @property
    def OutputContentFiles(self) -> list[object]: ...
