from enum import IntEnum, IntFlag
from typing import BinaryIO, overload
from .. import Color, Matrix, Rectangle, Vector2

class SurfaceFormat(IntEnum): Color: int
class DepthFormat(IntEnum): None_: int; Depth16: int; Depth24: int; Depth24Stencil8: int
class GraphicsProfile(IntEnum): Reach: int; HiDef: int
class SpriteSortMode(IntEnum): Deferred: int; Immediate: int; Texture: int; BackToFront: int; FrontToBack: int
class SpriteEffects(IntFlag): None_: int; FlipHorizontally: int; FlipVertically: int

class Viewport:
    X: int; Y: int; Width: int; Height: int; MinDepth: float; MaxDepth: float
    Bounds: Rectangle; AspectRatio: float
    @overload
    def __init__(self, bounds: Rectangle) -> None: ...
    @overload
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...

class GraphicsDevice:
    Viewport: Viewport
    def Clear(self, color: Color) -> None: ...
    def Dispose(self) -> None: ...

class GraphicsResource:
    IsDisposed: bool; GraphicsDevice: GraphicsDevice; Name: str | None; Tag: object
    def Dispose(self) -> None: ...

class Texture(GraphicsResource): ...

class Texture2D(Texture):
    Width: int; Height: int; Bounds: Rectangle
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int) -> None: ...
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, mipMap: bool, format: SurfaceFormat) -> None: ...
    @staticmethod
    @overload
    def FromStream(graphicsDevice: GraphicsDevice, stream: BinaryIO) -> Texture2D: ...
    @staticmethod
    @overload
    def FromStream(graphicsDevice: GraphicsDevice, stream: BinaryIO, width: int, height: int, zoom: bool) -> Texture2D: ...
    def SetData(self, *args: object) -> None: ...
    def GetData(self, *args: object) -> None: ...

class SpriteBatch(GraphicsResource):
    def __init__(self, graphicsDevice: GraphicsDevice) -> None: ...
    def Begin(self, *args: object) -> None: ...
    def Draw(self, *args: object) -> None: ...
    def End(self) -> None: ...
