from enum import IntEnum, IntFlag
from typing import Any, BinaryIO, Callable, ClassVar, Final, Iterable, Iterator, MutableSequence, Sequence, TypeVar, overload
from .. import Color, Matrix, Rectangle, Vector2, Vector3, Vector4
from .._language import Event

T = TypeVar("T")
TVertex = TypeVar("TVertex", bound="IVertexType")

class AlphaTestEffect(Effect):
    @overload
    def __init__(self, device: GraphicsDevice) -> None: ...
    @overload
    def __init__(self, cloneSource: AlphaTestEffect) -> None: ...
    def Clone(self) -> Effect: ...
    def OnApply(self) -> None: ...
    @property
    def World(self) -> Matrix: ...
    @World.setter
    def World(self, value: Matrix) -> None: ...
    @property
    def View(self) -> Matrix: ...
    @View.setter
    def View(self, value: Matrix) -> None: ...
    @property
    def Projection(self) -> Matrix: ...
    @Projection.setter
    def Projection(self, value: Matrix) -> None: ...
    @property
    def DiffuseColor(self) -> Vector3: ...
    @DiffuseColor.setter
    def DiffuseColor(self, value: Vector3) -> None: ...
    @property
    def Alpha(self) -> float: ...
    @Alpha.setter
    def Alpha(self, value: float) -> None: ...
    @property
    def FogEnabled(self) -> bool: ...
    @FogEnabled.setter
    def FogEnabled(self, value: bool) -> None: ...
    @property
    def FogStart(self) -> float: ...
    @FogStart.setter
    def FogStart(self, value: float) -> None: ...
    @property
    def FogEnd(self) -> float: ...
    @FogEnd.setter
    def FogEnd(self, value: float) -> None: ...
    @property
    def FogColor(self) -> Vector3: ...
    @FogColor.setter
    def FogColor(self, value: Vector3) -> None: ...
    @property
    def Texture(self) -> Texture2D: ...
    @Texture.setter
    def Texture(self, value: Texture2D) -> None: ...
    @property
    def VertexColorEnabled(self) -> bool: ...
    @VertexColorEnabled.setter
    def VertexColorEnabled(self, value: bool) -> None: ...
    @property
    def AlphaFunction(self) -> CompareFunction: ...
    @AlphaFunction.setter
    def AlphaFunction(self, value: CompareFunction) -> None: ...
    @property
    def ReferenceAlpha(self) -> int: ...
    @ReferenceAlpha.setter
    def ReferenceAlpha(self, value: int) -> None: ...

class BasicEffect(Effect):
    @overload
    def __init__(self, device: GraphicsDevice) -> None: ...
    @overload
    def __init__(self, cloneSource: BasicEffect) -> None: ...
    def Clone(self) -> Effect: ...
    def EnableDefaultLighting(self) -> None: ...
    def OnApply(self) -> None: ...
    @property
    def World(self) -> Matrix: ...
    @World.setter
    def World(self, value: Matrix) -> None: ...
    @property
    def View(self) -> Matrix: ...
    @View.setter
    def View(self, value: Matrix) -> None: ...
    @property
    def Projection(self) -> Matrix: ...
    @Projection.setter
    def Projection(self, value: Matrix) -> None: ...
    @property
    def DiffuseColor(self) -> Vector3: ...
    @DiffuseColor.setter
    def DiffuseColor(self, value: Vector3) -> None: ...
    @property
    def EmissiveColor(self) -> Vector3: ...
    @EmissiveColor.setter
    def EmissiveColor(self, value: Vector3) -> None: ...
    @property
    def SpecularColor(self) -> Vector3: ...
    @SpecularColor.setter
    def SpecularColor(self, value: Vector3) -> None: ...
    @property
    def SpecularPower(self) -> float: ...
    @SpecularPower.setter
    def SpecularPower(self, value: float) -> None: ...
    @property
    def Alpha(self) -> float: ...
    @Alpha.setter
    def Alpha(self, value: float) -> None: ...
    @property
    def LightingEnabled(self) -> bool: ...
    @LightingEnabled.setter
    def LightingEnabled(self, value: bool) -> None: ...
    @property
    def PreferPerPixelLighting(self) -> bool: ...
    @PreferPerPixelLighting.setter
    def PreferPerPixelLighting(self, value: bool) -> None: ...
    @property
    def AmbientLightColor(self) -> Vector3: ...
    @AmbientLightColor.setter
    def AmbientLightColor(self, value: Vector3) -> None: ...
    @property
    def DirectionalLight0(self) -> DirectionalLight: ...
    @property
    def DirectionalLight1(self) -> DirectionalLight: ...
    @property
    def DirectionalLight2(self) -> DirectionalLight: ...
    @property
    def FogEnabled(self) -> bool: ...
    @FogEnabled.setter
    def FogEnabled(self, value: bool) -> None: ...
    @property
    def FogStart(self) -> float: ...
    @FogStart.setter
    def FogStart(self, value: float) -> None: ...
    @property
    def FogEnd(self) -> float: ...
    @FogEnd.setter
    def FogEnd(self, value: float) -> None: ...
    @property
    def FogColor(self) -> Vector3: ...
    @FogColor.setter
    def FogColor(self, value: Vector3) -> None: ...
    @property
    def TextureEnabled(self) -> bool: ...
    @TextureEnabled.setter
    def TextureEnabled(self, value: bool) -> None: ...
    @property
    def Texture(self) -> Texture2D: ...
    @Texture.setter
    def Texture(self, value: Texture2D) -> None: ...
    @property
    def VertexColorEnabled(self) -> bool: ...
    @VertexColorEnabled.setter
    def VertexColorEnabled(self, value: bool) -> None: ...

class Blend(IntEnum):
    One: int
    Zero: int
    SourceColor: int
    InverseSourceColor: int
    SourceAlpha: int
    InverseSourceAlpha: int
    DestinationColor: int
    InverseDestinationColor: int
    DestinationAlpha: int
    InverseDestinationAlpha: int
    BlendFactor: int
    InverseBlendFactor: int
    SourceAlphaSaturation: int

class BlendFunction(IntEnum):
    Add: int
    Subtract: int
    ReverseSubtract: int
    Min: int
    Max: int

class BlendState(GraphicsResource):
    def __init__(self) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def MultiSampleMask(self) -> int: ...
    @MultiSampleMask.setter
    def MultiSampleMask(self, value: int) -> None: ...
    @property
    def BlendFactor(self) -> Color: ...
    @BlendFactor.setter
    def BlendFactor(self, value: Color) -> None: ...
    @property
    def ColorWriteChannels3(self) -> ColorWriteChannels: ...
    @ColorWriteChannels3.setter
    def ColorWriteChannels3(self, value: ColorWriteChannels) -> None: ...
    @property
    def ColorWriteChannels2(self) -> ColorWriteChannels: ...
    @ColorWriteChannels2.setter
    def ColorWriteChannels2(self, value: ColorWriteChannels) -> None: ...
    @property
    def ColorWriteChannels1(self) -> ColorWriteChannels: ...
    @ColorWriteChannels1.setter
    def ColorWriteChannels1(self, value: ColorWriteChannels) -> None: ...
    @property
    def ColorWriteChannels(self) -> ColorWriteChannels: ...
    @ColorWriteChannels.setter
    def ColorWriteChannels(self, value: ColorWriteChannels) -> None: ...
    @property
    def AlphaBlendFunction(self) -> BlendFunction: ...
    @AlphaBlendFunction.setter
    def AlphaBlendFunction(self, value: BlendFunction) -> None: ...
    @property
    def AlphaDestinationBlend(self) -> Blend: ...
    @AlphaDestinationBlend.setter
    def AlphaDestinationBlend(self, value: Blend) -> None: ...
    @property
    def AlphaSourceBlend(self) -> Blend: ...
    @AlphaSourceBlend.setter
    def AlphaSourceBlend(self, value: Blend) -> None: ...
    @property
    def ColorBlendFunction(self) -> BlendFunction: ...
    @ColorBlendFunction.setter
    def ColorBlendFunction(self, value: BlendFunction) -> None: ...
    @property
    def ColorDestinationBlend(self) -> Blend: ...
    @ColorDestinationBlend.setter
    def ColorDestinationBlend(self, value: Blend) -> None: ...
    @property
    def ColorSourceBlend(self) -> Blend: ...
    @ColorSourceBlend.setter
    def ColorSourceBlend(self, value: Blend) -> None: ...
    Opaque: ClassVar[BlendState]
    AlphaBlend: ClassVar[BlendState]
    Additive: ClassVar[BlendState]
    NonPremultiplied: ClassVar[BlendState]

class BufferUsage(IntFlag):
    None_: int
    WriteOnly: int

class ClearOptions(IntFlag):
    Target: int
    DepthBuffer: int
    Stencil: int

class ColorWriteChannels(IntFlag):
    None_: int
    Red: int
    Green: int
    Blue: int
    Alpha: int
    All: int

class CompareFunction(IntEnum):
    Always: int
    Never: int
    Less: int
    LessEqual: int
    Equal: int
    GreaterEqual: int
    Greater: int
    NotEqual: int

class CubeMapFace(IntEnum):
    PositiveX: int
    NegativeX: int
    PositiveY: int
    NegativeY: int
    PositiveZ: int
    NegativeZ: int

class CullMode(IntEnum):
    None_: int
    CullClockwiseFace: int
    CullCounterClockwiseFace: int

class DepthFormat(IntEnum):
    None_: int
    Depth16: int
    Depth24: int
    Depth24Stencil8: int

class DepthStencilState(GraphicsResource):
    def __init__(self) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def ReferenceStencil(self) -> int: ...
    @ReferenceStencil.setter
    def ReferenceStencil(self, value: int) -> None: ...
    @property
    def StencilWriteMask(self) -> int: ...
    @StencilWriteMask.setter
    def StencilWriteMask(self, value: int) -> None: ...
    @property
    def StencilMask(self) -> int: ...
    @StencilMask.setter
    def StencilMask(self, value: int) -> None: ...
    @property
    def CounterClockwiseStencilDepthBufferFail(self) -> StencilOperation: ...
    @CounterClockwiseStencilDepthBufferFail.setter
    def CounterClockwiseStencilDepthBufferFail(self, value: StencilOperation) -> None: ...
    @property
    def CounterClockwiseStencilFail(self) -> StencilOperation: ...
    @CounterClockwiseStencilFail.setter
    def CounterClockwiseStencilFail(self, value: StencilOperation) -> None: ...
    @property
    def CounterClockwiseStencilPass(self) -> StencilOperation: ...
    @CounterClockwiseStencilPass.setter
    def CounterClockwiseStencilPass(self, value: StencilOperation) -> None: ...
    @property
    def CounterClockwiseStencilFunction(self) -> CompareFunction: ...
    @CounterClockwiseStencilFunction.setter
    def CounterClockwiseStencilFunction(self, value: CompareFunction) -> None: ...
    @property
    def TwoSidedStencilMode(self) -> bool: ...
    @TwoSidedStencilMode.setter
    def TwoSidedStencilMode(self, value: bool) -> None: ...
    @property
    def StencilDepthBufferFail(self) -> StencilOperation: ...
    @StencilDepthBufferFail.setter
    def StencilDepthBufferFail(self, value: StencilOperation) -> None: ...
    @property
    def StencilFail(self) -> StencilOperation: ...
    @StencilFail.setter
    def StencilFail(self, value: StencilOperation) -> None: ...
    @property
    def StencilPass(self) -> StencilOperation: ...
    @StencilPass.setter
    def StencilPass(self, value: StencilOperation) -> None: ...
    @property
    def StencilFunction(self) -> CompareFunction: ...
    @StencilFunction.setter
    def StencilFunction(self, value: CompareFunction) -> None: ...
    @property
    def StencilEnable(self) -> bool: ...
    @StencilEnable.setter
    def StencilEnable(self, value: bool) -> None: ...
    @property
    def DepthBufferFunction(self) -> CompareFunction: ...
    @DepthBufferFunction.setter
    def DepthBufferFunction(self, value: CompareFunction) -> None: ...
    @property
    def DepthBufferWriteEnable(self) -> bool: ...
    @DepthBufferWriteEnable.setter
    def DepthBufferWriteEnable(self, value: bool) -> None: ...
    @property
    def DepthBufferEnable(self) -> bool: ...
    @DepthBufferEnable.setter
    def DepthBufferEnable(self, value: bool) -> None: ...
    None_: ClassVar[DepthStencilState]
    Default: ClassVar[DepthStencilState]
    DepthRead: ClassVar[DepthStencilState]

class DeviceLostException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, inner: Exception) -> None: ...

class DeviceNotResetException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, inner: Exception) -> None: ...

class DirectionalLight:
    def __init__(self, directionParameter: EffectParameter, diffuseColorParameter: EffectParameter, specularColorParameter: EffectParameter, cloneSource: DirectionalLight) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> None: ...
    @property
    def Direction(self) -> Vector3: ...
    @Direction.setter
    def Direction(self, value: Vector3) -> None: ...
    @property
    def DiffuseColor(self) -> Vector3: ...
    @DiffuseColor.setter
    def DiffuseColor(self, value: Vector3) -> None: ...
    @property
    def SpecularColor(self) -> Vector3: ...
    @SpecularColor.setter
    def SpecularColor(self, value: Vector3) -> None: ...

class DisplayMode:
    def ToString(self) -> str: ...
    @property
    def Format(self) -> SurfaceFormat: ...
    @property
    def Height(self) -> int: ...
    @property
    def Width(self) -> int: ...
    @property
    def AspectRatio(self) -> float: ...
    @property
    def TitleSafeArea(self) -> Rectangle: ...

class DisplayModeCollection:
    def GetEnumerator(self) -> Iterator[DisplayMode]: ...
    def __getitem__(self, format: SurfaceFormat) -> Iterable[DisplayMode]: ...
    def __iter__(self) -> Iterator[DisplayMode]: ...

class DualTextureEffect(Effect):
    @overload
    def __init__(self, device: GraphicsDevice) -> None: ...
    @overload
    def __init__(self, cloneSource: DualTextureEffect) -> None: ...
    def Clone(self) -> Effect: ...
    def OnApply(self) -> None: ...
    @property
    def World(self) -> Matrix: ...
    @World.setter
    def World(self, value: Matrix) -> None: ...
    @property
    def View(self) -> Matrix: ...
    @View.setter
    def View(self, value: Matrix) -> None: ...
    @property
    def Projection(self) -> Matrix: ...
    @Projection.setter
    def Projection(self, value: Matrix) -> None: ...
    @property
    def DiffuseColor(self) -> Vector3: ...
    @DiffuseColor.setter
    def DiffuseColor(self, value: Vector3) -> None: ...
    @property
    def Alpha(self) -> float: ...
    @Alpha.setter
    def Alpha(self, value: float) -> None: ...
    @property
    def FogEnabled(self) -> bool: ...
    @FogEnabled.setter
    def FogEnabled(self, value: bool) -> None: ...
    @property
    def FogStart(self) -> float: ...
    @FogStart.setter
    def FogStart(self, value: float) -> None: ...
    @property
    def FogEnd(self) -> float: ...
    @FogEnd.setter
    def FogEnd(self, value: float) -> None: ...
    @property
    def FogColor(self) -> Vector3: ...
    @FogColor.setter
    def FogColor(self, value: Vector3) -> None: ...
    @property
    def Texture(self) -> Texture2D: ...
    @Texture.setter
    def Texture(self, value: Texture2D) -> None: ...
    @property
    def Texture2(self) -> Texture2D: ...
    @Texture2.setter
    def Texture2(self, value: Texture2D) -> None: ...
    @property
    def VertexColorEnabled(self) -> bool: ...
    @VertexColorEnabled.setter
    def VertexColorEnabled(self, value: bool) -> None: ...

class DynamicIndexBuffer(IndexBuffer):
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, indexType: type, indexCount: int, usage: BufferUsage) -> None: ...
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, indexElementSize: IndexElementSize, indexCount: int, usage: BufferUsage) -> None: ...
    @overload
    def SetData(self, data: MutableSequence[T], startIndex: int, elementCount: int, options: SetDataOptions) -> None: ...
    @overload
    def SetData(self, offsetInBytes: int, data: MutableSequence[T], startIndex: int, elementCount: int, options: SetDataOptions) -> None: ...
    @property
    def IsContentLost(self) -> bool: ...
    ContentLost: Final[Event]

class DynamicVertexBuffer(VertexBuffer):
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, vertexType: type, vertexCount: int, usage: BufferUsage) -> None: ...
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, vertexDeclaration: VertexDeclaration, vertexCount: int, usage: BufferUsage) -> None: ...
    @overload
    def SetData(self, data: MutableSequence[T], startIndex: int, elementCount: int, options: SetDataOptions) -> None: ...
    @overload
    def SetData(self, offsetInBytes: int, data: MutableSequence[T], startIndex: int, elementCount: int, vertexStride: int, options: SetDataOptions) -> None: ...
    @property
    def IsContentLost(self) -> bool: ...
    ContentLost: Final[Event]

class Effect(GraphicsResource):
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, effectCode: Sequence[int]) -> None: ...
    @overload
    def __init__(self, cloneSource: Effect) -> None: ...
    def Clone(self) -> Effect: ...
    def OnApply(self) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def Parameters(self) -> EffectParameterCollection: ...
    @property
    def Techniques(self) -> EffectTechniqueCollection: ...
    @property
    def CurrentTechnique(self) -> EffectTechnique: ...
    @CurrentTechnique.setter
    def CurrentTechnique(self, value: EffectTechnique) -> None: ...

class EffectAnnotation:
    def GetValueBoolean(self) -> bool: ...
    def GetValueInt32(self) -> int: ...
    def GetValueSingle(self) -> float: ...
    def GetValueVector2(self) -> Vector2: ...
    def GetValueVector3(self) -> Vector3: ...
    def GetValueVector4(self) -> Vector4: ...
    def GetValueMatrix(self) -> Matrix: ...
    def GetValueString(self) -> str: ...
    @property
    def ParameterType(self) -> EffectParameterType: ...
    @property
    def ParameterClass(self) -> EffectParameterClass: ...
    @property
    def ColumnCount(self) -> int: ...
    @property
    def RowCount(self) -> int: ...
    @property
    def Semantic(self) -> str: ...
    @property
    def Name(self) -> str: ...

class EffectAnnotationCollection:
    def GetEnumerator(self) -> list[EffectAnnotation]: ...
    @overload
    def __getitem__(self, index: int) -> EffectAnnotation: ...
    @overload
    def __getitem__(self, name: str) -> EffectAnnotation: ...
    @property
    def Count(self) -> int: ...
    def __iter__(self) -> Iterator[EffectAnnotation]: ...

class EffectMaterial(Effect):
    def __init__(self, cloneSource: Effect) -> None: ...

class EffectParameter:
    @overload
    def SetValue(self, value: Texture) -> None: ...
    @overload
    def SetValue(self, value: str) -> None: ...
    @overload
    def SetValue(self, value: Sequence[Matrix]) -> None: ...
    @overload
    def SetValue(self, value: Matrix) -> None: ...
    @overload
    def SetValue(self, value: Sequence[Quaternion]) -> None: ...
    @overload
    def SetValue(self, value: Quaternion) -> None: ...
    @overload
    def SetValue(self, value: Sequence[Vector4]) -> None: ...
    @overload
    def SetValue(self, value: Vector4) -> None: ...
    @overload
    def SetValue(self, value: Sequence[Vector3]) -> None: ...
    @overload
    def SetValue(self, value: Vector3) -> None: ...
    @overload
    def SetValue(self, value: Sequence[Vector2]) -> None: ...
    @overload
    def SetValue(self, value: Vector2) -> None: ...
    @overload
    def SetValue(self, value: Sequence[float]) -> None: ...
    @overload
    def SetValue(self, value: float) -> None: ...
    @overload
    def SetValue(self, value: Sequence[int]) -> None: ...
    @overload
    def SetValue(self, value: int) -> None: ...
    @overload
    def SetValue(self, value: Sequence[bool]) -> None: ...
    @overload
    def SetValue(self, value: bool) -> None: ...
    @overload
    def SetValueTranspose(self, value: Sequence[Matrix]) -> None: ...
    @overload
    def SetValueTranspose(self, value: Matrix) -> None: ...
    def GetValueBoolean(self) -> bool: ...
    def GetValueBooleanArray(self, count: int) -> list[bool]: ...
    def GetValueInt32(self) -> int: ...
    def GetValueInt32Array(self, count: int) -> list[int]: ...
    def GetValueSingle(self) -> float: ...
    def GetValueSingleArray(self, count: int) -> list[float]: ...
    def GetValueVector2(self) -> Vector2: ...
    def GetValueVector2Array(self, count: int) -> list[Vector2]: ...
    def GetValueVector3(self) -> Vector3: ...
    def GetValueVector3Array(self, count: int) -> list[Vector3]: ...
    def GetValueVector4(self) -> Vector4: ...
    def GetValueVector4Array(self, count: int) -> list[Vector4]: ...
    def GetValueQuaternion(self) -> Quaternion: ...
    def GetValueQuaternionArray(self, count: int) -> list[Quaternion]: ...
    def GetValueMatrix(self) -> Matrix: ...
    def GetValueMatrixArray(self, count: int) -> list[Matrix]: ...
    def GetValueMatrixTranspose(self) -> Matrix: ...
    def GetValueMatrixTransposeArray(self, count: int) -> list[Matrix]: ...
    def GetValueString(self) -> str: ...
    def GetValueTexture2D(self) -> Texture2D: ...
    def GetValueTextureCube(self) -> TextureCube: ...
    def GetValueTexture3D(self) -> Texture3D: ...
    @property
    def ParameterType(self) -> EffectParameterType: ...
    @property
    def ParameterClass(self) -> EffectParameterClass: ...
    @property
    def Elements(self) -> EffectParameterCollection: ...
    @property
    def StructureMembers(self) -> EffectParameterCollection: ...
    @property
    def ColumnCount(self) -> int: ...
    @property
    def RowCount(self) -> int: ...
    @property
    def Annotations(self) -> EffectAnnotationCollection: ...
    @property
    def Semantic(self) -> str: ...
    @property
    def Name(self) -> str: ...

class EffectParameterClass(IntEnum):
    Scalar: int
    Vector: int
    Matrix: int
    Object: int
    Struct: int

class EffectParameterCollection:
    def GetParameterBySemantic(self, semantic: str) -> EffectParameter: ...
    def GetEnumerator(self) -> list[EffectParameter]: ...
    @overload
    def __getitem__(self, index: int) -> EffectParameter: ...
    @overload
    def __getitem__(self, name: str) -> EffectParameter: ...
    @property
    def Count(self) -> int: ...
    def __iter__(self) -> Iterator[EffectParameter]: ...

class EffectParameterType(IntEnum):
    Void: int
    Bool: int
    Int32: int
    Single: int
    String: int
    Texture: int
    Texture1D: int
    Texture2D: int
    Texture3D: int
    TextureCube: int

class EffectPass:
    def Apply(self) -> None: ...
    @property
    def Annotations(self) -> EffectAnnotationCollection: ...
    @property
    def Name(self) -> str: ...

class EffectPassCollection:
    def GetEnumerator(self) -> list[EffectPass]: ...
    @overload
    def __getitem__(self, index: int) -> EffectPass: ...
    @overload
    def __getitem__(self, name: str) -> EffectPass: ...
    @property
    def Count(self) -> int: ...
    def __iter__(self) -> Iterator[EffectPass]: ...

class EffectTechnique:
    @property
    def Annotations(self) -> EffectAnnotationCollection: ...
    @property
    def Passes(self) -> EffectPassCollection: ...
    @property
    def Name(self) -> str: ...

class EffectTechniqueCollection:
    def GetEnumerator(self) -> list[EffectTechnique]: ...
    @overload
    def __getitem__(self, index: int) -> EffectTechnique: ...
    @overload
    def __getitem__(self, name: str) -> EffectTechnique: ...
    @property
    def Count(self) -> int: ...
    def __iter__(self) -> Iterator[EffectTechnique]: ...

class EnvironmentMapEffect(Effect):
    @overload
    def __init__(self, device: GraphicsDevice) -> None: ...
    @overload
    def __init__(self, cloneSource: EnvironmentMapEffect) -> None: ...
    def Clone(self) -> Effect: ...
    def EnableDefaultLighting(self) -> None: ...
    def OnApply(self) -> None: ...
    @property
    def World(self) -> Matrix: ...
    @World.setter
    def World(self, value: Matrix) -> None: ...
    @property
    def View(self) -> Matrix: ...
    @View.setter
    def View(self, value: Matrix) -> None: ...
    @property
    def Projection(self) -> Matrix: ...
    @Projection.setter
    def Projection(self, value: Matrix) -> None: ...
    @property
    def DiffuseColor(self) -> Vector3: ...
    @DiffuseColor.setter
    def DiffuseColor(self, value: Vector3) -> None: ...
    @property
    def EmissiveColor(self) -> Vector3: ...
    @EmissiveColor.setter
    def EmissiveColor(self, value: Vector3) -> None: ...
    @property
    def Alpha(self) -> float: ...
    @Alpha.setter
    def Alpha(self, value: float) -> None: ...
    @property
    def AmbientLightColor(self) -> Vector3: ...
    @AmbientLightColor.setter
    def AmbientLightColor(self, value: Vector3) -> None: ...
    @property
    def DirectionalLight0(self) -> DirectionalLight: ...
    @property
    def DirectionalLight1(self) -> DirectionalLight: ...
    @property
    def DirectionalLight2(self) -> DirectionalLight: ...
    @property
    def FogEnabled(self) -> bool: ...
    @FogEnabled.setter
    def FogEnabled(self, value: bool) -> None: ...
    @property
    def FogStart(self) -> float: ...
    @FogStart.setter
    def FogStart(self, value: float) -> None: ...
    @property
    def FogEnd(self) -> float: ...
    @FogEnd.setter
    def FogEnd(self, value: float) -> None: ...
    @property
    def FogColor(self) -> Vector3: ...
    @FogColor.setter
    def FogColor(self, value: Vector3) -> None: ...
    @property
    def Texture(self) -> Texture2D: ...
    @Texture.setter
    def Texture(self, value: Texture2D) -> None: ...
    @property
    def EnvironmentMap(self) -> TextureCube: ...
    @EnvironmentMap.setter
    def EnvironmentMap(self, value: TextureCube) -> None: ...
    @property
    def EnvironmentMapAmount(self) -> float: ...
    @EnvironmentMapAmount.setter
    def EnvironmentMapAmount(self, value: float) -> None: ...
    @property
    def EnvironmentMapSpecular(self) -> Vector3: ...
    @EnvironmentMapSpecular.setter
    def EnvironmentMapSpecular(self, value: Vector3) -> None: ...
    @property
    def FresnelFactor(self) -> float: ...
    @FresnelFactor.setter
    def FresnelFactor(self, value: float) -> None: ...
    @property
    def LightingEnabled(self) -> bool: ...
    @LightingEnabled.setter
    def LightingEnabled(self, value: bool) -> None: ...

class FillMode(IntEnum):
    Solid: int
    WireFrame: int

class GraphicsAdapter:
    def QueryBackBufferFormat(self, graphicsProfile: GraphicsProfile, format: SurfaceFormat, depthFormat: DepthFormat, multiSampleCount: int) -> tuple[bool, SurfaceFormat, DepthFormat, int]: ...
    def QueryRenderTargetFormat(self, graphicsProfile: GraphicsProfile, format: SurfaceFormat, depthFormat: DepthFormat, multiSampleCount: int) -> tuple[bool, SurfaceFormat, DepthFormat, int]: ...
    def IsProfileSupported(self, graphicsProfile: GraphicsProfile) -> bool: ...
    UseReferenceDevice: ClassVar[bool]
    UseNullDevice: ClassVar[bool]
    @property
    def MonitorHandle(self) -> int: ...
    @property
    def SupportedDisplayModes(self) -> DisplayModeCollection: ...
    @property
    def CurrentDisplayMode(self) -> DisplayMode: ...
    @property
    def IsWideScreen(self) -> bool: ...
    @property
    def IsDefaultAdapter(self) -> bool: ...
    @property
    def Revision(self) -> int: ...
    @property
    def SubSystemId(self) -> int: ...
    @property
    def DeviceId(self) -> int: ...
    @property
    def VendorId(self) -> int: ...
    @property
    def DeviceName(self) -> str: ...
    @property
    def Description(self) -> str: ...
    DefaultAdapter: Final[GraphicsAdapter]
    Adapters: Final[tuple[GraphicsAdapter, ...]]

class GraphicsDevice:
    def __init__(self, adapter: GraphicsAdapter, graphicsProfile: GraphicsProfile, presentationParameters: PresentationParameters) -> None: ...
    @overload
    def Present(self, sourceRectangle: Rectangle | None, destinationRectangle: Rectangle | None, overrideWindowHandle: int) -> None: ...
    @overload
    def Present(self) -> None: ...
    @overload
    def Reset(self) -> None: ...
    @overload
    def Reset(self, presentationParameters: PresentationParameters) -> None: ...
    @overload
    def Reset(self, presentationParameters: PresentationParameters, graphicsAdapter: GraphicsAdapter) -> None: ...
    def DrawPrimitives(self, primitiveType: PrimitiveType, startVertex: int, primitiveCount: int) -> None: ...
    def DrawIndexedPrimitives(self, primitiveType: PrimitiveType, baseVertex: int, minVertexIndex: int, numVertices: int, startIndex: int, primitiveCount: int) -> None: ...
    def DrawInstancedPrimitives(self, primitiveType: PrimitiveType, baseVertex: int, minVertexIndex: int, numVertices: int, startIndex: int, primitiveCount: int, instanceCount: int) -> None: ...
    @overload
    def DrawUserIndexedPrimitives(self, primitiveType: PrimitiveType, vertexData: Sequence[TVertex], vertexOffset: int, numVertices: int, indexData: Sequence[int], indexOffset: int, primitiveCount: int) -> None: ...
    @overload
    def DrawUserIndexedPrimitives(self, primitiveType: PrimitiveType, vertexData: Sequence[T], vertexOffset: int, numVertices: int, indexData: Sequence[int], indexOffset: int, primitiveCount: int, vertexDeclaration: VertexDeclaration) -> None: ...
    @overload
    def DrawUserPrimitives(self, primitiveType: PrimitiveType, vertexData: Sequence[TVertex], vertexOffset: int, primitiveCount: int) -> None: ...
    @overload
    def DrawUserPrimitives(self, primitiveType: PrimitiveType, vertexData: Sequence[T], vertexOffset: int, primitiveCount: int, vertexDeclaration: VertexDeclaration) -> None: ...
    @overload
    def Clear(self, options: ClearOptions, color: Vector4, depth: float, stencil: int) -> None: ...
    @overload
    def Clear(self, options: ClearOptions, color: Color, depth: float, stencil: int) -> None: ...
    @overload
    def Clear(self, color: Color) -> None: ...
    def SetRenderTargets(self, renderTargets: Sequence[RenderTargetBinding]) -> None: ...
    @overload
    def SetRenderTarget(self, renderTarget: RenderTargetCube, cubeMapFace: CubeMapFace) -> None: ...
    @overload
    def SetRenderTarget(self, renderTarget: RenderTarget2D) -> None: ...
    def GetRenderTargets(self) -> list[RenderTargetBinding]: ...
    @overload
    def GetBackBufferData(self, rect: Rectangle | None, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetBackBufferData(self, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetBackBufferData(self, data: MutableSequence[T]) -> None: ...
    def GetVertexBuffers(self) -> list[VertexBufferBinding]: ...
    @overload
    def SetVertexBuffer(self, vertexBuffer: VertexBuffer, vertexOffset: int) -> None: ...
    @overload
    def SetVertexBuffer(self, vertexBuffer: VertexBuffer) -> None: ...
    def SetVertexBuffers(self, vertexBuffers: Sequence[VertexBufferBinding]) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def ScissorRectangle(self) -> Rectangle: ...
    @ScissorRectangle.setter
    def ScissorRectangle(self, value: Rectangle) -> None: ...
    @property
    def Indices(self) -> IndexBuffer: ...
    @Indices.setter
    def Indices(self, value: IndexBuffer) -> None: ...
    @property
    def Viewport(self) -> Viewport: ...
    @Viewport.setter
    def Viewport(self, value: Viewport) -> None: ...
    @property
    def DisplayMode(self) -> DisplayMode: ...
    @property
    def GraphicsDeviceStatus(self) -> GraphicsDeviceStatus: ...
    @property
    def GraphicsProfile(self) -> GraphicsProfile: ...
    @property
    def Adapter(self) -> GraphicsAdapter: ...
    @property
    def PresentationParameters(self) -> PresentationParameters: ...
    @property
    def RasterizerState(self) -> RasterizerState: ...
    @RasterizerState.setter
    def RasterizerState(self, value: RasterizerState) -> None: ...
    @property
    def ReferenceStencil(self) -> int: ...
    @ReferenceStencil.setter
    def ReferenceStencil(self, value: int) -> None: ...
    @property
    def DepthStencilState(self) -> DepthStencilState: ...
    @DepthStencilState.setter
    def DepthStencilState(self, value: DepthStencilState) -> None: ...
    @property
    def MultiSampleMask(self) -> int: ...
    @MultiSampleMask.setter
    def MultiSampleMask(self, value: int) -> None: ...
    @property
    def BlendFactor(self) -> Color: ...
    @BlendFactor.setter
    def BlendFactor(self, value: Color) -> None: ...
    @property
    def BlendState(self) -> BlendState: ...
    @BlendState.setter
    def BlendState(self, value: BlendState) -> None: ...
    @property
    def VertexTextures(self) -> TextureCollection: ...
    @property
    def Textures(self) -> TextureCollection: ...
    @property
    def VertexSamplerStates(self) -> SamplerStateCollection: ...
    @property
    def SamplerStates(self) -> SamplerStateCollection: ...
    Disposing: Final[Event]
    ResourceDestroyed: Final[Event]
    ResourceCreated: Final[Event]
    DeviceLost: Final[Event]
    DeviceReset: Final[Event]
    DeviceResetting: Final[Event]
    def __enter__(self) -> GraphicsDevice: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class GraphicsDeviceStatus(IntEnum):
    Normal: int
    Lost: int
    NotReset: int

class GraphicsProfile(IntEnum):
    Reach: int
    HiDef: int

class GraphicsResource:
    def ToString(self) -> str: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Tag(self) -> object: ...
    @Tag.setter
    def Tag(self, value: object) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    Disposing: Final[Event]
    def __enter__(self) -> GraphicsResource: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class IEffectFog:
    @property
    def FogEnabled(self) -> bool: ...
    @FogEnabled.setter
    def FogEnabled(self, value: bool) -> None: ...
    @property
    def FogStart(self) -> float: ...
    @FogStart.setter
    def FogStart(self, value: float) -> None: ...
    @property
    def FogEnd(self) -> float: ...
    @FogEnd.setter
    def FogEnd(self, value: float) -> None: ...
    @property
    def FogColor(self) -> Vector3: ...
    @FogColor.setter
    def FogColor(self, value: Vector3) -> None: ...

class IEffectLights:
    def EnableDefaultLighting(self) -> None: ...
    @property
    def DirectionalLight0(self) -> DirectionalLight: ...
    @property
    def DirectionalLight1(self) -> DirectionalLight: ...
    @property
    def DirectionalLight2(self) -> DirectionalLight: ...
    @property
    def AmbientLightColor(self) -> Vector3: ...
    @AmbientLightColor.setter
    def AmbientLightColor(self, value: Vector3) -> None: ...
    @property
    def LightingEnabled(self) -> bool: ...
    @LightingEnabled.setter
    def LightingEnabled(self, value: bool) -> None: ...

class IEffectMatrices:
    @property
    def World(self) -> Matrix: ...
    @World.setter
    def World(self, value: Matrix) -> None: ...
    @property
    def View(self) -> Matrix: ...
    @View.setter
    def View(self, value: Matrix) -> None: ...
    @property
    def Projection(self) -> Matrix: ...
    @Projection.setter
    def Projection(self, value: Matrix) -> None: ...

class IGraphicsDeviceService:
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    DeviceDisposing: Final[Event]
    DeviceReset: Final[Event]
    DeviceResetting: Final[Event]
    DeviceCreated: Final[Event]

class IVertexType:
    @property
    def VertexDeclaration(self) -> VertexDeclaration: ...

class IndexBuffer(GraphicsResource):
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, indexType: type, indexCount: int, usage: BufferUsage) -> None: ...
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, indexElementSize: IndexElementSize, indexCount: int, usage: BufferUsage) -> None: ...
    @overload
    def SetData(self, data: MutableSequence[T]) -> None: ...
    @overload
    def SetData(self, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def SetData(self, offsetInBytes: int, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetData(self, data: MutableSequence[T]) -> None: ...
    @overload
    def GetData(self, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetData(self, offsetInBytes: int, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def IndexCount(self) -> int: ...
    @property
    def IndexElementSize(self) -> IndexElementSize: ...
    @property
    def BufferUsage(self) -> BufferUsage: ...

class IndexElementSize(IntEnum):
    SixteenBits: int
    ThirtyTwoBits: int

class Model:
    def CopyBoneTransformsTo(self, destinationBoneTransforms: Sequence[Matrix]) -> None: ...
    def CopyAbsoluteBoneTransformsTo(self, destinationBoneTransforms: Sequence[Matrix]) -> None: ...
    def CopyBoneTransformsFrom(self, sourceBoneTransforms: Sequence[Matrix]) -> None: ...
    def Draw(self, world: Matrix, view: Matrix, projection: Matrix) -> None: ...
    @property
    def Root(self) -> ModelBone: ...
    @property
    def Bones(self) -> ModelBoneCollection: ...
    @property
    def Tag(self) -> object: ...
    @Tag.setter
    def Tag(self, value: object) -> None: ...
    @property
    def Meshes(self) -> ModelMeshCollection: ...

class ModelBone:
    @property
    def Name(self) -> str: ...
    @property
    def Index(self) -> int: ...
    @property
    def Transform(self) -> Matrix: ...
    @Transform.setter
    def Transform(self, value: Matrix) -> None: ...
    @property
    def Parent(self) -> ModelBone: ...
    @property
    def Children(self) -> ModelBoneCollection: ...

class ModelBoneCollection:
    def TryGetValue(self, boneName: str) -> tuple[bool, ModelBone]: ...
    def GetEnumerator(self) -> ModelBoneCollectionEnumerator: ...
    def __getitem__(self, boneName: str) -> ModelBone: ...

class ModelBoneCollectionEnumerator:
    def MoveNext(self) -> bool: ...
    def Dispose(self) -> None: ...
    @property
    def Current(self) -> ModelBone: ...
    def __iter__(self) -> Iterator[ModelBone]: ...
    def __copy__(self) -> ModelBoneCollectionEnumerator: ...
    def __deepcopy__(self, memo: object) -> ModelBoneCollectionEnumerator: ...

class ModelEffectCollection:
    def GetEnumerator(self) -> ModelEffectCollectionEnumerator: ...

class ModelEffectCollectionEnumerator:
    def MoveNext(self) -> bool: ...
    def Dispose(self) -> None: ...
    @property
    def Current(self) -> Effect: ...
    def __iter__(self) -> Iterator[Effect]: ...
    def __copy__(self) -> ModelEffectCollectionEnumerator: ...
    def __deepcopy__(self, memo: object) -> ModelEffectCollectionEnumerator: ...

class ModelMesh:
    def Draw(self) -> None: ...
    @property
    def Name(self) -> str: ...
    @property
    def ParentBone(self) -> ModelBone: ...
    @property
    def BoundingSphere(self) -> BoundingSphere: ...
    @property
    def Tag(self) -> object: ...
    @Tag.setter
    def Tag(self, value: object) -> None: ...
    @property
    def MeshParts(self) -> ModelMeshPartCollection: ...
    @property
    def Effects(self) -> ModelEffectCollection: ...

class ModelMeshCollection:
    def TryGetValue(self, meshName: str) -> tuple[bool, ModelMesh]: ...
    def GetEnumerator(self) -> ModelMeshCollectionEnumerator: ...
    def __getitem__(self, meshName: str) -> ModelMesh: ...

class ModelMeshCollectionEnumerator:
    def MoveNext(self) -> bool: ...
    def Dispose(self) -> None: ...
    @property
    def Current(self) -> ModelMesh: ...
    def __iter__(self) -> Iterator[ModelMesh]: ...
    def __copy__(self) -> ModelMeshCollectionEnumerator: ...
    def __deepcopy__(self, memo: object) -> ModelMeshCollectionEnumerator: ...

class ModelMeshPart:
    @property
    def StartIndex(self) -> int: ...
    @property
    def PrimitiveCount(self) -> int: ...
    @property
    def VertexOffset(self) -> int: ...
    @property
    def NumVertices(self) -> int: ...
    @property
    def IndexBuffer(self) -> IndexBuffer: ...
    @property
    def VertexBuffer(self) -> VertexBuffer: ...
    @property
    def Effect(self) -> Effect: ...
    @Effect.setter
    def Effect(self, value: Effect) -> None: ...
    @property
    def Tag(self) -> object: ...
    @Tag.setter
    def Tag(self, value: object) -> None: ...

class ModelMeshPartCollection:
    def GetEnumerator(self) -> ModelMeshPartCollectionEnumerator: ...

class ModelMeshPartCollectionEnumerator:
    def MoveNext(self) -> bool: ...
    def Dispose(self) -> None: ...
    @property
    def Current(self) -> ModelMeshPart: ...
    def __iter__(self) -> Iterator[ModelMeshPart]: ...
    def __copy__(self) -> ModelMeshPartCollectionEnumerator: ...
    def __deepcopy__(self, memo: object) -> ModelMeshPartCollectionEnumerator: ...

class NoSuitableGraphicsDeviceException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, inner: Exception) -> None: ...

class OcclusionQuery(GraphicsResource):
    def __init__(self, graphicsDevice: GraphicsDevice) -> None: ...
    def Begin(self) -> None: ...
    def End(self) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def PixelCount(self) -> int: ...
    @property
    def IsComplete(self) -> bool: ...

class PresentInterval(IntEnum):
    Default: int
    One: int
    Two: int
    Immediate: int

class PresentationParameters:
    def __init__(self) -> None: ...
    def Clone(self) -> PresentationParameters: ...
    @property
    def BackBufferWidth(self) -> int: ...
    @BackBufferWidth.setter
    def BackBufferWidth(self, value: int) -> None: ...
    @property
    def BackBufferHeight(self) -> int: ...
    @BackBufferHeight.setter
    def BackBufferHeight(self, value: int) -> None: ...
    @property
    def BackBufferFormat(self) -> SurfaceFormat: ...
    @BackBufferFormat.setter
    def BackBufferFormat(self, value: SurfaceFormat) -> None: ...
    @property
    def DepthStencilFormat(self) -> DepthFormat: ...
    @DepthStencilFormat.setter
    def DepthStencilFormat(self, value: DepthFormat) -> None: ...
    @property
    def MultiSampleCount(self) -> int: ...
    @MultiSampleCount.setter
    def MultiSampleCount(self, value: int) -> None: ...
    @property
    def DisplayOrientation(self) -> DisplayOrientation: ...
    @DisplayOrientation.setter
    def DisplayOrientation(self, value: DisplayOrientation) -> None: ...
    @property
    def PresentationInterval(self) -> PresentInterval: ...
    @PresentationInterval.setter
    def PresentationInterval(self, value: PresentInterval) -> None: ...
    @property
    def RenderTargetUsage(self) -> RenderTargetUsage: ...
    @RenderTargetUsage.setter
    def RenderTargetUsage(self, value: RenderTargetUsage) -> None: ...
    @property
    def DeviceWindowHandle(self) -> int: ...
    @DeviceWindowHandle.setter
    def DeviceWindowHandle(self, value: int) -> None: ...
    @property
    def IsFullScreen(self) -> bool: ...
    @IsFullScreen.setter
    def IsFullScreen(self, value: bool) -> None: ...
    @property
    def Bounds(self) -> Rectangle: ...

class PrimitiveType(IntEnum):
    TriangleList: int
    TriangleStrip: int
    LineList: int
    LineStrip: int

class RasterizerState(GraphicsResource):
    def __init__(self) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def SlopeScaleDepthBias(self) -> float: ...
    @SlopeScaleDepthBias.setter
    def SlopeScaleDepthBias(self, value: float) -> None: ...
    @property
    def DepthBias(self) -> float: ...
    @DepthBias.setter
    def DepthBias(self, value: float) -> None: ...
    @property
    def MultiSampleAntiAlias(self) -> bool: ...
    @MultiSampleAntiAlias.setter
    def MultiSampleAntiAlias(self, value: bool) -> None: ...
    @property
    def ScissorTestEnable(self) -> bool: ...
    @ScissorTestEnable.setter
    def ScissorTestEnable(self, value: bool) -> None: ...
    @property
    def FillMode(self) -> FillMode: ...
    @FillMode.setter
    def FillMode(self, value: FillMode) -> None: ...
    @property
    def CullMode(self) -> CullMode: ...
    @CullMode.setter
    def CullMode(self, value: CullMode) -> None: ...
    CullNone: ClassVar[RasterizerState]
    CullClockwise: ClassVar[RasterizerState]
    CullCounterClockwise: ClassVar[RasterizerState]

class RenderTarget2D(Texture2D):
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, mipMap: bool, preferredFormat: SurfaceFormat, preferredDepthFormat: DepthFormat, preferredMultiSampleCount: int, usage: RenderTargetUsage) -> None: ...
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, mipMap: bool, preferredFormat: SurfaceFormat, preferredDepthFormat: DepthFormat) -> None: ...
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def IsContentLost(self) -> bool: ...
    @property
    def RenderTargetUsage(self) -> RenderTargetUsage: ...
    @property
    def MultiSampleCount(self) -> int: ...
    @property
    def DepthStencilFormat(self) -> DepthFormat: ...
    ContentLost: Final[Event]

class RenderTargetBinding:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, renderTarget: RenderTargetCube, cubeMapFace: CubeMapFace) -> None: ...
    @overload
    def __init__(self, renderTarget: RenderTarget2D) -> None: ...
    @overload
    def __init__(self) -> RenderTargetBinding: ...
    @property
    def CubeMapFace(self) -> CubeMapFace: ...
    @property
    def RenderTarget(self) -> Texture: ...
    def __copy__(self) -> RenderTargetBinding: ...
    def __deepcopy__(self, memo: object) -> RenderTargetBinding: ...

class RenderTargetCube(TextureCube):
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, size: int, mipMap: bool, preferredFormat: SurfaceFormat, preferredDepthFormat: DepthFormat, preferredMultiSampleCount: int, usage: RenderTargetUsage) -> None: ...
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, size: int, mipMap: bool, preferredFormat: SurfaceFormat, preferredDepthFormat: DepthFormat) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def IsContentLost(self) -> bool: ...
    @property
    def RenderTargetUsage(self) -> RenderTargetUsage: ...
    @property
    def MultiSampleCount(self) -> int: ...
    @property
    def DepthStencilFormat(self) -> DepthFormat: ...
    ContentLost: Final[Event]

class RenderTargetUsage(IntEnum):
    DiscardContents: int
    PreserveContents: int
    PlatformContents: int

class ResourceCreatedEventArgs:
    @property
    def Resource(self) -> object: ...

class ResourceDestroyedEventArgs:
    @property
    def Name(self) -> str: ...
    @property
    def Tag(self) -> object: ...

class SamplerState(GraphicsResource):
    def __init__(self) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def MipMapLevelOfDetailBias(self) -> float: ...
    @MipMapLevelOfDetailBias.setter
    def MipMapLevelOfDetailBias(self, value: float) -> None: ...
    @property
    def MaxMipLevel(self) -> int: ...
    @MaxMipLevel.setter
    def MaxMipLevel(self, value: int) -> None: ...
    @property
    def MaxAnisotropy(self) -> int: ...
    @MaxAnisotropy.setter
    def MaxAnisotropy(self, value: int) -> None: ...
    @property
    def AddressW(self) -> TextureAddressMode: ...
    @AddressW.setter
    def AddressW(self, value: TextureAddressMode) -> None: ...
    @property
    def AddressV(self) -> TextureAddressMode: ...
    @AddressV.setter
    def AddressV(self, value: TextureAddressMode) -> None: ...
    @property
    def AddressU(self) -> TextureAddressMode: ...
    @AddressU.setter
    def AddressU(self, value: TextureAddressMode) -> None: ...
    @property
    def Filter(self) -> TextureFilter: ...
    @Filter.setter
    def Filter(self, value: TextureFilter) -> None: ...
    PointWrap: ClassVar[SamplerState]
    PointClamp: ClassVar[SamplerState]
    LinearWrap: ClassVar[SamplerState]
    LinearClamp: ClassVar[SamplerState]
    AnisotropicWrap: ClassVar[SamplerState]
    AnisotropicClamp: ClassVar[SamplerState]

class SamplerStateCollection:
    def __getitem__(self, index: int) -> SamplerState: ...

class SetDataOptions(IntFlag):
    None_: int
    Discard: int
    NoOverwrite: int

class SkinnedEffect(Effect):
    @overload
    def __init__(self, device: GraphicsDevice) -> None: ...
    @overload
    def __init__(self, cloneSource: SkinnedEffect) -> None: ...
    def SetBoneTransforms(self, boneTransforms: Sequence[Matrix]) -> None: ...
    def GetBoneTransforms(self, count: int) -> list[Matrix]: ...
    def Clone(self) -> Effect: ...
    def EnableDefaultLighting(self) -> None: ...
    def OnApply(self) -> None: ...
    @property
    def World(self) -> Matrix: ...
    @World.setter
    def World(self, value: Matrix) -> None: ...
    @property
    def View(self) -> Matrix: ...
    @View.setter
    def View(self, value: Matrix) -> None: ...
    @property
    def Projection(self) -> Matrix: ...
    @Projection.setter
    def Projection(self, value: Matrix) -> None: ...
    @property
    def DiffuseColor(self) -> Vector3: ...
    @DiffuseColor.setter
    def DiffuseColor(self, value: Vector3) -> None: ...
    @property
    def EmissiveColor(self) -> Vector3: ...
    @EmissiveColor.setter
    def EmissiveColor(self, value: Vector3) -> None: ...
    @property
    def SpecularColor(self) -> Vector3: ...
    @SpecularColor.setter
    def SpecularColor(self, value: Vector3) -> None: ...
    @property
    def SpecularPower(self) -> float: ...
    @SpecularPower.setter
    def SpecularPower(self, value: float) -> None: ...
    @property
    def Alpha(self) -> float: ...
    @Alpha.setter
    def Alpha(self, value: float) -> None: ...
    @property
    def PreferPerPixelLighting(self) -> bool: ...
    @PreferPerPixelLighting.setter
    def PreferPerPixelLighting(self, value: bool) -> None: ...
    @property
    def AmbientLightColor(self) -> Vector3: ...
    @AmbientLightColor.setter
    def AmbientLightColor(self, value: Vector3) -> None: ...
    @property
    def DirectionalLight0(self) -> DirectionalLight: ...
    @property
    def DirectionalLight1(self) -> DirectionalLight: ...
    @property
    def DirectionalLight2(self) -> DirectionalLight: ...
    @property
    def FogEnabled(self) -> bool: ...
    @FogEnabled.setter
    def FogEnabled(self, value: bool) -> None: ...
    @property
    def FogStart(self) -> float: ...
    @FogStart.setter
    def FogStart(self, value: float) -> None: ...
    @property
    def FogEnd(self) -> float: ...
    @FogEnd.setter
    def FogEnd(self, value: float) -> None: ...
    @property
    def FogColor(self) -> Vector3: ...
    @FogColor.setter
    def FogColor(self, value: Vector3) -> None: ...
    @property
    def Texture(self) -> Texture2D: ...
    @Texture.setter
    def Texture(self, value: Texture2D) -> None: ...
    @property
    def WeightsPerVertex(self) -> int: ...
    @WeightsPerVertex.setter
    def WeightsPerVertex(self, value: int) -> None: ...
    MaxBones: Final[int]
    @property
    def LightingEnabled(self) -> bool: ...
    @LightingEnabled.setter
    def LightingEnabled(self, value: bool) -> None: ...

class SpriteBatch(GraphicsResource):
    def __init__(self, graphicsDevice: GraphicsDevice) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Begin(self) -> None: ...
    @overload
    def Begin(self, sortMode: SpriteSortMode, blendState: BlendState) -> None: ...
    @overload
    def Begin(self, sortMode: SpriteSortMode, blendState: BlendState, samplerState: SamplerState, depthStencilState: DepthStencilState, rasterizerState: RasterizerState) -> None: ...
    @overload
    def Begin(self, sortMode: SpriteSortMode, blendState: BlendState, samplerState: SamplerState, depthStencilState: DepthStencilState, rasterizerState: RasterizerState, effect: Effect) -> None: ...
    @overload
    def Begin(self, sortMode: SpriteSortMode, blendState: BlendState, samplerState: SamplerState, depthStencilState: DepthStencilState, rasterizerState: RasterizerState, effect: Effect, transformMatrix: Matrix) -> None: ...
    def End(self) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, position: Vector2, color: Color) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, position: Vector2, sourceRectangle: Rectangle | None, color: Color) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, position: Vector2, sourceRectangle: Rectangle | None, color: Color, rotation: float, origin: Vector2, scale: float, effects: SpriteEffects, layerDepth: float) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, position: Vector2, sourceRectangle: Rectangle | None, color: Color, rotation: float, origin: Vector2, scale: Vector2, effects: SpriteEffects, layerDepth: float) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, destinationRectangle: Rectangle, color: Color) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, destinationRectangle: Rectangle, sourceRectangle: Rectangle | None, color: Color) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, destinationRectangle: Rectangle, sourceRectangle: Rectangle | None, color: Color, rotation: float, origin: Vector2, effects: SpriteEffects, layerDepth: float) -> None: ...
    @overload
    def DrawString(self, spriteFont: SpriteFont, text: str, position: Vector2, color: Color) -> None: ...
    @overload
    def DrawString(self, spriteFont: SpriteFont, text: str, position: Vector2, color: Color, rotation: float, origin: Vector2, scale: float, effects: SpriteEffects, layerDepth: float) -> None: ...
    @overload
    def DrawString(self, spriteFont: SpriteFont, text: str, position: Vector2, color: Color, rotation: float, origin: Vector2, scale: Vector2, effects: SpriteEffects, layerDepth: float) -> None: ...

class SpriteEffects(IntFlag):
    None_: int
    FlipHorizontally: int
    FlipVertically: int

class SpriteFont:
    def MeasureString(self, text: str) -> Vector2: ...
    @property
    def LineSpacing(self) -> int: ...
    @LineSpacing.setter
    def LineSpacing(self, value: int) -> None: ...
    @property
    def Spacing(self) -> float: ...
    @Spacing.setter
    def Spacing(self, value: float) -> None: ...
    @property
    def DefaultCharacter(self) -> str | None: ...
    @DefaultCharacter.setter
    def DefaultCharacter(self, value: str | None) -> None: ...
    @property
    def Characters(self) -> tuple[str, ...]: ...

class SpriteSortMode(IntEnum):
    Deferred: int
    Immediate: int
    Texture: int
    BackToFront: int
    FrontToBack: int

class StencilOperation(IntEnum):
    Keep: int
    Zero: int
    Replace: int
    Increment: int
    Decrement: int
    IncrementSaturation: int
    DecrementSaturation: int
    Invert: int

class SurfaceFormat(IntEnum):
    Color: int
    Bgr565: int
    Bgra5551: int
    Bgra4444: int
    Dxt1: int
    Dxt3: int
    Dxt5: int
    NormalizedByte2: int
    NormalizedByte4: int
    Rgba1010102: int
    Rg32: int
    Rgba64: int
    Alpha8: int
    Single: int
    Vector2: int
    Vector4: int
    HalfSingle: int
    HalfVector2: int
    HalfVector4: int
    HdrBlendable: int

class Texture(GraphicsResource):
    @property
    def LevelCount(self) -> int: ...
    @property
    def Format(self) -> SurfaceFormat: ...

class Texture2D(Texture):
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int) -> None: ...
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, mipMap: bool, format: SurfaceFormat) -> None: ...
    @overload
    @staticmethod
    def FromStream(graphicsDevice: GraphicsDevice, stream: BinaryIO, width: int, height: int, zoom: bool) -> Texture2D: ...
    @overload
    @staticmethod
    def FromStream(graphicsDevice: GraphicsDevice, stream: BinaryIO) -> Texture2D: ...
    def SaveAsJpeg(self, stream: BinaryIO, width: int, height: int) -> None: ...
    def SaveAsPng(self, stream: BinaryIO, width: int, height: int) -> None: ...
    @overload
    def SetData(self, data: MutableSequence[T]) -> None: ...
    @overload
    def SetData(self, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def SetData(self, level: int, rect: Rectangle | None, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetData(self, data: MutableSequence[T]) -> None: ...
    @overload
    def GetData(self, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetData(self, level: int, rect: Rectangle | None, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def Bounds(self) -> Rectangle: ...
    @property
    def Height(self) -> int: ...
    @property
    def Width(self) -> int: ...

class Texture3D(Texture):
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, depth: int, mipMap: bool, format: SurfaceFormat) -> None: ...
    @overload
    def SetData(self, data: MutableSequence[T]) -> None: ...
    @overload
    def SetData(self, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def SetData(self, level: int, left: int, top: int, right: int, bottom: int, front: int, back: int, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetData(self, data: MutableSequence[T]) -> None: ...
    @overload
    def GetData(self, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetData(self, level: int, left: int, top: int, right: int, bottom: int, front: int, back: int, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def Depth(self) -> int: ...
    @property
    def Height(self) -> int: ...
    @property
    def Width(self) -> int: ...

class TextureAddressMode(IntEnum):
    Wrap: int
    Clamp: int
    Mirror: int

class TextureCollection:
    def __getitem__(self, index: int) -> Texture: ...

class TextureCube(Texture):
    def __init__(self, graphicsDevice: GraphicsDevice, size: int, mipMap: bool, format: SurfaceFormat) -> None: ...
    @overload
    def SetData(self, cubeMapFace: CubeMapFace, data: MutableSequence[T]) -> None: ...
    @overload
    def SetData(self, cubeMapFace: CubeMapFace, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def SetData(self, cubeMapFace: CubeMapFace, level: int, rect: Rectangle | None, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetData(self, cubeMapFace: CubeMapFace, data: MutableSequence[T]) -> None: ...
    @overload
    def GetData(self, cubeMapFace: CubeMapFace, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetData(self, cubeMapFace: CubeMapFace, level: int, rect: Rectangle | None, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def Size(self) -> int: ...

class TextureFilter(IntEnum):
    Linear: int
    Point: int
    Anisotropic: int
    LinearMipPoint: int
    PointMipLinear: int
    MinLinearMagPointMipLinear: int
    MinLinearMagPointMipPoint: int
    MinPointMagLinearMipLinear: int
    MinPointMagLinearMipPoint: int

class VertexBuffer(GraphicsResource):
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, vertexType: type, vertexCount: int, usage: BufferUsage) -> None: ...
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, vertexDeclaration: VertexDeclaration, vertexCount: int, usage: BufferUsage) -> None: ...
    @overload
    def SetData(self, data: MutableSequence[T]) -> None: ...
    @overload
    def SetData(self, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def SetData(self, offsetInBytes: int, data: MutableSequence[T], startIndex: int, elementCount: int, vertexStride: int) -> None: ...
    @overload
    def GetData(self, data: MutableSequence[T]) -> None: ...
    @overload
    def GetData(self, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetData(self, offsetInBytes: int, data: MutableSequence[T], startIndex: int, elementCount: int, vertexStride: int) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def VertexDeclaration(self) -> VertexDeclaration: ...
    @property
    def VertexCount(self) -> int: ...
    @property
    def BufferUsage(self) -> BufferUsage: ...

class VertexBufferBinding:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, vertexBuffer: VertexBuffer, vertexOffset: int, instanceFrequency: int) -> None: ...
    @overload
    def __init__(self, vertexBuffer: VertexBuffer, vertexOffset: int) -> None: ...
    @overload
    def __init__(self, vertexBuffer: VertexBuffer) -> None: ...
    @overload
    def __init__(self) -> VertexBufferBinding: ...
    @property
    def InstanceFrequency(self) -> int: ...
    @property
    def VertexOffset(self) -> int: ...
    @property
    def VertexBuffer(self) -> VertexBuffer: ...
    def __copy__(self) -> VertexBufferBinding: ...
    def __deepcopy__(self, memo: object) -> VertexBufferBinding: ...

class VertexDeclaration(GraphicsResource):
    @overload
    def __init__(self, vertexStride: int, elements: Sequence[VertexElement]) -> None: ...
    @overload
    def __init__(self, elements: Sequence[VertexElement]) -> None: ...
    def GetVertexElements(self) -> list[VertexElement]: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def VertexStride(self) -> int: ...

class VertexElement:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, offset: int, elementFormat: VertexElementFormat, elementUsage: VertexElementUsage, usageIndex: int) -> None: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...
    def Equals(self, obj: object) -> bool: ...
    def __eq__(self, right: VertexElement) -> bool: ...
    def __ne__(self, right: VertexElement) -> bool: ...
    @property
    def Offset(self) -> int: ...
    @Offset.setter
    def Offset(self, value: int) -> None: ...
    @property
    def VertexElementFormat(self) -> VertexElementFormat: ...
    @VertexElementFormat.setter
    def VertexElementFormat(self, value: VertexElementFormat) -> None: ...
    @property
    def VertexElementUsage(self) -> VertexElementUsage: ...
    @VertexElementUsage.setter
    def VertexElementUsage(self, value: VertexElementUsage) -> None: ...
    @property
    def UsageIndex(self) -> int: ...
    @UsageIndex.setter
    def UsageIndex(self, value: int) -> None: ...
    def __copy__(self) -> VertexElement: ...
    def __deepcopy__(self, memo: object) -> VertexElement: ...

class VertexElementFormat(IntEnum):
    Single: int
    Vector2: int
    Vector3: int
    Vector4: int
    Color: int
    Byte4: int
    Short2: int
    Short4: int
    NormalizedShort2: int
    NormalizedShort4: int
    HalfVector2: int
    HalfVector4: int

class VertexElementUsage(IntEnum):
    Position: int
    Color: int
    TextureCoordinate: int
    Normal: int
    Binormal: int
    Tangent: int
    BlendIndices: int
    BlendWeight: int
    Depth: int
    Fog: int
    PointSize: int
    Sample: int
    TessellateFactor: int

class VertexPositionColor:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, position: Vector3, color: Color) -> None: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...
    def __eq__(self, right: VertexPositionColor) -> bool: ...
    def __ne__(self, right: VertexPositionColor) -> bool: ...
    def Equals(self, obj: object) -> bool: ...
    Position: Vector3
    Color: Color
    VertexDeclaration: ClassVar[VertexDeclaration]
    def __copy__(self) -> VertexPositionColor: ...
    def __deepcopy__(self, memo: object) -> VertexPositionColor: ...

class VertexPositionColorTexture:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, position: Vector3, color: Color, textureCoordinate: Vector2) -> None: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...
    def __eq__(self, right: VertexPositionColorTexture) -> bool: ...
    def __ne__(self, right: VertexPositionColorTexture) -> bool: ...
    def Equals(self, obj: object) -> bool: ...
    Position: Vector3
    Color: Color
    TextureCoordinate: Vector2
    VertexDeclaration: ClassVar[VertexDeclaration]
    def __copy__(self) -> VertexPositionColorTexture: ...
    def __deepcopy__(self, memo: object) -> VertexPositionColorTexture: ...

class VertexPositionNormalTexture:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, position: Vector3, normal: Vector3, textureCoordinate: Vector2) -> None: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...
    def __eq__(self, right: VertexPositionNormalTexture) -> bool: ...
    def __ne__(self, right: VertexPositionNormalTexture) -> bool: ...
    def Equals(self, obj: object) -> bool: ...
    Position: Vector3
    Normal: Vector3
    TextureCoordinate: Vector2
    VertexDeclaration: ClassVar[VertexDeclaration]
    def __copy__(self) -> VertexPositionNormalTexture: ...
    def __deepcopy__(self, memo: object) -> VertexPositionNormalTexture: ...

class VertexPositionTexture:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, position: Vector3, textureCoordinate: Vector2) -> None: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...
    def __eq__(self, right: VertexPositionTexture) -> bool: ...
    def __ne__(self, right: VertexPositionTexture) -> bool: ...
    def Equals(self, obj: object) -> bool: ...
    Position: Vector3
    TextureCoordinate: Vector2
    VertexDeclaration: ClassVar[VertexDeclaration]
    def __copy__(self) -> VertexPositionTexture: ...
    def __deepcopy__(self, memo: object) -> VertexPositionTexture: ...

class Viewport:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...
    @overload
    def __init__(self, bounds: Rectangle) -> None: ...
    def ToString(self) -> str: ...
    def Project(self, source: Vector3, projection: Matrix, view: Matrix, world: Matrix) -> Vector3: ...
    def Unproject(self, source: Vector3, projection: Matrix, view: Matrix, world: Matrix) -> Vector3: ...
    @property
    def X(self) -> int: ...
    @X.setter
    def X(self, value: int) -> None: ...
    @property
    def Y(self) -> int: ...
    @Y.setter
    def Y(self, value: int) -> None: ...
    @property
    def Width(self) -> int: ...
    @Width.setter
    def Width(self, value: int) -> None: ...
    @property
    def Height(self) -> int: ...
    @Height.setter
    def Height(self, value: int) -> None: ...
    @property
    def MinDepth(self) -> float: ...
    @MinDepth.setter
    def MinDepth(self, value: float) -> None: ...
    @property
    def MaxDepth(self) -> float: ...
    @MaxDepth.setter
    def MaxDepth(self, value: float) -> None: ...
    @property
    def Bounds(self) -> Rectangle: ...
    @Bounds.setter
    def Bounds(self, value: Rectangle) -> None: ...
    @property
    def AspectRatio(self) -> float: ...
    @property
    def TitleSafeArea(self) -> Rectangle: ...
    def __copy__(self) -> Viewport: ...
    def __deepcopy__(self, memo: object) -> Viewport: ...
