from enum import IntEnum, IntFlag
from typing import Any, BinaryIO, Callable, ClassVar, Final, Iterable, MutableSequence, Sequence, TypeVar, overload
from .. import Color, Matrix, Rectangle, Vector2, Vector3, Vector4
from .._language import Event

T = TypeVar("T")

class DepthFormat(IntEnum):
    None_: int
    Depth16: int
    Depth24: int
    Depth24Stencil8: int

class GraphicsDevice:
    def __init__(self, adapter: GraphicsAdapter, graphicsProfile: GraphicsProfile, presentationParameters: PresentationParameters) -> None: ...
    @overload
    def Clear(self, options: ClearOptions, color: Vector4, depth: float, stencil: int) -> None: ...
    @overload
    def Clear(self, options: ClearOptions, color: Color, depth: float, stencil: int) -> None: ...
    @overload
    def Clear(self, color: Color) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def Viewport(self) -> Viewport: ...
    @Viewport.setter
    def Viewport(self, value: Viewport) -> None: ...
    def __enter__(self) -> GraphicsDevice: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class GraphicsProfile(IntEnum):
    Reach: int
    HiDef: int

class GraphicsResource:
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Tag(self) -> object: ...
    @Tag.setter
    def Tag(self, value: object) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def GraphicsDevice(self) -> GraphicsDevice: ...
    def __enter__(self) -> GraphicsResource: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class SpriteBatch(GraphicsResource):
    def __init__(self, graphicsDevice: GraphicsDevice) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Begin(self) -> None: ...
    @overload
    def Begin(self, sortMode: SpriteSortMode, blendState: BlendState) -> None: ...
    @overload
    def Begin(self, sortMode: SpriteSortMode, blendState: BlendState, samplerState: SamplerState, depthStencilState: DepthStencilState, rasterizerState: RasterizerState) -> None: ...
    @overload
    def Begin(self, sortMode: SpriteSortMode, blendState: BlendState, samplerState: SamplerState, depthStencilState: DepthStencilState, rasterizerState: RasterizerState, effect: Effect) -> None: ...
    @overload
    def Begin(self, sortMode: SpriteSortMode, blendState: BlendState, samplerState: SamplerState, depthStencilState: DepthStencilState, rasterizerState: RasterizerState, effect: Effect, transformMatrix: Matrix) -> None: ...
    def End(self) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, position: Vector2, color: Color) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, position: Vector2, sourceRectangle: Rectangle | None, color: Color) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, position: Vector2, sourceRectangle: Rectangle | None, color: Color, rotation: float, origin: Vector2, scale: float, effects: SpriteEffects, layerDepth: float) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, position: Vector2, sourceRectangle: Rectangle | None, color: Color, rotation: float, origin: Vector2, scale: Vector2, effects: SpriteEffects, layerDepth: float) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, destinationRectangle: Rectangle, color: Color) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, destinationRectangle: Rectangle, sourceRectangle: Rectangle | None, color: Color) -> None: ...
    @overload
    def Draw(self, texture: Texture2D, destinationRectangle: Rectangle, sourceRectangle: Rectangle | None, color: Color, rotation: float, origin: Vector2, effects: SpriteEffects, layerDepth: float) -> None: ...

class SpriteEffects(IntFlag):
    None_: int
    FlipHorizontally: int
    FlipVertically: int

class SpriteSortMode(IntEnum):
    Deferred: int
    Immediate: int
    Texture: int
    BackToFront: int
    FrontToBack: int

class SurfaceFormat(IntEnum):
    Color: int

class Texture(GraphicsResource):
    ...

class Texture2D(Texture):
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int) -> None: ...
    @overload
    def __init__(self, graphicsDevice: GraphicsDevice, width: int, height: int, mipMap: bool, format: SurfaceFormat) -> None: ...
    @overload
    @staticmethod
    def FromStream(graphicsDevice: GraphicsDevice, stream: BinaryIO, width: int, height: int, zoom: bool) -> Texture2D: ...
    @overload
    @staticmethod
    def FromStream(graphicsDevice: GraphicsDevice, stream: BinaryIO) -> Texture2D: ...
    @overload
    def SetData(self, data: MutableSequence[T]) -> None: ...
    @overload
    def SetData(self, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def SetData(self, level: int, rect: Rectangle | None, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetData(self, data: MutableSequence[T]) -> None: ...
    @overload
    def GetData(self, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def GetData(self, level: int, rect: Rectangle | None, data: MutableSequence[T], startIndex: int, elementCount: int) -> None: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @property
    def Bounds(self) -> Rectangle: ...
    @property
    def Height(self) -> int: ...
    @property
    def Width(self) -> int: ...

class Viewport:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...
    @overload
    def __init__(self, bounds: Rectangle) -> None: ...
    def ToString(self) -> str: ...
    @property
    def X(self) -> int: ...
    @X.setter
    def X(self, value: int) -> None: ...
    @property
    def Y(self) -> int: ...
    @Y.setter
    def Y(self, value: int) -> None: ...
    @property
    def Width(self) -> int: ...
    @Width.setter
    def Width(self, value: int) -> None: ...
    @property
    def Height(self) -> int: ...
    @Height.setter
    def Height(self, value: int) -> None: ...
    @property
    def MinDepth(self) -> float: ...
    @MinDepth.setter
    def MinDepth(self, value: float) -> None: ...
    @property
    def MaxDepth(self) -> float: ...
    @MaxDepth.setter
    def MaxDepth(self, value: float) -> None: ...
    @property
    def Bounds(self) -> Rectangle: ...
    @Bounds.setter
    def Bounds(self, value: Rectangle) -> None: ...
    @property
    def AspectRatio(self) -> float: ...
    @property
    def TitleSafeArea(self) -> Rectangle: ...
    def __copy__(self) -> Viewport: ...
    def __deepcopy__(self, memo: object) -> Viewport: ...
