from datetime import timedelta
from enum import IntEnum
from typing import BinaryIO, ClassVar, Final, MutableSequence, Sequence, overload
from .. import Vector3
from .._language import Event

class AudioCategory:
    def SetVolume(self, volume: float) -> None: ...
    def Pause(self) -> None: ...
    def Resume(self) -> None: ...
    def Stop(self, options: AudioStopOptions) -> None: ...
    def ToString(self) -> str: ...
    @overload
    def Equals(self, other: AudioCategory) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, value2: AudioCategory) -> bool: ...
    def __ne__(self, value2: AudioCategory) -> bool: ...
    @property
    def Name(self) -> str | None: ...
    def __copy__(self) -> AudioCategory: ...
    def __deepcopy__(self, memo: object) -> AudioCategory: ...

class AudioChannels(IntEnum):
    Mono: int
    Stereo: int

class AudioEmitter:
    def __init__(self) -> None: ...
    @property
    def DopplerScale(self) -> float: ...
    @DopplerScale.setter
    def DopplerScale(self, value: float) -> None: ...
    @property
    def Forward(self) -> Vector3: ...
    @Forward.setter
    def Forward(self, value: Vector3) -> None: ...
    @property
    def Position(self) -> Vector3: ...
    @Position.setter
    def Position(self, value: Vector3) -> None: ...
    @property
    def Up(self) -> Vector3: ...
    @Up.setter
    def Up(self, value: Vector3) -> None: ...
    @property
    def Velocity(self) -> Vector3: ...
    @Velocity.setter
    def Velocity(self, value: Vector3) -> None: ...

class AudioEngine:
    @overload
    def __init__(self, settingsFile: str) -> None: ...
    @overload
    def __init__(self, settingsFile: str, lookAheadTime: timedelta, rendererId: str) -> None: ...
    def GetCategory(self, name: str) -> AudioCategory: ...
    def GetGlobalVariable(self, name: str) -> float: ...
    def SetGlobalVariable(self, name: str, value: float) -> None: ...
    def Update(self) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def RendererDetails(self) -> tuple[RendererDetail, ...]: ...
    Disposing: Final[Event]
    ContentVersion: Final[int]
    def __enter__(self) -> AudioEngine: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class AudioListener:
    def __init__(self) -> None: ...
    @property
    def Forward(self) -> Vector3: ...
    @Forward.setter
    def Forward(self, value: Vector3) -> None: ...
    @property
    def Position(self) -> Vector3: ...
    @Position.setter
    def Position(self, value: Vector3) -> None: ...
    @property
    def Up(self) -> Vector3: ...
    @Up.setter
    def Up(self, value: Vector3) -> None: ...
    @property
    def Velocity(self) -> Vector3: ...
    @Velocity.setter
    def Velocity(self, value: Vector3) -> None: ...

class AudioStopOptions(IntEnum):
    AsAuthored: int
    Immediate: int

class Cue:
    def Play(self) -> None: ...
    def Pause(self) -> None: ...
    def Resume(self) -> None: ...
    def Stop(self, options: AudioStopOptions) -> None: ...
    def GetVariable(self, name: str) -> float: ...
    def SetVariable(self, name: str, value: float) -> None: ...
    def Apply3D(self, listener: AudioListener, emitter: AudioEmitter) -> None: ...
    def Dispose(self) -> None: ...
    @property
    def IsCreated(self) -> bool: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IsPaused(self) -> bool: ...
    @property
    def IsPlaying(self) -> bool: ...
    @property
    def IsPrepared(self) -> bool: ...
    @property
    def IsPreparing(self) -> bool: ...
    @property
    def IsStopped(self) -> bool: ...
    @property
    def IsStopping(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    Disposing: Final[Event]
    def __enter__(self) -> Cue: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class DynamicSoundEffectInstance(SoundEffectInstance):
    def __init__(self, sampleRate: int, channels: AudioChannels) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def SubmitBuffer(self, buffer: Sequence[int]) -> None: ...
    @overload
    def SubmitBuffer(self, buffer: Sequence[int], offset: int, count: int) -> None: ...
    def GetSampleDuration(self, sizeInBytes: int) -> timedelta: ...
    def GetSampleSizeInBytes(self, duration: timedelta) -> int: ...
    def Play(self) -> None: ...
    @property
    def IsLooped(self) -> bool: ...
    @IsLooped.setter
    def IsLooped(self, value: bool) -> None: ...
    @property
    def PendingBufferCount(self) -> int: ...
    BufferNeeded: Final[Event]

class InstancePlayLimitException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, inner: Exception) -> None: ...

class Microphone:
    def GetSampleSizeInBytes(self, duration: timedelta) -> int: ...
    def GetSampleDuration(self, sizeInBytes: int) -> timedelta: ...
    def Start(self) -> None: ...
    def Stop(self) -> None: ...
    @overload
    def GetData(self, buffer: MutableSequence[int]) -> int: ...
    @overload
    def GetData(self, buffer: MutableSequence[int], offset: int, count: int) -> int: ...
    All: Final[tuple[Microphone, ...]]
    @property
    def BufferDuration(self) -> timedelta: ...
    @BufferDuration.setter
    def BufferDuration(self, value: timedelta) -> None: ...
    Default: Final[Microphone | None]
    @property
    def IsHeadset(self) -> bool: ...
    @property
    def SampleRate(self) -> int: ...
    @property
    def State(self) -> MicrophoneState: ...
    BufferReady: Final[Event]
    Name: str

class MicrophoneState(IntEnum):
    Started: int
    Stopped: int

class NoAudioHardwareException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, inner: Exception) -> None: ...

class NoMicrophoneConnectedException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, inner: Exception) -> None: ...

class RendererDetail:
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...
    def __eq__(self, right: RendererDetail) -> bool: ...
    def __ne__(self, right: RendererDetail) -> bool: ...
    def Equals(self, obj: object) -> bool: ...
    @property
    def FriendlyName(self) -> str | None: ...
    @property
    def RendererId(self) -> str | None: ...
    def __copy__(self) -> RendererDetail: ...
    def __deepcopy__(self, memo: object) -> RendererDetail: ...

class SoundBank:
    def __init__(self, audioEngine: AudioEngine, filename: str) -> None: ...
    def GetCue(self, name: str) -> Cue: ...
    @overload
    def PlayCue(self, name: str) -> None: ...
    @overload
    def PlayCue(self, name: str, listener: AudioListener, emitter: AudioEmitter) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IsInUse(self) -> bool: ...
    Disposing: Final[Event]
    def __enter__(self) -> SoundBank: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class SoundEffect:
    @overload
    def __init__(self, buffer: Sequence[int], sampleRate: int, channels: AudioChannels) -> None: ...
    @overload
    def __init__(self, buffer: Sequence[int], offset: int, count: int, sampleRate: int, channels: AudioChannels, loopStart: int, loopLength: int) -> None: ...
    @staticmethod
    def FromStream(stream: BinaryIO) -> SoundEffect: ...
    def Dispose(self) -> None: ...
    def CreateInstance(self) -> SoundEffectInstance: ...
    @overload
    def Play(self) -> bool: ...
    @overload
    def Play(self, volume: float, pitch: float, pan: float) -> bool: ...
    @staticmethod
    def GetSampleSizeInBytes(duration: timedelta, sampleRate: int, channels: AudioChannels) -> int: ...
    @staticmethod
    def GetSampleDuration(sizeInBytes: int, sampleRate: int, channels: AudioChannels) -> timedelta: ...
    DistanceScale: ClassVar[float]
    DopplerScale: ClassVar[float]
    @property
    def Duration(self) -> timedelta: ...
    @property
    def IsDisposed(self) -> bool: ...
    MasterVolume: ClassVar[float]
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    SpeedOfSound: ClassVar[float]
    def __enter__(self) -> SoundEffect: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class SoundEffectInstance:
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    def Play(self) -> None: ...
    @overload
    def Stop(self) -> None: ...
    @overload
    def Stop(self, immediate: bool) -> None: ...
    def Pause(self) -> None: ...
    def Resume(self) -> None: ...
    @overload
    def Apply3D(self, listener: AudioListener, emitter: AudioEmitter) -> None: ...
    @overload
    def Apply3D(self, listeners: Sequence[AudioListener], emitter: AudioEmitter) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IsLooped(self) -> bool: ...
    @IsLooped.setter
    def IsLooped(self, value: bool) -> None: ...
    @property
    def Pan(self) -> float: ...
    @Pan.setter
    def Pan(self, value: float) -> None: ...
    @property
    def Pitch(self) -> float: ...
    @Pitch.setter
    def Pitch(self, value: float) -> None: ...
    @property
    def State(self) -> SoundState: ...
    @property
    def Volume(self) -> float: ...
    @Volume.setter
    def Volume(self, value: float) -> None: ...
    def __enter__(self) -> SoundEffectInstance: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class SoundState(IntEnum):
    Paused: int
    Playing: int
    Stopped: int

class WaveBank:
    @overload
    def __init__(self, audioEngine: AudioEngine, nonStreamingWaveBankFilename: str) -> None: ...
    @overload
    def __init__(self, audioEngine: AudioEngine, streamingWaveBankFilename: str, offset: int, packetsize: int) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IsInUse(self) -> bool: ...
    @property
    def IsPrepared(self) -> bool: ...
    Disposing: Final[Event]
    def __enter__(self) -> WaveBank: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...
