"""Microsoft.Xna.Framework.Audio, as the Xbox 360 profile has it.

Generated by ``tools/generate_xbox_profile.py`` from the Xbox 360 reference
contract. Do not edit: run the generator, and the test suite checks that running
it changes nothing.
"""

from Microsoft.Xna.Framework.Audio import (
    AudioCategory,
    AudioChannels,
    AudioEmitter,
    AudioEngine,
    AudioListener,
    AudioStopOptions,
    Cue,
    DynamicSoundEffectInstance,
    InstancePlayLimitException,
    Microphone,
    MicrophoneState,
    NoAudioHardwareException,
    NoMicrophoneConnectedException,
    RendererDetail,
    SoundBank,
    SoundEffect,
    SoundEffectInstance,
    SoundState,
    WaveBank,
)


__all__ = [
    "AudioCategory",
    "AudioChannels",
    "AudioEmitter",
    "AudioEngine",
    "AudioListener",
    "AudioStopOptions",
    "Cue",
    "DynamicSoundEffectInstance",
    "InstancePlayLimitException",
    "Microphone",
    "MicrophoneState",
    "NoAudioHardwareException",
    "NoMicrophoneConnectedException",
    "RendererDetail",
    "SoundBank",
    "SoundEffect",
    "SoundEffectInstance",
    "SoundState",
    "WaveBank",
]
