from enum import IntEnum
from typing import Any, Iterable, Sequence, overload
from ..... import BoundingSphere, Color, Matrix
from .. import ContentItem, ContentProcessorContext, ContentProcessorOfT
from ..Audio import AudioContent, ConversionQuality
from ..Graphics import (
    FontDescription, MaterialContent, NodeContent, Texture2DContent,
    TextureContent,
)
from ...._video import VideoContent

class CompiledEffectContent(ContentItem):
    def __init__(self, effectCode: Sequence[int]) -> None: ...
    def GetEffectCode(self) -> list[int]: ...

class EffectProcessor:
    def __init__(self) -> None: ...
    def Process(self, input: EffectContent, context: ContentProcessorContext) -> CompiledEffectContent: ...
    @property
    def DebugMode(self) -> EffectProcessorDebugMode: ...
    @DebugMode.setter
    def DebugMode(self, value: EffectProcessorDebugMode) -> None: ...
    @property
    def Defines(self) -> str: ...
    @Defines.setter
    def Defines(self, value: str) -> None: ...

class EffectProcessorDebugMode(IntEnum):
    Auto: int
    Debug: int
    Optimize: int

class FontDescriptionProcessor:
    def __init__(self) -> None: ...
    def Process(self, input: FontDescription, context: ContentProcessorContext) -> SpriteFontContent: ...

class FontTextureProcessor:
    def __init__(self) -> None: ...
    def Process(self, input: Texture2DContent, context: ContentProcessorContext) -> SpriteFontContent: ...
    def GetCharacterForIndex(self, index: int) -> str: ...
    @property
    def TextureFormat(self) -> TextureProcessorOutputFormat: ...
    @TextureFormat.setter
    def TextureFormat(self, value: TextureProcessorOutputFormat) -> None: ...
    @property
    def PremultiplyAlpha(self) -> bool: ...
    @PremultiplyAlpha.setter
    def PremultiplyAlpha(self, value: bool) -> None: ...
    @property
    def FirstCharacter(self) -> str: ...
    @FirstCharacter.setter
    def FirstCharacter(self, value: str) -> None: ...

class MaterialProcessor:
    def __init__(self) -> None: ...
    def Process(self, input: MaterialContent, context: ContentProcessorContext) -> MaterialContent: ...
    def BuildEffect(self, effect: ExternalReferenceOfT[EffectContent], context: ContentProcessorContext) -> ExternalReferenceOfT[CompiledEffectContent]: ...
    def BuildTexture(self, textureName: str, texture: ExternalReferenceOfT[TextureContent], context: ContentProcessorContext) -> ExternalReferenceOfT[TextureContent]: ...
    @property
    def GenerateMipmaps(self) -> bool: ...
    @GenerateMipmaps.setter
    def GenerateMipmaps(self, value: bool) -> None: ...
    @property
    def TextureFormat(self) -> TextureProcessorOutputFormat: ...
    @TextureFormat.setter
    def TextureFormat(self, value: TextureProcessorOutputFormat) -> None: ...
    @property
    def ColorKeyEnabled(self) -> bool: ...
    @ColorKeyEnabled.setter
    def ColorKeyEnabled(self, value: bool) -> None: ...
    @property
    def ColorKeyColor(self) -> Color: ...
    @ColorKeyColor.setter
    def ColorKeyColor(self, value: Color) -> None: ...
    @property
    def ResizeTexturesToPowerOfTwo(self) -> bool: ...
    @ResizeTexturesToPowerOfTwo.setter
    def ResizeTexturesToPowerOfTwo(self, value: bool) -> None: ...
    @property
    def PremultiplyTextureAlpha(self) -> bool: ...
    @PremultiplyTextureAlpha.setter
    def PremultiplyTextureAlpha(self, value: bool) -> None: ...
    @property
    def DefaultEffect(self) -> MaterialProcessorDefaultEffect: ...
    @DefaultEffect.setter
    def DefaultEffect(self, value: MaterialProcessorDefaultEffect) -> None: ...

class MaterialProcessorDefaultEffect(IntEnum):
    BasicEffect: int
    SkinnedEffect: int
    EnvironmentMapEffect: int
    DualTextureEffect: int
    AlphaTestEffect: int

class ModelBoneContent:
    @property
    def Name(self) -> str: ...
    @property
    def Index(self) -> int: ...
    @property
    def Transform(self) -> Matrix: ...
    @Transform.setter
    def Transform(self, value: Matrix) -> None: ...
    @property
    def Parent(self) -> ModelBoneContent: ...
    @property
    def Children(self) -> ModelBoneContentCollection: ...

class ModelBoneContentCollection:
    ...

class ModelContent:
    @property
    def Root(self) -> ModelBoneContent: ...
    @property
    def Bones(self) -> ModelBoneContentCollection: ...
    @property
    def Tag(self) -> object: ...
    @Tag.setter
    def Tag(self, value: object) -> None: ...
    @property
    def Meshes(self) -> ModelMeshContentCollection: ...

class ModelMeshContent:
    @property
    def Name(self) -> str: ...
    @property
    def ParentBone(self) -> ModelBoneContent: ...
    @property
    def BoundingSphere(self) -> BoundingSphere: ...
    @property
    def Tag(self) -> object: ...
    @Tag.setter
    def Tag(self, value: object) -> None: ...
    @property
    def MeshParts(self) -> ModelMeshPartContentCollection: ...
    @property
    def SourceMesh(self) -> MeshContent: ...

class ModelMeshContentCollection:
    ...

class ModelMeshPartContent:
    @property
    def VertexOffset(self) -> int: ...
    @property
    def NumVertices(self) -> int: ...
    @property
    def StartIndex(self) -> int: ...
    @property
    def PrimitiveCount(self) -> int: ...
    @property
    def Material(self) -> MaterialContent: ...
    @Material.setter
    def Material(self, value: MaterialContent) -> None: ...
    @property
    def VertexBuffer(self) -> VertexBufferContent: ...
    @property
    def IndexBuffer(self) -> IndexCollection: ...
    @property
    def Tag(self) -> object: ...
    @Tag.setter
    def Tag(self, value: object) -> None: ...

class ModelMeshPartContentCollection:
    ...

class ModelProcessor:
    def __init__(self) -> None: ...
    def Process(self, input: NodeContent, context: ContentProcessorContext) -> ModelContent: ...
    def ProcessGeometryUsingMaterial(self, material: MaterialContent, geometryCollection: Iterable[GeometryContent], context: ContentProcessorContext) -> None: ...
    def ConvertMaterial(self, material: MaterialContent, context: ContentProcessorContext) -> MaterialContent: ...
    def ProcessVertexChannel(self, geometry: GeometryContent, vertexChannelIndex: int, context: ContentProcessorContext) -> None: ...
    @property
    def Scale(self) -> float: ...
    @Scale.setter
    def Scale(self, value: float) -> None: ...
    @property
    def GenerateTangentFrames(self) -> bool: ...
    @GenerateTangentFrames.setter
    def GenerateTangentFrames(self, value: bool) -> None: ...
    @property
    def SwapWindingOrder(self) -> bool: ...
    @SwapWindingOrder.setter
    def SwapWindingOrder(self, value: bool) -> None: ...
    @property
    def RotationX(self) -> float: ...
    @RotationX.setter
    def RotationX(self, value: float) -> None: ...
    @property
    def RotationY(self) -> float: ...
    @RotationY.setter
    def RotationY(self, value: float) -> None: ...
    @property
    def RotationZ(self) -> float: ...
    @RotationZ.setter
    def RotationZ(self, value: float) -> None: ...
    @property
    def GenerateMipmaps(self) -> bool: ...
    @GenerateMipmaps.setter
    def GenerateMipmaps(self, value: bool) -> None: ...
    @property
    def TextureFormat(self) -> TextureProcessorOutputFormat: ...
    @TextureFormat.setter
    def TextureFormat(self, value: TextureProcessorOutputFormat) -> None: ...
    @property
    def ColorKeyEnabled(self) -> bool: ...
    @ColorKeyEnabled.setter
    def ColorKeyEnabled(self, value: bool) -> None: ...
    @property
    def ColorKeyColor(self) -> Color: ...
    @ColorKeyColor.setter
    def ColorKeyColor(self, value: Color) -> None: ...
    @property
    def ResizeTexturesToPowerOfTwo(self) -> bool: ...
    @ResizeTexturesToPowerOfTwo.setter
    def ResizeTexturesToPowerOfTwo(self, value: bool) -> None: ...
    @property
    def PremultiplyTextureAlpha(self) -> bool: ...
    @PremultiplyTextureAlpha.setter
    def PremultiplyTextureAlpha(self, value: bool) -> None: ...
    @property
    def PremultiplyVertexColors(self) -> bool: ...
    @PremultiplyVertexColors.setter
    def PremultiplyVertexColors(self, value: bool) -> None: ...
    @property
    def DefaultEffect(self) -> MaterialProcessorDefaultEffect: ...
    @DefaultEffect.setter
    def DefaultEffect(self, value: MaterialProcessorDefaultEffect) -> None: ...

class ModelTextureProcessor(TextureProcessor):
    def __init__(self) -> None: ...
    def Process(self, input: TextureContent, context: ContentProcessorContext) -> TextureContent: ...
    @property
    def ColorKeyEnabled(self) -> bool: ...
    @property
    def ColorKeyColor(self) -> Color: ...
    @property
    def TextureFormat(self) -> TextureProcessorOutputFormat: ...
    @property
    def GenerateMipmaps(self) -> bool: ...
    @property
    def ResizeToPowerOfTwo(self) -> bool: ...

class PassThroughProcessor:
    def __init__(self) -> None: ...
    def Process(self, input: object, context: ContentProcessorContext) -> object: ...

class SongContent:
    ...

class SongProcessor:
    def __init__(self) -> None: ...
    def Process(self, input: AudioContent, context: ContentProcessorContext) -> SongContent: ...
    @property
    def Quality(self) -> ConversionQuality: ...
    @Quality.setter
    def Quality(self, value: ConversionQuality) -> None: ...

class SoundEffectContent:
    ...

class SoundEffectProcessor:
    def __init__(self) -> None: ...
    def Process(self, input: AudioContent, context: ContentProcessorContext) -> SoundEffectContent: ...
    @property
    def Quality(self) -> ConversionQuality: ...
    @Quality.setter
    def Quality(self, value: ConversionQuality) -> None: ...

class SpriteFontContent:
    ...

class SpriteTextureProcessor(TextureProcessor):
    def __init__(self) -> None: ...
    def Process(self, input: TextureContent, context: ContentProcessorContext) -> TextureContent: ...
    @property
    def ColorKeyEnabled(self) -> bool: ...
    @property
    def ColorKeyColor(self) -> Color: ...
    @property
    def TextureFormat(self) -> TextureProcessorOutputFormat: ...
    @property
    def GenerateMipmaps(self) -> bool: ...
    @property
    def ResizeToPowerOfTwo(self) -> bool: ...

class TextureProcessor:
    def __init__(self) -> None: ...
    def Process(self, input: TextureContent, context: ContentProcessorContext) -> TextureContent: ...
    @property
    def GenerateMipmaps(self) -> bool: ...
    @GenerateMipmaps.setter
    def GenerateMipmaps(self, value: bool) -> None: ...
    @property
    def TextureFormat(self) -> TextureProcessorOutputFormat: ...
    @TextureFormat.setter
    def TextureFormat(self, value: TextureProcessorOutputFormat) -> None: ...
    @property
    def ColorKeyEnabled(self) -> bool: ...
    @ColorKeyEnabled.setter
    def ColorKeyEnabled(self, value: bool) -> None: ...
    @property
    def ColorKeyColor(self) -> Color: ...
    @ColorKeyColor.setter
    def ColorKeyColor(self, value: Color) -> None: ...
    @property
    def ResizeToPowerOfTwo(self) -> bool: ...
    @ResizeToPowerOfTwo.setter
    def ResizeToPowerOfTwo(self, value: bool) -> None: ...
    @property
    def PremultiplyAlpha(self) -> bool: ...
    @PremultiplyAlpha.setter
    def PremultiplyAlpha(self, value: bool) -> None: ...

class TextureProcessorOutputFormat(IntEnum):
    NoChange: int
    Color: int
    DxtCompressed: int

class VertexBufferContent(ContentItem):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: int) -> None: ...
    @overload
    def Write(self, offset: int, stride: int, data: Iterable[T]) -> None: ...
    @overload
    def Write(self, offset: int, stride: int, dataType: type, data: IEnumerable) -> None: ...
    @staticmethod
    def SizeOf(type: type) -> int: ...
    @property
    def VertexDeclaration(self) -> VertexDeclarationContent: ...
    @VertexDeclaration.setter
    def VertexDeclaration(self, value: VertexDeclarationContent) -> None: ...
    @property
    def VertexData(self) -> list[int]: ...

class VertexDeclarationContent(ContentItem):
    def __init__(self) -> None: ...
    @property
    def VertexElements(self) -> Collection[VertexElement]: ...
    @property
    def VertexStride(self) -> int | None: ...
    @VertexStride.setter
    def VertexStride(self, value: int | None) -> None: ...

class VideoProcessor:
    def __init__(self) -> None: ...
    def Process(self, input: VideoContent, context: ContentProcessorContext) -> VideoContent: ...
    @property
    def VideoSoundtrackType(self) -> VideoSoundtrackType: ...
    @VideoSoundtrackType.setter
    def VideoSoundtrackType(self, value: VideoSoundtrackType) -> None: ...
