from typing import Generic, TypeVar, overload
from ... import Vector2, Vector3, Vector4

TPacked = TypeVar("TPacked")

class Alpha8(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, alpha: float) -> None: ...
    def ToAlpha(self) -> float: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Alpha8) -> bool: ...
    def __eq__(self, b: Alpha8) -> bool: ...
    def __ne__(self, b: Alpha8) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> Alpha8: ...
    def __deepcopy__(self, memo: object) -> Alpha8: ...

class Bgr565(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @overload
    def __init__(self, vector: Vector3) -> None: ...
    def ToVector3(self) -> Vector3: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Bgr565) -> bool: ...
    def __eq__(self, b: Bgr565) -> bool: ...
    def __ne__(self, b: Bgr565) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> Bgr565: ...
    def __deepcopy__(self, memo: object) -> Bgr565: ...

class Bgra4444(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @overload
    def __init__(self, vector: Vector4) -> None: ...
    def ToVector4(self) -> Vector4: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Bgra4444) -> bool: ...
    def __eq__(self, b: Bgra4444) -> bool: ...
    def __ne__(self, b: Bgra4444) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> Bgra4444: ...
    def __deepcopy__(self, memo: object) -> Bgra4444: ...

class Bgra5551(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @overload
    def __init__(self, vector: Vector4) -> None: ...
    def ToVector4(self) -> Vector4: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Bgra5551) -> bool: ...
    def __eq__(self, b: Bgra5551) -> bool: ...
    def __ne__(self, b: Bgra5551) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> Bgra5551: ...
    def __deepcopy__(self, memo: object) -> Bgra5551: ...

class Byte4(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @overload
    def __init__(self, vector: Vector4) -> None: ...
    def ToVector4(self) -> Vector4: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Byte4) -> bool: ...
    def __eq__(self, b: Byte4) -> bool: ...
    def __ne__(self, b: Byte4) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> Byte4: ...
    def __deepcopy__(self, memo: object) -> Byte4: ...

class HalfSingle(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: float) -> None: ...
    def ToSingle(self) -> float: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: HalfSingle) -> bool: ...
    def __eq__(self, b: HalfSingle) -> bool: ...
    def __ne__(self, b: HalfSingle) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> HalfSingle: ...
    def __deepcopy__(self, memo: object) -> HalfSingle: ...

class HalfVector2(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    @overload
    def __init__(self, vector: Vector2) -> None: ...
    def ToVector2(self) -> Vector2: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: HalfVector2) -> bool: ...
    def __eq__(self, b: HalfVector2) -> bool: ...
    def __ne__(self, b: HalfVector2) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> HalfVector2: ...
    def __deepcopy__(self, memo: object) -> HalfVector2: ...

class HalfVector4(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @overload
    def __init__(self, vector: Vector4) -> None: ...
    def ToVector4(self) -> Vector4: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: HalfVector4) -> bool: ...
    def __eq__(self, b: HalfVector4) -> bool: ...
    def __ne__(self, b: HalfVector4) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> HalfVector4: ...
    def __deepcopy__(self, memo: object) -> HalfVector4: ...

class IPackedVector:
    def ToVector4(self) -> Vector4: ...
    def PackFromVector4(self, vector: Vector4) -> None: ...

class IPackedVectorOfT(IPackedVector, Generic[TPacked]):
    @property
    def PackedValue(self) -> TPacked: ...
    @PackedValue.setter
    def PackedValue(self, value: TPacked) -> None: ...
    def ToVector4(self) -> Vector4: ...
    def PackFromVector4(self, vector: Vector4) -> None: ...

class NormalizedByte2(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    @overload
    def __init__(self, vector: Vector2) -> None: ...
    def ToVector2(self) -> Vector2: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: NormalizedByte2) -> bool: ...
    def __eq__(self, b: NormalizedByte2) -> bool: ...
    def __ne__(self, b: NormalizedByte2) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> NormalizedByte2: ...
    def __deepcopy__(self, memo: object) -> NormalizedByte2: ...

class NormalizedByte4(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @overload
    def __init__(self, vector: Vector4) -> None: ...
    def ToVector4(self) -> Vector4: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: NormalizedByte4) -> bool: ...
    def __eq__(self, b: NormalizedByte4) -> bool: ...
    def __ne__(self, b: NormalizedByte4) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> NormalizedByte4: ...
    def __deepcopy__(self, memo: object) -> NormalizedByte4: ...

class NormalizedShort2(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    @overload
    def __init__(self, vector: Vector2) -> None: ...
    def ToVector2(self) -> Vector2: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: NormalizedShort2) -> bool: ...
    def __eq__(self, b: NormalizedShort2) -> bool: ...
    def __ne__(self, b: NormalizedShort2) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> NormalizedShort2: ...
    def __deepcopy__(self, memo: object) -> NormalizedShort2: ...

class NormalizedShort4(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @overload
    def __init__(self, vector: Vector4) -> None: ...
    def ToVector4(self) -> Vector4: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: NormalizedShort4) -> bool: ...
    def __eq__(self, b: NormalizedShort4) -> bool: ...
    def __ne__(self, b: NormalizedShort4) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> NormalizedShort4: ...
    def __deepcopy__(self, memo: object) -> NormalizedShort4: ...

class Rg32(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    @overload
    def __init__(self, vector: Vector2) -> None: ...
    def ToVector2(self) -> Vector2: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Rg32) -> bool: ...
    def __eq__(self, b: Rg32) -> bool: ...
    def __ne__(self, b: Rg32) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> Rg32: ...
    def __deepcopy__(self, memo: object) -> Rg32: ...

class Rgba1010102(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @overload
    def __init__(self, vector: Vector4) -> None: ...
    def ToVector4(self) -> Vector4: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Rgba1010102) -> bool: ...
    def __eq__(self, b: Rgba1010102) -> bool: ...
    def __ne__(self, b: Rgba1010102) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> Rgba1010102: ...
    def __deepcopy__(self, memo: object) -> Rgba1010102: ...

class Rgba64(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @overload
    def __init__(self, vector: Vector4) -> None: ...
    def ToVector4(self) -> Vector4: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Rgba64) -> bool: ...
    def __eq__(self, b: Rgba64) -> bool: ...
    def __ne__(self, b: Rgba64) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> Rgba64: ...
    def __deepcopy__(self, memo: object) -> Rgba64: ...

class Short2(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    @overload
    def __init__(self, vector: Vector2) -> None: ...
    def ToVector2(self) -> Vector2: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Short2) -> bool: ...
    def __eq__(self, b: Short2) -> bool: ...
    def __ne__(self, b: Short2) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> Short2: ...
    def __deepcopy__(self, memo: object) -> Short2: ...

class Short4(IPackedVectorOfT[int]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @overload
    def __init__(self, vector: Vector4) -> None: ...
    def ToVector4(self) -> Vector4: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Short4) -> bool: ...
    def __eq__(self, b: Short4) -> bool: ...
    def __ne__(self, b: Short4) -> bool: ...
    @property
    def PackedValue(self) -> int: ...
    @PackedValue.setter
    def PackedValue(self, value: int) -> None: ...
    def __copy__(self) -> Short4: ...
    def __deepcopy__(self, memo: object) -> Short4: ...
