"""Microsoft.Xna.Framework.Content, as the XNA 4.0 Xbox 360 runtime profile has it.

Generated by ``tools/generate_platform_profile.py`` from the XNA 4.0 Xbox 360 runtime
reference contract. Do not edit: run the generator, and the test suite checks
that running it changes nothing.
"""

from Microsoft.Xna.Framework.Content import (
    ContentLoadException,
    ContentManager,
    ContentReader,
    ContentSerializerAttribute,
    ContentSerializerCollectionItemNameAttribute,
    ContentSerializerIgnoreAttribute,
    ContentSerializerRuntimeTypeAttribute,
    ContentSerializerTypeVersionAttribute,
    ContentTypeReader,
    ContentTypeReaderManager,
    ContentTypeReaderOfT,
    ResourceContentManager,
)


__all__ = [
    "ContentLoadException",
    "ContentManager",
    "ContentReader",
    "ContentSerializerAttribute",
    "ContentSerializerCollectionItemNameAttribute",
    "ContentSerializerIgnoreAttribute",
    "ContentSerializerRuntimeTypeAttribute",
    "ContentSerializerTypeVersionAttribute",
    "ContentTypeReader",
    "ContentTypeReaderManager",
    "ContentTypeReaderOfT",
    "ResourceContentManager",
]
