"""Microsoft.Xna.Framework.Storage, as the Xbox 360 profile has it.

Generated by ``tools/generate_xbox_profile.py`` from the Xbox 360 reference
contract. Do not edit: run the generator, and the test suite checks that running
it changes nothing.
"""

from Microsoft.Xna.Framework.Storage import (
    StorageContainer,
    StorageDevice,
    StorageDeviceNotConnectedException,
)


__all__ = [
    "StorageContainer",
    "StorageDevice",
    "StorageDeviceNotConnectedException",
]
