from typing import BinaryIO, Callable, Final, overload
from .. import PlayerIndex
from .._language import Event

class StorageContainer:
    def DirectoryExists(self, directory: str) -> bool: ...
    def FileExists(self, file: str) -> bool: ...
    def CreateDirectory(self, directory: str) -> None: ...
    def CreateFile(self, file: str) -> BinaryIO: ...
    def DeleteDirectory(self, directory: str) -> None: ...
    @overload
    def OpenFile(self, file: str, fileMode: str) -> BinaryIO: ...
    @overload
    def OpenFile(self, file: str, fileMode: str, fileAccess: str) -> BinaryIO: ...
    @overload
    def OpenFile(self, file: str, fileMode: str, fileAccess: str, fileShare: frozenset[str]) -> BinaryIO: ...
    def DeleteFile(self, file: str) -> None: ...
    @overload
    def GetDirectoryNames(self) -> list[str]: ...
    @overload
    def GetDirectoryNames(self, searchPattern: str) -> list[str]: ...
    @overload
    def GetFileNames(self) -> list[str]: ...
    @overload
    def GetFileNames(self, searchPattern: str) -> list[str]: ...
    def Dispose(self) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def StorageDevice(self) -> StorageDevice: ...
    Disposing: Final[Event]
    def __enter__(self) -> StorageContainer: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class StorageDevice:
    def DeleteContainer(self, titleName: str) -> None: ...
    @overload
    @staticmethod
    def BeginShowSelector(callback: Callable[[object], None], state: object) -> object: ...
    @overload
    @staticmethod
    def BeginShowSelector(sizeInBytes: int, directoryCount: int, callback: Callable[[object], None], state: object) -> object: ...
    @overload
    @staticmethod
    def BeginShowSelector(player: PlayerIndex, callback: Callable[[object], None], state: object) -> object: ...
    @overload
    @staticmethod
    def BeginShowSelector(player: PlayerIndex, sizeInBytes: int, directoryCount: int, callback: Callable[[object], None], state: object) -> object: ...
    @staticmethod
    def EndShowSelector(result: object) -> StorageDevice: ...
    def BeginOpenContainer(self, displayName: str, callback: Callable[[object], None], state: object) -> object: ...
    def EndOpenContainer(self, result: object) -> StorageContainer: ...
    @property
    def FreeSpace(self) -> int: ...
    @property
    def IsConnected(self) -> bool: ...
    @property
    def TotalSpace(self) -> int: ...
    DeviceChanged: Final[Event]

class StorageDeviceNotConnectedException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
