from datetime import timedelta
from enum import IntEnum
from typing import Any, Callable, Generic, Iterable, Iterator, Mapping, MutableSequence, Sequence, TextIO, TypeVar, overload
from .... import Color, Matrix, Vector2, Vector3

T = TypeVar("T")
TChild = TypeVar("TChild")
TInput = TypeVar("TInput")
TOutput = TypeVar("TOutput")
TParent = TypeVar("TParent")

class ChildCollectionOfT(Generic[TParent, TChild]):
    def __init__(self, parent: TParent) -> None: ...
    def GetParent(self, child: TChild) -> TParent: ...
    def SetParent(self, child: TChild, parent: TParent) -> None: ...
    def ClearItems(self) -> None: ...
    def InsertItem(self, index: int, item: TChild) -> None: ...
    def RemoveItem(self, index: int) -> None: ...
    def SetItem(self, index: int, item: TChild) -> None: ...

class ContentBuildLogger:
    def __init__(self) -> None: ...
    def LogMessage(self, message: str, messageArgs: Sequence[object]) -> None: ...
    def LogImportantMessage(self, message: str, messageArgs: Sequence[object]) -> None: ...
    def LogWarning(self, helpLink: str, contentIdentity: ContentIdentity, message: str, messageArgs: Sequence[object]) -> None: ...
    def PushFile(self, filename: str) -> None: ...
    def PopFile(self) -> None: ...
    def GetCurrentFilename(self, contentIdentity: ContentIdentity) -> str: ...
    @property
    def LoggerRootDirectory(self) -> str: ...
    @LoggerRootDirectory.setter
    def LoggerRootDirectory(self, value: str) -> None: ...

class ContentIdentity:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, sourceFilename: str) -> None: ...
    @overload
    def __init__(self, sourceFilename: str, sourceTool: str) -> None: ...
    @overload
    def __init__(self, sourceFilename: str, sourceTool: str, fragmentIdentifier: str) -> None: ...
    @property
    def SourceFilename(self) -> str: ...
    @SourceFilename.setter
    def SourceFilename(self, value: str) -> None: ...
    @property
    def SourceTool(self) -> str: ...
    @SourceTool.setter
    def SourceTool(self, value: str) -> None: ...
    @property
    def FragmentIdentifier(self) -> str: ...
    @FragmentIdentifier.setter
    def FragmentIdentifier(self, value: str) -> None: ...

class ContentImporterAttribute:
    @overload
    def __init__(self, fileExtension: str) -> None: ...
    @overload
    def __init__(self, fileExtensions: Sequence[str]) -> None: ...
    @property
    def FileExtensions(self) -> Iterable[str]: ...
    @property
    def CacheImportedData(self) -> bool: ...
    @CacheImportedData.setter
    def CacheImportedData(self, value: bool) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> None: ...
    @property
    def DefaultProcessor(self) -> str: ...
    @DefaultProcessor.setter
    def DefaultProcessor(self, value: str) -> None: ...

class ContentImporterContext:
    def __init__(self) -> None: ...
    def AddDependency(self, filename: str) -> None: ...
    @property
    def Logger(self) -> ContentBuildLogger: ...
    @property
    def OutputDirectory(self) -> str: ...
    @property
    def IntermediateDirectory(self) -> str: ...

class ContentImporterOfT(Generic[T]):
    def __init__(self) -> None: ...
    def Import(self, filename: str, context: ContentImporterContext) -> T: ...

class ContentItem:
    def __init__(self) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Identity(self) -> ContentIdentity: ...
    @Identity.setter
    def Identity(self, value: ContentIdentity) -> None: ...
    @property
    def OpaqueData(self) -> OpaqueDataDictionary: ...

class ContentProcessorAttribute:
    def __init__(self) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> None: ...

class ContentProcessorContext:
    def __init__(self) -> None: ...
    def AddDependency(self, filename: str) -> None: ...
    def AddOutputFile(self, filename: str) -> None: ...
    @overload
    def BuildAsset(self, sourceAsset: ExternalReferenceOfT[TInput], processorName: str, processorParameters: OpaqueDataDictionary, importerName: str, assetName: str) -> ExternalReferenceOfT[TOutput]: ...
    @overload
    def BuildAsset(self, sourceAsset: ExternalReferenceOfT[TInput], processorName: str) -> ExternalReferenceOfT[TOutput]: ...
    @overload
    def BuildAndLoadAsset(self, sourceAsset: ExternalReferenceOfT[TInput], processorName: str, processorParameters: OpaqueDataDictionary, importerName: str) -> TOutput: ...
    @overload
    def BuildAndLoadAsset(self, sourceAsset: ExternalReferenceOfT[TInput], processorName: str) -> TOutput: ...
    @overload
    def Convert(self, input: TInput, processorName: str, processorParameters: OpaqueDataDictionary) -> TOutput: ...
    @overload
    def Convert(self, input: TInput, processorName: str) -> TOutput: ...
    @property
    def Logger(self) -> ContentBuildLogger: ...
    @property
    def Parameters(self) -> OpaqueDataDictionary: ...
    @property
    def TargetPlatform(self) -> TargetPlatform: ...
    @property
    def TargetProfile(self) -> GraphicsProfile: ...
    @property
    def BuildConfiguration(self) -> str: ...
    @property
    def OutputFilename(self) -> str: ...
    @property
    def OutputDirectory(self) -> str: ...
    @property
    def IntermediateDirectory(self) -> str: ...

class ContentProcessorOfT(Generic[TInput, TOutput]):
    def __init__(self) -> None: ...
    def Process(self, input: TInput, context: ContentProcessorContext) -> TOutput: ...
    @property
    def InputType(self) -> type: ...
    @property
    def OutputType(self) -> type: ...

class EffectImporter:
    def __init__(self) -> None: ...
    def Import(self, filename: str, context: ContentImporterContext) -> EffectContent: ...

class ExternalReferenceOfT(ContentItem, Generic[T]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, filename: str, relativeToContent: ContentIdentity) -> None: ...
    @property
    def Filename(self) -> str: ...
    @Filename.setter
    def Filename(self, value: str) -> None: ...

class FbxImporter:
    def __init__(self) -> None: ...
    def Import(self, filename: str, context: ContentImporterContext) -> NodeContent: ...

class FontDescriptionImporter:
    def __init__(self) -> None: ...
    def Import(self, filename: str, context: ContentImporterContext) -> FontDescription: ...

class IContentImporter:
    def Import(self, filename: str, context: ContentImporterContext) -> object: ...

class IContentProcessor:
    def Process(self, input: object, context: ContentProcessorContext) -> object: ...
    @property
    def InputType(self) -> type: ...
    @property
    def OutputType(self) -> type: ...

class InvalidContentException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @overload
    def __init__(self, message: str, contentIdentity: ContentIdentity) -> None: ...
    @overload
    def __init__(self, message: str, contentIdentity: ContentIdentity, innerException: Exception) -> None: ...
    @overload
    def __init__(self, serializationInfo: object, streamingContext: object) -> None: ...
    def GetObjectData(self, info: object, context: object) -> None: ...
    @property
    def ContentIdentity(self) -> ContentIdentity: ...
    @ContentIdentity.setter
    def ContentIdentity(self, value: ContentIdentity) -> None: ...

class Mp3Importer:
    def __init__(self) -> None: ...
    def Import(self, filename: str, context: ContentImporterContext) -> AudioContent: ...

class NamedValueDictionaryOfT(Generic[T]):
    def __init__(self) -> None: ...
    def AddItem(self, key: str, value: T) -> None: ...
    def ClearItems(self) -> None: ...
    def RemoveItem(self, key: str) -> bool: ...
    def SetItem(self, key: str, value: T) -> None: ...
    def Add(self, key: str, value: T) -> None: ...
    def Clear(self) -> None: ...
    def ContainsKey(self, key: str) -> bool: ...
    def Remove(self, key: str) -> bool: ...
    def TryGetValue(self, key: str) -> tuple[bool, T]: ...
    def GetEnumerator(self) -> Iterator[KeyValuePair[str, T]]: ...
    @property
    def DefaultSerializerType(self) -> type: ...
    @property
    def Count(self) -> int: ...
    @property
    def Keys(self) -> ICollection[str]: ...
    @property
    def Values(self) -> ICollection[T]: ...
    def __getitem__(self, key: str) -> T: ...
    def __iter__(self) -> Iterator[tuple[str, T]]: ...
    def __len__(self) -> int: ...

class OpaqueDataDictionary:
    def __init__(self) -> None: ...
    def GetValue(self, key: str, defaultValue: T) -> T: ...
    def GetContentAsXml(self) -> str: ...
    def AddItem(self, key: str, value: object) -> None: ...
    def ClearItems(self) -> None: ...
    def RemoveItem(self, key: str) -> bool: ...
    def SetItem(self, key: str, value: object) -> None: ...
    @property
    def DefaultSerializerType(self) -> type: ...

class PipelineComponentScanner:
    def __init__(self) -> None: ...
    @overload
    def Update(self, pipelineAssemblies: Iterable[str]) -> bool: ...
    @overload
    def Update(self, pipelineAssemblies: Iterable[str], pipelineAssemblyDependencies: Iterable[str]) -> bool: ...
    @property
    def ImporterNames(self) -> Iterable[str]: ...
    @property
    def ImporterAttributes(self) -> IDictionary[str, ContentImporterAttribute]: ...
    @property
    def ImporterOutputTypes(self) -> IDictionary[str, str]: ...
    @property
    def ProcessorNames(self) -> Iterable[str]: ...
    @property
    def ProcessorAttributes(self) -> IDictionary[str, ContentProcessorAttribute]: ...
    @property
    def ProcessorInputTypes(self) -> IDictionary[str, str]: ...
    @property
    def ProcessorOutputTypes(self) -> IDictionary[str, str]: ...
    @property
    def ProcessorParameters(self) -> IDictionary[str, ProcessorParameterCollection]: ...
    @property
    def Errors(self) -> MutableSequence[str]: ...

class PipelineException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @overload
    def __init__(self, message: str, messageArgs: Sequence[object]) -> None: ...
    @overload
    def __init__(self, serializationInfo: object, streamingContext: object) -> None: ...

class ProcessorParameter:
    @property
    def PropertyName(self) -> str: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def PropertyType(self) -> str: ...
    @property
    def DefaultValue(self) -> object: ...
    @property
    def Description(self) -> str: ...
    @property
    def PossibleEnumValues(self) -> tuple[str, ...]: ...
    @property
    def IsEnum(self) -> bool: ...

class ProcessorParameterCollection:
    ...

class TargetPlatform(IntEnum):
    Windows: int
    Xbox360: int
    WindowsPhone: int

class TextureImporter:
    def __init__(self) -> None: ...
    def Import(self, filename: str, context: ContentImporterContext) -> TextureContent: ...

class VideoContent(ContentItem):
    def __init__(self, filename: str) -> None: ...
    def Dispose(self) -> None: ...
    @property
    def Filename(self) -> str: ...
    @property
    def VideoSoundtrackType(self) -> VideoSoundtrackType: ...
    @VideoSoundtrackType.setter
    def VideoSoundtrackType(self, value: VideoSoundtrackType) -> None: ...
    @property
    def Duration(self) -> timedelta: ...
    @property
    def Width(self) -> int: ...
    @property
    def Height(self) -> int: ...
    @property
    def BitsPerSecond(self) -> int: ...
    @property
    def FramesPerSecond(self) -> float: ...
    def __enter__(self) -> VideoContent: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class WavImporter:
    def __init__(self) -> None: ...
    def Import(self, filename: str, context: ContentImporterContext) -> AudioContent: ...

class WmaImporter:
    def __init__(self) -> None: ...
    def Import(self, filename: str, context: ContentImporterContext) -> AudioContent: ...

class WmvImporter:
    def __init__(self) -> None: ...
    def Import(self, filename: str, context: ContentImporterContext) -> VideoContent: ...

class XImporter:
    def __init__(self) -> None: ...
    def Import(self, filename: str, context: ContentImporterContext) -> NodeContent: ...
    @overload
    def Dispose(self, value: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    def __enter__(self) -> XImporter: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class XmlImporter:
    def __init__(self) -> None: ...
    def Import(self, filename: str, context: ContentImporterContext) -> object: ...
