from datetime import timedelta
from enum import IntEnum
from typing import Any, Iterable, Iterator, MutableSequence, Sequence, overload
from .. import Color, Matrix, PlayerIndex, Quaternion, Vector2, Vector3, Vector4
from .._language import Event
from ..GamerServices import GamerCollectionOfT, SignedInGamer

class AvailableNetworkSession:
    @property
    def HostGamertag(self) -> str: ...
    @property
    def CurrentGamerCount(self) -> int: ...
    @property
    def OpenPublicGamerSlots(self) -> int: ...
    @property
    def OpenPrivateGamerSlots(self) -> int: ...
    @property
    def SessionProperties(self) -> NetworkSessionProperties: ...
    @property
    def QualityOfService(self) -> QualityOfService: ...

class AvailableNetworkSessionCollection:
    def Dispose(self) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    def __enter__(self) -> AvailableNetworkSessionCollection: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class GameEndedEventArgs:
    def __init__(self) -> None: ...

class GameStartedEventArgs:
    def __init__(self) -> None: ...

class GamerJoinedEventArgs:
    def __init__(self, gamer: NetworkGamer) -> None: ...
    @property
    def Gamer(self) -> NetworkGamer: ...

class GamerLeftEventArgs:
    def __init__(self, gamer: NetworkGamer) -> None: ...
    @property
    def Gamer(self) -> NetworkGamer: ...

class HostChangedEventArgs:
    def __init__(self, oldHost: NetworkGamer, newHost: NetworkGamer) -> None: ...
    @property
    def OldHost(self) -> NetworkGamer: ...
    @property
    def NewHost(self) -> NetworkGamer: ...

class LocalNetworkGamer(NetworkGamer):
    def EnableSendVoice(self, remoteGamer: NetworkGamer, enable: bool) -> None: ...
    @overload
    def SendData(self, data: MutableSequence[int], options: SendDataOptions) -> None: ...
    @overload
    def SendData(self, data: MutableSequence[int], options: SendDataOptions, recipient: NetworkGamer) -> None: ...
    @overload
    def SendData(self, data: MutableSequence[int], offset: int, count: int, options: SendDataOptions) -> None: ...
    @overload
    def SendData(self, data: MutableSequence[int], offset: int, count: int, options: SendDataOptions, recipient: NetworkGamer) -> None: ...
    @overload
    def SendData(self, data: PacketWriter, options: SendDataOptions) -> None: ...
    @overload
    def SendData(self, data: PacketWriter, options: SendDataOptions, recipient: NetworkGamer) -> None: ...
    @overload
    def ReceiveData(self, data: MutableSequence[int]) -> tuple[int, NetworkGamer]: ...
    @overload
    def ReceiveData(self, data: MutableSequence[int], offset: int) -> tuple[int, NetworkGamer]: ...
    @overload
    def ReceiveData(self, data: PacketReader) -> tuple[int, NetworkGamer]: ...
    def SendPartyInvites(self) -> None: ...
    @property
    def SignedInGamer(self) -> SignedInGamer: ...
    @property
    def IsDataAvailable(self) -> bool: ...

class NetworkGamer(Gamer):
    @property
    def Session(self) -> NetworkSession: ...
    @property
    def Machine(self) -> NetworkMachine: ...
    @property
    def IsHost(self) -> bool: ...
    @property
    def IsLocal(self) -> bool: ...
    @property
    def IsPrivateSlot(self) -> bool: ...
    @property
    def IsReady(self) -> bool: ...
    @IsReady.setter
    def IsReady(self, value: bool) -> None: ...
    @property
    def HasVoice(self) -> bool: ...
    @property
    def IsTalking(self) -> bool: ...
    @property
    def IsMutedByLocalUser(self) -> bool: ...
    @property
    def IsGuest(self) -> bool: ...
    @property
    def RoundtripTime(self) -> timedelta: ...
    @property
    def Id(self) -> int: ...
    @property
    def HasLeftSession(self) -> bool: ...

class NetworkMachine:
    def RemoveFromSession(self) -> None: ...
    @property
    def Gamers(self) -> GamerCollectionOfT[NetworkGamer]: ...

class NetworkSession:
    @overload
    @staticmethod
    def Create(sessionType: NetworkSessionType, maxLocalGamers: int, maxGamers: int) -> NetworkSession: ...
    @overload
    @staticmethod
    def Create(sessionType: NetworkSessionType, maxLocalGamers: int, maxGamers: int, privateGamerSlots: int, sessionProperties: NetworkSessionProperties) -> NetworkSession: ...
    @overload
    @staticmethod
    def Create(sessionType: NetworkSessionType, localGamers: Iterable[SignedInGamer], maxGamers: int, privateGamerSlots: int, sessionProperties: NetworkSessionProperties) -> NetworkSession: ...
    @overload
    @staticmethod
    def BeginCreate(sessionType: NetworkSessionType, maxLocalGamers: int, maxGamers: int, callback: Callable[[object], None], asyncState: object) -> object: ...
    @overload
    @staticmethod
    def BeginCreate(sessionType: NetworkSessionType, maxLocalGamers: int, maxGamers: int, privateGamerSlots: int, sessionProperties: NetworkSessionProperties, callback: Callable[[object], None], asyncState: object) -> object: ...
    @overload
    @staticmethod
    def BeginCreate(sessionType: NetworkSessionType, localGamers: Iterable[SignedInGamer], maxGamers: int, privateGamerSlots: int, sessionProperties: NetworkSessionProperties, callback: Callable[[object], None], asyncState: object) -> object: ...
    @staticmethod
    def EndCreate(result: object) -> NetworkSession: ...
    @overload
    @staticmethod
    def Find(sessionType: NetworkSessionType, maxLocalGamers: int, searchProperties: NetworkSessionProperties) -> AvailableNetworkSessionCollection: ...
    @overload
    @staticmethod
    def Find(sessionType: NetworkSessionType, localGamers: Iterable[SignedInGamer], searchProperties: NetworkSessionProperties) -> AvailableNetworkSessionCollection: ...
    @overload
    @staticmethod
    def BeginFind(sessionType: NetworkSessionType, maxLocalGamers: int, searchProperties: NetworkSessionProperties, callback: Callable[[object], None], asyncState: object) -> object: ...
    @overload
    @staticmethod
    def BeginFind(sessionType: NetworkSessionType, localGamers: Iterable[SignedInGamer], searchProperties: NetworkSessionProperties, callback: Callable[[object], None], asyncState: object) -> object: ...
    @staticmethod
    def EndFind(result: object) -> AvailableNetworkSessionCollection: ...
    @staticmethod
    def Join(availableSession: AvailableNetworkSession) -> NetworkSession: ...
    @staticmethod
    def BeginJoin(availableSession: AvailableNetworkSession, callback: Callable[[object], None], asyncState: object) -> object: ...
    @staticmethod
    def EndJoin(result: object) -> NetworkSession: ...
    @overload
    @staticmethod
    def JoinInvited(maxLocalGamers: int) -> NetworkSession: ...
    @overload
    @staticmethod
    def JoinInvited(localGamers: Iterable[SignedInGamer]) -> NetworkSession: ...
    @overload
    @staticmethod
    def BeginJoinInvited(maxLocalGamers: int, callback: Callable[[object], None], asyncState: object) -> object: ...
    @overload
    @staticmethod
    def BeginJoinInvited(localGamers: Iterable[SignedInGamer], callback: Callable[[object], None], asyncState: object) -> object: ...
    @staticmethod
    def EndJoinInvited(result: object) -> NetworkSession: ...
    def Dispose(self) -> None: ...
    def Update(self) -> None: ...
    def StartGame(self) -> None: ...
    def EndGame(self) -> None: ...
    def ResetReady(self) -> None: ...
    def FindGamerById(self, gamerId: int) -> NetworkGamer: ...
    def AddLocalGamer(self, gamer: SignedInGamer) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def SessionType(self) -> NetworkSessionType: ...
    @property
    def SessionState(self) -> NetworkSessionState: ...
    @property
    def IsHost(self) -> bool: ...
    @property
    def Host(self) -> NetworkGamer: ...
    @property
    def AllGamers(self) -> GamerCollectionOfT[NetworkGamer]: ...
    @property
    def LocalGamers(self) -> GamerCollectionOfT[LocalNetworkGamer]: ...
    @property
    def RemoteGamers(self) -> GamerCollectionOfT[NetworkGamer]: ...
    @property
    def PreviousGamers(self) -> GamerCollectionOfT[NetworkGamer]: ...
    @property
    def IsEveryoneReady(self) -> bool: ...
    @property
    def MaxGamers(self) -> int: ...
    @MaxGamers.setter
    def MaxGamers(self, value: int) -> None: ...
    @property
    def PrivateGamerSlots(self) -> int: ...
    @PrivateGamerSlots.setter
    def PrivateGamerSlots(self, value: int) -> None: ...
    @property
    def SimulatedPacketLoss(self) -> float: ...
    @SimulatedPacketLoss.setter
    def SimulatedPacketLoss(self, value: float) -> None: ...
    @property
    def SimulatedLatency(self) -> timedelta: ...
    @SimulatedLatency.setter
    def SimulatedLatency(self, value: timedelta) -> None: ...
    @property
    def BytesPerSecondSent(self) -> int: ...
    @property
    def BytesPerSecondReceived(self) -> int: ...
    @property
    def SessionProperties(self) -> NetworkSessionProperties: ...
    @property
    def AllowJoinInProgress(self) -> bool: ...
    @AllowJoinInProgress.setter
    def AllowJoinInProgress(self, value: bool) -> None: ...
    @property
    def AllowHostMigration(self) -> bool: ...
    @AllowHostMigration.setter
    def AllowHostMigration(self, value: bool) -> None: ...
    SessionEnded: Final[Event]
    GamerJoined: Final[Event]
    GamerLeft: Final[Event]
    GameStarted: Final[Event]
    GameEnded: Final[Event]
    HostChanged: Final[Event]
    InviteAccepted: Final[Event]
    WriteArbitratedLeaderboard: Final[Event]
    WriteTrueSkill: Final[Event]
    WriteUnarbitratedLeaderboard: Final[Event]
    MaxSupportedGamers: Final[int]
    MaxPreviousGamers: Final[int]
    def __enter__(self) -> NetworkSession: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class NetworkSessionEndReason(IntEnum):
    ClientSignedOut: int
    HostEndedSession: int
    RemovedByHost: int
    Disconnected: int

class NetworkSessionEndedEventArgs:
    def __init__(self, endReason: NetworkSessionEndReason) -> None: ...
    @property
    def EndReason(self) -> NetworkSessionEndReason: ...

class NetworkSessionJoinError(IntEnum):
    SessionNotFound: int
    SessionNotJoinable: int
    SessionFull: int

class NetworkSessionJoinException(NetworkException):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, joinError: NetworkSessionJoinError) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @overload
    def __init__(self, info: object, context: object) -> None: ...
    def GetObjectData(self, info: object, context: object) -> None: ...
    @property
    def JoinError(self) -> NetworkSessionJoinError: ...
    @JoinError.setter
    def JoinError(self, value: NetworkSessionJoinError) -> None: ...

class NetworkSessionProperties:
    def __init__(self) -> None: ...
    def GetEnumerator(self) -> Iterator[int | None]: ...
    def __getitem__(self, index: int) -> int | None: ...
    @property
    def Count(self) -> int: ...
    def __setitem__(self, index: int, value: int | None) -> None: ...
    def __iter__(self) -> Iterator[int | None]: ...
    def __len__(self) -> int: ...

class NetworkSessionState(IntEnum):
    Lobby: int
    Playing: int
    Ended: int

class NetworkSessionType(IntEnum):
    Local: int
    SystemLink: int
    PlayerMatch: int
    Ranked: int
    LocalWithLeaderboards: int

class PacketReader:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, capacity: int) -> None: ...
    def ReadVector2(self) -> Vector2: ...
    def ReadVector3(self) -> Vector3: ...
    def ReadVector4(self) -> Vector4: ...
    def ReadMatrix(self) -> Matrix: ...
    def ReadQuaternion(self) -> Quaternion: ...
    def ReadColor(self) -> Color: ...
    def ReadSingle(self) -> float: ...
    def ReadDouble(self) -> float: ...
    @property
    def Length(self) -> int: ...
    @property
    def Position(self) -> int: ...
    @Position.setter
    def Position(self, value: int) -> None: ...

class PacketWriter:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, capacity: int) -> None: ...
    @overload
    def Write(self, value: Vector2) -> None: ...
    @overload
    def Write(self, value: Vector3) -> None: ...
    @overload
    def Write(self, value: Vector4) -> None: ...
    @overload
    def Write(self, value: Matrix) -> None: ...
    @overload
    def Write(self, value: Quaternion) -> None: ...
    @overload
    def Write(self, value: Color) -> None: ...
    @overload
    def Write(self, value: float) -> None: ...
    @property
    def Length(self) -> int: ...
    @property
    def Position(self) -> int: ...
    @Position.setter
    def Position(self, value: int) -> None: ...

class QualityOfService:
    @property
    def IsAvailable(self) -> bool: ...
    @property
    def BytesPerSecondUpstream(self) -> int: ...
    @property
    def BytesPerSecondDownstream(self) -> int: ...
    @property
    def AverageRoundtripTime(self) -> timedelta: ...
    @property
    def MinimumRoundtripTime(self) -> timedelta: ...

class SendDataOptions(IntFlag):
    None_: int
    Reliable: int
    InOrder: int
    ReliableInOrder: int
    Chat: int

class WriteLeaderboardsEventArgs:
    @property
    def Gamer(self) -> NetworkGamer: ...
    @property
    def IsLeaving(self) -> bool: ...
