"""Microsoft.Xna.Framework.Graphics.PackedVector, as the XNA 4.0 Xbox 360 runtime profile has it.

Generated by ``tools/generate_platform_profile.py`` from the XNA 4.0 Xbox 360 runtime
reference contract. Do not edit: run the generator, and the test suite checks
that running it changes nothing.
"""

from Microsoft.Xna.Framework.Graphics.PackedVector import (
    Alpha8,
    Bgr565,
    Bgra4444,
    Bgra5551,
    Byte4,
    HalfSingle,
    HalfVector2,
    HalfVector4,
    IPackedVector,
    IPackedVectorOfT,
    NormalizedByte2,
    NormalizedByte4,
    NormalizedShort2,
    NormalizedShort4,
    Rg32,
    Rgba1010102,
    Rgba64,
    Short2,
    Short4,
)


__all__ = [
    "Alpha8",
    "Bgr565",
    "Bgra4444",
    "Bgra5551",
    "Byte4",
    "HalfSingle",
    "HalfVector2",
    "HalfVector4",
    "IPackedVector",
    "IPackedVectorOfT",
    "NormalizedByte2",
    "NormalizedByte4",
    "NormalizedShort2",
    "NormalizedShort4",
    "Rg32",
    "Rgba1010102",
    "Rgba64",
    "Short2",
    "Short4",
]
