from datetime import datetime, timedelta
from enum import IntEnum
from typing import BinaryIO, ClassVar, Iterator, MutableSequence, overload
from .._language import Event
from ..Graphics import Texture2D

class Album:
    def Dispose(self) -> None: ...
    def GetAlbumArt(self) -> BinaryIO: ...
    def GetThumbnail(self) -> BinaryIO: ...
    def __eq__(self, second: Album) -> bool: ...
    def __ne__(self, second: Album) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Album) -> bool: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Artist(self) -> Artist | None: ...
    @property
    def Songs(self) -> SongCollection: ...
    @property
    def Genre(self) -> Genre | None: ...
    @property
    def Duration(self) -> timedelta: ...
    @property
    def HasArt(self) -> bool: ...
    def __enter__(self) -> Album: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class AlbumCollection:
    def Dispose(self) -> None: ...
    def GetEnumerator(self) -> Iterator[Album]: ...
    @property
    def IsDisposed(self) -> bool: ...
    def __getitem__(self, index: int) -> Album: ...
    @property
    def Count(self) -> int: ...
    def __iter__(self) -> Iterator[Album]: ...
    def __enter__(self) -> AlbumCollection: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class Artist:
    def Dispose(self) -> None: ...
    def __eq__(self, second: Artist) -> bool: ...
    def __ne__(self, second: Artist) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Artist) -> bool: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Songs(self) -> SongCollection: ...
    @property
    def Albums(self) -> AlbumCollection: ...
    def __enter__(self) -> Artist: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class ArtistCollection:
    def Dispose(self) -> None: ...
    def GetEnumerator(self) -> Iterator[Artist]: ...
    @property
    def IsDisposed(self) -> bool: ...
    def __getitem__(self, index: int) -> Artist: ...
    @property
    def Count(self) -> int: ...
    def __iter__(self) -> Iterator[Artist]: ...
    def __enter__(self) -> ArtistCollection: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class Genre:
    def Dispose(self) -> None: ...
    def __eq__(self, second: Genre) -> bool: ...
    def __ne__(self, second: Genre) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Genre) -> bool: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Songs(self) -> SongCollection: ...
    @property
    def Albums(self) -> AlbumCollection: ...
    def __enter__(self) -> Genre: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class GenreCollection:
    def Dispose(self) -> None: ...
    def GetEnumerator(self) -> Iterator[Genre]: ...
    @property
    def IsDisposed(self) -> bool: ...
    def __getitem__(self, index: int) -> Genre: ...
    @property
    def Count(self) -> int: ...
    def __iter__(self) -> Iterator[Genre]: ...
    def __enter__(self) -> GenreCollection: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class MediaLibrary:
    @overload
    def __init__(self, mediaSource: MediaSource) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def SavePicture(self, name: str, imageBuffer: Sequence[int]) -> Picture: ...
    @overload
    def SavePicture(self, name: str, source: BinaryIO) -> Picture: ...
    def GetPictureFromToken(self, token: str) -> Picture | None: ...
    def Dispose(self) -> None: ...
    @property
    def Pictures(self) -> PictureCollection: ...
    @property
    def RootPictureAlbum(self) -> PictureAlbum | None: ...
    @property
    def SavedPictures(self) -> PictureCollection: ...
    @property
    def MediaSource(self) -> MediaSource: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Songs(self) -> SongCollection: ...
    @property
    def Artists(self) -> ArtistCollection: ...
    @property
    def Albums(self) -> AlbumCollection: ...
    @property
    def Playlists(self) -> PlaylistCollection: ...
    @property
    def Genres(self) -> GenreCollection: ...
    def __enter__(self) -> MediaLibrary: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class MediaPlayer:
    @overload
    @staticmethod
    def Play(song: Song) -> None: ...
    @overload
    @staticmethod
    def Play(songs: SongCollection) -> None: ...
    @overload
    @staticmethod
    def Play(songs: SongCollection, index: int) -> None: ...
    @staticmethod
    def Pause() -> None: ...
    @staticmethod
    def Resume() -> None: ...
    @staticmethod
    def Stop() -> None: ...
    @staticmethod
    def MoveNext() -> None: ...
    @staticmethod
    def MovePrevious() -> None: ...
    @staticmethod
    def GetVisualizationData(visualizationData: VisualizationData) -> None: ...
    IsShuffled: ClassVar[bool]
    IsRepeating: ClassVar[bool]
    Queue: Final[MediaQueue]
    State: Final[MediaState]
    PlayPosition: Final[timedelta]
    Volume: ClassVar[float]
    IsMuted: ClassVar[bool]
    IsVisualizationEnabled: ClassVar[bool]
    GameHasControl: Final[bool]
    ActiveSongChanged: Final[Event]
    MediaStateChanged: Final[Event]

class MediaQueue:
    @property
    def Count(self) -> int: ...
    @property
    def ActiveSongIndex(self) -> int: ...
    @ActiveSongIndex.setter
    def ActiveSongIndex(self, value: int) -> None: ...
    @property
    def ActiveSong(self) -> Song | None: ...
    def __getitem__(self, index: int) -> Song: ...

class MediaSource:
    def ToString(self) -> str: ...
    @staticmethod
    def GetAvailableMediaSources() -> MutableSequence[MediaSource]: ...
    @property
    def MediaSourceType(self) -> MediaSourceType: ...
    @property
    def Name(self) -> str: ...

class MediaSourceType(IntEnum):
    LocalDevice: int
    WindowsMediaConnect: int

class MediaState(IntEnum):
    Paused: int
    Playing: int
    Stopped: int

class Picture:
    def Dispose(self) -> None: ...
    def GetImage(self) -> BinaryIO: ...
    def GetThumbnail(self) -> BinaryIO: ...
    def __eq__(self, second: Picture) -> bool: ...
    def __ne__(self, second: Picture) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Picture) -> bool: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Album(self) -> PictureAlbum | None: ...
    @property
    def Width(self) -> int: ...
    @property
    def Height(self) -> int: ...
    @property
    def Date(self) -> datetime: ...
    def __enter__(self) -> Picture: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class PictureAlbum:
    def Dispose(self) -> None: ...
    def __eq__(self, second: PictureAlbum) -> bool: ...
    def __ne__(self, second: PictureAlbum) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: PictureAlbum) -> bool: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Albums(self) -> PictureAlbumCollection: ...
    @property
    def Pictures(self) -> PictureCollection: ...
    @property
    def Parent(self) -> PictureAlbum | None: ...
    def __enter__(self) -> PictureAlbum: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class PictureAlbumCollection:
    def Dispose(self) -> None: ...
    def GetEnumerator(self) -> Iterator[PictureAlbum]: ...
    @property
    def IsDisposed(self) -> bool: ...
    def __getitem__(self, index: int) -> PictureAlbum: ...
    @property
    def Count(self) -> int: ...
    def __iter__(self) -> Iterator[PictureAlbum]: ...
    def __enter__(self) -> PictureAlbumCollection: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class PictureCollection:
    def Dispose(self) -> None: ...
    def GetEnumerator(self) -> Iterator[Picture]: ...
    @property
    def IsDisposed(self) -> bool: ...
    def __getitem__(self, index: int) -> Picture: ...
    @property
    def Count(self) -> int: ...
    def __iter__(self) -> Iterator[Picture]: ...
    def __enter__(self) -> PictureCollection: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class Playlist:
    def Dispose(self) -> None: ...
    def __eq__(self, second: Playlist) -> bool: ...
    def __ne__(self, second: Playlist) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Playlist) -> bool: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Songs(self) -> SongCollection: ...
    @property
    def Duration(self) -> timedelta: ...
    def __enter__(self) -> Playlist: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class PlaylistCollection:
    def Dispose(self) -> None: ...
    def GetEnumerator(self) -> Iterator[Playlist]: ...
    @property
    def IsDisposed(self) -> bool: ...
    def __getitem__(self, index: int) -> Playlist: ...
    @property
    def Count(self) -> int: ...
    def __iter__(self) -> Iterator[Playlist]: ...
    def __enter__(self) -> PlaylistCollection: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class Song:
    @staticmethod
    def FromUri(name: str, uri: str) -> Song: ...
    def Dispose(self) -> None: ...
    def __eq__(self, second: Song) -> bool: ...
    def __ne__(self, second: Song) -> bool: ...
    @overload
    def Equals(self, obj: object) -> bool: ...
    @overload
    def Equals(self, other: Song) -> bool: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Artist(self) -> Artist | None: ...
    @property
    def Album(self) -> Album | None: ...
    @property
    def Genre(self) -> Genre | None: ...
    @property
    def Duration(self) -> timedelta: ...
    @property
    def IsRated(self) -> bool: ...
    @property
    def Rating(self) -> int: ...
    @property
    def PlayCount(self) -> int: ...
    @property
    def TrackNumber(self) -> int: ...
    @property
    def IsProtected(self) -> bool: ...
    def __enter__(self) -> Song: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class SongCollection:
    def Dispose(self) -> None: ...
    def GetEnumerator(self) -> Iterator[Song]: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Count(self) -> int: ...
    def __getitem__(self, index: int) -> Song: ...
    def __iter__(self) -> Iterator[Song]: ...
    def __enter__(self) -> SongCollection: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class Video:
    @property
    def Duration(self) -> timedelta: ...
    @property
    def Width(self) -> int: ...
    @property
    def Height(self) -> int: ...
    @property
    def FramesPerSecond(self) -> float: ...
    @property
    def VideoSoundtrackType(self) -> VideoSoundtrackType: ...

class VideoPlayer:
    def __init__(self) -> None: ...
    def Dispose(self) -> None: ...
    def Play(self, video: Video) -> None: ...
    def Pause(self) -> None: ...
    def Resume(self) -> None: ...
    def Stop(self) -> None: ...
    def GetTexture(self) -> Texture2D | None: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Video(self) -> Video | None: ...
    @property
    def State(self) -> MediaState: ...
    @property
    def IsLooped(self) -> bool: ...
    @IsLooped.setter
    def IsLooped(self, value: bool) -> None: ...
    @property
    def IsMuted(self) -> bool: ...
    @IsMuted.setter
    def IsMuted(self, value: bool) -> None: ...
    @property
    def Volume(self) -> float: ...
    @Volume.setter
    def Volume(self, value: float) -> None: ...
    @property
    def PlayPosition(self) -> timedelta: ...
    def __enter__(self) -> VideoPlayer: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class VideoSoundtrackType(IntEnum):
    Music: int
    Dialog: int
    MusicAndDialog: int

class VisualizationData:
    def __init__(self) -> None: ...
    @property
    def Frequencies(self) -> tuple[float, ...]: ...
    @property
    def Samples(self) -> tuple[float, ...]: ...
