"""ctypes manifest for CNA's ``cnb.h`` compiled-content family.

Split out of :mod:`_cna_native.loader` because it is a family of its own: 270
routes over one header, imported because ``cna.extensions.content`` projects
them, not because the XNA profile needs any of them.  Every entry is proven
against the canonical C declaration by ``tools/verify_prototypes.py``, and the
fourth column states the ownership contract the Python wrapper has to keep.

Two ``cnb.h`` routes are deliberately absent.  ``cna_cnb_checked_add`` and
``cna_cnb_checked_multiply`` exist so a C reader can combine two file-declared
64-bit values without wrapping around; Python integers are unbounded, so the
same computation is exact without them and a call would only convert an exact
answer into a narrower one.  ``_cna_native.cnb_support`` performs those bounds
checks in Python instead, at the point where a value actually has to fit a
native width.
"""

from __future__ import annotations

import ctypes as c

from . import abi
from . import cnb_abi as cnb

#: Every imported ``cnb.h`` route, with its ownership contract.
CNB_FUNCTION_MANIFEST: tuple[tuple[str, object, list[object], str], ...] = (
    ("cna_cnb_read_limits_init", c.c_uint32, [c.POINTER(cnb.CNA_CnbReadLimits)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_copy_format_magic", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_make_chunk_id", c.c_uint32, [c.c_uint8, c.c_uint8, c.c_uint8, c.c_uint8, c.POINTER(c.c_uint32)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_get_chunk_id_string_size", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_copy_chunk_id_string", c.c_uint32, [c.c_uint32, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_is_well_formed_chunk_id", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_asset_type_id_from_name", c.c_uint32, [abi.CNA_StringView, c.POINTER(c.c_uint32)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_is_custom_asset_type_id", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_get_asset_type_name_size", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_copy_asset_type_name", c.c_uint32, [c.c_uint32, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_get_logical_name_problem_size", c.c_uint32, [abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_copy_logical_name_problem", c.c_uint32, [abi.CNA_StringView, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_crc32c", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint32)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_crc32c_continue", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint32)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_crc32c_uses_hardware", c.c_uint32, [c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_crc32c_portable", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint32)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_is_compression_supported", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_get_compression_name_size", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_copy_compression_name", c.c_uint32, [c.c_uint32, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_get_compressed_byte_count", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, c.c_uint32, c.c_int32, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_copy_compressed", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, c.c_uint32, c.c_int32, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_copy_decompressed", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, c.c_uint32, c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_chunk_entry_is_mandatory", c.c_uint32, [c.POINTER(cnb.CNA_CnbChunkEntry), c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_has_magic", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_document_parse", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, abi.CNA_StringView, c.POINTER(cnb.CNA_CnbReadLimits), c.POINTER(c.c_uint64)],
     "owned document; copies the file bytes"),
    ("cna_cnb_document_parse_file", c.c_uint32, [abi.CNA_StringView, c.POINTER(cnb.CNA_CnbReadLimits), c.POINTER(c.c_uint64)],
     "owned document; copies the file bytes"),
    ("cna_cnb_document_destroy", c.c_uint32, [c.c_uint64],
     "consumes document; refused while a chunk reader still borrows it"),
    ("cna_cnb_document_get_origin_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_copy_origin", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_container_major", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint16)],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_container_minor", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint16)],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_asset_type_id", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_asset_schema_version", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_chunk_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_chunk", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbChunkEntry)],
     "caller output; borrowed document"),
    ("cna_cnb_document_copy_chunk_data", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_open_chunk", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "owned reader that borrows the document until it is destroyed"),
    ("cna_cnb_document_find_all", c.c_uint32, [c.c_uint64, c.c_uint32, c.POINTER(c.c_uint64), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_find_single", c.c_uint32, [c.c_uint64, c.c_uint32, c.POINTER(c.c_uint8), c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_require_single", c.c_uint32, [c.c_uint64, c.c_uint32, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_require_mandatory_chunks_understood", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32), c.c_uint64],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_metadata", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbMetadata)],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_metadata_asset_type_name_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_copy_metadata_asset_type_name", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_metadata_content_name_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_copy_metadata_content_name", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_external_reference_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_external_reference", c.c_uint32, [c.c_uint64, c.c_uint64, abi.CNA_StringView, c.POINTER(cnb.CNA_CnbExternalReference)],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_external_reference_name_size", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_copy_external_reference_name", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document"),
    ("cna_cnb_document_require_asset", c.c_uint32, [c.c_uint64, c.c_uint32, c.c_uint32],
     "caller output; borrowed document"),
    ("cna_cnb_document_get_limits", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbReadLimits)],
     "caller output; borrowed document"),
    ("cna_cnb_reader_create", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, abi.CNA_StringView, c.POINTER(cnb.CNA_CnbReadLimits), c.POINTER(c.c_uint64)],
     "owned reader; copies the bytes it is given"),
    ("cna_cnb_reader_destroy", c.c_uint32, [c.c_uint64],
     "consumes reader; releases any document borrow"),
    ("cna_cnb_reader_get_remaining", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_get_position", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_get_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_get_context_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_copy_context", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_read_u8", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_read_u16", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint16)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_read_u32", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_read_u64", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_read_i32", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_read_f32", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_read_f64", c.c_uint32, [c.c_uint64, c.POINTER(c.c_double)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_read_string", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_copy_string", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_read_count", c.c_uint32, [c.c_uint64, c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint32)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_read_bytes", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_skip", c.c_uint32, [c.c_uint64, c.c_uint64],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_require_exhausted", c.c_uint32, [c.c_uint64],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_fail", c.c_uint32, [c.c_uint64, abi.CNA_StringView],
     "caller output; borrowed reader"),
    ("cna_cnb_is_well_formed_utf8", c.c_uint32, [abi.CNA_StringView, c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_byte_writer_create", c.c_uint32, [c.POINTER(c.c_uint64)],
     "owned byte writer"),
    ("cna_cnb_byte_writer_create_from_bytes", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "owned byte writer; copies the initial bytes"),
    ("cna_cnb_byte_writer_destroy", c.c_uint32, [c.c_uint64],
     "consumes byte writer"),
    ("cna_cnb_byte_writer_write_u8", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed byte writer; copies the value"),
    ("cna_cnb_byte_writer_write_u16", c.c_uint32, [c.c_uint64, c.c_uint16],
     "borrowed byte writer; copies the value"),
    ("cna_cnb_byte_writer_write_u32", c.c_uint32, [c.c_uint64, c.c_uint32],
     "borrowed byte writer; copies the value"),
    ("cna_cnb_byte_writer_write_u64", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed byte writer; copies the value"),
    ("cna_cnb_byte_writer_write_i32", c.c_uint32, [c.c_uint64, c.c_int32],
     "borrowed byte writer; copies the value"),
    ("cna_cnb_byte_writer_write_f32", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed byte writer; copies the value"),
    ("cna_cnb_byte_writer_write_f64", c.c_uint32, [c.c_uint64, c.c_double],
     "borrowed byte writer; copies the value"),
    ("cna_cnb_byte_writer_write_string", c.c_uint32, [c.c_uint64, abi.CNA_StringView],
     "borrowed byte writer; copies the value"),
    ("cna_cnb_byte_writer_write_bytes", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64],
     "borrowed byte writer; copies the value"),
    ("cna_cnb_byte_writer_write_zeros", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed byte writer; copies the value"),
    ("cna_cnb_byte_writer_get_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed byte writer"),
    ("cna_cnb_byte_writer_copy_bytes", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed byte writer"),
    ("cna_cnb_byte_writer_take", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; empties the writer on success and takes nothing on refusal"),
    ("cna_cnb_writer_create", c.c_uint32, [c.c_uint32, c.c_uint32, c.POINTER(c.c_uint64)],
     "owned container writer"),
    ("cna_cnb_writer_destroy", c.c_uint32, [c.c_uint64],
     "consumes container writer"),
    ("cna_cnb_writer_set_metadata", c.c_uint32, [c.c_uint64, abi.CNA_StringView, abi.CNA_StringView],
     "borrowed container writer; copies the value"),
    ("cna_cnb_writer_add_external_reference", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbExternalReference), abi.CNA_StringView],
     "borrowed container writer; copies the value"),
    ("cna_cnb_writer_clear_external_references", c.c_uint32, [c.c_uint64],
     "borrowed container writer; copies the value"),
    ("cna_cnb_writer_add_chunk", c.c_uint32, [c.c_uint64, c.c_uint32, c.POINTER(c.c_uint8), c.c_uint64, c.c_uint32, c.c_uint32],
     "borrowed container writer; copies the value"),
    ("cna_cnb_writer_get_schema_chunk_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed container writer"),
    ("cna_cnb_writer_set_compression", c.c_uint32, [c.c_uint64, c.c_uint32, c.c_int32],
     "borrowed container writer; copies the value"),
    ("cna_cnb_writer_set_limits", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbReadLimits)],
     "borrowed container writer; copies the value"),
    ("cna_cnb_writer_get_limits", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbReadLimits)],
     "caller output; borrowed container writer"),
    ("cna_cnb_writer_build", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed container writer"),
    ("cna_cnb_writer_write_to_file", c.c_uint32, [c.c_uint64, abi.CNA_StringView],
     "caller output; borrowed container writer"),
    ("cna_cnb_is_known_texture_format", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_get_texture_format_name_size", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_copy_texture_format_name", c.c_uint32, [c.c_uint32, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_is_block_compressed_texture_format", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_get_texture_format_unit_bytes", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint32)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_get_texture_level_byte_size", c.c_uint32, [c.c_uint32, c.c_uint32, c.c_uint32, c.c_uint32, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_texture_format_to_surface_format", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint32)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_texture_format_from_surface_format", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint32)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_texture_data_create", c.c_uint32, [c.c_uint32, c.c_uint32, c.c_uint32, c.c_uint32, c.c_uint32, c.POINTER(c.c_uint64)],
     "owned texture data; copies any pixels it is given"),
    ("cna_cnb_texture_data_create_rgba8", c.c_uint32, [c.c_uint32, c.c_uint32, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "owned texture data; copies any pixels it is given"),
    ("cna_cnb_texture_data_destroy", c.c_uint32, [c.c_uint64],
     "consumes texture data"),
    ("cna_cnb_texture_data_get_info", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbTextureInfo)],
     "caller output; borrowed texture data"),
    ("cna_cnb_texture_data_get_level_dimensions", c.c_uint32, [c.c_uint64, c.c_uint32, c.POINTER(c.c_uint32), c.POINTER(c.c_uint32), c.POINTER(c.c_uint32)],
     "caller output; borrowed texture data"),
    ("cna_cnb_texture_data_add_representation", c.c_uint32, [c.c_uint64, c.c_uint32, c.POINTER(c.c_uint64)],
     "borrowed texture data; copies the payload"),
    ("cna_cnb_texture_data_get_representation_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed texture data"),
    ("cna_cnb_texture_data_get_representation_format", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed texture data"),
    ("cna_cnb_texture_data_get_level_count", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed texture data"),
    ("cna_cnb_texture_data_set_level", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64],
     "borrowed texture data; copies the payload"),
    ("cna_cnb_texture_data_copy_level", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed texture data"),
    ("cna_cnb_texture_data_select_representation", c.c_uint32, [c.c_uint64, cnb.CNA_CnbTextureFormatSupportedFn, c.c_void_p, c.POINTER(c.c_uint8), c.POINTER(c.c_uint64)],
     "caller output; the predicate is call-scoped and never retained"),
    ("cna_cnb_encode_texture2d", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed texture data"),
    ("cna_cnb_encode_texture_cube", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed texture data"),
    ("cna_cnb_encode_texture3d", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed texture data"),
    ("cna_cnb_decode_texture2d", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned texture data; borrowed document"),
    ("cna_cnb_decode_texture_cube", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned texture data; borrowed document"),
    ("cna_cnb_decode_texture3d", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned texture data; borrowed document"),
    ("cna_cnb_writer_append_embedded_texture2d", c.c_uint32, [c.c_uint64, c.c_uint64, abi.CNA_StringView],
     "borrowed container writer; copies the value"),
    ("cna_cnb_document_read_embedded_texture2d", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "owned texture data; borrowed document"),
    ("cna_cnb_model_create", c.c_uint32, [c.POINTER(c.c_uint64)],
     "owned model data"),
    ("cna_cnb_model_destroy", c.c_uint32, [c.c_uint64],
     "consumes model data"),
    ("cna_cnb_model_get_info", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbModelInfo)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_set_flags", c.c_uint32, [c.c_uint64, c.c_uint8, c.c_uint8],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_add_bone", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.c_int32, c.POINTER(c.c_float), c.POINTER(c.c_uint64)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_get_bone", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbModelBone)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_get_bone_name_size", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_copy_bone_name", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_add_part", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbModelPartInfo), abi.CNA_StringView, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_get_part", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbModelPartInfo)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_set_part", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbModelPartInfo)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_get_part_name_size", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_copy_part_name", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_get_part_external_effect_size", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_copy_part_external_effect", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_set_part_vertex_bytes", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_copy_part_vertex_bytes", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_set_part_index_bytes", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_copy_part_index_bytes", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_get_material", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbMaterialInfo)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_set_material", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbMaterialInfo)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_get_material_texture_size", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint32, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_copy_material_texture", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint32, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_set_material_texture", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint32, abi.CNA_StringView],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_get_material_texture_coordinate_set", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_set_material_texture_coordinate_set", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.c_uint8],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_get_material_texture_transform", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbTextureTransform)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_set_material_texture_transform", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbTextureTransform)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_get_material_sampler", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbSamplerState)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_set_material_sampler", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbSamplerState)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_has_morph", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_get_morph", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbMorphInfo)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_set_morph", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbMorphInfo)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_clear_morph", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_add_morph_target", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_set_morph_target_deltas", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.c_uint32, c.POINTER(c.c_float), c.c_uint64],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_copy_morph_target_deltas", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.c_uint32, c.POINTER(c.c_float), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_set_morph_weights", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_float), c.c_uint64],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_copy_morph_weights", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_float), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_add_morph_weight_key", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_double, c.POINTER(c.c_float), c.c_uint64, c.POINTER(c.c_float), c.c_uint64, c.POINTER(c.c_float), c.c_uint64, c.POINTER(c.c_uint64)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_get_morph_weight_key", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbMorphWeightKeyInfo)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_copy_morph_weight_key_values", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.c_uint32, c.POINTER(c.c_float), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_add_mesh", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.c_int32, c.POINTER(c.c_uint32), c.c_uint64, c.POINTER(c.c_uint64)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_get_mesh", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbMeshInfo)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_get_mesh_name_size", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_copy_mesh_name", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_copy_mesh_part_indices", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint32), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_set_skeleton", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32), c.c_uint64, c.POINTER(c.c_float), c.POINTER(c.c_float), c.POINTER(c.c_float)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_clear_skeleton", c.c_uint32, [c.c_uint64],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_get_skeleton", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbSkeletonInfo)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_copy_skeleton_hierarchy", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_copy_skeleton_matrices", c.c_uint32, [c.c_uint64, c.c_uint32, c.POINTER(c.c_float), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_add_animation", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(cnb.CNA_AnimationClipEXTDescriptor), c.c_uint32, c.POINTER(c.c_uint64)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_get_animation_name_size", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_copy_animation_name", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_get_animation", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_double), c.POINTER(c.c_uint64), c.POINTER(c.c_uint32)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_get_animation_track", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.POINTER(c.c_int32), c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_copy_animation_keyframes", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_KeyframeEXT), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_model_add_light", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbModelLight), c.POINTER(c.c_uint64)],
     "borrowed model data; copies the value"),
    ("cna_cnb_model_get_light", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_CnbModelLight)],
     "caller output; borrowed model data"),
    ("cna_cnb_encode_model", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed model data"),
    ("cna_cnb_decode_model", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned model data; borrowed document"),
    ("cna_cnb_build_model_from_cnj", c.c_uint32, [abi.CNA_StringView, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "owned compile result"),
    ("cna_cnb_model_from_cnj_destroy", c.c_uint32, [c.c_uint64],
     "consumes compile result"),
    ("cna_cnb_model_from_cnj_take_model", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "transfers the model out of the result exactly once; the result keeps none"),
    ("cna_cnb_model_from_cnj_get_absorbed_file_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_model_from_cnj_get_absorbed_file_size", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_model_from_cnj_copy_absorbed_file", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_model_from_cnj_get_external_reference_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_model_from_cnj_get_external_reference_size", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_model_from_cnj_copy_external_reference", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_sprite_font_data_create", c.c_uint32, [c.POINTER(c.c_uint64)],
     "owned sprite font data"),
    ("cna_cnb_sprite_font_data_destroy", c.c_uint32, [c.c_uint64],
     "consumes sprite font data"),
    ("cna_cnb_sprite_font_data_get_info", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbSpriteFontInfo)],
     "caller output; borrowed sprite font data"),
    ("cna_cnb_sprite_font_data_set_info", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbSpriteFontInfo)],
     "borrowed sprite font data; copies the value"),
    ("cna_cnb_sprite_font_data_add_glyph", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_SpriteFontGlyph), c.POINTER(c.c_uint64)],
     "borrowed sprite font data; copies the value"),
    ("cna_cnb_sprite_font_data_get_glyph", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(abi.CNA_SpriteFontGlyph)],
     "caller output; borrowed sprite font data"),
    ("cna_cnb_sprite_font_data_set_glyph", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(abi.CNA_SpriteFontGlyph)],
     "borrowed sprite font data; copies the value"),
    ("cna_cnb_sprite_font_data_set_atlas", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed font; copies the atlas rather than adopting the handle"),
    ("cna_cnb_sprite_font_data_copy_atlas", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned texture data holding a copy of the atlas; borrowed font"),
    ("cna_cnb_encode_sprite_font", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed sprite font data"),
    ("cna_cnb_decode_sprite_font", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned sprite font data; borrowed document"),
    ("cna_cnb_audio_frame_bytes", c.c_uint32, [c.c_uint32, c.c_uint32, c.POINTER(c.c_uint32)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_get_audio_format_name_size", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_copy_audio_format_name", c.c_uint32, [c.c_uint32, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cnb_sound_effect_data_create", c.c_uint32, [c.POINTER(cnb.CNA_CnbSoundEffectInfo), c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "owned sound data; copies the samples"),
    ("cna_cnb_sound_effect_data_destroy", c.c_uint32, [c.c_uint64],
     "consumes sound data"),
    ("cna_cnb_sound_effect_data_get_info", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbSoundEffectInfo)],
     "caller output; borrowed sound data"),
    ("cna_cnb_sound_effect_data_copy_samples", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed sound data"),
    ("cna_cnb_encode_sound_effect", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed sound data"),
    ("cna_cnb_decode_sound_effect", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned sound data; borrows its source for the call only"),
    ("cna_cnb_encode_song", c.c_uint32, [abi.CNA_StringView, abi.CNA_StringView, c.c_uint32, abi.CNA_StringView, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document or borrowed input strings"),
    ("cna_cnb_decode_song_duration_milliseconds", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed document or borrowed input strings"),
    ("cna_cnb_decode_song_stream_reference_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document or borrowed input strings"),
    ("cna_cnb_decode_song_stream_reference", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document or borrowed input strings"),
    ("cna_cnb_decode_song_name_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document or borrowed input strings"),
    ("cna_cnb_decode_song_name", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document or borrowed input strings"),
    ("cna_cnb_encode_video", c.c_uint32, [abi.CNA_StringView, c.POINTER(cnb.CNA_CnbVideoInfo), abi.CNA_StringView, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document or borrowed input strings"),
    ("cna_cnb_decode_video", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_CnbVideoInfo)],
     "caller output; borrowed document or borrowed input strings"),
    ("cna_cnb_decode_video_stream_reference_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document or borrowed input strings"),
    ("cna_cnb_decode_video_stream_reference", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed document or borrowed input strings"),
    ("cna_cnb_encode_curve", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed native curve"),
    ("cna_cnb_decode_curve", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned native curve; borrowed document"),
    ("cna_cnb_encode_animation_clip", c.c_uint32, [c.POINTER(cnb.CNA_AnimationClipEXTDescriptor), c.c_uint32, abi.CNA_StringView, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrows the descriptor for the call only"),
    ("cna_cnb_decode_animation_clip", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned animation clip; borrowed document"),
    ("cna_cnb_animation_clip_destroy", c.c_uint32, [c.c_uint64],
     "consumes animation clip"),
    ("cna_cnb_animation_clip_get", c.c_uint32, [c.c_uint64, c.POINTER(c.c_double), c.POINTER(c.c_uint64), c.POINTER(c.c_uint32)],
     "caller output; borrowed animation clip"),
    ("cna_cnb_animation_clip_get_track", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_int32), c.POINTER(c.c_uint64)],
     "caller output; borrowed animation clip"),
    ("cna_cnb_animation_clip_copy_keyframes", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(cnb.CNA_KeyframeEXT), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed animation clip"),
    ("cna_cnb_reader_read_seconds", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_double)],
     "caller output; borrowed reader"),
    ("cna_cnb_reader_read_keyframe", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_KeyframeEXT)],
     "caller output; borrowed reader"),
    ("cna_cnb_byte_writer_write_keyframe", c.c_uint32, [c.c_uint64, c.POINTER(cnb.CNA_KeyframeEXT)],
     "borrowed byte writer; copies the value"),
    ("cna_cnb_loader_registry_register", c.c_uint32, [c.c_uint32, abi.CNA_StringView, cnb.CNA_CnbLoaderCallback, c.c_void_p],
     "process-global registration; the callback and its context must outlive it"),
    ("cna_cnb_loader_registry_remove", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint8)],
     "process-global registration; withdraws it"),
    ("cna_cnb_loader_registry_clear", c.c_uint32, [],
     "process-global registration; withdraws it"),
    ("cna_cnb_loader_registry_is_registered", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint8)],
     "caller output; process-global registry"),
    ("cna_cnb_loader_registry_find", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint8), c.POINTER(c.c_uint64)],
     "owned loader copy; process-global registry"),
    ("cna_cnb_loader_registry_get_registered_type_name_size", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64)],
     "caller output; process-global registry"),
    ("cna_cnb_loader_registry_copy_registered_type_name", c.c_uint32, [c.c_uint32, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; process-global registry"),
    ("cna_cnb_loader_registry_resolve_for_document", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned loader copy; process-global registry"),
    ("cna_cnb_loader_registry_register_builtins", c.c_uint32, [],
     "process-global registration; idempotent"),
    ("cna_cnb_loader_destroy", c.c_uint32, [c.c_uint64],
     "consumes loader copy"),
    ("cna_cnb_loader_invoke", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_void_p)],
     "caller output; the object pointer is never dereferenced, copied or freed by CNA"),
    ("cna_cnb_import_image_as_texture2d", c.c_uint32, [abi.CNA_StringView, c.POINTER(cnb.CNA_CnbImageImportOptions), c.POINTER(c.c_uint64)],
     "owned texture data; borrows its source for the call only"),
    ("cna_cnb_import_dds_as_texture_cube", c.c_uint32, [abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "owned texture data; borrows its source for the call only"),
    ("cna_cnb_decode_dds_as_texture_cube", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "owned texture data; borrows its source for the call only"),
    ("cna_cnb_decode_wav_as_sound_effect", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "owned sound data; borrows its source for the call only"),
    ("cna_cnb_import_wav_as_sound_effect", c.c_uint32, [abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "owned sound data; borrows its source for the call only"),
    ("cna_cnb_compile_cnj", c.c_uint32, [abi.CNA_StringView, abi.CNA_StringView, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "owned compile result"),
    ("cna_cnb_cnj_result_destroy", c.c_uint32, [c.c_uint64],
     "consumes compile result"),
    ("cna_cnb_cnj_result_get_asset_type_id", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed compile result"),
    ("cna_cnb_cnj_result_get_asset_type_name_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_cnj_result_copy_asset_type_name", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_cnj_result_copy_bytes", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_cnj_result_get_absorbed_file_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_cnj_result_get_absorbed_file_size", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_cnj_result_copy_absorbed_file", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_cnj_result_get_external_reference_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_cnj_result_get_external_reference_size", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
    ("cna_cnb_cnj_result_copy_external_reference", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed compile result"),
)

#: The minimal ``curve.h`` slice the CNB curve codec depends on.
#:
#: ``cna_cnb_encode_curve`` takes a native ``Curve`` handle and
#: ``cna_cnb_decode_curve`` produces one, so the codec cannot be reached at all
#: from a managed-only ``Microsoft.Xna.Framework.Curve``.  These eleven routes
#: are the smallest set that builds a native curve from managed keys and reads
#: one back; they are a dependency of the selected CNB profile rather than a
#: decision to bind ``curve.h``, and the strict XNA ``Curve`` stays managed and
#: unchanged.
CURVE_CODEC_FUNCTION_MANIFEST: tuple[tuple[str, object, list[object], str], ...] = (
    ("cna_curve_create", c.c_uint32, [c.POINTER(c.c_uint64)],
     "owned native curve, built only to feed the CNB curve codec"),
    ("cna_curve_destroy", c.c_uint32, [c.c_uint64],
     "consumes native curve"),
    ("cna_curve_get_keys", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned collection view that retains its curve"),
    ("cna_curve_get_pre_loop", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed native curve"),
    ("cna_curve_set_pre_loop", c.c_uint32, [c.c_uint64, c.c_uint32],
     "borrowed native curve; copies the value"),
    ("cna_curve_get_post_loop", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed native curve"),
    ("cna_curve_set_post_loop", c.c_uint32, [c.c_uint64, c.c_uint32],
     "borrowed native curve; copies the value"),
    ("cna_curve_key_collection_destroy", c.c_uint32, [c.c_uint64],
     "consumes collection view"),
    ("cna_curve_key_collection_get_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed native curve"),
    ("cna_curve_key_collection_get", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(cnb.CNA_CurveKey)],
     "caller output; borrowed native curve"),
    ("cna_curve_key_collection_add", c.c_uint32, [c.c_uint64, cnb.CNA_CurveKey],
     "borrowed native curve; copies the value"),
)

#: The minimal ``content.h`` slice the CNB loader registry depends on.
#:
#: ``cna_cnb_loader_invoke`` takes a content-manager handle and **requires** it:
#: passing none is refused, because the canonical loader signature takes the
#: manager by reference and there is no "no manager" to pass.  Without these two
#: routes a registered loader can be resolved and never invoked, so the registry
#: would be surface with no capability behind it.
#:
#: Exactly create and destroy are imported.  No load route, no cache route and no
#: root-directory route is: this manager exists so a loader has the collaborator
#: its signature demands, and it shares nothing with
#: ``Microsoft.Xna.Framework.Content.ContentManager``, which stays managed XNB
#: with its own separate cache.
NATIVE_CONTENT_MANAGER_FUNCTION_MANIFEST: tuple[
        tuple[str, object, list[object], str], ...] = (
    ("cna_content_manager_create", c.c_uint32,
     [c.c_uint64, c.POINTER(cnb.CNA_ContentManagerCreateInfo), c.POINTER(c.c_uint64)],
     "owned content manager; borrows the graphics device for the call"),
    ("cna_content_manager_destroy", c.c_uint32, [c.c_uint64],
     "consumes content manager; must run on the game creation thread"),
)
