"""ctypes manifest for CNA's ``sensors.h``, ``devices.h`` family.

Do not edit. ``tools/generate_family_manifest.py`` derives every prototype
from the canonical headers, and ``--check`` fails when the checked-in copy is
not what the current headers produce. Every entry is proven against the
canonical C declaration by ``tools/verify_prototypes.py`` -- being generated is
not a reason to trust it.

The fourth column is the ownership contract the Python wrapper has to keep.
"""

from __future__ import annotations

import ctypes as c

from . import abi
from . import devices_abi

Entry = tuple[str, object, list[object], str]

#: The accelerometer: its reading value, its state machine, and the synthetic
#: backend the qualification uses instead of physical hardware.
DEVICES_ACCELEROMETER_MANIFEST: tuple[Entry, ...] = (
    ("cna_accelerometer_copy_last_dispatch_exception_message_for_tests_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_accelerometer_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned sensor; borrows the game for the call and holds no reference to it"),
    ("cna_accelerometer_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_accelerometer_dispatch_to_instances_for_tests_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64), c.c_uint64, c.c_float, c.c_float, c.c_float],
     "borrowed handle; retains nothing"),
    ("cna_accelerometer_dispose", c.c_uint32, [c.c_uint64],
     "stops the sensor and releases its subsystem hold; the handle stays valid"),
    ("cna_accelerometer_get_current_value", c.c_uint32, [c.c_uint64, c.POINTER(devices_abi.CNA_AccelerometerReading)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_accelerometer_get_dispatch_exception_count_for_tests_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_accelerometer_get_is_data_valid", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_accelerometer_get_is_supported", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_accelerometer_get_last_dispatch_exception_message_size_for_tests_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_accelerometer_get_state", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_accelerometer_get_subsystem_held_for_tests_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_accelerometer_get_time_between_updates_ticks", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_accelerometer_inject_synthetic_update_ext", c.c_uint32, [c.c_uint64, c.c_float, c.c_float, c.c_float],
     "borrowed handle; retains nothing"),
    ("cna_accelerometer_is_sensor_connected_for_tests_ext", c.c_uint32, [c.c_uint64, c.c_int64, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_accelerometer_reading_copy_string", c.c_uint32, [c.POINTER(devices_abi.CNA_AccelerometerReading), c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_accelerometer_reading_equals", c.c_uint32, [c.POINTER(devices_abi.CNA_AccelerometerReading), c.POINTER(devices_abi.CNA_AccelerometerReading), c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_accelerometer_reading_event_info_copy_string", c.c_uint32, [c.POINTER(devices_abi.CNA_AccelerometerReadingEventInfo), c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_accelerometer_reading_event_info_equals", c.c_uint32, [c.POINTER(devices_abi.CNA_AccelerometerReadingEventInfo), c.POINTER(devices_abi.CNA_AccelerometerReadingEventInfo), c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_accelerometer_reading_event_info_get_hash_code", c.c_uint32, [c.POINTER(devices_abi.CNA_AccelerometerReadingEventInfo), c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_accelerometer_reading_event_info_get_string_size", c.c_uint32, [c.POINTER(devices_abi.CNA_AccelerometerReadingEventInfo), c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_accelerometer_reading_event_info_init_from_values", c.c_uint32, [c.c_double, c.c_double, c.c_double, devices_abi.CNA_DateTimeOffset, c.POINTER(devices_abi.CNA_AccelerometerReadingEventInfo)],
     "pure value initialiser over caller-owned storage"),
    ("cna_accelerometer_reading_get_hash_code", c.c_uint32, [c.POINTER(devices_abi.CNA_AccelerometerReading), c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_accelerometer_reading_get_string_size", c.c_uint32, [c.POINTER(devices_abi.CNA_AccelerometerReading), c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_accelerometer_reading_init_from_values", c.c_uint32, [devices_abi.CNA_DateTimeOffset, abi.CNA_Vector3, c.POINTER(devices_abi.CNA_AccelerometerReading)],
     "pure value initialiser over caller-owned storage"),
    ("cna_accelerometer_register_started_instance_for_tests_ext", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_accelerometer_set_disposal_cleanup_hook_for_tests_ext", c.c_uint32, [c.c_uint64, devices_abi.CNA_SensorEventCallback, c.c_void_p],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_accelerometer_set_event_watch_registration_failure_for_tests_ext", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_accelerometer_set_started_for_tests_ext", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_accelerometer_set_supported_for_tests_ext", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_accelerometer_set_time_between_updates_ticks", c.c_uint32, [c.c_uint64, c.c_int64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_accelerometer_start", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_accelerometer_stop", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_accelerometer_subscribe_current_value_changed", c.c_uint32, [c.c_uint64, devices_abi.CNA_AccelerometerReadingCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_accelerometer_subscribe_reading_changed", c.c_uint32, [c.c_uint64, devices_abi.CNA_AccelerometerReadingEventCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_accelerometer_unregister_started_instance_for_tests_ext", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
)

#: The compass: magnetic and true heading, accuracy, and calibration requests.
DEVICES_COMPASS_MANIFEST: tuple[Entry, ...] = (
    ("cna_compass_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned sensor; borrows the game for the call and holds no reference to it"),
    ("cna_compass_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_compass_dispose", c.c_uint32, [c.c_uint64],
     "stops the sensor and releases its subsystem hold; the handle stays valid"),
    ("cna_compass_get_current_value", c.c_uint32, [c.c_uint64, c.POINTER(devices_abi.CNA_CompassReading)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_compass_get_is_data_valid", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_compass_get_is_supported", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_compass_get_state", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_compass_get_time_between_updates_ticks", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_compass_inject_calibration_request_ext", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_compass_inject_synthetic_update_ext", c.c_uint32, [c.c_uint64, c.POINTER(devices_abi.CNA_CompassReading)],
     "borrowed handle; retains nothing"),
    ("cna_compass_reading_copy_string", c.c_uint32, [c.POINTER(devices_abi.CNA_CompassReading), c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_compass_reading_equals", c.c_uint32, [c.POINTER(devices_abi.CNA_CompassReading), c.POINTER(devices_abi.CNA_CompassReading), c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_compass_reading_get_hash_code", c.c_uint32, [c.POINTER(devices_abi.CNA_CompassReading), c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_compass_reading_get_string_size", c.c_uint32, [c.POINTER(devices_abi.CNA_CompassReading), c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_compass_reading_init_from_values", c.c_uint32, [c.c_double, c.c_double, abi.CNA_Vector3, devices_abi.CNA_DateTimeOffset, c.c_double, c.POINTER(devices_abi.CNA_CompassReading)],
     "pure value initialiser over caller-owned storage"),
    ("cna_compass_set_test_backend_ext", c.c_uint32, [c.c_uint64, c.c_uint8, c.c_uint8],
     "test backend only; installs a deterministic implementation and resets its log"),
    ("cna_compass_set_time_between_updates_ticks", c.c_uint32, [c.c_uint64, c.c_int64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_compass_start", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_compass_stop", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_compass_subscribe_calibrate", c.c_uint32, [c.c_uint64, devices_abi.CNA_SensorEventCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_compass_subscribe_current_value_changed", c.c_uint32, [c.c_uint64, devices_abi.CNA_CompassReadingCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
)

#: The gyroscope: angular rotation rate and its state machine.
DEVICES_GYROSCOPE_MANIFEST: tuple[Entry, ...] = (
    ("cna_gyroscope_copy_last_dispatch_exception_message_for_tests_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_gyroscope_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned sensor; borrows the game for the call and holds no reference to it"),
    ("cna_gyroscope_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_gyroscope_dispatch_to_instances_for_tests_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64), c.c_uint64, c.c_float, c.c_float, c.c_float],
     "borrowed handle; retains nothing"),
    ("cna_gyroscope_dispose", c.c_uint32, [c.c_uint64],
     "stops the sensor and releases its subsystem hold; the handle stays valid"),
    ("cna_gyroscope_get_current_value", c.c_uint32, [c.c_uint64, c.POINTER(devices_abi.CNA_GyroscopeReading)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gyroscope_get_dispatch_exception_count_for_tests_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gyroscope_get_is_data_valid", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gyroscope_get_is_supported", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gyroscope_get_last_dispatch_exception_message_size_for_tests_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_gyroscope_get_state", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gyroscope_get_subsystem_held_for_tests_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gyroscope_get_time_between_updates_ticks", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gyroscope_inject_synthetic_update_ext", c.c_uint32, [c.c_uint64, c.c_float, c.c_float, c.c_float],
     "borrowed handle; retains nothing"),
    ("cna_gyroscope_is_sensor_connected_for_tests_ext", c.c_uint32, [c.c_uint64, c.c_int64, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_gyroscope_reading_copy_string", c.c_uint32, [c.POINTER(devices_abi.CNA_GyroscopeReading), c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_gyroscope_reading_equals", c.c_uint32, [c.POINTER(devices_abi.CNA_GyroscopeReading), c.POINTER(devices_abi.CNA_GyroscopeReading), c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_gyroscope_reading_get_hash_code", c.c_uint32, [c.POINTER(devices_abi.CNA_GyroscopeReading), c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gyroscope_reading_get_string_size", c.c_uint32, [c.POINTER(devices_abi.CNA_GyroscopeReading), c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_gyroscope_reading_init_from_values", c.c_uint32, [abi.CNA_Vector3, devices_abi.CNA_DateTimeOffset, c.POINTER(devices_abi.CNA_GyroscopeReading)],
     "pure value initialiser over caller-owned storage"),
    ("cna_gyroscope_register_started_instance_for_tests_ext", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_gyroscope_set_disposal_cleanup_hook_for_tests_ext", c.c_uint32, [c.c_uint64, devices_abi.CNA_SensorEventCallback, c.c_void_p],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_gyroscope_set_event_watch_registration_failure_for_tests_ext", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_gyroscope_set_started_for_tests_ext", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_gyroscope_set_supported_for_tests_ext", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_gyroscope_set_time_between_updates_ticks", c.c_uint32, [c.c_uint64, c.c_int64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_gyroscope_start", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_gyroscope_stop", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_gyroscope_subscribe_current_value_changed", c.c_uint32, [c.c_uint64, devices_abi.CNA_GyroscopeReadingCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_gyroscope_unregister_started_instance_for_tests_ext", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
)

#: The fused motion sensor: attitude, gravity, device acceleration and rate.
DEVICES_MOTION_MANIFEST: tuple[Entry, ...] = (
    ("cna_motion_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned sensor; borrows the game for the call and holds no reference to it"),
    ("cna_motion_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_motion_dispose", c.c_uint32, [c.c_uint64],
     "stops the sensor and releases its subsystem hold; the handle stays valid"),
    ("cna_motion_get_current_value", c.c_uint32, [c.c_uint64, c.POINTER(devices_abi.CNA_MotionReading)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_motion_get_is_attitude_north_referenced_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_motion_get_is_data_valid", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_motion_get_is_supported", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_motion_get_state", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_motion_get_time_between_updates_ticks", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_motion_inject_calibration_request_ext", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_motion_inject_synthetic_update_ext", c.c_uint32, [c.c_uint64, c.POINTER(devices_abi.CNA_MotionReading)],
     "borrowed handle; retains nothing"),
    ("cna_motion_reading_copy_string", c.c_uint32, [c.POINTER(devices_abi.CNA_MotionReading), c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_motion_reading_equals", c.c_uint32, [c.POINTER(devices_abi.CNA_MotionReading), c.POINTER(devices_abi.CNA_MotionReading), c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_motion_reading_get_hash_code", c.c_uint32, [c.POINTER(devices_abi.CNA_MotionReading), c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_motion_reading_get_string_size", c.c_uint32, [c.POINTER(devices_abi.CNA_MotionReading), c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_motion_reading_init_from_values", c.c_uint32, [c.POINTER(devices_abi.CNA_AttitudeReading), abi.CNA_Vector3, abi.CNA_Vector3, abi.CNA_Vector3, devices_abi.CNA_DateTimeOffset, c.POINTER(devices_abi.CNA_MotionReading)],
     "pure value initialiser over caller-owned storage"),
    ("cna_motion_set_test_backend_ext", c.c_uint32, [c.c_uint64, c.c_uint8, c.c_uint8, c.c_uint8],
     "test backend only; installs a deterministic implementation and resets its log"),
    ("cna_motion_set_time_between_updates_ticks", c.c_uint32, [c.c_uint64, c.c_int64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_motion_start", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_motion_stop", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_motion_subscribe_calibrate", c.c_uint32, [c.c_uint64, devices_abi.CNA_SensorEventCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_motion_subscribe_current_value_changed", c.c_uint32, [c.c_uint64, devices_abi.CNA_MotionReadingCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
)

#: What every sensor shares: the attitude reading, calibration event identity,
#: the last error, and the one unsubscribe every sensor registration uses.
DEVICES_SENSOR_SHARED_MANIFEST: tuple[Entry, ...] = (
    ("cna_attitude_reading_copy_string", c.c_uint32, [c.POINTER(devices_abi.CNA_AttitudeReading), c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_attitude_reading_equals", c.c_uint32, [c.POINTER(devices_abi.CNA_AttitudeReading), c.POINTER(devices_abi.CNA_AttitudeReading), c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_attitude_reading_get_hash_code", c.c_uint32, [c.POINTER(devices_abi.CNA_AttitudeReading), c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_attitude_reading_get_string_size", c.c_uint32, [c.POINTER(devices_abi.CNA_AttitudeReading), c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_attitude_reading_init_from_values", c.c_uint32, [c.c_float, c.c_float, c.c_float, abi.CNA_Quaternion, abi.CNA_Matrix, devices_abi.CNA_DateTimeOffset, c.POINTER(devices_abi.CNA_AttitudeReading)],
     "pure value initialiser over caller-owned storage"),
    ("cna_sensor_unsubscribe_ext", c.c_uint32, [c.c_uint64],
     "consumes a subscription registration; no callback arrives afterwards"),
    ("cna_sensors_get_last_error_id_ext", c.c_uint32, [c.POINTER(c.c_int32), c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
)

#: The camera: enumeration, the deterministic frame backend, and acquisition.
DEVICES_CAMERA_MANIFEST: tuple[Entry, ...] = (
    ("cna_camera_copy_name_at_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_camera_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned camera; borrows the game for the call and holds no reference to it"),
    ("cna_camera_create_with_test_backend_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned camera over a deterministic backend; test use only"),
    ("cna_camera_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_camera_get_count_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_camera_get_frame_height_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_camera_get_frame_width_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_camera_get_info_at_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(devices_abi.CNA_CameraDeviceInfo)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_camera_get_is_supported_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_camera_get_name_size_at_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_camera_get_state_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_camera_set_test_frame_ext", c.c_uint32, [c.c_uint64, c.c_int32, c.c_int32, c.POINTER(abi.CNA_Color), c.c_uint64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_camera_set_test_state_ext", c.c_uint32, [c.c_uint64, c.c_uint32],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_camera_try_acquire_frame_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; copies the frame bytes into caller storage, retains nothing"),
)

#: The host itself: clipboard, display metrics, device class, locales, power
#: and system information.
DEVICES_HOST_MANIFEST: tuple[Entry, ...] = (
    ("cna_devices_clipboard_set_text_ext", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8)],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_devices_ext_is_available", c.c_uint32, [c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_display_info_get_content_scale_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_display_info_get_safe_area_ext", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Rectangle)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_environment_get_device_type", c.c_uint32, [c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_locale_copy_country_at_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_locale_copy_language_at_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_locale_get_country_size_at_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_locale_get_language_size_at_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_locale_get_preferred_count_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_power_get_battery_percent_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_power_get_seconds_remaining_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_power_get_state_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_system_info_get_logical_cpu_core_count_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_system_info_get_system_ram_megabytes_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_url_launcher_open_ext", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8)],
     "owned handle; the caller closes it and nothing else may"),
)

#: Host UI: file dialogs, message boxes and the system tray, each with the test
#: backend that answers without putting anything on a physical desktop.
DEVICES_DIALOGS_MANIFEST: tuple[Entry, ...] = (
    ("cna_file_dialog_get_is_supported_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_file_dialog_set_test_backend_ext", c.c_uint32, [c.c_uint64, c.c_uint8, c.POINTER(abi.CNA_StringView), c.c_uint64],
     "test backend only; installs a deterministic implementation and resets its log"),
    ("cna_file_dialog_show_open_file_ext", c.c_uint32, [c.c_uint64, devices_abi.CNA_FileDialogResultCallback, c.c_void_p, c.POINTER(devices_abi.CNA_FileDialogFilter), c.c_uint64, abi.CNA_StringView, c.c_uint8],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_file_dialog_show_open_folder_ext", c.c_uint32, [c.c_uint64, devices_abi.CNA_FileDialogResultCallback, c.c_void_p, abi.CNA_StringView, c.c_uint8],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_file_dialog_show_save_file_ext", c.c_uint32, [c.c_uint64, devices_abi.CNA_FileDialogResultCallback, c.c_void_p, c.POINTER(devices_abi.CNA_FileDialogFilter), c.c_uint64, abi.CNA_StringView],
     "borrowed handle; retains nothing"),
    ("cna_message_box_get_is_supported_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_message_box_get_test_log_ext", c.c_uint32, [c.c_uint64, c.POINTER(devices_abi.CNA_MessageBoxTestLog)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_message_box_set_test_backend_ext", c.c_uint32, [c.c_uint64, c.c_uint8, c.c_int32],
     "test backend only; installs a deterministic implementation and resets its log"),
    ("cna_message_box_show_ext", c.c_uint32, [c.c_uint64, c.c_uint32, abi.CNA_StringView, abi.CNA_StringView, c.POINTER(abi.CNA_StringView), c.c_uint64, c.POINTER(c.c_int32)],
     "borrowed handle; retains nothing"),
    ("cna_message_box_show_simple_ext", c.c_uint32, [c.c_uint64, c.c_uint32, abi.CNA_StringView, abi.CNA_StringView],
     "borrowed handle; retains nothing"),
    ("cna_system_tray_add_entry", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.c_uint8, c.c_uint8, c.c_uint8, devices_abi.CNA_TrayEntryClickCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_system_tray_click_entry_for_tests_ext", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_system_tray_create", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "owned tray; borrows the game for the call and holds no reference to it"),
    ("cna_system_tray_create_with_test_backend_ext", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "owned tray over a deterministic backend; test use only"),
    ("cna_system_tray_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_system_tray_get_entry_checked", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_system_tray_get_entry_enabled", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_system_tray_get_is_supported_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_system_tray_set_entry_checked", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_system_tray_set_entry_enabled", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_system_tray_set_entry_label", c.c_uint32, [c.c_uint64, c.c_uint64, abi.CNA_StringView],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_system_tray_set_tooltip", c.c_uint32, [c.c_uint64, abi.CNA_StringView],
     "borrowed handle; copies the value, retains nothing"),
)

#: Controller vibration, and the test log that records what was asked for.
DEVICES_VIBRATION_MANIFEST: tuple[Entry, ...] = (
    ("cna_vibrate_controller_copy_device_name_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_vibrate_controller_get_device_name_size_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_vibrate_controller_get_is_supported_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_vibrate_controller_get_test_log_ext", c.c_uint32, [c.c_uint64, c.POINTER(devices_abi.CNA_VibrationTestLog)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_vibrate_controller_set_test_backend_ext", c.c_uint32, [c.c_uint64, c.c_uint8, c.c_uint8, abi.CNA_StringView],
     "test backend only; installs a deterministic implementation and resets its log"),
    ("cna_vibrate_controller_start", c.c_uint32, [c.c_uint64, c.c_int64],
     "borrowed handle; retains nothing"),
    ("cna_vibrate_controller_start_left_right_ext", c.c_uint32, [c.c_uint64, c.c_float, c.c_float, c.c_int64],
     "borrowed handle; retains nothing"),
    ("cna_vibrate_controller_start_with_intensity_ext", c.c_uint32, [c.c_uint64, c.c_int64, c.c_float],
     "borrowed handle; retains nothing"),
    ("cna_vibrate_controller_stop", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
)

#: Every group above, in one tuple for :mod:`_cna_native.loader`.
DEVICES_FUNCTION_MANIFEST: tuple[Entry, ...] = (
    DEVICES_ACCELEROMETER_MANIFEST
    +
    DEVICES_COMPASS_MANIFEST
    +
    DEVICES_GYROSCOPE_MANIFEST
    +
    DEVICES_MOTION_MANIFEST
    +
    DEVICES_SENSOR_SHARED_MANIFEST
    +
    DEVICES_CAMERA_MANIFEST
    +
    DEVICES_HOST_MANIFEST
    +
    DEVICES_DIALOGS_MANIFEST
    +
    DEVICES_VIBRATION_MANIFEST
)
