"""ctypes manifest for CNA's ``engine_layer.h`` family.

Split out of :mod:`_cna_native.loader` because it is a family of its own,
imported because ``cna.extensions.engine`` projects it rather than because the
XNA profile needs any of it. Every entry is proven against the canonical C
declaration by ``tools/verify_prototypes.py``, and the fourth column states the
ownership contract the Python wrapper has to keep.

Routes are added as their consumers land, never speculatively: an imported route
with no caller is dead native surface, and ``tools/verify_route_reachability.py``
fails on one.
"""

from __future__ import annotations

import ctypes as c

from . import abi
from . import engine_abi as engine

#: The engine layer's own identity. These two are the only routes in the family
#: that answer meaningfully in a build with no engine layer, which is what makes
#: them the ones that tell the two kinds of "not supported" apart.
ENGINE_IDENTITY_MANIFEST: tuple[tuple[str, object, list[object], str], ...] = (
    ("cna_engine_layer_get_version", c.c_uint32, [c.POINTER(c.c_int32)],
     "pure function over caller-owned output; nothing is retained"),
    ("cna_engine_layer_copy_version_string", c.c_uint32,
     [c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol"),
)

#: GPU compute: the barrier mask, storage buffers, compute programs and timers.
ENGINE_COMPUTE_MANIFEST: tuple[tuple[str, object, list[object], str], ...] = (
    ("cna_graphics_memory_barrier_has", c.c_uint32,
     [c.c_uint32, c.c_uint32, c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),

    ("cna_storage_buffer_create", c.c_uint32,
     [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "owned storage buffer; borrows the graphics device for the call"),
    ("cna_storage_buffer_create_typed", c.c_uint32,
     [c.c_uint64, c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "owned storage buffer; borrows the graphics device for the call"),
    ("cna_storage_buffer_set_bytes", c.c_uint32, [c.c_uint64, c.c_void_p, c.c_uint64],
     "borrowed buffer; copies the bytes, retains nothing"),
    ("cna_storage_buffer_get_bytes", c.c_uint32, [c.c_uint64, c.c_void_p, c.c_uint64],
     "caller output; borrowed buffer"),
    ("cna_storage_buffer_get_byte_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed buffer"),
    ("cna_storage_buffer_set_elements", c.c_uint32,
     [c.c_uint64, c.c_void_p, c.c_uint64, c.c_uint64],
     "borrowed buffer; copies the elements, retains nothing"),
    ("cna_storage_buffer_get_elements", c.c_uint32,
     [c.c_uint64, c.c_void_p, c.c_uint64, c.c_uint64],
     "caller output; borrowed buffer"),
    ("cna_storage_buffer_get_element_count", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_uint64)], "caller output; borrowed buffer"),
    ("cna_storage_buffer_get_element_byte_size", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_uint64)], "caller output; borrowed buffer"),
    ("cna_storage_buffer_destroy", c.c_uint32, [c.c_uint64],
     "consumes storage buffer"),

    ("cna_compute_shader_create", c.c_uint32,
     [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "owned compute shader; borrows the device and the source for the call"),
    ("cna_compute_shader_set_uniform_int", c.c_uint32,
     [c.c_uint64, abi.CNA_StringView, c.c_int32],
     "borrowed shader; copies the value"),
    ("cna_compute_shader_set_uniform_float", c.c_uint32,
     [c.c_uint64, abi.CNA_StringView, c.c_float],
     "borrowed shader; copies the value"),
    ("cna_compute_shader_bind_storage_buffer", c.c_uint32,
     [c.c_uint64, c.c_int32, c.c_uint64],
     "borrowed shader; the buffer is BORROWED and must outlive every dispatch"),
    ("cna_compute_shader_bind_texture", c.c_uint32,
     [c.c_uint64, c.c_int32, abi.CNA_StringView, c.c_uint64],
     "borrowed shader; the texture is BORROWED and must outlive every dispatch"),
    ("cna_compute_shader_is_image_binding_supported", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_uint8)], "caller output; borrowed shader"),
    ("cna_compute_shader_bind_image", c.c_uint32,
     [c.c_uint64, c.c_int32, c.c_uint64, c.c_uint32],
     "borrowed shader; the texture is BORROWED and must outlive every dispatch"),
    ("cna_compute_shader_dispatch", c.c_uint32,
     [c.c_uint64, c.c_int32, c.c_int32, c.c_int32], "borrowed shader"),
    ("cna_compute_shader_barrier", c.c_uint32, [c.c_uint64, c.c_uint32],
     "borrowed shader"),
    ("cna_compute_shader_is_valid", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed shader"),
    ("cna_compute_shader_copy_compile_error", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol"),
    ("cna_compute_shader_destroy", c.c_uint32, [c.c_uint64],
     "consumes compute shader"),

    ("cna_gpu_timer_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned GPU timer; borrows the graphics device for the call"),
    ("cna_gpu_timer_is_supported", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed timer"),
    ("cna_gpu_timer_copy_unsupported_reason", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol"),
    ("cna_gpu_timer_begin", c.c_uint32, [c.c_uint64], "borrowed timer"),
    ("cna_gpu_timer_end", c.c_uint32, [c.c_uint64], "borrowed timer"),
    ("cna_gpu_timer_is_result_available", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed timer"),
    ("cna_gpu_timer_poll", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed timer"),
    ("cna_gpu_timer_get_last_milliseconds", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_double)], "caller output; borrowed timer"),
    ("cna_gpu_timer_get_sample_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed timer"),
    ("cna_gpu_timer_is_open", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed timer"),
    ("cna_gpu_timer_destroy", c.c_uint32, [c.c_uint64], "consumes GPU timer"),
)

#: The post-process foundation: pooled intermediates, the named shader-effect
#: cache, the render-target save/restore bracket, full-screen drawing, the pass
#: vocabulary and the chain that orders passes.
ENGINE_POSTPROCESS_MANIFEST: tuple[tuple[str, object, list[object], str], ...] = (
    ("cna_render_target_pool_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned pool; borrows the graphics device for the call"),
    ("cna_render_target_pool_acquire", c.c_uint32,
     [c.c_uint64, c.c_int32, c.c_int32, c.c_uint32, c.c_uint32, c.c_int32,
      c.POINTER(c.c_uint64)],
     "owned VIEW of a pool-owned target; released with cna_render_target_destroy, "
     "which does not dispose the pooled target. The pool refuses reset and "
     "destruction while any view is outstanding"),
    ("cna_render_target_pool_reset", c.c_uint32, [c.c_uint64],
     "borrowed pool; refused while a borrowed view is outstanding"),
    ("cna_render_target_pool_get_target_count", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_uint64)], "caller output; borrowed pool"),
    ("cna_render_target_pool_get_estimated_bytes", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_uint64)], "caller output; borrowed pool"),
    ("cna_render_target_pool_destroy", c.c_uint32, [c.c_uint64],
     "consumes pool; refused while a borrowed view is outstanding"),

    ("cna_shader_effect_factory_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned factory; borrows the graphics device for the call"),
    ("cna_shader_effect_factory_acquire", c.c_uint32,
     [c.c_uint64, abi.CNA_StringView, abi.CNA_StringView, abi.CNA_StringView,
      c.POINTER(c.c_uint64)],
     "owned VIEW of a factory-owned effect; released with cna_effect_destroy. "
     "The factory refuses clear and destruction while any view is outstanding"),
    ("cna_shader_effect_factory_contains", c.c_uint32,
     [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8)],
     "caller output; borrowed factory"),
    ("cna_shader_effect_factory_get_compile_count", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_uint64)], "caller output; borrowed factory"),
    ("cna_shader_effect_factory_clear", c.c_uint32, [c.c_uint64],
     "borrowed factory; refused while a borrowed effect view is outstanding"),
    ("cna_shader_effect_factory_destroy", c.c_uint32, [c.c_uint64],
     "consumes factory; refused while a borrowed effect view is outstanding"),

    ("cna_scoped_render_target_begin", c.c_uint32,
     [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "owned active scope; borrows the device and the destination"),
    ("cna_scoped_render_target_get_has_recorded_previous", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_uint8)], "caller output; borrowed scope"),
    ("cna_scoped_render_target_end", c.c_uint32, [c.c_uint64],
     "consumes scope; must be the innermost scope on its device"),

    ("cna_fullscreen_pass_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned full-screen pass; borrows the graphics device for the call"),
    ("cna_fullscreen_pass_draw", c.c_uint32,
     [c.c_uint64, c.c_uint64, c.c_uint64, c.c_uint64, c.c_int32, c.c_int32,
      c.POINTER(abi.CNA_SamplerState)],
     "borrowed pass; source, destination and effect are borrowed for the call"),
    ("cna_fullscreen_pass_draw_over_current_target", c.c_uint32,
     [c.c_uint64, c.c_uint64, c.c_uint64, c.c_int32, c.c_int32,
      c.POINTER(abi.CNA_SamplerState)],
     "borrowed pass; source and effect are borrowed for the call"),
    ("cna_fullscreen_pass_destroy", c.c_uint32, [c.c_uint64],
     "consumes full-screen pass"),

    ("cna_post_process_context_init", c.c_uint32,
     [c.POINTER(engine.CNA_PostProcessContext)],
     "fills a caller-owned value structure with CNA's own defaults"),
    ("cna_blit_pass_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned pass; borrows the graphics device for the call"),
    ("cna_post_process_effect_pass_create", c.c_uint32,
     [c.c_uint64, c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "owned pass; the effect is BORROWED and must outlive the pass"),
    ("cna_post_process_effect_pass_get_effect", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the effect is borrowed from the pass and must not be destroyed"),
    ("cna_post_process_effect_pass_set_effect", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed pass; the new effect is BORROWED and the old one is not released"),
    ("cna_post_process_pass_apply", c.c_uint32,
     [c.c_uint64, c.POINTER(engine.CNA_PostProcessContext)],
     "borrowed pass; every handle in the context is borrowed for the call"),
    ("cna_post_process_pass_copy_name", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol"),
    ("cna_post_process_pass_is_supported", c.c_uint32,
     [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed pass and device"),
    ("cna_post_process_pass_destroy", c.c_uint32, [c.c_uint64],
     "consumes pass, and the effect it owns if it owns one"),

    ("cna_post_process_chain_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned chain; borrows the graphics device for the call"),
    ("cna_post_process_chain_destroy", c.c_uint32, [c.c_uint64],
     "consumes chain and every pass it owns; borrowed passes survive it"),
    ("cna_post_process_chain_add_pass", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed chain; the pass stays the caller's and must outlive its membership"),
    ("cna_post_process_chain_clear", c.c_uint32, [c.c_uint64],
     "borrowed chain; drops every pass it borrows, and would release any it owned"),
    ("cna_post_process_chain_get_pass_count", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_int32)], "caller output; borrowed chain"),
    ("cna_post_process_chain_apply", c.c_uint32,
     [c.c_uint64, c.POINTER(engine.CNA_PostProcessContext)],
     "borrowed chain; every handle in the context is borrowed for the call"),
    ("cna_post_process_chain_reset_targets", c.c_uint32, [c.c_uint64],
     "borrowed chain; releases its pooled intermediates"),
    ("cna_post_process_chain_get_target_pool", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_uint64)],
     "COUNTED BORROW of the chain's pool; the chain refuses destruction while it is out"),
    ("cna_post_process_chain_is_gpu_timing_enabled", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_uint8)], "caller output; borrowed chain"),
    ("cna_post_process_chain_set_gpu_timing_enabled", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed chain; a renderer without timers accepts and stays off"),
    ("cna_post_process_chain_get_pass_timing_count", c.c_uint32,
     [c.c_uint64, c.POINTER(c.c_uint64)], "caller output; borrowed chain"),
    ("cna_post_process_chain_get_pass_timing", c.c_uint32,
     [c.c_uint64, c.c_uint64, c.POINTER(engine.CNA_PassTimingEXT)],
     "caller output; borrowed chain"),
    ("cna_post_process_chain_copy_pass_timing_name", c.c_uint32,
     [c.c_uint64, c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol"),
)


#: Engine light values, the shadow maps that cast from them, and the engine
#: state a stock effect accepts so it can sample one.
ENGINE_SHADOW_MANIFEST: tuple[tuple[str, object, list[object], str], ...] = (
    ("cna_directional_light_ext_init", c.c_uint32, [c.POINTER(engine.CNA_DirectionalLightEXT)],
     "fills a caller-owned value structure with CNA's own defaults"),
    ("cna_point_light_ext_init", c.c_uint32, [c.POINTER(engine.CNA_PointLightEXT)],
     "fills a caller-owned value structure with CNA's own defaults"),
    ("cna_spot_light_ext_init", c.c_uint32, [c.POINTER(engine.CNA_SpotLightEXT)],
     "fills a caller-owned value structure with CNA's own defaults"),
    ("cna_punctual_light_ext_init", c.c_uint32, [c.POINTER(engine.CNA_PunctualLightEXT)],
     "fills a caller-owned value structure with CNA's own defaults"),
    ("cna_shadow_cascade_state_ext_init", c.c_uint32, [c.POINTER(engine.CNA_ShadowCascadeStateEXT)],
     "fills a caller-owned value structure with CNA's own defaults"),
    ("cna_graphics_device_supports_shadow_sampling_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "borrowed graphics device"),
    ("cna_shadow_map_create", c.c_uint32, [c.c_uint64, c.c_uint32, c.POINTER(c.c_uint64)],
     "owned shadow map; borrows the graphics device for the call"),
    ("cna_shadow_map_is_supported", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed shadow map"),
    ("cna_shadow_map_begin", c.c_uint32, [c.c_uint64, c.POINTER(engine.CNA_DirectionalLightEXT), c.POINTER(engine.CNA_BoundingBox)],
     "borrowed shadow map"),
    ("cna_shadow_map_end", c.c_uint32, [c.c_uint64],
     "borrowed shadow map"),
    ("cna_shadow_map_get_caster_effect", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "COUNTED BORROW of the map's caster effect; a distinct handle per call, "
     "released with cna_effect_destroy"),
    ("cna_shadow_map_get_skinned_caster_effect", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "COUNTED BORROW of the map's skinned caster effect; released with "
     "cna_effect_destroy"),
    ("cna_shadow_map_apply_caster", c.c_uint32, [c.c_uint64],
     "borrowed shadow map"),
    ("cna_shadow_map_apply_skinned_caster", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Matrix), c.c_uint64, c.c_int32],
     "borrowed shadow map"),
    ("cna_shadow_map_get_shadow_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "COUNTED BORROW of the map's own target; released with "
     "cna_render_target_destroy, which does not dispose it. The map refuses "
     "destruction while one is outstanding"),
    ("cna_shadow_map_get_light_view_projection", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Matrix)],
     "caller output; borrowed shadow map"),
    ("cna_shadow_map_get_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed shadow map"),
    ("cna_shadow_map_get_quality", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed shadow map"),
    ("cna_shadow_map_get_depth_bias", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed shadow map"),
    ("cna_shadow_map_set_depth_bias", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed shadow map; copies the value"),
    ("cna_shadow_map_get_filter_radius", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed shadow map"),
    ("cna_shadow_map_compute_light_view", c.c_uint32, [c.POINTER(engine.CNA_DirectionalLightEXT), c.POINTER(engine.CNA_BoundingBox), c.POINTER(abi.CNA_Matrix)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_shadow_map_compute_light_projection", c.c_uint32, [c.POINTER(abi.CNA_Matrix), c.POINTER(engine.CNA_BoundingBox), c.POINTER(abi.CNA_Matrix)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_shadow_map_size_for_quality", c.c_uint32, [c.c_uint32, c.POINTER(c.c_int32)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_shadow_map_filter_radius_for_quality", c.c_uint32, [c.c_uint32, c.POINTER(c.c_int32)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_shadow_map_destroy", c.c_uint32, [c.c_uint64],
     "consumes shadow map"),
    ("cna_spot_shadow_map_create", c.c_uint32, [c.c_uint64, c.c_uint32, c.POINTER(c.c_uint64)],
     "owned spot shadow map; borrows the graphics device for the call"),
    ("cna_spot_shadow_map_is_supported", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed spot shadow map"),
    ("cna_spot_shadow_map_begin", c.c_uint32, [c.c_uint64, c.POINTER(engine.CNA_SpotLightEXT)],
     "borrowed spot shadow map"),
    ("cna_spot_shadow_map_end", c.c_uint32, [c.c_uint64],
     "borrowed spot shadow map"),
    ("cna_spot_shadow_map_get_shadow_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "COUNTED BORROW of the map's own target; released with "
     "cna_render_target_destroy"),
    ("cna_spot_shadow_map_get_caster_effect", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "COUNTED BORROW of the map's caster effect; released with "
     "cna_effect_destroy"),
    ("cna_spot_shadow_map_get_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed spot shadow map"),
    ("cna_spot_shadow_map_get_quality", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed spot shadow map"),
    ("cna_spot_shadow_map_get_light_view_projection", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Matrix)],
     "caller output; borrowed spot shadow map"),
    ("cna_spot_shadow_map_get_light_position", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector3)],
     "caller output; borrowed spot shadow map"),
    ("cna_spot_shadow_map_get_light_range", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed spot shadow map"),
    ("cna_spot_shadow_map_get_depth_bias", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed spot shadow map"),
    ("cna_spot_shadow_map_set_depth_bias", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed spot shadow map; copies the value"),
    ("cna_spot_shadow_map_compute_light_view", c.c_uint32, [c.POINTER(engine.CNA_SpotLightEXT), c.POINTER(abi.CNA_Matrix)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_spot_shadow_map_compute_light_projection", c.c_uint32, [c.POINTER(engine.CNA_SpotLightEXT), c.POINTER(abi.CNA_Matrix)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_spot_shadow_map_destroy", c.c_uint32, [c.c_uint64],
     "consumes spot shadow map"),
    ("cna_cascaded_shadow_map_create", c.c_uint32, [c.c_uint64, c.c_uint32, c.c_int32, c.POINTER(c.c_uint64)],
     "owned cascaded shadow map; borrows the graphics device for the call"),
    ("cna_cascaded_shadow_map_is_supported", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_update", c.c_uint32, [c.c_uint64, c.POINTER(engine.CNA_DirectionalLightEXT), c.POINTER(abi.CNA_Matrix), c.POINTER(abi.CNA_Matrix)],
     "borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_begin", c.c_uint32, [c.c_uint64, c.c_int32],
     "borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_end", c.c_uint32, [c.c_uint64],
     "borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_get_cascade_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_get_cascade_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_get_shadow_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "COUNTED BORROW of the map's own atlas; released with "
     "cna_render_target_destroy"),
    ("cna_cascaded_shadow_map_get_caster_effect", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "COUNTED BORROW of the map's caster effect; released with "
     "cna_effect_destroy"),
    ("cna_cascaded_shadow_map_get_cascade_matrix", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(abi.CNA_Matrix)],
     "caller output; borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_get_split_distance", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(c.c_float)],
     "caller output; borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_get_blend_band", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_set_blend_band", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed cascaded shadow map; copies the value"),
    ("cna_cascaded_shadow_map_is_debug_tint_enabled", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_set_debug_tint_enabled", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed cascaded shadow map; copies the value"),
    ("cna_cascaded_shadow_map_select_cascade", c.c_uint32, [c.c_uint64, c.c_float, c.POINTER(c.c_int32)],
     "caller output; borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_get_split_lambda", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_set_split_lambda", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed cascaded shadow map; copies the value"),
    ("cna_cascaded_shadow_map_compute_split_distances", c.c_uint32, [c.c_float, c.c_float, c.c_int32, c.c_float, c.POINTER(c.c_float), c.c_uint64, c.POINTER(c.c_uint64)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cascaded_shadow_map_compute_frustum_corners", c.c_uint32, [c.POINTER(abi.CNA_Matrix), c.POINTER(abi.CNA_Matrix), c.POINTER(abi.CNA_Vector3)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cascaded_shadow_map_compute_bounding_sphere", c.c_uint32, [c.POINTER(abi.CNA_Vector3), c.POINTER(abi.CNA_Vector3), c.POINTER(c.c_float)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cascaded_shadow_map_snap_to_texel_grid", c.c_uint32, [c.POINTER(abi.CNA_Vector3), c.c_float, c.c_int32, c.POINTER(abi.CNA_Vector3)],
     "borrowed cascaded shadow map"),
    ("cna_cascaded_shadow_map_destroy", c.c_uint32, [c.c_uint64],
     "consumes cascaded shadow map"),
    ("cna_cube_shadow_map_create", c.c_uint32, [c.c_uint64, c.c_uint32, c.POINTER(c.c_uint64)],
     "owned cube shadow map; borrows the graphics device for the call"),
    ("cna_cube_shadow_map_is_supported", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed cube shadow map"),
    ("cna_cube_shadow_map_update", c.c_uint32, [c.c_uint64, c.POINTER(engine.CNA_PointLightEXT)],
     "borrowed cube shadow map"),
    ("cna_cube_shadow_map_begin", c.c_uint32, [c.c_uint64, c.c_int32],
     "borrowed cube shadow map"),
    ("cna_cube_shadow_map_end", c.c_uint32, [c.c_uint64],
     "borrowed cube shadow map"),
    ("cna_cube_shadow_map_get_shadow_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "COUNTED BORROW of the map's own cube; released with "
     "cna_render_target_destroy"),
    ("cna_cube_shadow_map_get_caster_effect", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "COUNTED BORROW of the map's caster effect; released with "
     "cna_effect_destroy"),
    ("cna_cube_shadow_map_get_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed cube shadow map"),
    ("cna_cube_shadow_map_get_quality", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed cube shadow map"),
    ("cna_cube_shadow_map_get_light_position", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector3)],
     "caller output; borrowed cube shadow map"),
    ("cna_cube_shadow_map_get_light_range", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed cube shadow map"),
    ("cna_cube_shadow_map_get_depth_bias", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed cube shadow map"),
    ("cna_cube_shadow_map_set_depth_bias", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed cube shadow map; copies the value"),
    ("cna_cube_shadow_map_compute_face_view", c.c_uint32, [c.c_uint32, c.POINTER(abi.CNA_Vector3), c.POINTER(abi.CNA_Matrix)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cube_shadow_map_compute_face_projection", c.c_uint32, [c.c_float, c.POINTER(abi.CNA_Matrix)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cube_shadow_map_size_for_quality", c.c_uint32, [c.c_uint32, c.POINTER(c.c_int32)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_cube_shadow_map_destroy", c.c_uint32, [c.c_uint64],
     "consumes cube shadow map"),
    ("cna_cascaded_shadow_map_apply_to_receiver", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed cascaded shadow map"),
    ("cna_effect_set_shadow_map_ext", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed effect; the shadow texture is BORROWED and must outlive the "
     "draws that use it"),
    ("cna_effect_get_shadow_map_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the handle is the texture the effect already holds and "
     "is not a new borrow"),
    ("cna_effect_set_light_view_projection_ext", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Matrix)],
     "borrowed effect; copies the value"),
    ("cna_effect_get_light_view_projection_ext", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Matrix)],
     "caller output; borrowed effect"),
    ("cna_effect_set_shadows_enabled_ext", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed effect; copies the value"),
    ("cna_effect_is_shadows_enabled_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed effect"),
    ("cna_effect_set_shadow_depth_bias_ext", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed effect; copies the value"),
    ("cna_effect_get_shadow_depth_bias_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed effect"),
    ("cna_effect_set_shadow_filter_radius_ext", c.c_uint32, [c.c_uint64, c.c_int32],
     "borrowed effect; copies the value"),
    ("cna_effect_get_shadow_filter_radius_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed effect"),
    ("cna_effect_set_shadow_cascades_ext", c.c_uint32, [c.c_uint64, c.POINTER(engine.CNA_ShadowCascadeStateEXT)],
     "borrowed effect; copies the value"),
    ("cna_effect_get_shadow_cascades_ext", c.c_uint32, [c.c_uint64, c.POINTER(engine.CNA_ShadowCascadeStateEXT)],
     "caller output; borrowed effect"),
    ("cna_effect_set_punctual_light_ext", c.c_uint32, [c.c_uint64, c.POINTER(engine.CNA_PunctualLightEXT)],
     "borrowed effect; copies the value"),
    ("cna_effect_get_punctual_light_ext", c.c_uint32, [c.c_uint64, c.POINTER(engine.CNA_PunctualLightEXT)],
     "caller output; borrowed effect"),
)

#: Physically based materials: the value, its glTF extensions, the bridge that
#: builds one from a glTF material, and the effects that render it.
ENGINE_PBR_MANIFEST: tuple[tuple[str, object, list[object], str], ...] = (
    ("cna_pbr_effect_apply_material", c.c_uint32, [c.c_uint64, c.POINTER(engine.CNA_PbrMaterialEXT)],
     "borrowed effect; every field of the value crosses, textures by handle"),
    ("cna_skinned_pbr_effect_apply_material", c.c_uint32, [c.c_uint64, c.POINTER(engine.CNA_PbrMaterialEXT)],
     "borrowed effect; every field of the value crosses, textures by handle"),
    ("cna_pbr_effect_extract_material", c.c_uint32, [c.c_uint64, c.POINTER(engine.CNA_PbrMaterialEXT)],
     "caller output; the texture handles are the effect's and are not new "
     "borrows"),
    ("cna_skinned_pbr_effect_extract_material", c.c_uint32, [c.c_uint64, c.POINTER(engine.CNA_PbrMaterialEXT)],
     "caller output; the texture handles are the effect's and are not new "
     "borrows"),
    ("cna_pbr_material_apply_state", c.c_uint32, [c.POINTER(engine.CNA_PbrMaterialEXT), c.c_uint64],
     "borrowed graphics device; sets blending, depth write and culling from "
     "the value"),
    ("cna_pbr_material_extensions_create", c.c_uint32, [c.POINTER(c.c_uint64)],
     "owned material extensions; needs no device, so it works wherever the "
     "layer is"),
    ("cna_pbr_material_extensions_destroy", c.c_uint32, [c.c_uint64],
     "consumes material extensions"),
    ("cna_pbr_material_extensions_copy_from", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed destination and source; copies every field, retains nothing"),
    ("cna_pbr_material_extensions_get_clearcoat_factor", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_clearcoat_factor", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_clearcoat_roughness", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_clearcoat_roughness", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_clearcoat_normal_scale", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_clearcoat_normal_scale", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_sheen_roughness", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_sheen_roughness", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_transmission_factor", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_transmission_factor", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_thickness_factor", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_thickness_factor", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_attenuation_distance", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_attenuation_distance", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_iridescence_factor", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_iridescence_factor", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_iridescence_ior", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_iridescence_ior", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_iridescence_thickness_minimum", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_iridescence_thickness_minimum", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_iridescence_thickness_maximum", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_iridescence_thickness_maximum", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_subsurface_wrap", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_subsurface_wrap", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_sheen_color_factor", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector3)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_sheen_color_factor", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector3)],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_attenuation_color", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector3)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_attenuation_color", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector3)],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_subsurface_color", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector3)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_subsurface_color", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector3)],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_clearcoat_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the handle is the one that was set and is not a new borrow"),
    ("cna_pbr_material_extensions_set_clearcoat_texture", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_clearcoat_roughness_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_clearcoat_roughness_texture", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_clearcoat_normal_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_clearcoat_normal_texture", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_sheen_color_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_sheen_color_texture", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_sheen_roughness_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_sheen_roughness_texture", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_transmission_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_transmission_texture", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_thickness_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_thickness_texture", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_iridescence_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_iridescence_texture", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_get_iridescence_thickness_texture", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_set_iridescence_thickness_texture", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed material extensions; copies the value"),
    ("cna_pbr_material_extensions_is_subsurface_enabled", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_is_iridescence_enabled", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_is_transmission_enabled", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_is_sheen_enabled", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_is_neutral", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_equals", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "borrowed material extensions"),
    ("cna_pbr_material_extensions_get_hash_code", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed material extensions"),
    ("cna_pbr_material_extensions_copy_to_string", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "borrowed material extensions"),
    ("cna_thin_film_iridescence_evaluate", c.c_uint32, [c.c_float, c.c_float, c.c_float, c.c_float, c.POINTER(abi.CNA_Vector3), c.POINTER(abi.CNA_Vector3)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_thin_film_iridescence_copy_glsl", c.c_uint32, [c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol"),
    ("cna_pbr_material_ext_equals", c.c_uint32, [c.POINTER(engine.CNA_PbrMaterialEXT), c.POINTER(engine.CNA_PbrMaterialEXT), c.POINTER(c.c_uint8)],
     "pure function over two caller-owned values; textures compare by handle "
     "identity"),
    ("cna_pbr_material_ext_get_hash_code", c.c_uint32, [c.POINTER(engine.CNA_PbrMaterialEXT), c.POINTER(c.c_uint64)],
     "caller output; borrowed PBR material value"),
    ("cna_pbr_material_ext_copy_to_string", c.c_uint32, [c.POINTER(engine.CNA_PbrMaterialEXT), c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "borrowed PBR material value"),
    ("cna_gltf_material_source_ext_init", c.c_uint32, [c.POINTER(engine.CNA_GltfMaterialSourceEXT)],
     "fills a caller-owned value structure with CNA's own defaults"),
    ("cna_gltf_material_extension_source_ext_init", c.c_uint32, [c.POINTER(engine.CNA_GltfMaterialExtensionSourceEXT)],
     "fills a caller-owned value structure with CNA's own defaults"),
    ("cna_gltf_material_textures_ext_init", c.c_uint32, [c.POINTER(engine.CNA_GltfMaterialTexturesEXT)],
     "fills a caller-owned value structure with CNA's own defaults"),
    ("cna_gltf_material_extension_textures_ext_init", c.c_uint32, [c.POINTER(engine.CNA_GltfMaterialExtensionTexturesEXT)],
     "fills a caller-owned value structure with CNA's own defaults"),
    ("cna_gltf_material_bridge_build_material", c.c_uint32, [c.POINTER(engine.CNA_GltfMaterialSourceEXT), c.POINTER(engine.CNA_GltfMaterialTexturesEXT), c.POINTER(engine.CNA_PbrMaterialEXT)],
     "caller output; pure over the source and the caller's borrowed textures"),
    ("cna_gltf_material_bridge_build_extensions", c.c_uint32, [c.POINTER(engine.CNA_GltfMaterialExtensionSourceEXT), c.POINTER(engine.CNA_GltfMaterialExtensionTexturesEXT), c.c_uint64],
     "borrowed destination extensions; pure over the source and borrowed "
     "textures"),
)

#: The minimal slices two other canonical headers have to contribute before the
#: PBR family is reachable at all.
#:
#: ``graphics_ext.h``: ``CNA_PbrMaterialEXT`` is declared there, and
#: ``cna_pbr_material_ext_init`` is the only route that fills one with CNA's own
#: defaults. Without it a material would have to be built from a Python-side
#: transcription of every default, which is the one thing this family must not
#: do -- the material is 27 fields, and a drifted default is invisible.
#:
#: ``effects.h``: nothing in ``engine_layer.h`` creates a ``PbrEffect``, and
#: ``cna_pbr_effect_apply_material`` refuses an effect that is not one. The two
#: constructors are imported for that reason.
#:
#: The texture pair is imported for a second, measured reason.
#: ``cna_pbr_effect_apply_material`` is documented to carry *every* field of the
#: material and does carry every scalar, but drops all seven texture slots:
#: after applying a material with a base-colour texture,
#: ``cna_pbr_effect_get_texture`` reports no texture in any slot. Without these
#: two routes a PBR effect could never have a texture at all, which is the
#: family's central capability. See ENGINE-005 in
#: ``docs/engine-upstream-findings.md``. No other per-field setter from that
#: header is imported: the scalars really do cross.
ENGINE_PBR_DEPENDENCY_MANIFEST: tuple[tuple[str, object, list[object], str], ...] = (
    ("cna_pbr_material_ext_init", c.c_uint32, [c.POINTER(engine.CNA_PbrMaterialEXT)],
     "fills a caller-owned value structure with CNA's own defaults"),
    ("cna_pbr_effect_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned effect; borrows the graphics device for the call"),
    ("cna_skinned_pbr_effect_create", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned effect; borrows the graphics device for the call"),
    ("cna_pbr_effect_set_texture", c.c_uint32, [c.c_uint64, c.c_uint32, c.c_uint64],
     "borrowed effect; retains the texture for the slot"),
    ("cna_pbr_effect_get_texture", c.c_uint32,
     [c.c_uint64, c.c_uint32, c.POINTER(c.c_uint8), c.POINTER(c.c_uint64)],
     "caller output; the handle is the one the effect retains"),
)

#: Every engine route this binding imports, in one tuple for the loader.
ENGINE_FUNCTION_MANIFEST: tuple[tuple[str, object, list[object], str], ...] = (
    ENGINE_IDENTITY_MANIFEST
    + ENGINE_COMPUTE_MANIFEST
    + ENGINE_POSTPROCESS_MANIFEST
    + ENGINE_SHADOW_MANIFEST
    + ENGINE_PBR_MANIFEST
    + ENGINE_PBR_DEPENDENCY_MANIFEST
)

# ``engine`` is imported for the structures later slices pass by pointer; the
# reference keeps the module a declared dependency of this manifest rather than
# an accident of import order.
_STRUCTURES = engine.ENGINE_STRUCTURES
