"""Exact ctypes prototypes for the canonical CNA 0.7 Media/Video surface used here."""

from __future__ import annotations

import ctypes as c

from . import abi

R = c.c_uint32
H = c.c_uint64
I = c.c_int32
U = c.c_uint32
L = c.c_int64
B = c.c_uint8
F = c.c_float
SV = abi.CNA_StringView
PH = c.POINTER(H)
PI = c.POINTER(I)
PU = c.POINTER(U)
PL = c.POINTER(L)
PB = c.POINTER(B)
PF = c.POINTER(F)
PZ = c.POINTER(c.c_uint64)
PC = c.POINTER(c.c_char)
PBY = c.POINTER(c.c_uint8)


def _e(name: str, args: list[object], ownership: str = "borrowed handle") -> tuple[str, object, list[object], str]:
    return (name, R, args, ownership)


MEDIA_FUNCTION_MANIFEST: tuple[tuple[str, object, list[object], str], ...] = tuple([
    _e("cna_media_source_get_available_count", [H, PU], "caller output"),
    _e("cna_media_source_get_type_at", [H, U, PU], "caller output"),
    _e("cna_media_source_get_name_size_at", [H, U, PZ], "caller output"),
    _e("cna_media_source_copy_name_at", [H, U, PC, c.c_uint64, PZ], "caller output"),
    _e("cna_song_create_from_uri", [H, SV, SV, PH], "owned Song"),
    _e("cna_song_get_name_size", [H, PZ], "caller output"),
    _e("cna_song_copy_name", [H, PC, c.c_uint64, PZ], "caller output"),
    _e("cna_song_get_duration", [H, PL], "caller output"),
    _e("cna_song_get_is_protected", [H, PB], "caller output"),
    _e("cna_song_get_is_rated", [H, PB], "caller output"),
    _e("cna_song_get_play_count", [H, PI], "caller output"),
    _e("cna_song_get_rating", [H, PI], "caller output"),
    _e("cna_song_get_track_number", [H, PI], "caller output"),
    _e("cna_song_get_is_disposed", [H, PB], "caller output"),
    _e("cna_song_dispose", [H], "marks disposed"),
    _e("cna_song_destroy", [H], "destroys Song handle"),
    _e("cna_song_equals", [H, H, PB], "caller output"),
    _e("cna_song_get_hash_code", [H, PI], "caller output"),
    _e("cna_song_get_album", [H, PH, PB], "owned nullable Album"),
    _e("cna_song_get_artist", [H, PH, PB], "owned nullable Artist"),
    _e("cna_song_get_genre", [H, PH, PB], "owned nullable Genre"),
    _e("cna_media_player_get_game_has_control", [H, PB], "caller output"),
    _e("cna_media_player_get_is_muted", [H, PB], "caller output"),
    _e("cna_media_player_set_is_muted", [H, B]),
    _e("cna_media_player_get_is_repeating", [H, PB], "caller output"),
    _e("cna_media_player_set_is_repeating", [H, B]),
    _e("cna_media_player_get_is_shuffled", [H, PB], "caller output"),
    _e("cna_media_player_set_is_shuffled", [H, B]),
    _e("cna_media_player_get_play_position_ticks", [H, PL], "caller output"),
    _e("cna_media_player_get_state", [H, PU], "caller output"),
    _e("cna_media_player_get_volume", [H, PF], "caller output"),
    _e("cna_media_player_set_volume", [H, F]),
    _e("cna_media_player_get_is_visualization_enabled", [H, PB], "caller output"),
    _e("cna_media_player_set_is_visualization_enabled", [H, B]),
    _e("cna_media_player_get_visualization_data", [H, c.POINTER(abi.CNA_VisualizationData)], "caller output"),
    _e("cna_media_player_get_queue", [H, PH], "owned queue view"),
    _e("cna_media_player_play_song", [H, H]),
    _e("cna_media_player_play_songs", [H, H]),
    _e("cna_media_player_play_songs_from", [H, H, I]),
    _e("cna_media_player_move_next", [H]),
    _e("cna_media_player_move_previous", [H]),
    _e("cna_media_player_pause", [H]),
    _e("cna_media_player_resume", [H]),
    _e("cna_media_player_stop", [H]),
    _e("cna_media_player_update_ext", [H]),
    _e("cna_media_player_program_exit_ext", [H]),
    _e("cna_media_player_subscribe_active_song_changed_ext", [abi.CNA_MediaPlayerEventCallback, c.c_void_p, PH], "owned registration"),
    _e("cna_media_player_subscribe_media_state_changed_ext", [abi.CNA_MediaPlayerEventCallback, c.c_void_p, PH], "owned registration"),
    _e("cna_media_player_unsubscribe_ext", [H], "consumes registration"),
    _e("cna_media_player_raise_active_song_changed_ext", [H]),
    _e("cna_media_player_raise_media_state_changed_ext", [H]),
    _e("cna_media_queue_get_count", [H, PI], "caller output"),
    _e("cna_media_queue_get_active_song_index", [H, PI], "caller output"),
    _e("cna_media_queue_set_active_song_index", [H, I]),
    _e("cna_media_queue_get_active_song", [H, PH, PB], "owned nullable Song"),
    _e("cna_media_queue_get_at", [H, I, PH], "owned Song"),
    _e("cna_media_queue_destroy", [H], "destroys queue view"),
    _e("cna_media_library_create", [H, PH], "owned MediaLibrary"),
    _e("cna_media_library_create_from_source", [H, U, PH], "owned MediaLibrary"),
    _e("cna_media_library_get_is_disposed", [H, PB], "caller output"),
    _e("cna_media_library_dispose", [H], "marks disposed"),
    _e("cna_media_library_destroy", [H], "destroys MediaLibrary"),
    _e("cna_media_library_get_media_source_type", [H, PU], "caller output"),
    _e("cna_media_library_get_media_source_name_size", [H, PZ], "caller output"),
    _e("cna_media_library_copy_media_source_name", [H, PC, c.c_uint64, PZ], "caller output"),
    *[_e(f"cna_media_library_get_{name}", [H, PH], f"owned {kind}") for name, kind in (
        ("songs", "SongCollection"), ("albums", "AlbumCollection"),
        ("artists", "ArtistCollection"), ("genres", "GenreCollection"),
        ("playlists", "PlaylistCollection"), ("pictures", "PictureCollection"),
        ("saved_pictures", "PictureCollection"))],
    _e("cna_media_library_get_root_picture_album", [H, PH, PB], "owned nullable PictureAlbum"),
    _e("cna_media_library_get_picture_from_token", [H, SV, PH, PB], "owned nullable Picture"),
    _e("cna_media_library_save_picture", [H, SV, c.POINTER(c.c_uint8), c.c_uint64, PH], "copies bytes; owned Picture"),
    _e("cna_album_get_name_size", [H, PZ], "caller output"),
    _e("cna_album_copy_name", [H, PC, c.c_uint64, PZ], "caller output"),
    _e("cna_album_get_is_disposed", [H, PB], "caller output"),
    _e("cna_album_dispose", [H], "marks disposed"),
    _e("cna_album_destroy", [H], "destroys Album handle"),
    _e("cna_album_get_hash_code", [H, PI], "caller output"),
    _e("cna_album_equals", [H, H, PB], "caller output"),
    _e("cna_album_get_songs", [H, PH], "owned SongCollection"),
    _e("cna_album_get_artist", [H, PH, PB], "owned nullable Artist"),
    _e("cna_album_get_genre", [H, PH, PB], "owned nullable Genre"),
    _e("cna_album_get_duration", [H, PL], "caller output"),
    _e("cna_album_get_has_art", [H, PB], "caller output"),
    _e("cna_album_get_art_size", [H, PZ], "caller output"),
    _e("cna_album_copy_art", [H, PBY, c.c_uint64, PZ], "caller output"),
    _e("cna_album_get_thumbnail_size", [H, PZ], "caller output"),
    _e("cna_album_copy_thumbnail", [H, PBY, c.c_uint64, PZ], "caller output"),
    _e("cna_artist_get_name_size", [H, PZ], "caller output"),
    _e("cna_artist_copy_name", [H, PC, c.c_uint64, PZ], "caller output"),
    _e("cna_artist_get_is_disposed", [H, PB], "caller output"),
    _e("cna_artist_dispose", [H], "marks disposed"),
    _e("cna_artist_destroy", [H], "destroys Artist handle"),
    _e("cna_artist_get_hash_code", [H, PI], "caller output"),
    _e("cna_artist_equals", [H, H, PB], "caller output"),
    _e("cna_artist_get_songs", [H, PH], "owned SongCollection"),
    _e("cna_artist_get_albums", [H, PH], "owned AlbumCollection"),
    _e("cna_genre_get_name_size", [H, PZ], "caller output"),
    _e("cna_genre_copy_name", [H, PC, c.c_uint64, PZ], "caller output"),
    _e("cna_genre_get_is_disposed", [H, PB], "caller output"),
    _e("cna_genre_dispose", [H], "marks disposed"),
    _e("cna_genre_destroy", [H], "destroys Genre handle"),
    _e("cna_genre_get_hash_code", [H, PI], "caller output"),
    _e("cna_genre_equals", [H, H, PB], "caller output"),
    _e("cna_genre_get_songs", [H, PH], "owned SongCollection"),
    _e("cna_genre_get_albums", [H, PH], "owned AlbumCollection"),
    _e("cna_playlist_get_name_size", [H, PZ], "caller output"),
    _e("cna_playlist_copy_name", [H, PC, c.c_uint64, PZ], "caller output"),
    _e("cna_playlist_get_is_disposed", [H, PB], "caller output"),
    _e("cna_playlist_dispose", [H], "marks disposed"),
    _e("cna_playlist_destroy", [H], "destroys Playlist handle"),
    _e("cna_playlist_get_hash_code", [H, PI], "caller output"),
    _e("cna_playlist_equals", [H, H, PB], "caller output"),
    _e("cna_playlist_get_songs", [H, PH], "owned SongCollection"),
    _e("cna_playlist_get_duration", [H, PL], "caller output"),
    _e("cna_picture_get_name_size", [H, PZ], "caller output"),
    _e("cna_picture_copy_name", [H, PC, c.c_uint64, PZ], "caller output"),
    _e("cna_picture_get_album", [H, PH, PB], "owned nullable PictureAlbum"),
    _e("cna_picture_get_date_unix_ticks", [H, PL], "caller output"),
    _e("cna_picture_get_width", [H, PI], "caller output"),
    _e("cna_picture_get_height", [H, PI], "caller output"),
    _e("cna_picture_get_image_size", [H, PZ], "caller output"),
    _e("cna_picture_copy_image", [H, PBY, c.c_uint64, PZ], "caller output"),
    _e("cna_picture_get_thumbnail_size", [H, PZ], "caller output"),
    _e("cna_picture_copy_thumbnail", [H, PBY, c.c_uint64, PZ], "caller output"),
    _e("cna_picture_get_is_disposed", [H, PB], "caller output"),
    _e("cna_picture_dispose", [H], "marks disposed"),
    _e("cna_picture_destroy", [H], "destroys Picture handle"),
    _e("cna_picture_equals", [H, H, PB], "caller output"),
    _e("cna_picture_get_hash_code", [H, PI], "caller output"),
    _e("cna_picture_album_get_name_size", [H, PZ], "caller output"),
    _e("cna_picture_album_copy_name", [H, PC, c.c_uint64, PZ], "caller output"),
    _e("cna_picture_album_get_parent", [H, PH, PB], "owned nullable PictureAlbum"),
    _e("cna_picture_album_get_albums", [H, PH], "owned PictureAlbumCollection"),
    _e("cna_picture_album_get_pictures", [H, PH], "owned PictureCollection"),
    _e("cna_picture_album_get_is_disposed", [H, PB], "caller output"),
    _e("cna_picture_album_dispose", [H], "marks disposed"),
    _e("cna_picture_album_destroy", [H], "destroys PictureAlbum handle"),
    _e("cna_picture_album_equals", [H, H, PB], "caller output"),
    _e("cna_picture_album_get_hash_code", [H, PI], "caller output"),
    _e("cna_video_create_with_metadata", [H, SV, I, I, I, F, U, PH], "owned Video"),
    _e("cna_video_get_width", [H, PI], "caller output"),
    _e("cna_video_get_height", [H, PI], "caller output"),
    _e("cna_video_get_frames_per_second", [H, PF], "caller output"),
    _e("cna_video_get_duration", [H, PL], "caller output"),
    _e("cna_video_get_soundtrack_type", [H, PU], "caller output"),
    _e("cna_video_destroy", [H], "destroys Video"),
    _e("cna_video_player_create", [H, PH], "owned VideoPlayer"),
    _e("cna_video_player_get_is_disposed", [H, PB], "caller output"),
    _e("cna_video_player_get_is_looped", [H, PB], "caller output"),
    _e("cna_video_player_set_is_looped", [H, B]),
    _e("cna_video_player_get_is_muted", [H, PB], "caller output"),
    _e("cna_video_player_set_is_muted", [H, B]),
    _e("cna_video_player_get_play_position_ticks", [H, PL], "caller output"),
    _e("cna_video_player_get_state", [H, PU], "caller output"),
    _e("cna_video_player_get_volume", [H, PF], "caller output"),
    _e("cna_video_player_set_volume", [H, F]),
    _e("cna_video_player_get_texture", [H, PH, PB], "borrowed transient texture"),
    _e("cna_video_player_get_frame_ext", [H, c.POINTER(abi.CNA_VideoFrameEXT)],
       "caller output; borrowed frame texture plus its monotonic decode generation"),
    _e("cna_video_player_play", [H, H], "retains Video"),
    _e("cna_video_player_stop", [H]),
    _e("cna_video_player_pause", [H]),
    _e("cna_video_player_resume", [H]),
    _e("cna_video_player_dispose", [H], "marks player disposed"),
    _e("cna_video_player_destroy", [H], "destroys VideoPlayer"),
] + [
    _e(f"cna_{kind}_collection_{suffix}", args, ownership)
    for kind in ("song", "album", "artist", "genre", "playlist", "picture", "picture_album")
    for suffix, args, ownership in (
        ("get_count", [H, PI], "caller output"),
        ("get_at", [H, I, PH], f"owned {kind} item"),
        ("get_is_disposed", [H, PB], "caller output"),
        ("dispose", [H], "empties collection"),
        ("destroy", [H], "destroys collection handle"),
    )
])
