"""ctypes manifest for CNA's ``net.h``, ``net_gamers.h``, ``net_sessions.h``, ``gamer_services.h`` family.

Do not edit. ``tools/generate_family_manifest.py`` derives every prototype
from the canonical headers, and ``--check`` fails when the checked-in copy is
not what the current headers produce. Every entry is proven against the
canonical C declaration by ``tools/verify_prototypes.py`` -- being generated is
not a reason to trust it.

The fourth column is the ownership contract the Python wrapper has to keep.
"""

from __future__ import annotations

import ctypes as c

from . import abi
from . import devices_abi
from . import online_abi

Entry = tuple[str, object, list[object], str]

#: PacketReader and PacketWriter: the typed two sides of a network packet.
ONLINE_PACKETS_MANIFEST: tuple[Entry, ...] = (
    ("cna_packet_reader_create", c.c_uint32, [c.c_int32, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_packet_reader_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_packet_reader_get_length", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_packet_reader_get_position", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_packet_reader_read_color", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Color)],
     "borrowed handle; retains nothing"),
    ("cna_packet_reader_read_double", c.c_uint32, [c.c_uint64, c.POINTER(c.c_double)],
     "borrowed handle; retains nothing"),
    ("cna_packet_reader_read_matrix", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Matrix)],
     "borrowed handle; retains nothing"),
    ("cna_packet_reader_read_quaternion", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Quaternion)],
     "borrowed handle; retains nothing"),
    ("cna_packet_reader_read_single", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "borrowed handle; retains nothing"),
    ("cna_packet_reader_read_vector2", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector2)],
     "borrowed handle; retains nothing"),
    ("cna_packet_reader_read_vector3", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector3)],
     "borrowed handle; retains nothing"),
    ("cna_packet_reader_read_vector4", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector4)],
     "borrowed handle; retains nothing"),
    ("cna_packet_reader_set_data_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_packet_reader_set_position", c.c_uint32, [c.c_uint64, c.c_int32],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_packet_writer_copy_data_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_packet_writer_create", c.c_uint32, [c.c_int32, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_packet_writer_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_packet_writer_get_length", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_packet_writer_get_position", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_packet_writer_set_position", c.c_uint32, [c.c_uint64, c.c_int32],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_packet_writer_write_color", c.c_uint32, [c.c_uint64, abi.CNA_Color],
     "borrowed handle; retains nothing"),
    ("cna_packet_writer_write_double", c.c_uint32, [c.c_uint64, c.c_double],
     "borrowed handle; retains nothing"),
    ("cna_packet_writer_write_matrix", c.c_uint32, [c.c_uint64, abi.CNA_Matrix],
     "borrowed handle; retains nothing"),
    ("cna_packet_writer_write_quaternion", c.c_uint32, [c.c_uint64, abi.CNA_Quaternion],
     "borrowed handle; retains nothing"),
    ("cna_packet_writer_write_single", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed handle; retains nothing"),
    ("cna_packet_writer_write_vector2", c.c_uint32, [c.c_uint64, abi.CNA_Vector2],
     "borrowed handle; retains nothing"),
    ("cna_packet_writer_write_vector3", c.c_uint32, [c.c_uint64, abi.CNA_Vector3],
     "borrowed handle; retains nothing"),
    ("cna_packet_writer_write_vector4", c.c_uint32, [c.c_uint64, abi.CNA_Vector4],
     "borrowed handle; retains nothing"),
)

#: NetworkSessionProperties: the searchable property list a session
#: advertises, and its enumerator.
ONLINE_SESSION_PROPERTIES_MANIFEST: tuple[Entry, ...] = (
    ("cna_network_session_properties_add", c.c_uint32, [c.c_uint64, online_abi.CNA_OptionalInt32],
     "borrowed handle; retains nothing"),
    ("cna_network_session_properties_clear", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_network_session_properties_contains", c.c_uint32, [c.c_uint64, online_abi.CNA_OptionalInt32, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_properties_copy_to", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_OptionalInt32), c.c_uint64, c.c_int32, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_network_session_properties_create", c.c_uint32, [c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_network_session_properties_create_enumerator", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_network_session_properties_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_network_session_properties_get_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_properties_get_is_read_only", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_properties_get_item", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(online_abi.CNA_OptionalInt32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_properties_index_of", c.c_uint32, [c.c_uint64, online_abi.CNA_OptionalInt32, c.POINTER(c.c_int32)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_properties_insert", c.c_uint32, [c.c_uint64, c.c_int32, online_abi.CNA_OptionalInt32],
     "borrowed handle; retains nothing"),
    ("cna_network_session_properties_remove", c.c_uint32, [c.c_uint64, online_abi.CNA_OptionalInt32, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_properties_remove_at", c.c_uint32, [c.c_uint64, c.c_int32],
     "borrowed handle; retains nothing"),
    ("cna_network_session_properties_set_item", c.c_uint32, [c.c_uint64, c.c_int32, online_abi.CNA_OptionalInt32],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_session_property_enumerator_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_network_session_property_enumerator_get_current", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_OptionalInt32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_property_enumerator_move_next", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_property_enumerator_reset", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
)

#: QualityOfService, and the last join failure the network layer recorded.
ONLINE_QUALITY_OF_SERVICE_MANIFEST: tuple[Entry, ...] = (
    ("cna_net_get_last_join_error", c.c_uint32, [c.POINTER(c.c_uint32), c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_quality_of_service_init_measured", c.c_uint32, [c.c_int64, c.POINTER(online_abi.CNA_QualityOfService)],
     "pure value initialiser over caller-owned storage"),
)

#: NetworkSession and AvailableNetworkSession: creation, discovery, join,
#: rosters, state and events.
ONLINE_SESSION_MANIFEST: tuple[Entry, ...] = (
    ("cna_available_network_session_collection_copy_session", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_available_network_session_collection_create_ext", c.c_uint32, [c.POINTER(c.c_uint64), c.c_uint64, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_available_network_session_collection_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_available_network_session_collection_dispose", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_available_network_session_collection_get_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_available_network_session_copy_connect_address_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_available_network_session_copy_host_gamertag", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_available_network_session_copy_session_properties", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_available_network_session_create_ext", c.c_uint32, [c.POINTER(online_abi.CNA_AvailableNetworkSessionCreateInfo), c.POINTER(online_abi.CNA_QualityOfService), c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_available_network_session_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_available_network_session_equals", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_available_network_session_get_connect_address_size_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_available_network_session_get_connect_port_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint16)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_available_network_session_get_current_gamer_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_available_network_session_get_host_gamertag_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_available_network_session_get_open_private_gamer_slots", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_available_network_session_get_open_public_gamer_slots", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_available_network_session_get_quality_of_service", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_QualityOfService)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_available_network_session_get_session_type_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_available_network_session_not_equals", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_network_session_add_local_gamer", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_network_session_add_remote_gamer_ext", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_network_session_copy_session_properties", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_network_session_create", c.c_uint32, [c.c_uint32, c.c_int32, c.c_int32, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_network_session_create_async", c.c_uint32, [c.c_uint32, c.c_int32, c.c_int32, online_abi.CNA_NetworkSessionAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_network_session_create_with_local_gamers", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64), c.c_uint64, c.c_int32, c.c_int32, c.c_uint64, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_network_session_create_with_local_gamers_async", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64), c.c_uint64, c.c_int32, c.c_int32, c.c_uint64, online_abi.CNA_NetworkSessionAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_network_session_create_with_properties", c.c_uint32, [c.c_uint32, c.c_int32, c.c_int32, c.c_int32, c.c_uint64, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_network_session_create_with_properties_async", c.c_uint32, [c.c_uint32, c.c_int32, c.c_int32, c.c_int32, c.c_uint64, online_abi.CNA_NetworkSessionAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_network_session_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_network_session_dispose", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_network_session_end_game", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_network_session_find", c.c_uint32, [c.c_uint32, c.c_int32, c.c_uint64, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_find_async", c.c_uint32, [c.c_uint32, c.c_int32, c.c_uint64, online_abi.CNA_NetworkSessionAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_find_gamer_by_id", c.c_uint32, [c.c_uint64, c.c_uint8, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_find_with_local_gamers", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64), c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_find_with_local_gamers_async", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64), c.c_uint64, c.c_uint64, online_abi.CNA_NetworkSessionAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_get_active_action_count_ext", c.c_uint32, [c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_allow_host_migration", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_allow_join_in_progress", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_bytes_per_second_received", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_bytes_per_second_sent", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_gamer", c.c_uint32, [c.c_uint64, c.c_uint32, c.c_int32, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_gamer_count", c.c_uint32, [c.c_uint64, c.c_uint32, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_host", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_instance_count_ext", c.c_uint32, [c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_is_everyone_ready", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_is_host", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_max_gamers", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_owned_gamer_count_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_private_gamer_slots", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_session_state", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_session_type", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_simulated_latency_ticks", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_get_simulated_packet_loss", c.c_uint32, [c.c_uint64, c.POINTER(c.c_float)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_session_join", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_join_async", c.c_uint32, [c.c_uint64, online_abi.CNA_NetworkSessionAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_join_invited", c.c_uint32, [c.c_int32, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_join_invited_async", c.c_uint32, [c.c_int32, online_abi.CNA_NetworkSessionAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_join_invited_with_local_gamers", c.c_uint32, [c.POINTER(c.c_uint64), c.c_uint64, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_join_invited_with_local_gamers_async", c.c_uint32, [c.POINTER(c.c_uint64), c.c_uint64, online_abi.CNA_NetworkSessionAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_remove_gamer_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint32],
     "borrowed handle; retains nothing"),
    ("cna_network_session_replace_session_properties", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_network_session_reset_ready", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_network_session_send_network_event_ext", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_NetworkEventInfo)],
     "borrowed handle; retains nothing"),
    ("cna_network_session_set_allow_host_migration", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_session_set_allow_join_in_progress", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_session_set_max_gamers", c.c_uint32, [c.c_uint64, c.c_int32],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_session_set_private_gamer_slots", c.c_uint32, [c.c_uint64, c.c_int32],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_session_set_simulated_latency_ticks", c.c_uint32, [c.c_uint64, c.c_int64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_session_set_simulated_packet_loss", c.c_uint32, [c.c_uint64, c.c_float],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_session_start_game", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_network_session_subscribe_game_ended", c.c_uint32, [c.c_uint64, online_abi.CNA_GameEndedCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_network_session_subscribe_game_started", c.c_uint32, [c.c_uint64, online_abi.CNA_GameStartedCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_network_session_subscribe_gamer_joined", c.c_uint32, [c.c_uint64, online_abi.CNA_GamerJoinedCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_network_session_subscribe_gamer_left", c.c_uint32, [c.c_uint64, online_abi.CNA_GamerLeftCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_network_session_subscribe_host_changed", c.c_uint32, [c.c_uint64, online_abi.CNA_HostChangedCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_network_session_subscribe_invite_accepted", c.c_uint32, [online_abi.CNA_InviteAcceptedCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_network_session_subscribe_session_ended", c.c_uint32, [c.c_uint64, online_abi.CNA_NetworkSessionEndedCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_network_session_subscribe_write_arbitrated_leaderboard", c.c_uint32, [c.c_uint64, online_abi.CNA_WriteLeaderboardsCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_network_session_subscribe_write_true_skill", c.c_uint32, [c.c_uint64, online_abi.CNA_WriteLeaderboardsCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_network_session_subscribe_write_unarbitrated_leaderboard", c.c_uint32, [c.c_uint64, online_abi.CNA_WriteLeaderboardsCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_network_session_unsubscribe", c.c_uint32, [c.c_uint64],
     "consumes a subscription registration; no callback arrives afterwards"),
    ("cna_network_session_update", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
)

#: NetworkGamer, LocalNetworkGamer and NetworkMachine.
ONLINE_GAMERS_MANIFEST: tuple[Entry, ...] = (
    ("cna_local_network_gamer_clear_packet_queue_ext", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_local_network_gamer_create_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_local_network_gamer_enable_send_voice", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint8],
     "borrowed handle; retains nothing"),
    ("cna_local_network_gamer_enqueue_packet_ext", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_NetworkEventInfo)],
     "borrowed handle; retains nothing"),
    ("cna_local_network_gamer_get_is_data_available", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_local_network_gamer_get_signed_in_gamer", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_local_network_gamer_receive_data", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64), c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_local_network_gamer_receive_data_at", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.c_int32, c.POINTER(c.c_uint64), c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_local_network_gamer_receive_data_into_packet_reader", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint64), c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_local_network_gamer_send_data", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.c_uint32],
     "borrowed handle; retains nothing"),
    ("cna_local_network_gamer_send_data_range", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.c_int32, c.c_int32, c.c_uint32],
     "borrowed handle; retains nothing"),
    ("cna_local_network_gamer_send_data_range_to", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.c_int32, c.c_int32, c.c_uint32, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_local_network_gamer_send_data_to", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.c_uint32, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_local_network_gamer_send_packet_writer", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint32],
     "borrowed handle; retains nothing"),
    ("cna_local_network_gamer_send_packet_writer_to", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint32, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_local_network_gamer_send_party_invites", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_network_gamer_copy_machine", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_network_gamer_create", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_network_gamer_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_network_gamer_get_has_left_session", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_gamer_get_has_voice", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_gamer_get_id", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_gamer_get_is_guest", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_gamer_get_is_host", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_gamer_get_is_local", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_gamer_get_is_muted_by_local_user", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_gamer_get_is_private_slot", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_gamer_get_is_ready", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_gamer_get_is_talking", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_gamer_get_roundtrip_ticks", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_gamer_get_session", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_gamer_set_has_left_session_ext", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_gamer_set_id_ext", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_gamer_set_is_host_ext", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_gamer_set_is_ready", c.c_uint32, [c.c_uint64, c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_gamer_set_machine", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_gamer_set_roundtrip_ticks_ext", c.c_uint32, [c.c_uint64, c.c_int64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_network_machine_create", c.c_uint32, [c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_network_machine_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_network_machine_get_gamer", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_machine_get_gamer_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_network_machine_remove_from_session", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
)

#: The event payloads a session raises.
ONLINE_EVENTS_MANIFEST: tuple[Entry, ...] = (
)

#: Gamer, SignedInGamer, GamerProfile, friends and the game defaults.
ONLINE_GAMER_MANIFEST: tuple[Entry, ...] = (
    ("cna_friend_collection_create_ext", c.c_uint32, [c.POINTER(c.c_uint64), c.c_uint64, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_friend_gamer_copy_presence", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_friend_gamer_create_ext", c.c_uint32, [abi.CNA_StringView, abi.CNA_StringView, c.c_uint8, c.c_uint8, c.c_uint8, c.c_uint8, c.c_uint8, c.c_uint8, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_friend_gamer_get_info", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_FriendGamerInfo)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_friend_gamer_get_presence_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_gamer_begin_get_from_gamertag", c.c_uint32, [abi.CNA_StringView, online_abi.CNA_GamerAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_begin_get_partner_token", c.c_uint32, [abi.CNA_StringView, online_abi.CNA_GamerAsyncCallback, c.c_void_p, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_begin_get_profile", c.c_uint32, [c.c_uint64, online_abi.CNA_GamerAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_collection_add", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_gamer_collection_clear", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_gamer_collection_contains", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_gamer_collection_copy_to", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64), c.c_uint64, c.c_int32, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_gamer_collection_create_enumerator", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_gamer_collection_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_gamer_collection_get_at", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_collection_get_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_collection_index_of", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_int32)],
     "borrowed handle; retains nothing"),
    ("cna_gamer_collection_remove", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_gamer_copy_display_name", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_gamer_copy_gamertag", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_gamer_copy_partner_token", c.c_uint32, [abi.CNA_StringView, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_gamer_copy_text", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_gamer_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_gamer_enumerator_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_gamer_enumerator_get_current", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_enumerator_move_next", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_gamer_enumerator_reset", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_gamer_get_display_name_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_gamer_get_from_gamertag", c.c_uint32, [abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_get_gamertag_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_gamer_get_partner_token_size", c.c_uint32, [abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_gamer_get_profile", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_get_signed_in_gamer_at", c.c_uint32, [c.c_int32, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_get_signed_in_gamer_at_player_index", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint8), c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_get_signed_in_gamer_count", c.c_uint32, [c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_get_tag", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_get_text_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_gamer_profile_copy_motto", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_gamer_profile_copy_region_name", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_gamer_profile_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_gamer_profile_get_info", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_GamerProfileInfo)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_profile_get_motto_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_gamer_profile_get_picture_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_gamer_profile_get_region_name_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_gamer_set_display_name", c.c_uint32, [c.c_uint64, abi.CNA_StringView],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_gamer_set_signed_in_gamers_ext", c.c_uint32, [c.POINTER(c.c_uint64), c.c_uint64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_gamer_set_tag", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_gamer_signed_in_contains", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_gamer_signed_in_index_of", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "borrowed handle; retains nothing"),
    ("cna_gamer_unsubscribe_ext", c.c_uint32, [c.c_uint64],
     "consumes a subscription registration; no callback arrives afterwards"),
    ("cna_signed_in_gamer_award_achievement", c.c_uint32, [c.c_uint64, abi.CNA_StringView],
     "borrowed handle; retains nothing"),
    ("cna_signed_in_gamer_begin_award_achievement", c.c_uint32, [c.c_uint64, abi.CNA_StringView, online_abi.CNA_GamerAsyncCallback, c.c_void_p],
     "borrowed handle; retains nothing"),
    ("cna_signed_in_gamer_begin_get_achievements", c.c_uint32, [c.c_uint64, online_abi.CNA_GamerAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_signed_in_gamer_copy_gamertag", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_signed_in_gamer_create_ext", c.c_uint32, [abi.CNA_StringView, c.c_uint8, c.c_uint8, c.c_uint32, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_signed_in_gamer_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_signed_in_gamer_get_achievements", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_signed_in_gamer_get_friends", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_signed_in_gamer_get_game_defaults", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_GameDefaults)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_signed_in_gamer_get_gamertag_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_signed_in_gamer_get_is_guest", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_signed_in_gamer_get_is_signed_in_to_live", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_signed_in_gamer_get_party_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_signed_in_gamer_get_player_index", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_signed_in_gamer_get_presence", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_GamerPresence)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_signed_in_gamer_get_privileges", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_GamerPrivileges)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_signed_in_gamer_is_friend", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_signed_in_gamer_is_headset", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_signed_in_gamer_set_party_size", c.c_uint32, [c.c_uint64, c.c_int32],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_signed_in_gamer_set_presence", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_GamerPresence)],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_signed_in_gamer_set_presence_mode_string_ext", c.c_uint32, [c.c_uint64, abi.CNA_StringView],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_signed_in_gamer_subscribe_signed_in_ext", c.c_uint32, [online_abi.CNA_SignedInGamerEventCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_signed_in_gamer_subscribe_signed_out_ext", c.c_uint32, [online_abi.CNA_SignedInGamerEventCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
)

#: Guide, and the GamerServices component and dispatcher.
ONLINE_GUIDE_MANIFEST: tuple[Entry, ...] = (
    ("cna_gamer_services_dispatcher_get_freed_gamer_count_ext", c.c_uint32, [c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_services_dispatcher_get_is_initialized", c.c_uint32, [c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_services_dispatcher_get_window_handle", c.c_uint32, [c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_gamer_services_dispatcher_subscribe_installing_title_update_ext", c.c_uint32, [online_abi.CNA_GamerAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_gamer_services_dispatcher_update_async", c.c_uint32, [c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_guide_begin_show_keyboard_input", c.c_uint32, [c.c_uint32, abi.CNA_StringView, abi.CNA_StringView, abi.CNA_StringView, c.c_uint8, online_abi.CNA_GamerAsyncCallback, c.c_void_p],
     "borrowed handle; retains nothing"),
    ("cna_guide_begin_show_message_box", c.c_uint32, [c.c_uint32, abi.CNA_StringView, abi.CNA_StringView, c.POINTER(abi.CNA_StringView), c.c_uint64, c.c_int32, c.c_uint32, online_abi.CNA_GamerAsyncCallback, c.c_void_p],
     "borrowed handle; retains nothing"),
    ("cna_guide_copy_pending_keyboard_input_description_ext", c.c_uint32, [c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_guide_copy_pending_keyboard_input_display_text_ext", c.c_uint32, [c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_guide_copy_pending_keyboard_input_title_ext", c.c_uint32, [c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_guide_delay_notifications", c.c_uint32, [c.c_int64],
     "borrowed handle; retains nothing"),
    ("cna_guide_end_show_keyboard_input", c.c_uint32, [c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_guide_end_show_keyboard_input_size", c.c_uint32, [c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_guide_end_show_message_box", c.c_uint32, [c.POINTER(c.c_uint8), c.POINTER(c.c_int32)],
     "borrowed handle; retains nothing"),
    ("cna_guide_get_has_pending_keyboard_input_ext", c.c_uint32, [c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_guide_get_has_pending_message_box_ext", c.c_uint32, [c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_guide_get_is_screen_saver_enabled", c.c_uint32, [c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_guide_get_is_trial_mode", c.c_uint32, [c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_guide_get_is_visible", c.c_uint32, [c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_guide_get_notification_position", c.c_uint32, [c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_guide_get_pending_keyboard_input_description_size_ext", c.c_uint32, [c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_guide_get_pending_keyboard_input_display_text_size_ext", c.c_uint32, [c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_guide_get_pending_keyboard_input_title_size_ext", c.c_uint32, [c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_guide_get_pending_message_box_focus_button_ext", c.c_uint32, [c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_guide_get_simulate_trial_mode", c.c_uint32, [c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_guide_render_pending_keyboard_input_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_guide_render_pending_message_box_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_guide_reset_pending_keyboard_input_ext", c.c_uint32, [],
     "borrowed handle; retains nothing"),
    ("cna_guide_reset_pending_message_box_ext", c.c_uint32, [],
     "borrowed handle; retains nothing"),
    ("cna_guide_set_is_screen_saver_enabled", c.c_uint32, [c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_guide_set_is_trial_mode", c.c_uint32, [c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_guide_set_is_visible", c.c_uint32, [c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_guide_set_notification_position", c.c_uint32, [c.c_uint32],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_guide_set_simulate_trial_mode", c.c_uint32, [c.c_uint8],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_guide_show_achievements_ext", c.c_uint32, [c.c_uint32],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_compose_message", c.c_uint32, [c.c_uint32, abi.CNA_StringView, c.POINTER(c.c_uint64), c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_friend_request", c.c_uint32, [c.c_uint32, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_friends", c.c_uint32, [c.c_uint32],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_game_invite", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64), c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_game_invite_for_session", c.c_uint32, [abi.CNA_StringView],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_gamer_card", c.c_uint32, [c.c_uint32, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_marketplace", c.c_uint32, [c.c_uint32],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_messages", c.c_uint32, [c.c_uint32],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_party", c.c_uint32, [c.c_uint32],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_party_sessions", c.c_uint32, [c.c_uint32],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_player_review", c.c_uint32, [c.c_uint32, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_players", c.c_uint32, [c.c_uint32],
     "borrowed handle; retains nothing"),
    ("cna_guide_show_sign_in", c.c_uint32, [c.c_int32, c.c_uint8],
     "borrowed handle; retains nothing"),
    ("cna_guide_simulate_keyboard_input_cancel_ext", c.c_uint32, [],
     "borrowed handle; retains nothing"),
    ("cna_guide_simulate_message_box_click_ext", c.c_uint32, [c.c_int32],
     "borrowed handle; retains nothing"),
    ("cna_guide_was_keyboard_input_canceled_ext", c.c_uint32, [c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
)

#: Achievements, leaderboards and the typed property dictionary they use.
ONLINE_ACHIEVEMENTS_MANIFEST: tuple[Entry, ...] = (
    ("cna_achievement_collection_add", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_achievement_collection_clear", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_achievement_collection_contains", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_achievement_collection_copy_to", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64), c.c_uint64, c.c_int32, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_achievement_collection_create_ext", c.c_uint32, [c.POINTER(c.c_uint64), c.c_uint64, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_achievement_collection_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_achievement_collection_get_at", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_achievement_collection_get_by_key", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_achievement_collection_get_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_achievement_collection_get_is_read_only", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_achievement_collection_index_of", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_int32)],
     "borrowed handle; retains nothing"),
    ("cna_achievement_collection_insert", c.c_uint32, [c.c_uint64, c.c_int32, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_achievement_collection_remove", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_achievement_collection_remove_at", c.c_uint32, [c.c_uint64, c.c_int32],
     "borrowed handle; retains nothing"),
    ("cna_achievement_copy_description", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_achievement_copy_how_to_earn", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_achievement_copy_key", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_achievement_copy_name", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_achievement_create_ext", c.c_uint32, [abi.CNA_StringView, abi.CNA_StringView, abi.CNA_StringView, c.c_uint8, c.c_uint8, c.c_int64, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_achievement_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_achievement_equals", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_achievement_get_description_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_achievement_get_how_to_earn_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_achievement_get_info", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_AchievementInfo)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_achievement_get_key_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_achievement_get_name_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_achievement_get_picture_size", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_leaderboard_entry_create_ext", c.c_uint32, [c.c_uint64, c.c_int64, c.c_int32, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_leaderboard_entry_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_leaderboard_entry_equals", c.c_uint32, [c.c_uint64, c.c_uint64, c.POINTER(c.c_uint8)],
     "pure function over caller-owned input; nothing is retained"),
    ("cna_leaderboard_entry_get_columns", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_leaderboard_entry_get_gamer", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_leaderboard_entry_get_info", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_LeaderboardEntryInfo)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_leaderboard_entry_set_rating", c.c_uint32, [c.c_uint64, c.c_int64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_leaderboard_entry_set_rating_changed_hook_ext", c.c_uint32, [c.c_uint64, online_abi.CNA_GamerAsyncCallback, c.c_void_p],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_leaderboard_reader_begin_page_down", c.c_uint32, [c.c_uint64, online_abi.CNA_GamerAsyncCallback, c.c_void_p],
     "borrowed handle; retains nothing"),
    ("cna_leaderboard_reader_begin_page_up", c.c_uint32, [c.c_uint64, online_abi.CNA_GamerAsyncCallback, c.c_void_p],
     "borrowed handle; retains nothing"),
    ("cna_leaderboard_reader_begin_read", c.c_uint32, [c.POINTER(online_abi.CNA_LeaderboardIdentity), c.c_int32, c.c_int32, online_abi.CNA_GamerAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_leaderboard_reader_begin_read_from_gamers", c.c_uint32, [c.POINTER(online_abi.CNA_LeaderboardIdentity), c.POINTER(c.c_uint64), c.c_uint64, c.c_uint64, c.c_int32, online_abi.CNA_GamerAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_leaderboard_reader_begin_read_from_pivot", c.c_uint32, [c.POINTER(online_abi.CNA_LeaderboardIdentity), c.c_uint64, c.c_int32, online_abi.CNA_GamerAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_leaderboard_reader_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_leaderboard_reader_get_entry_at", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_leaderboard_reader_get_identity", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_LeaderboardIdentity)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_leaderboard_reader_get_info", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_LeaderboardReaderInfo)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_leaderboard_reader_page_down", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_leaderboard_reader_page_up", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_leaderboard_reader_read", c.c_uint32, [c.POINTER(online_abi.CNA_LeaderboardIdentity), c.c_int32, c.c_int32, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_leaderboard_reader_read_from_gamers", c.c_uint32, [c.POINTER(online_abi.CNA_LeaderboardIdentity), c.POINTER(c.c_uint64), c.c_uint64, c.c_uint64, c.c_int32, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_leaderboard_reader_read_from_pivot", c.c_uint32, [c.POINTER(online_abi.CNA_LeaderboardIdentity), c.c_uint64, c.c_int32, c.POINTER(c.c_uint64)],
     "borrowed handle; retains nothing"),
    ("cna_property_dictionary_clear", c.c_uint32, [c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_property_dictionary_contains_key", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_property_dictionary_copy_key_at", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_property_dictionary_copy_string", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_property_dictionary_create_ext", c.c_uint32, [c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_property_dictionary_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_property_dictionary_get_count", c.c_uint32, [c.c_uint64, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_property_dictionary_get_date_time_ticks", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_int64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_property_dictionary_get_double", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_double)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_property_dictionary_get_int32", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_property_dictionary_get_int64", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_int64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_property_dictionary_get_is_read_only", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_property_dictionary_get_key_size_at", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_property_dictionary_get_outcome", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_property_dictionary_get_single", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_float)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_property_dictionary_get_stream_size_ext", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8), c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_property_dictionary_get_string_size", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_property_dictionary_get_time_span_ticks", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_int64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_property_dictionary_remove", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8)],
     "borrowed handle; retains nothing"),
    ("cna_property_dictionary_set_date_time_ticks", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.c_int64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_property_dictionary_set_double", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.c_double],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_property_dictionary_set_int32", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.c_int32],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_property_dictionary_set_int64", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.c_int64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_property_dictionary_set_outcome", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.c_uint32],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_property_dictionary_set_single", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.c_float],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_property_dictionary_set_string", c.c_uint32, [c.c_uint64, abi.CNA_StringView, abi.CNA_StringView],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_property_dictionary_set_time_span_ticks", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.c_int64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_property_dictionary_try_get_value_kind_ext", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.POINTER(c.c_uint8), c.POINTER(c.c_uint32)],
     "caller output; borrowed handle, nothing is retained"),
)

#: AvatarDescription, AvatarAnimation, AvatarRenderer and their values.
ONLINE_AVATAR_MANIFEST: tuple[Entry, ...] = (
    ("cna_avatar_animation_copy_real_clip_name_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_avatar_animation_create", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_avatar_animation_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_avatar_animation_get_bone_transform_at", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(abi.CNA_Matrix)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_avatar_animation_get_expression", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_AvatarExpression)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_avatar_animation_get_info", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_AvatarAnimationInfo)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_avatar_animation_get_real_clip_name_size_ext", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_avatar_animation_preset_copy_clip_name_ext", c.c_uint32, [c.c_uint32, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_avatar_animation_preset_get_clip_name_size_ext", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_avatar_animation_set_current_position", c.c_uint32, [c.c_uint64, c.c_int64],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_avatar_animation_set_real_clip_name_ext", c.c_uint32, [c.c_uint64, abi.CNA_StringView],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_avatar_animation_update", c.c_uint32, [c.c_uint64, c.c_int64, c.c_uint8],
     "borrowed handle; retains nothing"),
    ("cna_avatar_appearance_init_ext", c.c_uint32, [c.POINTER(online_abi.CNA_AvatarAppearanceEXT)],
     "pure value initialiser over caller-owned storage"),
    ("cna_avatar_body_type_copy_content_name_ext", c.c_uint32, [c.c_uint32, c.POINTER(c.c_char), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_avatar_body_type_get_content_name_size_ext", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64)],
     "caller output; the size half of the size/copy protocol"),
    ("cna_avatar_description_copy_description", c.c_uint32, [c.c_uint64, c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "caller output; two-call size/copy protocol, no partial write"),
    ("cna_avatar_description_create", c.c_uint32, [c.POINTER(c.c_uint8), c.c_uint64, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_avatar_description_create_random", c.c_uint32, [c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_avatar_description_create_random_for_body_type", c.c_uint32, [c.c_uint32, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_avatar_description_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_avatar_description_get_from_gamer", c.c_uint32, [c.c_uint64, online_abi.CNA_GamerAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_avatar_description_get_info", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_AvatarDescriptionInfo)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_avatar_description_subscribe_changed_ext", c.c_uint32, [online_abi.CNA_GamerAsyncCallback, c.c_void_p, c.POINTER(c.c_uint64)],
     "roots a callback trampoline; the registration is owned and must be released before the owner is destroyed"),
    ("cna_avatar_renderer_create", c.c_uint32, [c.c_uint64, c.c_uint8, c.POINTER(c.c_uint64)],
     "owned handle; the caller closes it and nothing else may"),
    ("cna_avatar_renderer_destroy", c.c_uint32, [c.c_uint64],
     "consumes the handle; every borrowed view of it is invalid afterwards"),
    ("cna_avatar_renderer_draw_animation", c.c_uint32, [c.c_uint64, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_avatar_renderer_draw_bones", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Matrix), c.c_uint64, c.POINTER(online_abi.CNA_AvatarExpression)],
     "borrowed handle; retains nothing"),
    ("cna_avatar_renderer_draw_real_ext", c.c_uint32, [c.c_uint64, abi.CNA_StringView, c.c_int64, c.c_uint8],
     "borrowed handle; retains nothing"),
    ("cna_avatar_renderer_enable_real_rendering_ext", c.c_uint32, [c.c_uint64, c.c_uint64, c.c_uint64],
     "borrowed handle; retains nothing"),
    ("cna_avatar_renderer_get_bind_pose_at", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(abi.CNA_Matrix)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_avatar_renderer_get_info", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_AvatarRendererInfo)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_avatar_renderer_get_lighting", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector3), c.POINTER(abi.CNA_Vector3), c.POINTER(abi.CNA_Vector3)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_avatar_renderer_get_parent_bone_at", c.c_uint32, [c.c_uint64, c.c_int32, c.POINTER(c.c_int32)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_avatar_renderer_get_transforms", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Matrix), c.POINTER(abi.CNA_Matrix), c.POINTER(abi.CNA_Matrix)],
     "caller output; borrowed handle, nothing is retained"),
    ("cna_avatar_renderer_set_appearance_ext", c.c_uint32, [c.c_uint64, c.POINTER(online_abi.CNA_AvatarAppearanceEXT)],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_avatar_renderer_set_lighting", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Vector3), c.POINTER(abi.CNA_Vector3), c.POINTER(abi.CNA_Vector3)],
     "borrowed handle; copies the value, retains nothing"),
    ("cna_avatar_renderer_set_transforms", c.c_uint32, [c.c_uint64, c.POINTER(abi.CNA_Matrix), c.POINTER(abi.CNA_Matrix), c.POINTER(abi.CNA_Matrix)],
     "borrowed handle; copies the value, retains nothing"),
)

#: Every group above, in one tuple for :mod:`_cna_native.loader`.
ONLINE_FUNCTION_MANIFEST: tuple[Entry, ...] = (
    ONLINE_PACKETS_MANIFEST
    +
    ONLINE_SESSION_PROPERTIES_MANIFEST
    +
    ONLINE_QUALITY_OF_SERVICE_MANIFEST
    +
    ONLINE_SESSION_MANIFEST
    +
    ONLINE_GAMERS_MANIFEST
    +
    ONLINE_EVENTS_MANIFEST
    +
    ONLINE_GAMER_MANIFEST
    +
    ONLINE_GUIDE_MANIFEST
    +
    ONLINE_ACHIEVEMENTS_MANIFEST
    +
    ONLINE_AVATAR_MANIFEST
)
