"""Microsoft.Xna.Framework.Input, as the XNA 4.0 Xbox 360 runtime profile has it.

Generated by ``tools/generate_platform_profile.py`` from the XNA 4.0 Xbox 360 runtime
reference contract. Do not edit: run the generator, and the test suite checks
that running it changes nothing.
"""

from Microsoft.Xna.Framework.Input import (
    ButtonState,
    Buttons,
    GamePad,
    GamePadButtons,
    GamePadCapabilities,
    GamePadDPad,
    GamePadDeadZone,
    GamePadState,
    GamePadThumbSticks,
    GamePadTriggers,
    GamePadType,
    KeyState,
    Keyboard,
    KeyboardState,
    Keys,
    Mouse,
    MouseState,
)


__all__ = [
    "ButtonState",
    "Buttons",
    "GamePad",
    "GamePadButtons",
    "GamePadCapabilities",
    "GamePadDPad",
    "GamePadDeadZone",
    "GamePadState",
    "GamePadThumbSticks",
    "GamePadTriggers",
    "GamePadType",
    "KeyState",
    "Keyboard",
    "KeyboardState",
    "Keys",
    "Mouse",
    "MouseState",
]
