from typing import Any, BinaryIO, Generic, TypeVar, overload
from ...... import Color, Matrix, Quaternion, Vector2, Vector3, Vector4
from ......Graphics import GraphicsProfile
from ... import ExternalReferenceOfT, TargetPlatform

T = TypeVar("T")

class ContentCompiler:
    def GetTypeWriter(self, type: type) -> ContentTypeWriter: ...

class ContentTypeWriter:
    def __init__(self, targetType: type) -> None: ...
    def Initialize(self, compiler: ContentCompiler) -> None: ...
    def Write(self, output: ContentWriter, value: object) -> None: ...
    def GetRuntimeType(self, targetPlatform: TargetPlatform) -> str: ...
    def GetRuntimeReader(self, targetPlatform: TargetPlatform) -> str: ...
    def ShouldCompressContent(self, targetPlatform: TargetPlatform, value: object) -> bool: ...
    @property
    def TargetType(self) -> type: ...
    @property
    def TypeVersion(self) -> int: ...
    @property
    def CanDeserializeIntoExistingObject(self) -> bool: ...

class ContentTypeWriterAttribute:
    def __init__(self) -> None: ...

class ContentTypeWriterOfT(ContentTypeWriter, Generic[T]):
    def __init__(self) -> None: ...
    @overload
    def Write(self, output: ContentWriter, value: T) -> None: ...
    @overload
    def Write(self, output: ContentWriter, value: object) -> None: ...

class ContentWriter:
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def WriteObject(self, value: T) -> None: ...
    @overload
    def WriteObject(self, value: T, typeWriter: ContentTypeWriter) -> None: ...
    @overload
    def WriteRawObject(self, value: T) -> None: ...
    @overload
    def WriteRawObject(self, value: T, typeWriter: ContentTypeWriter) -> None: ...
    def WriteSharedResource(self, value: T) -> None: ...
    def WriteExternalReference(self, reference: ExternalReferenceOfT[T]) -> None: ...
    @overload
    def Write(self, value: Vector2) -> None: ...
    @overload
    def Write(self, value: Vector3) -> None: ...
    @overload
    def Write(self, value: Vector4) -> None: ...
    @overload
    def Write(self, value: Matrix) -> None: ...
    @overload
    def Write(self, value: Quaternion) -> None: ...
    @overload
    def Write(self, value: Color) -> None: ...
    @property
    def TargetPlatform(self) -> TargetPlatform: ...
    @property
    def TargetProfile(self) -> GraphicsProfile: ...
