from datetime import timedelta
from enum import IntEnum
from typing import Any, Sequence
from .. import ContentItem

class AudioContent(ContentItem):
    def __init__(self, audioFileName: str, audioFileType: AudioFileType) -> None: ...
    def Dispose(self) -> None: ...
    def ConvertFormat(self, formatType: ConversionFormat, quality: ConversionQuality, targetFileName: str) -> None: ...
    @property
    def FileName(self) -> str: ...
    @property
    def FileType(self) -> AudioFileType: ...
    @property
    def Format(self) -> AudioFormat: ...
    @property
    def Data(self) -> tuple[int, ...]: ...
    @property
    def Duration(self) -> timedelta: ...
    @property
    def LoopStart(self) -> int: ...
    @property
    def LoopLength(self) -> int: ...
    def __enter__(self) -> AudioContent: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class AudioFileType(IntEnum):
    Wav: int
    Mp3: int
    Wma: int

class AudioFormat:
    @property
    def Format(self) -> int: ...
    @property
    def ChannelCount(self) -> int: ...
    @property
    def SampleRate(self) -> int: ...
    @property
    def AverageBytesPerSecond(self) -> int: ...
    @property
    def BlockAlign(self) -> int: ...
    @property
    def BitsPerSample(self) -> int: ...
    @property
    def NativeWaveFormat(self) -> tuple[int, ...]: ...

class ConversionFormat(IntEnum):
    Pcm: int
    Adpcm: int
    WindowsMedia: int
    Xma: int

class ConversionQuality(IntEnum):
    Low: int
    Medium: int
    Best: int
