from datetime import timedelta
from enum import IntEnum
from typing import Any, Callable, Generic, Iterable, Iterator, MutableSequence, Sequence, TypeVar, overload
from ..... import Color, Matrix, Rectangle, Vector2, Vector3
from .....Graphics import CompareFunction, GraphicsProfile, SurfaceFormat, VertexElementFormat, VertexElementUsage
from .. import ContentItem, ExternalReferenceOfT, NamedValueDictionaryOfT

T = TypeVar("T")
# XNA constrains MaterialContent.GetValueTypeProperty's T to a value
# type; the constraint is projected as the bound and the name carries
# it, so the type's three differently constrained Ts stay distinct.
TValue = TypeVar("TValue", bound=object)
ElementType = TypeVar("ElementType")
TargetType = TypeVar("TargetType")
TInput = TypeVar("TInput")
TOutput = TypeVar("TOutput")

class AlphaTestMaterialContent(MaterialContent):
    def __init__(self) -> None: ...
    @property
    def AlphaFunction(self) -> CompareFunction | None: ...
    @AlphaFunction.setter
    def AlphaFunction(self, value: CompareFunction | None) -> None: ...
    @property
    def ReferenceAlpha(self) -> int | None: ...
    @ReferenceAlpha.setter
    def ReferenceAlpha(self, value: int | None) -> None: ...
    @property
    def DiffuseColor(self) -> Vector3 | None: ...
    @DiffuseColor.setter
    def DiffuseColor(self, value: Vector3 | None) -> None: ...
    @property
    def Alpha(self) -> float | None: ...
    @Alpha.setter
    def Alpha(self, value: float | None) -> None: ...
    @property
    def VertexColorEnabled(self) -> bool | None: ...
    @VertexColorEnabled.setter
    def VertexColorEnabled(self, value: bool | None) -> None: ...
    @property
    def Texture(self) -> ExternalReferenceOfT[TextureContent]: ...
    @Texture.setter
    def Texture(self, value: ExternalReferenceOfT[TextureContent]) -> None: ...
    AlphaFunctionKey: Final[str]
    ReferenceAlphaKey: Final[str]
    DiffuseColorKey: Final[str]
    AlphaKey: Final[str]
    VertexColorEnabledKey: Final[str]
    TextureKey: Final[str]

class AnimationChannel:
    def __init__(self) -> None: ...
    def Add(self, item: AnimationKeyframe) -> int: ...
    def Clear(self) -> None: ...
    def Contains(self, item: AnimationKeyframe) -> bool: ...
    def IndexOf(self, item: AnimationKeyframe) -> int: ...
    def Remove(self, item: AnimationKeyframe) -> bool: ...
    def RemoveAt(self, index: int) -> None: ...
    def GetEnumerator(self) -> Iterator[AnimationKeyframe]: ...
    @property
    def Count(self) -> int: ...
    def __getitem__(self, index: int) -> AnimationKeyframe: ...
    def __iter__(self) -> Iterator[AnimationKeyframe]: ...
    def __len__(self) -> int: ...

class AnimationChannelDictionary:
    def __init__(self) -> None: ...

class AnimationContent(ContentItem):
    def __init__(self) -> None: ...
    @property
    def Duration(self) -> timedelta: ...
    @Duration.setter
    def Duration(self, value: timedelta) -> None: ...
    @property
    def Channels(self) -> AnimationChannelDictionary: ...

class AnimationContentDictionary:
    def __init__(self) -> None: ...

class AnimationKeyframe:
    def __init__(self, time: timedelta, transform: Matrix) -> None: ...
    def CompareTo(self, other: AnimationKeyframe) -> int: ...
    @property
    def Time(self) -> timedelta: ...
    @property
    def Transform(self) -> Matrix: ...
    @Transform.setter
    def Transform(self, value: Matrix) -> None: ...

class BasicMaterialContent(MaterialContent):
    def __init__(self) -> None: ...
    @property
    def DiffuseColor(self) -> Vector3 | None: ...
    @DiffuseColor.setter
    def DiffuseColor(self, value: Vector3 | None) -> None: ...
    @property
    def SpecularColor(self) -> Vector3 | None: ...
    @SpecularColor.setter
    def SpecularColor(self, value: Vector3 | None) -> None: ...
    @property
    def EmissiveColor(self) -> Vector3 | None: ...
    @EmissiveColor.setter
    def EmissiveColor(self, value: Vector3 | None) -> None: ...
    @property
    def SpecularPower(self) -> float | None: ...
    @SpecularPower.setter
    def SpecularPower(self, value: float | None) -> None: ...
    @property
    def Alpha(self) -> float | None: ...
    @Alpha.setter
    def Alpha(self, value: float | None) -> None: ...
    @property
    def VertexColorEnabled(self) -> bool | None: ...
    @VertexColorEnabled.setter
    def VertexColorEnabled(self, value: bool | None) -> None: ...
    @property
    def Texture(self) -> ExternalReferenceOfT[TextureContent]: ...
    @Texture.setter
    def Texture(self, value: ExternalReferenceOfT[TextureContent]) -> None: ...
    DiffuseColorKey: Final[str]
    SpecularColorKey: Final[str]
    EmissiveColorKey: Final[str]
    SpecularPowerKey: Final[str]
    AlphaKey: Final[str]
    VertexColorEnabledKey: Final[str]
    TextureKey: Final[str]

class BitmapContent(ContentItem):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, width: int, height: int) -> None: ...
    @overload
    @staticmethod
    def Copy(sourceBitmap: BitmapContent, destinationBitmap: BitmapContent) -> None: ...
    @overload
    @staticmethod
    def Copy(sourceBitmap: BitmapContent, sourceRegion: Rectangle, destinationBitmap: BitmapContent, destinationRegion: Rectangle) -> None: ...
    @staticmethod
    def ValidateCopyArguments(sourceBitmap: BitmapContent, sourceRegion: Rectangle, destinationBitmap: BitmapContent, destinationRegion: Rectangle) -> None: ...
    def TryCopyTo(self, destinationBitmap: BitmapContent, sourceRegion: Rectangle, destinationRegion: Rectangle) -> bool: ...
    def TryCopyFrom(self, sourceBitmap: BitmapContent, sourceRegion: Rectangle, destinationRegion: Rectangle) -> bool: ...
    def SetPixelData(self, sourceData: Sequence[int]) -> None: ...
    def GetPixelData(self) -> list[int]: ...
    def TryGetFormat(self) -> tuple[bool, SurfaceFormat]: ...
    def ToString(self) -> str: ...
    @property
    def Width(self) -> int: ...
    @property
    def Height(self) -> int: ...

class BoneContent(NodeContent):
    def __init__(self) -> None: ...

class BoneWeight:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, boneName: str, weight: float) -> None: ...
    @property
    def BoneName(self) -> str: ...
    @property
    def Weight(self) -> float: ...
    def __copy__(self) -> BoneWeight: ...
    def __deepcopy__(self, memo: object) -> BoneWeight: ...

class BoneWeightCollection:
    def __init__(self) -> None: ...
    @overload
    def NormalizeWeights(self) -> None: ...
    @overload
    def NormalizeWeights(self, maxWeights: int) -> None: ...

class DualTextureMaterialContent(MaterialContent):
    def __init__(self) -> None: ...
    @property
    def DiffuseColor(self) -> Vector3 | None: ...
    @DiffuseColor.setter
    def DiffuseColor(self, value: Vector3 | None) -> None: ...
    @property
    def Alpha(self) -> float | None: ...
    @Alpha.setter
    def Alpha(self, value: float | None) -> None: ...
    @property
    def VertexColorEnabled(self) -> bool | None: ...
    @VertexColorEnabled.setter
    def VertexColorEnabled(self, value: bool | None) -> None: ...
    @property
    def Texture(self) -> ExternalReferenceOfT[TextureContent]: ...
    @Texture.setter
    def Texture(self, value: ExternalReferenceOfT[TextureContent]) -> None: ...
    @property
    def Texture2(self) -> ExternalReferenceOfT[TextureContent]: ...
    @Texture2.setter
    def Texture2(self, value: ExternalReferenceOfT[TextureContent]) -> None: ...
    DiffuseColorKey: Final[str]
    AlphaKey: Final[str]
    VertexColorEnabledKey: Final[str]
    TextureKey: Final[str]
    Texture2Key: Final[str]

class Dxt1BitmapContent(DxtBitmapContent):
    def __init__(self, width: int, height: int) -> None: ...
    def TryGetFormat(self) -> tuple[bool, SurfaceFormat]: ...

class Dxt3BitmapContent(DxtBitmapContent):
    def __init__(self, width: int, height: int) -> None: ...
    def TryGetFormat(self) -> tuple[bool, SurfaceFormat]: ...

class Dxt5BitmapContent(DxtBitmapContent):
    def __init__(self, width: int, height: int) -> None: ...
    def TryGetFormat(self) -> tuple[bool, SurfaceFormat]: ...

class DxtBitmapContent(BitmapContent):
    @overload
    def __init__(self, blockSize: int) -> None: ...
    @overload
    def __init__(self, blockSize: int, width: int, height: int) -> None: ...
    def TryCopyTo(self, destinationBitmap: BitmapContent, sourceRegion: Rectangle, destinationRegion: Rectangle) -> bool: ...
    def TryCopyFrom(self, sourceBitmap: BitmapContent, sourceRegion: Rectangle, destinationRegion: Rectangle) -> bool: ...
    def SetPixelData(self, sourceData: Sequence[int]) -> None: ...
    def GetPixelData(self) -> list[int]: ...

class EffectContent(ContentItem):
    def __init__(self) -> None: ...
    @property
    def EffectCode(self) -> str: ...
    @EffectCode.setter
    def EffectCode(self, value: str) -> None: ...

class EffectMaterialContent(MaterialContent):
    def __init__(self) -> None: ...
    @property
    def Effect(self) -> ExternalReferenceOfT[EffectContent]: ...
    @Effect.setter
    def Effect(self, value: ExternalReferenceOfT[EffectContent]) -> None: ...
    @property
    def CompiledEffect(self) -> ExternalReferenceOfT[CompiledEffectContent]: ...
    @CompiledEffect.setter
    def CompiledEffect(self, value: ExternalReferenceOfT[CompiledEffectContent]) -> None: ...
    EffectKey: Final[str]
    CompiledEffectKey: Final[str]

class EnvironmentMapMaterialContent(MaterialContent):
    def __init__(self) -> None: ...
    @property
    def EnvironmentMapAmount(self) -> float | None: ...
    @EnvironmentMapAmount.setter
    def EnvironmentMapAmount(self, value: float | None) -> None: ...
    @property
    def EnvironmentMapSpecular(self) -> Vector3 | None: ...
    @EnvironmentMapSpecular.setter
    def EnvironmentMapSpecular(self, value: Vector3 | None) -> None: ...
    @property
    def FresnelFactor(self) -> float | None: ...
    @FresnelFactor.setter
    def FresnelFactor(self, value: float | None) -> None: ...
    @property
    def DiffuseColor(self) -> Vector3 | None: ...
    @DiffuseColor.setter
    def DiffuseColor(self, value: Vector3 | None) -> None: ...
    @property
    def EmissiveColor(self) -> Vector3 | None: ...
    @EmissiveColor.setter
    def EmissiveColor(self, value: Vector3 | None) -> None: ...
    @property
    def Alpha(self) -> float | None: ...
    @Alpha.setter
    def Alpha(self, value: float | None) -> None: ...
    @property
    def Texture(self) -> ExternalReferenceOfT[TextureContent]: ...
    @Texture.setter
    def Texture(self, value: ExternalReferenceOfT[TextureContent]) -> None: ...
    @property
    def EnvironmentMap(self) -> ExternalReferenceOfT[TextureContent]: ...
    @EnvironmentMap.setter
    def EnvironmentMap(self, value: ExternalReferenceOfT[TextureContent]) -> None: ...
    EnvironmentMapAmountKey: Final[str]
    EnvironmentMapSpecularKey: Final[str]
    FresnelFactorKey: Final[str]
    DiffuseColorKey: Final[str]
    EmissiveColorKey: Final[str]
    AlphaKey: Final[str]
    TextureKey: Final[str]
    EnvironmentMapKey: Final[str]

class FontDescription(ContentItem):
    @overload
    def __init__(self, fontName: str, size: float, spacing: float) -> None: ...
    @overload
    def __init__(self, fontName: str, size: float, spacing: float, fontStyle: FontDescriptionStyle) -> None: ...
    @overload
    def __init__(self, fontName: str, size: float, spacing: float, fontStyle: FontDescriptionStyle, useKerning: bool) -> None: ...
    @property
    def FontName(self) -> str: ...
    @FontName.setter
    def FontName(self, value: str) -> None: ...
    @property
    def Size(self) -> float: ...
    @Size.setter
    def Size(self, value: float) -> None: ...
    @property
    def Spacing(self) -> float: ...
    @Spacing.setter
    def Spacing(self, value: float) -> None: ...
    @property
    def UseKerning(self) -> bool: ...
    @UseKerning.setter
    def UseKerning(self, value: bool) -> None: ...
    @property
    def Style(self) -> FontDescriptionStyle: ...
    @Style.setter
    def Style(self, value: FontDescriptionStyle) -> None: ...
    @property
    def DefaultCharacter(self) -> str | None: ...
    @DefaultCharacter.setter
    def DefaultCharacter(self, value: str | None) -> None: ...
    @property
    def Characters(self) -> ICollection[str]: ...

class FontDescriptionStyle(IntFlag):
    Regular: int
    Bold: int
    Italic: int

class GeometryContent(ContentItem):
    def __init__(self) -> None: ...
    @property
    def Parent(self) -> MeshContent: ...
    @property
    def Material(self) -> MaterialContent: ...
    @Material.setter
    def Material(self, value: MaterialContent) -> None: ...
    @property
    def Indices(self) -> IndexCollection: ...
    @property
    def Vertices(self) -> VertexContent: ...

class GeometryContentCollection:
    def GetParent(self, child: GeometryContent) -> MeshContent: ...
    def SetParent(self, child: GeometryContent, parent: MeshContent) -> None: ...

class IndexCollection:
    def __init__(self) -> None: ...
    def AddRange(self, indices: Iterable[int]) -> None: ...

class IndirectPositionCollection:
    def GetEnumerator(self) -> Iterator[Vector3]: ...
    def IndexOf(self, item: Vector3) -> int: ...
    def Contains(self, item: Vector3) -> bool: ...
    def CopyTo(self, array: Sequence[Vector3], arrayIndex: int) -> None: ...
    @property
    def Count(self) -> int: ...
    def __getitem__(self, index: int) -> Vector3: ...
    def __setitem__(self, index: int, value: Vector3) -> None: ...
    def __iter__(self) -> Iterator[Vector3]: ...
    def __len__(self) -> int: ...

class MaterialContent(ContentItem):
    def __init__(self) -> None: ...
    def SetProperty(self, key: str, value: T) -> None: ...
    def SetTexture(self, key: str, value: ExternalReferenceOfT[TextureContent]) -> None: ...
    def GetValueTypeProperty(self, key: str) -> TValue | None: ...
    def GetReferenceTypeProperty(self, key: str) -> T: ...
    def GetTexture(self, key: str) -> ExternalReferenceOfT[TextureContent]: ...
    @property
    def Textures(self) -> TextureReferenceDictionary: ...

class MeshBuilder:
    @staticmethod
    def StartMesh(name: str) -> MeshBuilder: ...
    @overload
    def CreatePosition(self, x: float, y: float, z: float) -> int: ...
    @overload
    def CreatePosition(self, pos: Vector3) -> int: ...
    def CreateVertexChannel(self, usage: str, *, elementType: type[T]) -> int: ...
    def AddTriangleVertex(self, indexIntoVertexCollection: int) -> None: ...
    def SetMaterial(self, material: MaterialContent) -> None: ...
    def SetOpaqueData(self, opaqueData: OpaqueDataDictionary) -> None: ...
    def SetVertexChannelData(self, vertexDataIndex: int, channelData: object) -> None: ...
    def FinishMesh(self) -> MeshContent: ...
    @property
    def SwapWindingOrder(self) -> bool: ...
    @SwapWindingOrder.setter
    def SwapWindingOrder(self, value: bool) -> None: ...
    @property
    def MergeDuplicatePositions(self) -> bool: ...
    @MergeDuplicatePositions.setter
    def MergeDuplicatePositions(self, value: bool) -> None: ...
    @property
    def MergePositionTolerance(self) -> float: ...
    @MergePositionTolerance.setter
    def MergePositionTolerance(self, value: float) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...

class MeshContent(NodeContent):
    def __init__(self) -> None: ...
    @property
    def Positions(self) -> PositionCollection: ...
    @property
    def Geometry(self) -> GeometryContentCollection: ...

class MeshHelper:
    @staticmethod
    def CalculateNormals(mesh: MeshContent, overwriteExistingNormals: bool) -> None: ...
    @staticmethod
    def CalculateTangentFrames(mesh: MeshContent, textureCoordinateChannelName: str, tangentChannelName: str, binormalChannelName: str) -> None: ...
    @staticmethod
    def OptimizeForCache(mesh: MeshContent) -> None: ...
    @staticmethod
    def SwapWindingOrder(mesh: MeshContent) -> None: ...
    @staticmethod
    def MergeDuplicatePositions(mesh: MeshContent, tolerance: float) -> None: ...
    @overload
    @staticmethod
    def MergeDuplicateVertices(mesh: MeshContent) -> None: ...
    @overload
    @staticmethod
    def MergeDuplicateVertices(geometry: GeometryContent) -> None: ...
    @staticmethod
    def TransformScene(scene: NodeContent, transform: Matrix) -> None: ...
    @staticmethod
    def FindSkeleton(node: NodeContent) -> BoneContent: ...
    @staticmethod
    def FlattenSkeleton(skeleton: BoneContent) -> MutableSequence[BoneContent]: ...

class MipmapChain:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, bitmap: BitmapContent) -> None: ...
    @overload
    def __init__(self) -> MipmapChain: ...
    def InsertItem(self, index: int, item: BitmapContent) -> None: ...
    def SetItem(self, index: int, item: BitmapContent) -> None: ...

class MipmapChainCollection:
    def ClearItems(self) -> None: ...
    def InsertItem(self, index: int, item: MipmapChain) -> None: ...
    def RemoveItem(self, index: int) -> None: ...
    def SetItem(self, index: int, item: MipmapChain) -> None: ...

class NodeContent(ContentItem):
    def __init__(self) -> None: ...
    @property
    def Parent(self) -> NodeContent: ...
    @property
    def Transform(self) -> Matrix: ...
    @Transform.setter
    def Transform(self, value: Matrix) -> None: ...
    @property
    def AbsoluteTransform(self) -> Matrix: ...
    @property
    def Children(self) -> NodeContentCollection: ...
    @property
    def Animations(self) -> AnimationContentDictionary: ...

class NodeContentCollection:
    def GetParent(self, child: NodeContent) -> NodeContent: ...
    def SetParent(self, child: NodeContent, parent: NodeContent) -> None: ...

class PixelBitmapContentOfT(BitmapContent, Generic[T]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, width: int, height: int) -> None: ...
    def GetRow(self, y: int) -> list[T]: ...
    def GetPixel(self, x: int, y: int) -> T: ...
    def SetPixel(self, x: int, y: int, value: T) -> None: ...
    def TryCopyTo(self, destinationBitmap: BitmapContent, sourceRegion: Rectangle, destinationRegion: Rectangle) -> bool: ...
    def TryCopyFrom(self, sourceBitmap: BitmapContent, sourceRegion: Rectangle, destinationRegion: Rectangle) -> bool: ...
    def SetPixelData(self, sourceData: Sequence[int]) -> None: ...
    def GetPixelData(self) -> list[int]: ...
    def ReplaceColor(self, originalColor: T, newColor: T) -> None: ...
    def TryGetFormat(self) -> tuple[bool, SurfaceFormat]: ...
    def ToString(self) -> str: ...

class PositionCollection:
    def __init__(self) -> None: ...

class SkinnedMaterialContent(MaterialContent):
    def __init__(self) -> None: ...
    @property
    def WeightsPerVertex(self) -> int | None: ...
    @WeightsPerVertex.setter
    def WeightsPerVertex(self, value: int | None) -> None: ...
    @property
    def DiffuseColor(self) -> Vector3 | None: ...
    @DiffuseColor.setter
    def DiffuseColor(self, value: Vector3 | None) -> None: ...
    @property
    def SpecularColor(self) -> Vector3 | None: ...
    @SpecularColor.setter
    def SpecularColor(self, value: Vector3 | None) -> None: ...
    @property
    def EmissiveColor(self) -> Vector3 | None: ...
    @EmissiveColor.setter
    def EmissiveColor(self, value: Vector3 | None) -> None: ...
    @property
    def SpecularPower(self) -> float | None: ...
    @SpecularPower.setter
    def SpecularPower(self, value: float | None) -> None: ...
    @property
    def Alpha(self) -> float | None: ...
    @Alpha.setter
    def Alpha(self, value: float | None) -> None: ...
    @property
    def Texture(self) -> ExternalReferenceOfT[TextureContent]: ...
    @Texture.setter
    def Texture(self, value: ExternalReferenceOfT[TextureContent]) -> None: ...
    WeightsPerVertexKey: Final[str]
    DiffuseColorKey: Final[str]
    SpecularColorKey: Final[str]
    EmissiveColorKey: Final[str]
    SpecularPowerKey: Final[str]
    AlphaKey: Final[str]
    TextureKey: Final[str]

class Texture2DContent(TextureContent):
    def __init__(self) -> None: ...
    def Validate(self, targetProfile: GraphicsProfile | None) -> None: ...
    @property
    def Mipmaps(self) -> MipmapChain: ...
    @Mipmaps.setter
    def Mipmaps(self, value: MipmapChain) -> None: ...

class Texture3DContent(TextureContent):
    def __init__(self) -> None: ...
    def Validate(self, targetProfile: GraphicsProfile | None) -> None: ...
    def GenerateMipmaps(self, overwriteExistingMipmaps: bool) -> None: ...

class TextureContent(ContentItem):
    def __init__(self, faces: MipmapChainCollection) -> None: ...
    def Validate(self, targetProfile: GraphicsProfile | None) -> None: ...
    def GenerateMipmaps(self, overwriteExistingMipmaps: bool) -> None: ...
    def ConvertBitmapType(self, newBitmapType: type) -> None: ...
    @property
    def Faces(self) -> MipmapChainCollection: ...

class TextureCubeContent(TextureContent):
    def __init__(self) -> None: ...
    def Validate(self, targetProfile: GraphicsProfile | None) -> None: ...

class TextureReferenceDictionary:
    def __init__(self) -> None: ...

class VectorConverter:
    @staticmethod
    def TryGetSurfaceFormat(vectorType: type) -> tuple[bool, SurfaceFormat]: ...
    @overload
    @staticmethod
    def TryGetVectorType(surfaceFormat: SurfaceFormat) -> tuple[bool, type]: ...
    @overload
    @staticmethod
    def TryGetVectorType(vertexElementFormat: VertexElementFormat) -> tuple[bool, type]: ...
    @staticmethod
    def TryGetVertexElementFormat(vectorType: type) -> tuple[bool, VertexElementFormat]: ...
    @staticmethod
    def GetConverter(*, sourceType: type[TInput], destinationType: type[TOutput]) -> Converter[TInput, TOutput]: ...

class VertexChannel:
    def ReadConvertedContent(self, *, targetType: type[TargetType]) -> Iterable[TargetType]: ...
    def Contains(self, value: object) -> bool: ...
    def CopyTo(self, array: Array, index: int) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def IndexOf(self, value: object) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def ElementType(self) -> type: ...
    @property
    def Count(self) -> int: ...
    def __getitem__(self, index: int) -> object: ...
    def __iter__(self) -> Iterator[object]: ...
    def __len__(self) -> int: ...

class VertexChannelCollection:
    @overload
    def Add(self, name: str, channelData: Iterable[ElementType]) -> VertexChannelOfT[ElementType]: ...
    @overload
    def Add(self, name: str, elementType: type, channelData: IEnumerable) -> VertexChannel: ...
    @overload
    def Insert(self, index: int, name: str, channelData: Iterable[ElementType]) -> VertexChannelOfT[ElementType]: ...
    @overload
    def Insert(self, index: int, name: str, elementType: type, channelData: IEnumerable) -> VertexChannel: ...
    @overload
    def ConvertChannelContent(self, index: int, *, targetType: type[TargetType]) -> VertexChannelOfT[TargetType]: ...
    @overload
    def ConvertChannelContent(self, name: str, *, targetType: type[TargetType]) -> VertexChannelOfT[TargetType]: ...
    @overload
    def Contains(self, name: str) -> bool: ...
    @overload
    def Contains(self, item: VertexChannel) -> bool: ...
    @overload
    def IndexOf(self, name: str) -> int: ...
    @overload
    def IndexOf(self, item: VertexChannel) -> int: ...
    @overload
    def Remove(self, name: str) -> bool: ...
    @overload
    def Remove(self, item: VertexChannel) -> bool: ...
    @overload
    def Get(self, name: str) -> VertexChannelOfT[T]: ...
    @overload
    def Get(self, index: int) -> VertexChannelOfT[T]: ...
    def GetEnumerator(self) -> Iterator[VertexChannel]: ...
    def Clear(self) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    @overload
    def __getitem__(self, name: str) -> VertexChannel: ...
    @overload
    def __getitem__(self, index: int) -> VertexChannel: ...
    @property
    def Count(self) -> int: ...
    def __setitem__(self, index: int, value: VertexChannel) -> None: ...
    def __iter__(self) -> Iterator[VertexChannel]: ...
    def __len__(self) -> int: ...

class VertexChannelNames:
    @overload
    @staticmethod
    def Normal() -> str: ...
    @overload
    @staticmethod
    def Normal(usageIndex: int) -> str: ...
    @staticmethod
    def Color(usageIndex: int) -> str: ...
    @staticmethod
    def TextureCoordinate(usageIndex: int) -> str: ...
    @staticmethod
    def Tangent(usageIndex: int) -> str: ...
    @staticmethod
    def Binormal(usageIndex: int) -> str: ...
    @overload
    @staticmethod
    def Weights() -> str: ...
    @overload
    @staticmethod
    def Weights(usageIndex: int) -> str: ...
    @overload
    @staticmethod
    def EncodeName(baseName: str, usageIndex: int) -> str: ...
    @overload
    @staticmethod
    def EncodeName(vertexElementUsage: VertexElementUsage, usageIndex: int) -> str: ...
    @staticmethod
    def DecodeBaseName(encodedName: str) -> str: ...
    @staticmethod
    def DecodeUsageIndex(encodedName: str) -> int: ...
    @staticmethod
    def TryDecodeUsage(encodedName: str) -> tuple[bool, VertexElementUsage]: ...

class VertexChannelOfT(VertexChannel, Generic[T]):
    def ReadConvertedContent(self, *, targetType: type[TargetType]) -> Iterable[TargetType]: ...
    def Contains(self, item: T) -> bool: ...
    def CopyTo(self, array: Sequence[T], arrayIndex: int) -> None: ...
    def IndexOf(self, item: T) -> int: ...
    def GetEnumerator(self) -> Iterator[T]: ...
    @property
    def ElementType(self) -> type: ...
    def __getitem__(self, index: int) -> T: ...
    def __setitem__(self, index: int, value: T) -> None: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...

class VertexContent:
    def Add(self, positionIndex: int) -> int: ...
    def AddRange(self, positionIndexCollection: Iterable[int]) -> None: ...
    def Insert(self, index: int, positionIndex: int) -> None: ...
    def InsertRange(self, index: int, positionIndexCollection: Iterable[int]) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def RemoveRange(self, index: int, count: int) -> None: ...
    def CreateVertexBuffer(self) -> VertexBufferContent: ...
    @property
    def PositionIndices(self) -> VertexChannelOfT[int]: ...
    @property
    def Positions(self) -> IndirectPositionCollection: ...
    @property
    def Channels(self) -> VertexChannelCollection: ...
    @property
    def VertexCount(self) -> int: ...
