#!/usr/bin/env python3
"""Generates a platform import root from that platform's reference contract.

A platform build of XNA is the Windows surface with names taken away. Xbox 360
is thirteen types and ten members short of it, measured before a line of this
was written; Windows Phone would be a different subtraction from the same set.
So a platform projection is a *filter*, and writing one by hand would be writing
its contract out a second time in a place nothing checks against the first.

What the generator emits, for whichever platform profile it is given:

* one package per XNA namespace, under that profile's import root, re-exporting
  the Windows implementation of every type the platform's contract has;
* a *generated* subclass for each type whose platform surface differs from the
  Windows one, so that the difference is a real difference between two Python
  types rather than a comment.

``--check`` regenerates into memory and reports whether anything would change,
which is what the test suite runs: the committed packages and the contract
cannot drift apart without something saying so.

It is parameterised rather than named after Xbox because the Windows Phone
profile is blocked on a *file* and on nothing else: the day the reference
assemblies are present, the same three commands produce that root too. See
``docs/windowsphone-profile.md``.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
CONTRACTS = ROOT / "tools" / "api_compat" / "reference"
RULES = ROOT / "tools" / "api_compat" / "mapping-rules.json"
PROFILES = ROOT / "tools" / "api_compat" / "profiles"

#: The Windows profiles a platform surface is drawn from. Both, because a
#: platform's assemblies carry what Windows splits between the runtime and the
#: online ones.
WINDOWS_CONTRACTS = ("xna40-windows-runtime-contract.json",
                     "xna40-windows-online-contract.json")

#: The platform profiles this repository can generate today, and where each
#: one's packages live. A profile blocked on its reference assemblies is not
#: here -- it has no contract to generate from -- and says so in its own
#: descriptor.
PLATFORM_ROOTS = {
    "xna40-xbox360-runtime": SRC / "cna" / "profiles" / "xbox360",
}

HEADER = '''"""{namespace}, as the {platform} profile has it.

Generated by ``tools/generate_platform_profile.py`` from the {platform}
reference contract. Do not edit: run the generator, and the test suite checks
that running it changes nothing.
"""
'''

#: The one thing a hand-written note has to say, and it says it once.
ROOT_NOTE = '''"""XNA 4.0 as the Xbox 360 declares it.

A **surface** profile. Importing from here gives a game exactly the types and
members an Xbox 360 build of XNA has -- no more, which is the point: a name that
is Windows-only is an ``ImportError`` here rather than a link error on a console
nobody has.

It is not an Xbox *runtime*. There is no Xbox hardware in this repository and
CNA does not target one, so anything that would actually run on a console is
BLOCKED_PLATFORM and says so. What this profile is for is checking, on the
machine you have, that the code you wrote would still be there on the one you
do not.

The measured difference is small and exact: Xbox 360 XNA is the Windows runtime
and online surfaces together, minus the thirteen ``Microsoft.Xna.Framework.Design``
type converters, minus ten .NET-Framework-only serialization members. There is
nothing on Xbox that Windows does not have.

See ``docs/xbox360-profile.md``.
"""
'''


PROFILES_MODULE = '''"""Platform surface profiles: XNA as a console or a phone declares it.

Each is an import root of its own, because two profiles cannot both be
``Microsoft.Xna.Framework`` in one interpreter. What they hold is the *surface* a
platform has; the implementation under it is the one this repository ships.

This module holds the one thing they share: how a member that a platform does
**not** have is spelled.
"""

from __future__ import annotations


class _RemovedOnPlatform:
    """A member the platform's assemblies do not declare.

    Reading it raises ``AttributeError``, which is what reading a member that is
    not there does: ``hasattr`` answers False, ``getattr`` with a default
    answers the default, and code that asks before calling behaves the way it
    would on the console. Raising only when *called* would let all three of
    those lie.

    It is a descriptor rather than a deletion because the type it sits on
    inherits from the Windows one -- which is what keeps an ``except`` clause
    written against either of them working -- and inheritance has no way to take
    something back.
    """

    __slots__ = ("_name", "_reason")

    #: Read by the strict verifier, which counts a removed member as absent, and
    #: by the profile-separation gate, which checks every removal against the
    #: two contracts that justify it.
    _xna_removed_on_platform = True

    def __init__(self, name: str, reason: str) -> None:
        self._name = name
        self._reason = reason

    def __get__(self, instance: object, owner: type | None = None):
        raise AttributeError(f"{self._name} is not declared on this platform: "
                             f"{self._reason}")

    def __set__(self, instance: object, value: object) -> None:
        raise AttributeError(f"{self._name} is not declared on this platform: "
                             f"{self._reason}")

    def __repr__(self) -> str:
        return f"<removed on this platform: {self._name}>"
'''


def member_signature(member: dict) -> str:
    parameters = ",".join(value["type"] for value in member.get("parameters", ()))
    return f"{member['kind']}:{member['name']}({parameters})"


def projected_name(identity: str, names: dict[str, str]) -> str:
    return names.get(identity, identity.rsplit(".", 1)[-1].split("`", 1)[0])


def plan(profile: str) -> tuple[dict[str, list[str]], dict[str, dict[str, list[str]]]]:
    """``(namespace -> exported names, namespace -> name -> missing members)``."""
    names = json.loads(RULES.read_text())["typeNames"]
    platform_contract = json.loads(
        (PROFILES / f"{profile}.json").read_text())["contract"]
    xbox = {entry["name"]: entry for entry in
            json.loads((CONTRACTS / platform_contract).read_text())["types"]}
    windows: dict[str, dict] = {}
    for contract in WINDOWS_CONTRACTS:
        for entry in json.loads((CONTRACTS / contract).read_text())["types"]:
            windows[entry["name"]] = entry

    exports: dict[str, list[str]] = {}
    generated: dict[str, dict[str, list[str]]] = {}
    for identity, entry in xbox.items():
        name = projected_name(identity, names)
        if "." in name:
            continue  # a nested type, reached through the type that owns it
        namespace = identity.rsplit(".", 1)[0]
        exports.setdefault(namespace, []).append(name)
        reference = windows.get(identity)
        if reference is None:
            raise SystemExit(
                f"{identity} is on this platform and in neither Windows "
                "contract; the platform surface was measured as a subset of "
                "Windows and no longer is")
        theirs = {member_signature(value) for value in entry["members"]}
        ours = {member_signature(value) for value in reference["members"]}
        missing = sorted(ours - theirs)
        if missing:
            generated.setdefault(namespace, {})[name] = missing
    return {key: sorted(value) for key, value in exports.items()}, generated


def projected_member_names(missing: list[str], names: dict[str, str],
                           reference: dict) -> list[str]:
    """The *Python* names a missing CLR member set removes, if any.

    A constructor overload that collapses onto one Python ``__init__`` removes
    nothing: the Python surface is the same either way, and that is a mapping
    fact rather than a platform one. A method with a name of its own does
    remove something.
    """
    removed: list[str] = []
    for signature in missing:
        kind, rest = signature.split(":", 1)
        member = rest.split("(", 1)[0]
        if kind == "constructor":
            continue
        removed.append(member)
    return sorted(set(removed))


def render(namespace: str, exported: list[str],
           generated: dict[str, list[str]], names: dict[str, str],
           windows: dict[str, dict], platform: str) -> str:
    lines = [HEADER.format(namespace=namespace, platform=platform)]
    plain, subclassed = [], {}
    for name in exported:
        identity = next(key for key, mapped in
                        [(f"{namespace}.{name}", name)] + list(names.items())
                        if mapped == name and key.rsplit(".", 1)[0] == namespace)
        missing = generated.get(name)
        removed = projected_member_names(missing or [], names,
                                         windows.get(identity, {}))

        if removed:
            subclassed[name] = (removed, windows.get(identity, {}).get("baseType"))
        else:
            plain.append(name)

    # A narrowed type lists its *declared* base as well as the Windows type it
    # narrows: Python accepts both because one derives from the other, and it
    # keeps the class's declared base the one the contract names rather than an
    # artefact of how the narrowing is spelled. A base from another namespace is
    # imported under a private alias, so it does not join this package's surface.
    extra: dict[str, str] = {}
    base_of: dict[str, str] = {}
    for name, (_removed, base) in subclassed.items():
        if not base or not base.startswith("Microsoft.Xna.Framework"):
            continue
        simple = projected_name(base, names)
        if simple == name or "." in simple:
            continue
        base_namespace = base.rsplit(".", 1)[0]
        if base_namespace == namespace and simple in exported:
            base_of[name] = simple
            continue
        alias = f"_Base{simple}"
        extra[f"from {base_namespace} import {simple} as {alias}"] = alias
        base_of[name] = alias

    imported = sorted(plain + [f"{name} as _Windows{name}" for name in subclassed])
    if subclassed:
        lines.append("from cna.profiles import _RemovedOnPlatform")
    for statement in sorted(extra):
        lines.append(statement)
    lines.append(f"from {namespace} import (")
    for entry in imported:
        lines.append(f"    {entry},")
    lines.append(")")
    lines.append("")
    for name in sorted(subclassed):
        removed = subclassed[name][0]
        bases = [f"_Windows{name}"]
        if name in base_of:
            bases.append(base_of[name])
        lines.append("")
        lines.append(f"class {name}({', '.join(bases)}):")
        word = "member" if len(removed) == 1 else "members"
        lines.append(f'    """{name} without the {word} this platform does not declare.')
        lines.append("")
        lines.append(f"    Removed: {', '.join(removed)}. Accessing one raises")
        lines.append("    ``AttributeError``, which is what a member that is not")
        lines.append("    there does -- so ``hasattr`` answers False and code")
        lines.append("    that asks before calling behaves the way it would on")
        lines.append("    the platform.")
        lines.append("")
        lines.append("    A subclass of the Windows type, so that ``except``")
        lines.append("    clauses written against either one still catch this.")
        lines.append('    """')
        lines.append("")
        lines.append("    __slots__ = ()")
        lines.append("")
        for member in removed:
            lines.append(f'    {member} = _RemovedOnPlatform(')
            lines.append(f'        "{name}.{member}",')
            lines.append('        "the Xbox 360 assemblies were built against the .NET Compact "')
            lines.append('        "Framework, which has no ISerializable")')
        lines.append("")
    lines.append("")
    lines.append("__all__ = [")
    for name in exported:
        lines.append(f'    "{name}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", default="xna40-xbox360-runtime",
                        choices=sorted(PLATFORM_ROOTS),
                        help="which platform profile to generate")
    parser.add_argument("--check", action="store_true",
                        help="report whether regenerating would change anything")
    arguments = parser.parse_args()
    profile_root = PLATFORM_ROOTS[arguments.profile]
    platform_name = json.loads(
        (PROFILES / f"{arguments.profile}.json").read_text())["name"]

    names = json.loads(RULES.read_text())["typeNames"]
    windows: dict[str, dict] = {}
    for contract in WINDOWS_CONTRACTS:
        for entry in json.loads((CONTRACTS / contract).read_text())["types"]:
            windows[entry["name"]] = entry
    exports, generated = plan(arguments.profile)

    written: dict[Path, str] = {}
    for namespace, exported in sorted(exports.items()):
        relative = namespace.split(".")
        path = profile_root.joinpath(*relative, "__init__.py")
        written[path] = render(namespace, exported, generated.get(namespace, {}),
                               names, windows, platform_name)
    written[profile_root / "__init__.py"] = ROOT_NOTE
    written[SRC / "cna" / "profiles" / "__init__.py"] = PROFILES_MODULE

    differences = 0
    for path, text in sorted(written.items()):
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing == text:
            continue
        differences += 1
        if arguments.check:
            print(f"WOULD_CHANGE={path.relative_to(ROOT)}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"WROTE={path.relative_to(ROOT)}")
    print(f"PACKAGES={len(written)}")
    print(f"EXPORTED_TYPES={sum(len(value) for value in exports.values())}")
    print(f"GENERATED_TYPES={sum(len(value) for value in generated.values())}")
    print(f"DIFFERENCES={differences}")
    return 1 if (arguments.check and differences) else 0


if __name__ == "__main__":
    raise SystemExit(main())
