#!/usr/bin/env python3
"""Generates the Xbox 360 import root from the Xbox reference contract.

XNA on Xbox 360 is the Windows surface with thirteen types and ten members
taken away -- there is nothing on Xbox that Windows does not have, which this
repository measured before writing a line of this. So the projection is a
*filter*, and writing it by hand would be writing the Xbox contract out a second
time in a place nothing checks against the first.

What the generator emits:

* one package per XNA namespace, under ``cna.profiles.xbox360``, re-exporting
  the Windows implementation of every type the Xbox contract has;
* a *generated* subclass for each type whose Xbox surface differs from the
  Windows one, so that the difference is a real difference between two Python
  types rather than a comment.

``--check`` regenerates into memory and reports whether anything would change,
which is what the test suite runs: the committed packages and the contract
cannot drift apart without something saying so.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
CONTRACTS = ROOT / "tools" / "api_compat" / "reference"
RULES = ROOT / "tools" / "api_compat" / "mapping-rules.json"
PROFILE_ROOT = SRC / "cna" / "profiles" / "xbox360"

#: The Windows profiles the Xbox surface is drawn from. Both, because XNA's
#: Xbox assemblies carry what Windows splits between the runtime and the online
#: assemblies.
WINDOWS_CONTRACTS = ("xna40-windows-runtime-contract.json",
                     "xna40-windows-online-contract.json")
XBOX_CONTRACT = "xna40-xbox360-runtime-contract.json"

HEADER = '''"""{namespace}, as the Xbox 360 profile has it.

Generated by ``tools/generate_xbox_profile.py`` from the Xbox 360 reference
contract. Do not edit: run the generator, and the test suite checks that running
it changes nothing.
"""
'''

#: The one thing a hand-written note has to say, and it says it once.
ROOT_NOTE = '''"""XNA 4.0 as the Xbox 360 declares it.

A **surface** profile. Importing from here gives a game exactly the types and
members an Xbox 360 build of XNA has -- no more, which is the point: a name that
is Windows-only is an ``ImportError`` here rather than a link error on a console
nobody has.

It is not an Xbox *runtime*. There is no Xbox hardware in this repository and
CNA does not target one, so anything that would actually run on a console is
BLOCKED_PLATFORM and says so. What this profile is for is checking, on the
machine you have, that the code you wrote would still be there on the one you
do not.

The measured difference is small and exact: Xbox 360 XNA is the Windows runtime
and online surfaces together, minus the thirteen ``Microsoft.Xna.Framework.Design``
type converters, minus ten .NET-Framework-only serialization members. There is
nothing on Xbox that Windows does not have.

See ``docs/xbox360-profile.md``.
"""
'''


PROFILES_MODULE = '''"""Platform surface profiles: XNA as a console or a phone declares it.

Each is an import root of its own, because two profiles cannot both be
``Microsoft.Xna.Framework`` in one interpreter. What they hold is the *surface* a
platform has; the implementation under it is the one this repository ships.

This module holds the one thing they share: how a member that a platform does
**not** have is spelled.
"""

from __future__ import annotations


class _RemovedOnPlatform:
    """A member the platform's assemblies do not declare.

    Reading it raises ``AttributeError``, which is what reading a member that is
    not there does: ``hasattr`` answers False, ``getattr`` with a default
    answers the default, and code that asks before calling behaves the way it
    would on the console. Raising only when *called* would let all three of
    those lie.

    It is a descriptor rather than a deletion because the type it sits on
    inherits from the Windows one -- which is what keeps an ``except`` clause
    written against either of them working -- and inheritance has no way to take
    something back.
    """

    __slots__ = ("_name", "_reason")

    #: Read by the strict verifier, which counts a removed member as absent, and
    #: by the profile-separation gate, which checks every removal against the
    #: two contracts that justify it.
    _xna_removed_on_platform = True

    def __init__(self, name: str, reason: str) -> None:
        self._name = name
        self._reason = reason

    def __get__(self, instance: object, owner: type | None = None):
        raise AttributeError(f"{self._name} is not declared on this platform: "
                             f"{self._reason}")

    def __set__(self, instance: object, value: object) -> None:
        raise AttributeError(f"{self._name} is not declared on this platform: "
                             f"{self._reason}")

    def __repr__(self) -> str:
        return f"<removed on this platform: {self._name}>"
'''


def member_signature(member: dict) -> str:
    parameters = ",".join(value["type"] for value in member.get("parameters", ()))
    return f"{member['kind']}:{member['name']}({parameters})"


def projected_name(identity: str, names: dict[str, str]) -> str:
    return names.get(identity, identity.rsplit(".", 1)[-1].split("`", 1)[0])


def plan() -> tuple[dict[str, list[str]], dict[str, dict[str, list[str]]]]:
    """``(namespace -> exported names, namespace -> name -> missing members)``."""
    names = json.loads(RULES.read_text())["typeNames"]
    xbox = {entry["name"]: entry for entry in
            json.loads((CONTRACTS / XBOX_CONTRACT).read_text())["types"]}
    windows: dict[str, dict] = {}
    for contract in WINDOWS_CONTRACTS:
        for entry in json.loads((CONTRACTS / contract).read_text())["types"]:
            windows[entry["name"]] = entry

    exports: dict[str, list[str]] = {}
    generated: dict[str, dict[str, list[str]]] = {}
    for identity, entry in xbox.items():
        name = projected_name(identity, names)
        if "." in name:
            continue  # a nested type, reached through the type that owns it
        namespace = identity.rsplit(".", 1)[0]
        exports.setdefault(namespace, []).append(name)
        reference = windows.get(identity)
        if reference is None:
            raise SystemExit(
                f"{identity} is on Xbox and in neither Windows contract; the "
                "Xbox surface was measured as a subset and no longer is")
        theirs = {member_signature(value) for value in entry["members"]}
        ours = {member_signature(value) for value in reference["members"]}
        missing = sorted(ours - theirs)
        if missing:
            generated.setdefault(namespace, {})[name] = missing
    return {key: sorted(value) for key, value in exports.items()}, generated


def projected_member_names(missing: list[str], names: dict[str, str],
                           reference: dict) -> list[str]:
    """The *Python* names a missing CLR member set removes, if any.

    A constructor overload that collapses onto one Python ``__init__`` removes
    nothing: the Python surface is the same either way, and that is a mapping
    fact rather than a platform one. A method with a name of its own does
    remove something.
    """
    removed: list[str] = []
    for signature in missing:
        kind, rest = signature.split(":", 1)
        member = rest.split("(", 1)[0]
        if kind == "constructor":
            continue
        removed.append(member)
    return sorted(set(removed))


def render(namespace: str, exported: list[str],
           generated: dict[str, list[str]], names: dict[str, str],
           windows: dict[str, dict]) -> str:
    lines = [HEADER.format(namespace=namespace)]
    plain, subclassed = [], {}
    for name in exported:
        identity = next(key for key, mapped in
                        [(f"{namespace}.{name}", name)] + list(names.items())
                        if mapped == name and key.rsplit(".", 1)[0] == namespace)
        missing = generated.get(name)
        removed = projected_member_names(missing or [], names,
                                         windows.get(identity, {}))

        if removed:
            subclassed[name] = (removed, windows.get(identity, {}).get("baseType"))
        else:
            plain.append(name)

    # A narrowed type lists its *declared* base as well as the Windows type it
    # narrows: Python accepts both because one derives from the other, and it
    # keeps the class's declared base the one the contract names rather than an
    # artefact of how the narrowing is spelled. A base from another namespace is
    # imported under a private alias, so it does not join this package's surface.
    extra: dict[str, str] = {}
    base_of: dict[str, str] = {}
    for name, (_removed, base) in subclassed.items():
        if not base or not base.startswith("Microsoft.Xna.Framework"):
            continue
        simple = projected_name(base, names)
        if simple == name or "." in simple:
            continue
        base_namespace = base.rsplit(".", 1)[0]
        if base_namespace == namespace and simple in exported:
            base_of[name] = simple
            continue
        alias = f"_Base{simple}"
        extra[f"from {base_namespace} import {simple} as {alias}"] = alias
        base_of[name] = alias

    imported = sorted(plain + [f"{name} as _Windows{name}" for name in subclassed])
    if subclassed:
        lines.append("from cna.profiles import _RemovedOnPlatform")
    for statement in sorted(extra):
        lines.append(statement)
    lines.append(f"from {namespace} import (")
    for entry in imported:
        lines.append(f"    {entry},")
    lines.append(")")
    lines.append("")
    for name in sorted(subclassed):
        removed = subclassed[name][0]
        bases = [f"_Windows{name}"]
        if name in base_of:
            bases.append(base_of[name])
        lines.append("")
        lines.append(f"class {name}({', '.join(bases)}):")
        word = "member" if len(removed) == 1 else "members"
        lines.append(f'    """{name} without the {word} Xbox 360 does not declare.')
        lines.append("")
        lines.append(f"    Removed: {', '.join(removed)}. Accessing one raises")
        lines.append("    ``AttributeError``, which is what a member that is not")
        lines.append("    there does -- so ``hasattr`` answers False and code")
        lines.append("    that asks before calling behaves the way it would on")
        lines.append("    a console.")
        lines.append("")
        lines.append("    A subclass of the Windows type, so that ``except``")
        lines.append("    clauses written against either one still catch this.")
        lines.append('    """')
        lines.append("")
        lines.append("    __slots__ = ()")
        lines.append("")
        for member in removed:
            lines.append(f'    {member} = _RemovedOnPlatform(')
            lines.append(f'        "{name}.{member}",')
            lines.append('        "the Xbox 360 assemblies were built against the .NET Compact "')
            lines.append('        "Framework, which has no ISerializable")')
        lines.append("")
    lines.append("")
    lines.append("__all__ = [")
    for name in exported:
        lines.append(f'    "{name}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="report whether regenerating would change anything")
    arguments = parser.parse_args()

    names = json.loads(RULES.read_text())["typeNames"]
    windows: dict[str, dict] = {}
    for contract in WINDOWS_CONTRACTS:
        for entry in json.loads((CONTRACTS / contract).read_text())["types"]:
            windows[entry["name"]] = entry
    exports, generated = plan()

    written: dict[Path, str] = {}
    for namespace, exported in sorted(exports.items()):
        relative = namespace.split(".")
        path = PROFILE_ROOT.joinpath(*relative, "__init__.py")
        written[path] = render(namespace, exported, generated.get(namespace, {}),
                               names, windows)
    written[PROFILE_ROOT / "__init__.py"] = ROOT_NOTE
    written[SRC / "cna" / "profiles" / "__init__.py"] = PROFILES_MODULE

    differences = 0
    for path, text in sorted(written.items()):
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing == text:
            continue
        differences += 1
        if arguments.check:
            print(f"WOULD_CHANGE={path.relative_to(ROOT)}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"WROTE={path.relative_to(ROOT)}")
    print(f"PACKAGES={len(written)}")
    print(f"EXPORTED_TYPES={sum(len(value) for value in exports.values())}")
    print(f"GENERATED_TYPES={sum(len(value) for value in generated.values())}")
    print(f"DIFFERENCES={differences}")
    return 1 if (arguments.check and differences) else 0


if __name__ == "__main__":
    raise SystemExit(main())
