"""Microsoft.Xna.Framework.Net, as the XNA 4.0 Xbox 360 runtime profile has it.

Generated by ``tools/generate_platform_profile.py`` from the XNA 4.0 Xbox 360 runtime
reference contract. Do not edit: run the generator, and the test suite checks
that running it changes nothing.
"""

from cna.profiles import _RemovedOnPlatform
from Microsoft.Xna.Framework.GamerServices import NetworkException as _BaseNetworkException
from Microsoft.Xna.Framework.Net import (
    AvailableNetworkSession,
    AvailableNetworkSessionCollection,
    GameEndedEventArgs,
    GameStartedEventArgs,
    GamerJoinedEventArgs,
    GamerLeftEventArgs,
    HostChangedEventArgs,
    LocalNetworkGamer,
    NetworkGamer,
    NetworkMachine,
    NetworkSession,
    NetworkSessionEndReason,
    NetworkSessionEndedEventArgs,
    NetworkSessionJoinError,
    NetworkSessionJoinException as _WindowsNetworkSessionJoinException,
    NetworkSessionProperties,
    NetworkSessionState,
    NetworkSessionType,
    PacketReader,
    PacketWriter,
    QualityOfService,
    SendDataOptions,
    WriteLeaderboardsEventArgs,
)


class NetworkSessionJoinException(_WindowsNetworkSessionJoinException, _BaseNetworkException):
    """NetworkSessionJoinException without the member this platform does not declare.

    Removed: GetObjectData. Accessing one raises
    ``AttributeError``, which is what a member that is not
    there does -- so ``hasattr`` answers False and code
    that asks before calling behaves the way it would on
    the platform.

    A subclass of the Windows type, so that ``except``
    clauses written against either one still catch this.
    """

    __slots__ = ()

    GetObjectData = _RemovedOnPlatform(
        "NetworkSessionJoinException.GetObjectData",
        "the Xbox 360 assemblies were built against the .NET Compact "
        "Framework, which has no ISerializable")


__all__ = [
    "AvailableNetworkSession",
    "AvailableNetworkSessionCollection",
    "GameEndedEventArgs",
    "GameStartedEventArgs",
    "GamerJoinedEventArgs",
    "GamerLeftEventArgs",
    "HostChangedEventArgs",
    "LocalNetworkGamer",
    "NetworkGamer",
    "NetworkMachine",
    "NetworkSession",
    "NetworkSessionEndReason",
    "NetworkSessionEndedEventArgs",
    "NetworkSessionJoinError",
    "NetworkSessionJoinException",
    "NetworkSessionProperties",
    "NetworkSessionState",
    "NetworkSessionType",
    "PacketReader",
    "PacketWriter",
    "QualityOfService",
    "SendDataOptions",
    "WriteLeaderboardsEventArgs",
]
