from datetime import datetime, timedelta
from enum import IntEnum
from typing import Any, BinaryIO, Iterable, Iterator, MutableSequence, Sequence, TypeVar, overload
from .. import Color, Game, GameComponent, GameTime, Matrix, PlayerIndex, Vector3
from .._language import Event

T = TypeVar("T")

class Achievement:
    def GetPicture(self) -> BinaryIO: ...
    @property
    def Key(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Description(self) -> str: ...
    @property
    def HowToEarn(self) -> str: ...
    @property
    def GamerScore(self) -> int: ...
    @property
    def IsEarned(self) -> bool: ...
    @property
    def EarnedOnline(self) -> bool: ...
    @property
    def DisplayBeforeEarned(self) -> bool: ...
    @property
    def EarnedDateTime(self) -> datetime: ...

class AchievementCollection:
    def Dispose(self) -> None: ...
    def GetEnumerator(self) -> Iterator[Achievement]: ...
    @property
    def IsDisposed(self) -> bool: ...
    def __getitem__(self, index: int) -> Achievement: ...
    @property
    def Count(self) -> int: ...
    def __iter__(self) -> Iterator[Achievement]: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> AchievementCollection: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class AvatarAnimation:
    def __init__(self, animationPreset: AvatarAnimationPreset) -> None: ...
    def Update(self, elapsedAnimationTime: timedelta, loop: bool) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    @property
    def Length(self) -> timedelta: ...
    @property
    def CurrentPosition(self) -> timedelta: ...
    @CurrentPosition.setter
    def CurrentPosition(self, value: timedelta) -> None: ...
    @property
    def BoneTransforms(self) -> tuple[Matrix, ...]: ...
    @property
    def Expression(self) -> AvatarExpression: ...
    @property
    def IsDisposed(self) -> bool: ...
    def __enter__(self) -> AvatarAnimation: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class AvatarAnimationPreset(IntEnum):
    Stand0: int
    Stand1: int
    Stand2: int
    Stand3: int
    Stand4: int
    Stand5: int
    Stand6: int
    Stand7: int
    Clap: int
    Wave: int
    Celebrate: int
    FemaleIdleCheckNails: int
    FemaleIdleLookAround: int
    FemaleIdleShiftWeight: int
    FemaleIdleFixShoe: int
    FemaleAngry: int
    FemaleConfused: int
    FemaleLaugh: int
    FemaleCry: int
    FemaleShocked: int
    FemaleYawn: int
    MaleIdleLookAround: int
    MaleIdleStretch: int
    MaleIdleShiftWeight: int
    MaleIdleCheckHand: int
    MaleAngry: int
    MaleConfused: int
    MaleLaugh: int
    MaleCry: int
    MaleSurprised: int
    MaleYawn: int

class AvatarBodyType(IntEnum):
    Female: int
    Male: int

class AvatarBone(IntEnum):
    Root: int
    BackLower: int
    HipLeft: int
    HipRight: int
    BackUpper: int
    KneeLeft: int
    KneeRight: int
    AnkleLeft: int
    CollarLeft: int
    Neck: int
    AnkleRight: int
    CollarRight: int
    Head: int
    ShoulderLeft: int
    ToeLeft: int
    ShoulderRight: int
    ToeRight: int
    ElbowLeft: int
    ElbowRight: int
    WristLeft: int
    WristRight: int
    FingerIndexLeft: int
    FingerMiddleLeft: int
    FingerRingLeft: int
    FingerSmallLeft: int
    PropLeft: int
    SpecialLeft: int
    FingerThumbLeft: int
    FingerIndexRight: int
    FingerMiddleRight: int
    FingerRingRight: int
    FingerSmallRight: int
    PropRight: int
    SpecialRight: int
    FingerThumbRight: int
    FingerIndex2Left: int
    FingerMiddle2Left: int
    FingerRing2Left: int
    FingerSmall2Left: int
    FingerThumb2Left: int
    FingerIndex2Right: int
    FingerMiddle2Right: int
    FingerRing2Right: int
    FingerSmall2Right: int
    FingerThumb2Right: int
    FingerIndex3Left: int
    FingerMiddle3Left: int
    FingerRing3Left: int
    FingerSmall3Left: int
    FingerThumb3Left: int
    FingerIndex3Right: int
    FingerMiddle3Right: int
    FingerRing3Right: int
    FingerSmall3Right: int
    FingerThumb3Right: int

class AvatarDescription:
    def __init__(self, data: MutableSequence[int]) -> None: ...
    @staticmethod
    def BeginGetFromGamer(gamer: Gamer, callback: Callable[[object], None], state: object) -> object: ...
    @staticmethod
    def EndGetFromGamer(result: object) -> AvatarDescription: ...
    @overload
    @staticmethod
    def CreateRandom() -> AvatarDescription: ...
    @overload
    @staticmethod
    def CreateRandom(bodyType: AvatarBodyType) -> AvatarDescription: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def Description(self) -> list[int]: ...
    @property
    def Height(self) -> float: ...
    @property
    def BodyType(self) -> AvatarBodyType: ...
    Changed: Final[Event]

class AvatarExpression:
    @property
    def Mouth(self) -> AvatarMouth: ...
    @Mouth.setter
    def Mouth(self, value: AvatarMouth) -> None: ...
    @property
    def LeftEye(self) -> AvatarEye: ...
    @LeftEye.setter
    def LeftEye(self, value: AvatarEye) -> None: ...
    @property
    def RightEye(self) -> AvatarEye: ...
    @RightEye.setter
    def RightEye(self, value: AvatarEye) -> None: ...
    @property
    def LeftEyebrow(self) -> AvatarEyebrow: ...
    @LeftEyebrow.setter
    def LeftEyebrow(self, value: AvatarEyebrow) -> None: ...
    @property
    def RightEyebrow(self) -> AvatarEyebrow: ...
    @RightEyebrow.setter
    def RightEyebrow(self, value: AvatarEyebrow) -> None: ...
    def __copy__(self) -> AvatarExpression: ...
    def __deepcopy__(self, memo: object) -> AvatarExpression: ...

class AvatarEye(IntEnum):
    Neutral: int
    Sad: int
    Angry: int
    Confused: int
    Laughing: int
    Shocked: int
    Happy: int
    Yawning: int
    Sleeping: int
    LookUp: int
    LookDown: int
    LookLeft: int
    LookRight: int
    Blink: int

class AvatarEyebrow(IntEnum):
    Neutral: int
    Sad: int
    Angry: int
    Confused: int
    Raised: int

class AvatarMouth(IntEnum):
    Neutral: int
    Sad: int
    Angry: int
    Confused: int
    Laughing: int
    Shocked: int
    Happy: int
    PhoneticO: int
    PhoneticAi: int
    PhoneticEe: int
    PhoneticFv: int
    PhoneticW: int
    PhoneticL: int
    PhoneticDth: int

class AvatarRenderer:
    @overload
    def __init__(self, avatarDescription: AvatarDescription) -> None: ...
    @overload
    def __init__(self, avatarDescription: AvatarDescription, useLoadingEffect: bool) -> None: ...
    @overload
    def Draw(self, animation: IAvatarAnimation) -> None: ...
    @overload
    def Draw(self, bones: MutableSequence[Matrix], expression: AvatarExpression) -> None: ...
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Dispose(self, disposing: bool) -> None: ...
    @property
    def World(self) -> Matrix: ...
    @World.setter
    def World(self, value: Matrix) -> None: ...
    @property
    def View(self) -> Matrix: ...
    @View.setter
    def View(self, value: Matrix) -> None: ...
    @property
    def Projection(self) -> Matrix: ...
    @Projection.setter
    def Projection(self, value: Matrix) -> None: ...
    @property
    def ParentBones(self) -> tuple[int, ...]: ...
    @property
    def BindPose(self) -> tuple[Matrix, ...]: ...
    @property
    def State(self) -> AvatarRendererState: ...
    @property
    def LightColor(self) -> Vector3: ...
    @LightColor.setter
    def LightColor(self, value: Vector3) -> None: ...
    @property
    def LightDirection(self) -> Vector3: ...
    @LightDirection.setter
    def LightDirection(self, value: Vector3) -> None: ...
    @property
    def AmbientLightColor(self) -> Vector3: ...
    @AmbientLightColor.setter
    def AmbientLightColor(self, value: Vector3) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    BoneCount: Final[int]
    def __enter__(self) -> AvatarRenderer: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class AvatarRendererState(IntEnum):
    Loading: int
    Ready: int
    Unavailable: int

class ControllerSensitivity(IntEnum):
    Low: int
    Medium: int
    High: int

class FriendCollection:
    def Dispose(self) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    def __enter__(self) -> FriendCollection: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class FriendGamer(Gamer):
    @property
    def Presence(self) -> str: ...
    @property
    def IsOnline(self) -> bool: ...
    @property
    def IsPlaying(self) -> bool: ...
    @property
    def IsJoinable(self) -> bool: ...
    @property
    def IsAway(self) -> bool: ...
    @property
    def IsBusy(self) -> bool: ...
    @property
    def HasVoice(self) -> bool: ...
    @property
    def FriendRequestReceivedFrom(self) -> bool: ...
    @property
    def FriendRequestSentTo(self) -> bool: ...
    @property
    def InviteReceivedFrom(self) -> bool: ...
    @property
    def InviteSentTo(self) -> bool: ...
    @property
    def InviteAccepted(self) -> bool: ...
    @property
    def InviteRejected(self) -> bool: ...

class GameDefaults:
    @property
    def GameDifficulty(self) -> GameDifficulty: ...
    @property
    def ControllerSensitivity(self) -> ControllerSensitivity: ...
    @property
    def PrimaryColor(self) -> Color | None: ...
    @property
    def SecondaryColor(self) -> Color | None: ...
    @property
    def AutoAim(self) -> bool: ...
    @property
    def AutoCenter(self) -> bool: ...
    @property
    def MoveWithRightThumbStick(self) -> bool: ...
    @property
    def InvertYAxis(self) -> bool: ...
    @property
    def ManualTransmission(self) -> bool: ...
    @property
    def RacingCameraAngle(self) -> RacingCameraAngle: ...
    @property
    def AccelerateWithButtons(self) -> bool: ...
    @property
    def BrakeWithButtons(self) -> bool: ...

class GameDifficulty(IntEnum):
    Easy: int
    Normal: int
    Hard: int

class GameUpdateRequiredException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @overload
    def __init__(self, info: object, context: object) -> None: ...

class Gamer:
    def ToString(self) -> str: ...
    def GetProfile(self) -> GamerProfile: ...
    def BeginGetProfile(self, callback: Callable[[object], None], asyncState: object) -> object: ...
    def EndGetProfile(self, result: object) -> GamerProfile: ...
    @staticmethod
    def BeginGetFromGamertag(gamertag: str, callback: Callable[[object], None], asyncState: object) -> object: ...
    @staticmethod
    def EndGetFromGamertag(result: object) -> Gamer: ...
    @staticmethod
    def GetFromGamertag(gamertag: str) -> Gamer: ...
    @staticmethod
    def BeginGetPartnerToken(audienceUri: str, callback: Callable[[object], None], asyncState: object) -> object: ...
    @staticmethod
    def EndGetPartnerToken(result: object) -> str: ...
    @staticmethod
    def GetPartnerToken(audienceUri: str) -> str: ...
    @property
    def Gamertag(self) -> str: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def Tag(self) -> object: ...
    @Tag.setter
    def Tag(self, value: object) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    SignedInGamers: Final[SignedInGamerCollection]
    @property
    def LeaderboardWriter(self) -> LeaderboardWriter: ...

class GamerCollectionOfT(Generic[T]):
    def GetEnumerator(self) -> GamerCollectionOfT.GamerCollectionEnumerator[T]: ...
    def __iter__(self) -> Iterator[Gamer]: ...
    class GamerCollectionEnumerator(Generic[T]):
        def Dispose(self) -> None: ...
        def MoveNext(self) -> bool: ...
        @property
        def Current(self) -> T: ...
        def __iter__(self) -> Iterator[T]: ...
        def __copy__(self) -> GamerCollectionEnumerator: ...
        def __deepcopy__(self, memo: object) -> GamerCollectionEnumerator: ...

class GamerPresence:
    @property
    def PresenceMode(self) -> GamerPresenceMode: ...
    @PresenceMode.setter
    def PresenceMode(self, value: GamerPresenceMode) -> None: ...
    @property
    def PresenceValue(self) -> int: ...
    @PresenceValue.setter
    def PresenceValue(self, value: int) -> None: ...

class GamerPresenceMode(IntEnum):
    None_: int
    SinglePlayer: int
    Multiplayer: int
    LocalCoOp: int
    LocalVersus: int
    OnlineCoOp: int
    OnlineVersus: int
    VersusComputer: int
    Stage: int
    Level: int
    CoOpStage: int
    CoOpLevel: int
    ArcadeMode: int
    CampaignMode: int
    ChallengeMode: int
    ExplorationMode: int
    PracticeMode: int
    PuzzleMode: int
    ScenarioMode: int
    StoryMode: int
    SurvivalMode: int
    TutorialMode: int
    DifficultyEasy: int
    DifficultyMedium: int
    DifficultyHard: int
    DifficultyExtreme: int
    Score: int
    VersusScore: int
    Winning: int
    Losing: int
    ScoreIsTied: int
    Outnumbered: int
    OnARoll: int
    InCombat: int
    BattlingBoss: int
    TimeAttack: int
    TryingForRecord: int
    FreePlay: int
    WastingTime: int
    StuckOnAHardBit: int
    NearlyFinished: int
    LookingForGames: int
    WaitingForPlayers: int
    WaitingInLobby: int
    SettingUpMatch: int
    PlayingWithFriends: int
    AtMenu: int
    StartingGame: int
    Paused: int
    GameOver: int
    WonTheGame: int
    ConfiguringSettings: int
    CustomizingPlayer: int
    EditingLevel: int
    InGameStore: int
    WatchingCutscene: int
    WatchingCredits: int
    PlayingMinigame: int
    FoundSecret: int
    CornflowerBlue: int

class GamerPrivilegeException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @overload
    def __init__(self, info: object, context: object) -> None: ...

class GamerPrivilegeSetting(IntEnum):
    Blocked: int
    FriendsOnly: int
    Everyone: int

class GamerPrivileges:
    @property
    def AllowOnlineSessions(self) -> bool: ...
    @property
    def AllowCommunication(self) -> GamerPrivilegeSetting: ...
    @property
    def AllowProfileViewing(self) -> GamerPrivilegeSetting: ...
    @property
    def AllowUserCreatedContent(self) -> GamerPrivilegeSetting: ...
    @property
    def AllowTradeContent(self) -> bool: ...
    @property
    def AllowPurchaseContent(self) -> bool: ...
    @property
    def AllowPremiumContent(self) -> bool: ...

class GamerProfile:
    def Dispose(self) -> None: ...
    def GetGamerPicture(self) -> BinaryIO: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Motto(self) -> str: ...
    @property
    def Reputation(self) -> float: ...
    @property
    def GamerZone(self) -> GamerZone: ...
    @property
    def Region(self) -> str: ...
    @property
    def GamerScore(self) -> int: ...
    @property
    def TitlesPlayed(self) -> int: ...
    @property
    def TotalAchievements(self) -> int: ...
    def __enter__(self) -> GamerProfile: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class GamerServicesDispatcher:
    @staticmethod
    def Initialize(serviceProvider: object) -> None: ...
    @staticmethod
    def Update() -> None: ...
    IsInitialized: Final[bool]
    WindowHandle: ClassVar[int]
    InstallingTitleUpdate: Final[Event]

class GamerServicesNotAvailableException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @overload
    def __init__(self, info: object, context: object) -> None: ...

class GamerZone(IntEnum):
    Unknown: int
    Recreation: int
    Pro: int
    Family: int
    Underground: int

class Guide:
    @overload
    @staticmethod
    def BeginShowMessageBox(player: PlayerIndex, title: str, text: str, buttons: Iterable[str], focusButton: int, icon: MessageBoxIcon, callback: Callable[[object], None], state: object) -> object: ...
    @overload
    @staticmethod
    def BeginShowMessageBox(title: str, text: str, buttons: Iterable[str], focusButton: int, icon: MessageBoxIcon, callback: Callable[[object], None], state: object) -> object: ...
    @staticmethod
    def EndShowMessageBox(result: object) -> int | None: ...
    @staticmethod
    def ShowSignIn(paneCount: int, onlineOnly: bool) -> None: ...
    @overload
    @staticmethod
    def BeginShowKeyboardInput(player: PlayerIndex, title: str, description: str, defaultText: str, callback: Callable[[object], None], state: object) -> object: ...
    @overload
    @staticmethod
    def BeginShowKeyboardInput(player: PlayerIndex, title: str, description: str, defaultText: str, callback: Callable[[object], None], state: object, usePasswordMode: bool) -> object: ...
    @staticmethod
    def EndShowKeyboardInput(result: object) -> str: ...
    @staticmethod
    def ShowMessages(player: PlayerIndex) -> None: ...
    @staticmethod
    def ShowFriends(player: PlayerIndex) -> None: ...
    @staticmethod
    def ShowPlayers(player: PlayerIndex) -> None: ...
    @staticmethod
    def ShowFriendRequest(player: PlayerIndex, gamer: Gamer) -> None: ...
    @staticmethod
    def ShowPlayerReview(player: PlayerIndex, gamer: Gamer) -> None: ...
    @staticmethod
    def ShowGamerCard(player: PlayerIndex, gamer: Gamer) -> None: ...
    @staticmethod
    def ShowParty(player: PlayerIndex) -> None: ...
    @staticmethod
    def ShowPartySessions(player: PlayerIndex) -> None: ...
    @staticmethod
    def ShowComposeMessage(player: PlayerIndex, text: str, recipients: Iterable[Gamer]) -> None: ...
    @staticmethod
    def DelayNotifications(delay: timedelta) -> None: ...
    @overload
    @staticmethod
    def ShowGameInvite(player: PlayerIndex, recipients: Iterable[Gamer]) -> None: ...
    @overload
    @staticmethod
    def ShowGameInvite(sessionId: str) -> None: ...
    @staticmethod
    def ShowMarketplace(player: PlayerIndex) -> None: ...
    IsScreenSaverEnabled: ClassVar[bool]
    IsVisible: Final[bool]
    NotificationPosition: ClassVar[NotificationPosition]
    IsTrialMode: Final[bool]
    SimulateTrialMode: ClassVar[bool]

class GuideAlreadyVisibleException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @overload
    def __init__(self, info: object, context: object) -> None: ...

class IAvatarAnimation:
    def Update(self, elapsedAnimationTime: timedelta, loop: bool) -> None: ...
    @property
    def BoneTransforms(self) -> tuple[Matrix, ...]: ...
    @property
    def CurrentPosition(self) -> timedelta: ...
    @CurrentPosition.setter
    def CurrentPosition(self, value: timedelta) -> None: ...
    @property
    def Length(self) -> timedelta: ...
    @property
    def Expression(self) -> AvatarExpression: ...

class InviteAcceptedEventArgs:
    def __init__(self, gamer: SignedInGamer, isCurrentSession: bool) -> None: ...
    @property
    def IsCurrentSession(self) -> bool: ...
    @property
    def Gamer(self) -> SignedInGamer: ...

class LeaderboardEntry:
    @property
    def Gamer(self) -> Gamer: ...
    @property
    def Rating(self) -> int: ...
    @Rating.setter
    def Rating(self, value: int) -> None: ...
    @property
    def Columns(self) -> PropertyDictionary: ...

class LeaderboardIdentity:
    @overload
    @staticmethod
    def Create(key: LeaderboardKey, gameMode: int) -> LeaderboardIdentity: ...
    @overload
    @staticmethod
    def Create(key: LeaderboardKey) -> LeaderboardIdentity: ...
    @property
    def Key(self) -> str: ...
    @Key.setter
    def Key(self, value: str) -> None: ...
    @property
    def GameMode(self) -> int: ...
    @GameMode.setter
    def GameMode(self, value: int) -> None: ...
    def __copy__(self) -> LeaderboardIdentity: ...
    def __deepcopy__(self, memo: object) -> LeaderboardIdentity: ...

class LeaderboardKey(IntEnum):
    BestScoreLifeTime: int
    BestScoreRecent: int
    BestTimeLifeTime: int
    BestTimeRecent: int

class LeaderboardOutcome(IntEnum):
    None_: int
    Win: int
    Loss: int
    Tie: int

class LeaderboardReader:
    @overload
    @staticmethod
    def Read(leaderboardId: LeaderboardIdentity, gamers: Iterable[Gamer], pivotGamer: Gamer, pageSize: int) -> LeaderboardReader: ...
    @overload
    @staticmethod
    def Read(leaderboardId: LeaderboardIdentity, pivotGamer: Gamer, pageSize: int) -> LeaderboardReader: ...
    @overload
    @staticmethod
    def Read(leaderboardId: LeaderboardIdentity, pageStart: int, pageSize: int) -> LeaderboardReader: ...
    @overload
    @staticmethod
    def BeginRead(leaderboardId: LeaderboardIdentity, gamers: Iterable[Gamer], pivotGamer: Gamer, pageSize: int, callback: Callable[[object], None], asyncState: object) -> object: ...
    @overload
    @staticmethod
    def BeginRead(leaderboardId: LeaderboardIdentity, pivotGamer: Gamer, pageSize: int, callback: Callable[[object], None], asyncState: object) -> object: ...
    @overload
    @staticmethod
    def BeginRead(leaderboardId: LeaderboardIdentity, pageStart: int, pageSize: int, callback: Callable[[object], None], asyncState: object) -> object: ...
    @staticmethod
    def EndRead(result: object) -> LeaderboardReader: ...
    def Dispose(self) -> None: ...
    def PageUp(self) -> None: ...
    def PageDown(self) -> None: ...
    def BeginPageUp(self, callback: Callable[[object], None], asyncState: object) -> object: ...
    def BeginPageDown(self, callback: Callable[[object], None], asyncState: object) -> object: ...
    def EndPageUp(self, result: object) -> None: ...
    def EndPageDown(self, result: object) -> None: ...
    @property
    def LeaderboardIdentity(self) -> LeaderboardIdentity: ...
    @property
    def TotalLeaderboardSize(self) -> int: ...
    @property
    def PageStart(self) -> int: ...
    @property
    def Entries(self) -> tuple[LeaderboardEntry, ...]: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def CanPageUp(self) -> bool: ...
    @property
    def CanPageDown(self) -> bool: ...
    def __enter__(self) -> LeaderboardReader: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...

class LeaderboardWriter:
    def __init__(self) -> None: ...
    def GetLeaderboard(self, leaderboardId: LeaderboardIdentity) -> LeaderboardEntry: ...

class MessageBoxIcon(IntEnum):
    None_: int
    Error: int
    Warning: int
    Alert: int

class NetworkException(Exception):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @overload
    def __init__(self, info: object, context: object) -> None: ...

class NetworkNotAvailableException(NetworkException):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, message: str) -> None: ...
    @overload
    def __init__(self, message: str, innerException: Exception) -> None: ...
    @overload
    def __init__(self, info: object, context: object) -> None: ...

class NotificationPosition(IntEnum):
    TopLeft: int
    TopCenter: int
    TopRight: int
    CenterLeft: int
    Center: int
    CenterRight: int
    BottomLeft: int
    BottomCenter: int
    BottomRight: int

class PropertyDictionary:
    def GetValueInt32(self, key: str) -> int: ...
    def GetValueInt64(self, key: str) -> int: ...
    def GetValueSingle(self, key: str) -> float: ...
    def GetValueDouble(self, key: str) -> float: ...
    def GetValueString(self, key: str) -> str: ...
    def GetValueOutcome(self, key: str) -> LeaderboardOutcome: ...
    def GetValueDateTime(self, key: str) -> datetime: ...
    def GetValueTimeSpan(self, key: str) -> timedelta: ...
    def GetValueStream(self, key: str) -> BinaryIO: ...
    @overload
    def SetValue(self, key: str, value: int) -> None: ...
    @overload
    def SetValue(self, key: str, value: float) -> None: ...
    @overload
    def SetValue(self, key: str, value: str) -> None: ...
    @overload
    def SetValue(self, key: str, value: LeaderboardOutcome) -> None: ...
    @overload
    def SetValue(self, key: str, value: datetime) -> None: ...
    @overload
    def SetValue(self, key: str, value: timedelta) -> None: ...
    def ContainsKey(self, key: str) -> bool: ...
    def TryGetValue(self, key: str) -> tuple[bool, object]: ...
    def GetEnumerator(self) -> Iterator[KeyValuePair[str, object]]: ...
    @property
    def Count(self) -> int: ...
    def __getitem__(self, key: str) -> object: ...
    def __iter__(self) -> Iterator[tuple[str, object]]: ...
    def __len__(self) -> int: ...

class RacingCameraAngle(IntEnum):
    Back: int
    Front: int
    Inside: int

class SignedInEventArgs:
    def __init__(self, gamer: SignedInGamer) -> None: ...
    @property
    def Gamer(self) -> SignedInGamer: ...

class SignedInGamer(Gamer):
    def IsFriend(self, gamer: Gamer) -> bool: ...
    def GetFriends(self) -> FriendCollection: ...
    def IsHeadset(self, microphone: Microphone) -> bool: ...
    def BeginAwardAchievement(self, achievementKey: str, callback: Callable[[object], None], state: object) -> object: ...
    def EndAwardAchievement(self, result: object) -> None: ...
    def AwardAchievement(self, achievementKey: str) -> None: ...
    def BeginGetAchievements(self, callback: Callable[[object], None], asyncState: object) -> object: ...
    def EndGetAchievements(self, result: object) -> AchievementCollection: ...
    def GetAchievements(self) -> AchievementCollection: ...
    @property
    def PlayerIndex(self) -> PlayerIndex: ...
    @property
    def IsSignedInToLive(self) -> bool: ...
    @property
    def IsGuest(self) -> bool: ...
    @property
    def GameDefaults(self) -> GameDefaults: ...
    @property
    def Privileges(self) -> GamerPrivileges: ...
    @property
    def PartySize(self) -> int: ...
    @property
    def Presence(self) -> GamerPresence: ...
    SignedIn: Final[Event]
    SignedOut: Final[Event]

class SignedInGamerCollection:
    def __getitem__(self, index: PlayerIndex) -> SignedInGamer: ...

class SignedOutEventArgs:
    def __init__(self, gamer: SignedInGamer) -> None: ...
    @property
    def Gamer(self) -> SignedInGamer: ...

class GamerServicesComponent(GameComponent):
    def __init__(self, game: Game) -> None: ...
    def Initialize(self) -> None: ...
    def Update(self, gameTime: GameTime) -> None: ...
