from .. import Game, GameComponent, GameTime

class GamerServicesComponent(GameComponent):
    def __init__(self, game: Game) -> None: ...
    def Initialize(self) -> None: ...
    def Update(self, gameTime: GameTime) -> None: ...
